drivers/frequency/admv1013/admv1013.c
drivers/frequency/admv1013/admv1013.h

The ADMV1013 is a wideband, microwave upconverter optimized
for point to point microwave radio designs operating in the
24 GHz to 44 GHz radio frequency (RF) range.
Datasheet: https://www.analog.com/en/products/admv1013.html

drivers: frequency: admv1013: add support

---

drivers/adc/ad9081/api/adi_ad9081_sync.c
drivers/adc/ad9467/ad9467.c

Super minor typos where some conditional statements are always true.
Fixes:
- On the AD9081, it will mask bits the LSB's and will set a new value, even if the input is out of range.
- On the AD9467, the jitter mux bit cannot be set and will always return API_CMS_ERROR_INVALID_PARAM.

Input parameter conditional checks always true

---

drivers/frequency/admv1014/admv1014.c
drivers/frequency/admv1014/admv1014.h

The ADMV1014 is a silicon germanium (SiGe), wideband,
microwave downconverter optimized for point to point microwave
radio designs operating in the 24 GHz to 44 GHz frequency range.
Datasheet: https://www.analog.com/en/products/admv1014.html

drivers: frequency: admv1014: add support

---

drivers/platform/maxim/maxim_irq.c

Declaring is_callback as extern without a type modifier
resulted in using int as it's type (even though is_callback
was declared globally as bool). This caused an overflow to occur,
overwriting the next global variable.

drivers:platform:maxim:maxim_irq.c: Fixed overflow

---

drivers/dac/ltc2688/ltc2688.c
drivers/dac/ltc2688/ltc2688.h

Added an extra parameter in device descriptor to store the computed dac code.

drivers:dac:ltc2688: Minor Update

---

drivers/adc/ad717x/ad717x.c
drivers/adc/ad717x/ad717x.h

1) Updated the ad717x_init_param to add num_setups as a member
2) Utilized the num_setups in the for loop for configuring the SETUPCON registers
Signed-off-by: Janani Sunil <Janani.Sunil@analog.com>

drivers:adc:ad717x: Added num_setups in the init struct member

---

drivers/platform/mbed/mbed_uart.cpp
drivers/platform/mbed/mbed_uart.h

1) The drivers now make use of USBSerial instead of USBCDC library for virtual com port creation.
2) Added support for explictly using either UART or USB for console stdio operations.
3) Astyle fix

drivers:platform:mbed: Uart updates.

---

iio/iio.c
iio/iio.h
iio/iio_trigger.c
iio/iio_trigger.h

Add generic trigger APIs for hardware and software triggers which shall be used by all IIO devices with trigger capabilities.
There are two types of triggers which can be instantiated:
1. software trigger: 
- does not require any interrupt mapping
- is generated by writing the attribute of the trigger device
- are not supported over serial communication
Example of software trigger initialization for a device:
```
static struct iio_attribute trig_attr[] = {
{
.name = "trigger_now",
.store = iio_sw_trig_handler
},
END_ATTRIBUTES_ARRAY
};
struct iio_trigger sw_trig_desc = {
.is_synchronous = true,
.attributes = trig_attr,
};
```
In case of a software trigger, the is_synchronous flag specifies whether the measurement is performed from the context of the software trigger handler …

iio:iio_trigger: Add generic trigger APIs

---

drivers/platform/maxim/maxim_gpio_irq.c
drivers/platform/maxim/maxim_rtc.c

- Removed a useless list search in `trigger_level_set` function.
- Updated the `MXC_RTC_CheckBusy` function calls to `MXC_RTC_Wait_BusyToClear`, because the API changed in the last
SDK update.

Maxim RTC API update

---

drivers/adc/ad9208/ad9208_api/api_def.h

Fix ifdef statement for `NO_OS_DIV_U64`.
Fixes: 108ffba ("include:no_os_util.h Add no_os_prefix to functions, enums, structures.")

drivers: adc: ad9208: fix ifdef statement

---

drivers/temperature/max31875/max31875.c

The `regval` is passed as reference to the max31875_reg_read function.
Fixes: 2b9c133 ("drivers:temperature:max31875: initial commit")

drivers: temperature: max31875: fix read function

---

drivers/adc/ad7799/ad7799.c

Since polarity is of bool type, use if..else statement instead.
Fix "switch condition has boolean value" warning.
Fixes: 91b87ce ("drivers: adc: add AD7798/AD7799 driver")

drivers: adc: ad7799: rework switch condition

---

drivers/accel/adxl355/adxl355.c
drivers/accel/adxl355/adxl355.h
drivers/accel/adxl355/iio_adxl355.c

- Remove empty items from available frequency and hpf frequency lists.
- Remove not needed white spaces.

iio_adxl355: Remove empty line from available items list

---

drivers/adc/ad7799/iio_ad7799.c

After the latest changes of the iio driver, the `data` variable should
be of unsigned type.
Fixes: 1737aec ("drivers:adc:ad7799_iio: read raw data")

drivers: ad7799: iio: fix variable type

---

drivers/accel/adxl367/adxl367.h
drivers/display/ssd_1306/ssd_1306.c

- Fix warning related to incompatible types.
- display: ssd_1306: properly pass array to function

drivers: misc fixes

---

projects/iio_demo/src/platform/maxim/main.c
projects/iio_demo/src/platform/maxim/parameters.c
projects/iio_demo/src/platform/maxim/parameters.h
projects/iio_demo/src/platform/maxim/platform_src.mk

Implemented support for iio_demo on Maxim platform. For now, the baudrate will be set to 57600.
Tested on MAX32650 and MAX32655.

iio_demo for maxim

---

drivers/afe/ad4110/ad4110.c
drivers/afe/ad4110/ad4110.h
projects/ad4110/src/app/main.c

Switch from int32_t to uint32_t since the adc resolution is 24-bit.
Fix incompatible types warnings.
Fixes: 8b68f1c ("drivers:afe:ad4110: Add continuous_read function")

ad4110: change buffer type

---

drivers/temperature/max31855/iio_max31855.c
drivers/temperature/max31855/iio_max31855.h
drivers/temperature/max31855/max31855.c
drivers/temperature/max31855/max31855.h
iio/iio.c
iio/iio_types.h

The MAX31855 performs cold-junction compensation
and digitizes the signal from a K-, J-, N-, T-, S-, R-, or
E-type thermocouple. The data is output in a signed
14-bit, SPI-compatible, read-only format. This converter
resolves temperatures to 0.25°C, allows readings as
high as +1800°C and as low as -270°C, and exhibits
thermocouple accuracy of ±2°C for temperatures ranging
from -200°C to +700°C for K-type thermocouples.

MAX31855 thermocouple driver

---

iio/iio_trigger.c
iio/iio_trigger.h

Change return type for iio_hw_trig_handler from int to void seeing how the handler is called from interrupt and the
return value is never used.

iio:iio_trigger: Change return type for iio_hw_trig_handler

---

tools/scripts/build_projects.py

For stm32 platform always set new_hdf to true in order to regenerate bsp at each build to avoid situations in which the already existing bsp is not the correct one due to HAL changes.

tools:scripts:build_projects.py: Always regenerate bsp for stm32

---

tools/scripts/platform/xilinx/util.tcl
tools/scripts/xilinx.mk

Enhance utility script to support JTAG cable name for microblaze
platforms.
Signed-off-by: Travis F. Collins <travis.collins@analog.com>

Multi-JTAG support for Microblaze

---

drivers/platform/maxim/maxim_spi.c
drivers/platform/maxim/maxim_uart.c

Updated the Maxim platform drivers to support MAX78000 target (UART and SPI are the only ones that required changes).

MAX78000 platform drivers

---

projects/eval-adxl355-pmdz/src/platform/maxim/parameters.h

The build on Maxim failed because a define was missing.

projects:eval-adxl355-pmdz: Fixed maxim build

---

drivers/dac/ad7293/ad7293.c
drivers/dac/ad7293/ad7293.h

The AD7293 is a PA drain current controller containing
functionality for general-purpose monitoring and control of
current, voltage, and temperature, integrated into a single chip
solution with an SPI-compatible interface.

drivers: dac: ad7293: add ad7293 support

---

include/no_os_fifo.h
include/no_os_units.h
include/no_os_util.h

Similar to linux version:
https://github.com/torvalds/linux/blob/master/include/linux/units.h
Add units header file containing standard units definition.
This is a minimal implementation, subject to being expanded.
The purpose of this file is to avoid redefinition of these kind for
macros in drivers that require them.
For now, it can be used in conjunction with https://github.com/analogdevicesinc/no-OS/pull/1393 which redefines `TERA` and `MEGA`

 include: add no_os_units.h

---

drivers/accel/adxl313/adxl313.c
drivers/accel/adxl313/adxl313.h

Updated the driver with the figures specified by the datasheet of the ADXL314 device.

ADXL313 driver update with ADXL314 datasheet data

---

drivers/accel/adxl355/iio_adxl355.c

Remove generic defines from iio_adxl355.c and use no_os_units.h header
file instead.

accel: adxl355: iio_adxl355: use no_os_units.h

---

projects/eval-adxl355-pmdz/src.mk

With d5bd455 no_os_units.h is used with iio_adxl355.
Update src.mk of eval-adxl355-pmdz project accordingly.

projects: eval-adxl355-pmdz: add units.h to src.mk

---

drivers/adc/adc_demo/adc_demo.c
drivers/adc/adc_demo/adc_demo.h
drivers/adc/adc_demo/iio_adc_demo.c
drivers/dac/dac_demo/dac_demo.c
drivers/dac/dac_demo/dac_demo.h
drivers/dac/dac_demo/iio_dac_demo.c

- Use submit function instead of read_dev for buffer readings.
- Move adc_submit_samples and adc_demo_trigger_handler implementations to iio_adc_demo.c.
- Use submit function instead of write_dev for buffer writings.
- Move dac_submit_samples and dac_demo_trigger_handler implementations to iio_dac_demo.c.

adc_demo, dac_demo: use submit function instead of read_dev, write_dev functions for buffer handling

---

ci/astyle.sh

Fix possible error when downloading astyle:
"ERROR: cannot verify downloads.sourceforge.net's ceritficate."

ci: astyle: skip certificate check

---

drivers/dac/ltc268x/ltc268x.c
drivers/dac/ltc268x/ltc268x.h

* Moved the channel array inside the source file so as to avoid linking issues with different compilers.

drivers:dac:ltc268x: Minor Fix.

---

iio/iio.c

Call submit function for reading/writing the buffer only when a trigger is not assigned, otherwise the readings/writings will be handled in trigger_handler function.

iio:iio.c: Use submit function only when triggers are inactive

---

tools/scripts/build_projects.py

Due to a yet elusive problem, stm32cubemx sometimes hangs while building
on azure.
This commit adds a workaround to not block the other builds by
time bounding the make all execution.
It seems reverting stm32cubemx to 6.3.0 would fix the problem, but 6.3.0
has another issue that was the reason we currently  use 6.5.0.
So this workaround should be removed once 6.6.0 arrives and fixes the
code generation hanging problem.

stm32 build hang workaround

---

drivers/afe/ad4110/ad4110.c

1) Replaced AD4110_ENABLE with the correct data to be written
2) Set I_EXEC_SEL to 100uA in case of RTD 2-wire as that is the only permissible option for 2-wire mode
Signed-off-by: Janani Sunil <Janani.Sunil@analog.com>

drivers:afe:ad4110:Corrections in AD4110 driver

---

drivers/adc/ad469x/ad469x.c
drivers/adc/ad469x/ad469x.h

* Added macros for configuring reference control register.
* Updated the ad469x_std_pin_pairing() function so that only the desired
bits of the register are updated.

drivers:adc:ad469x: Minor Updates.

---

ci/gen_dox.sh

The `-z` condition does not work properly if EXCLUDE_PART is initialized
with 0. Use `-eq` instead.
Fixes: 4d39b40 ("ci: gen_dox: rework excluded paths handling")

ci: gen_dox: fix if statement

---

drivers/platform/aducm3029/aducm3029_irq.c
drivers/platform/aducm3029/aducm3029_timer.c
drivers/platform/aducm3029/aducm3029_timer.h
drivers/platform/aducm3029/delay.c
drivers/platform/aducm3029/irq_extra.h
projects/ad7124-8pmdz/src.mk
projects/ad7746-ebz/src.mk
projects/ada4250_ardz/src.mk
projects/aducm_blinky_example/src.mk
projects/adxrs290-pmdz/Makefile
projects/adxrs290-pmdz/builds.json
projects/adxrs290-pmdz/src.mk
projects/adxrs290-pmdz/src/common/common_data.c
projects/adxrs290-pmdz/src/common/common_data.h
projects/adxrs290-pmdz/src/examples/examples_src.mk
projects/adxrs290-pmdz/src/examples/iio_timer_trigger_example/iio_timer_trigger_example.c
projects/adxrs290-pmdz/src/examples/iio_timer_trigger_example/iio_timer_trigger_example.h
projects/adxrs290-pmdz/src/platform/aducm3029/main.c
projects/adxrs290-pmdz/src/platform/aducm3029/parameters.c
projects/adxrs290-pmdz/src/platform/aducm3029/platform_src.mk
projects/adxrs290-pmdz/src/platform/maxim/main.c
projects/adxrs290-pmdz/src/platform/stm32/main.c
projects/cn0531/src.mk
projects/cn0552/src.mk
projects/iio_adpd1080/src.mk
projects/iio_aducm3029/src.mk
projects/iio_demo/src/platform/aducm3029/platform_src.mk
tools/scripts/iio_srcs.mk

- Add timer support for aducm3029 platform and adapt projects accordingly.
- Add trigger timer support for aducm3029 and interrupt timer support.
- Add example with timer trigger for adxrs290-pmdz project for aducm3029.

drivers:platform:aducm3029: Add timer support

---

drivers/temperature/adt7420/adt7420.c
drivers/temperature/adt7420/adt7420.h

The adt7420 had some reduntant code and some
hard to read functions. This commit aims to clear
the code and bring the driver up to date with
current no-os standards.
Signed-off-by: Ramona Alexandra Nechita <ramona.nechita@analog.com>

drivers: adt7420: update driver functions

---

iio/iio.c

In case a buffer overrun takes place, the iio will treat this behavior as an error and will return an error to the iio client.
In some cases, the user might want to ignore this error, even if it means overwriting sampled data which was not sent to the client.
By adding IIO_IGNORE_BUFF_OVERRUN_ERR flag in CFLAGS the user can now enable this functionality.

iio:iio.c: Add compiler switch for buffer overrun error

---

drivers/platform/aducm3029/aducm3029_timer.c
drivers/platform/aducm3029/delay.c
drivers/platform/maxim/max32650/maxim_timer.c
drivers/platform/maxim/max32655/maxim_timer.c
drivers/platform/maxim/max32660/maxim_timer.c
drivers/platform/maxim/max32665/maxim_timer.c
drivers/platform/maxim/max78000/maxim_timer.c
drivers/platform/stm32/stm32_timer.c
drivers/platform/xilinx/no_os_timer.c
include/no_os_timer.h
libraries/mqtt/mqtt_noos_support.c
projects/adv7511/src/main.c
projects/adxrs290-pmdz/src/common/common_data.c
projects/adxrs290-pmdz/src/platform/aducm3029/parameters.h
projects/iio_adpd1080/src/main.c
projects/iio_demo/src/common/common_data.c
projects/iio_demo/src/platform/stm32/parameters.h

The name load_value does not describe the parameter usage correctly. It implies that it is the start value of the timer, however we use it to describe the number of ticks the timer counts until it resets. A rename is done to better describe this parameter usage.

include:no_os_timer: Rename load_value to ticks_count

---

drivers/adc/ad7616/ad7616.h
drivers/adc/ad9081/ad9081.h
drivers/adc/ad9083/ad9083.h
drivers/frequency/ad9528/ad9528.h
include/no_os_gpio.h
projects/fmcadc2/src/fmcadc2.c
projects/fmcadc5/src/fmcadc5.c
projects/fmcdaq3/src/app/fmcdaq3.c
projects/fmcjesdadc1/src/app/fmcjesdadc1.c

Using custom naming for data types is no longer supported in the no-OS
repository.

include: gpio: remove typedefs

---

drivers/adc/ad738x/ad738x.c
drivers/adc/ad738x/ad738x.h

Change 1:
Added standard SPI support for ad738x drivers to work with baremetal systems.
- The SPI engine functionality has been enabled by default. If macro 'USE_STANDARD_SPI' is added,
- the SPI engine code is replaced with standard no-os platform drivers SPI code.
- This change is similar to what has been done on ad4696 drivers.
Change 2:
Fixed the register data read function
As per ad7380 datasheet (Rev A, Page 27, section-ADDRESSING REGISTERS), to read the register data, the command needs to be send twice.
First word (2-bytes) of data read request, holds the command to inform register address to ADC.
Second word (2-bytes) of data request, is dummy read (NOP) to read the contents of that register.
Behavior is tested on SDP-K1 board using AD7380FMCZ board.
Signed-off-by: MPhalke …

drivers:adc:ad738x Added standard SPI support

---

drivers/afe/ad413x/ad413x.c
drivers/afe/ad413x/ad413x.h
drivers/afe/ad413x/iio_ad413x.c
drivers/afe/ad413x/iio_ad413x.h
projects/ad413x/Makefile
projects/ad413x/src.mk
projects/ad413x/src/app/main.c
projects/ad413x/src/app/parameters.h

The driver and application are ported from bitbucket since the part is now released.
*NOTE:* missing builds.json file due to lack of .xsa file

AD413x: add driver support and project

---

drivers/afe/ad413x/iio_ad413x.c
drivers/afe/ad413x/iio_ad413x.h
projects/ad413x/src/app/main.c

Add irq descriptor as member of the ad413x_iio_init_param structure and
initialized it in the main application.

ad413x: iio: rework irq desc assignment

---

drivers/platform/mbed/mbed_gpio_irq.cpp
drivers/platform/mbed/mbed_gpio_irq.h
drivers/platform/mbed/mbed_irq.cpp

1. Added implementation for Mbed GPIO IRQ handling. The implementation is similar to existing 'mbed_irq.cpp' module,
except addition on new function - 'mbed_gpio_irq_trigger_level_set'. Restructured existing APIs to follow the common
procedure to register callback, enable/disable gpio irqs, set gpio trigger level on IRQ, etc, similar to what has been
on other platform drivers. The original functionality has been however intact.
2. Updated 'mbed_irq.cpp' module to remove external/gpio IRQ handling functionality. This functionality is moved into
'mbed_gpio_irq.cpp' module.
3. Updated code comments, added for demonstrating the use of init param structures in the irq modules.

drivers:platform:mbed: Updated Mbed IRQ platform drivers for handling GPIO irq's

---

include/jesd204.h
jesd204/jesd204-core.c
jesd204/jesd204-fsm.c
jesd204/jesd204-priv.h

More details:
https://wiki.analog.com/resources/tools-software/linux-drivers/jesd204/jesd204-fsm-framework
The no-OS specific code is marked accordingly (/* no-OS specific */).

jesd204: Adding jesd204-fsm support on no-OS

---

drivers/axi_core/jesd204/axi_adxcvr.c
drivers/axi_core/jesd204/xilinx_transceiver.c
drivers/dac/ad9144/ad9144.c
drivers/frequency/ad9523/ad9523.c
projects/fmcdaq2/src/app/fmcdaq2.c

Fixes for solving the problems that generate warnings during the make process for the fmcdaq2 project. 
These will decrease the number of warnings for other projects using the modified driver files.

Removal of  warnings generated during make for the fmcdaq2 project

---

drivers/platform/maxim/max32670/maxim_spi.c
drivers/platform/maxim/max32670/maxim_spi.h

The SPI drivers for MAX32670 and similar to MAX32660. The source and header files are therefore
used from MAX32660 folder. The SPI communication is tested onto MAX32670 EVKIT MCU board and
it is working fine.
As code is used from MAX32660, original author information is kept as-is.

drivers:platform:maxim:max32670 Initial implementation of SPI drivers for MAX32670

---

projects/adxrs290-pmdz/src/common/common_data.c
projects/adxrs290-pmdz/src/platform/pico/parameters.h
projects/iio_demo/src/common/common_data.c

irq_ctrl_id should be 0 (specific to NVIC IRQ controller) for timer interrupts.

Add correct value for irq_ctrl_id in projects

---

drivers/adc/adaq8092/adaq8092.h

Fix the device initialization parameters structure header comment.

drivers:adc:adaq8092: fix header comment

---

drivers/adc/ad400x/ad400x.c
drivers/adc/ad400x/ad400x.h

SPI engine used in this driver is FGPA specific. Hence added a
macro to switch between using standard SPI for specifically with
MCU.
Signed-off-by: Naveen Godekeresiddaramaiah <Naveen.Godekeresiddaramaiah@analog.com>

drivers:adc:ad400x: Added macro USE_STANDARD_SPI

---

drivers/platform/maxim/max32660/maxim_i2c.c
drivers/platform/maxim/max32665/maxim_i2c.c
drivers/platform/maxim/max78000/maxim_i2c.c
drivers/platform/maxim/max78000/maxim_i2c.h

Fixed compilation errors and warnings for the I2C driver on Maxim
platform.

drivers:platform:maxim: Fixed errors and warnings

---

drivers/platform/aducm3029/aducm3029_gpio_irq.c
drivers/platform/aducm3029/aducm3029_irq.c
projects/adxrs290-pmdz/src/common/common_data.c
projects/adxrs290-pmdz/src/platform/aducm3029/main.c
projects/adxrs290-pmdz/src/platform/aducm3029/parameters.h

- Added implementation for IRQ set_priority API for aducm3029 platform for NVIC controller.
- Added implementation for IRQ set_priority API for aducm3029 platform for GPIO controller.
- Added extra checks for irq_id in case of external interrupt event for GPIO controller.
- Fixed the trigger level setting for GPIO controller.
- Added GPIO trigger example for aducm3029 platform for adxrs290-pmdz project.

ADUCM3029 platform set irq priority

---

drivers/accel/adxl313/adxl313.h
drivers/accel/adxl345/adxl345.h
drivers/accel/adxl355/adxl355.h
drivers/accel/adxl367/adxl367.h
drivers/accel/adxl372/adxl372.h
drivers/adc-dac/ad5592r/ad5592r-base.h
drivers/adc/ad7091r5/ad7091r5.h
drivers/adc/ad799x/ad799x.h
drivers/cdc/ad7156/ad7156.h
drivers/cdc/ad7746/ad7746.h
drivers/dac/ad5629r/ad5629r.h
drivers/dac/ad5686/ad5686.h
drivers/impedance-analyzer/ad5933/ad5933.h
drivers/io-expander/adp5589/adp5589.h
drivers/platform/xilinx/xilinx_i2c.c
drivers/potentiometer/ad5110/ad5110.h
drivers/potentiometer/ad525x/ad525x.h
drivers/temperature/adt7420/adt7420.h
include/no_os_i2c.h

Typedefs are no longer supported on the no-os repository.
Adjust drivers accordingly.

include: no_os_i2c: remove typedefs

---

drivers/adc/ad469x/ad469x.c

The AD469x expects a delay to be elapsed between the 5 bit command word
and the rising CS. The delay is proportional to additional 19 SCK pulses.
Hence, the exit conversion spi transaction in now 3 bytes.

drivers:adc:ad469x: Correct way to exit conversion mode.

---

drivers/platform/maxim/max32670/maxim_uart.c
drivers/platform/maxim/max32670/maxim_uart.h

The baseline code for this is taken from UART implementation of MAX32660.
Below minor changes done w.r.t. to implementation:
1. Removed the switch case for UART 'mark' and 'space' parity as MAX32670 does not
support these parity modes. For odd and even parity, MAX32670 provides two modes-
mode0 and mode1. As no_os_uart_parity enum provides only odd and even parity settings,
mode0 of odd and even parity is used for max32670. This is done in uart init function.
2. MAX32670 does not support low and high flow control. It supports only enable/disable of flow control.
So, for both low and high flow enum switch case, MXC_UART_FLOW_EN value is set. This is done in uart init function.
3. 3rd argument to MXC_UART_Init() function is set as MXC_UART_APB_CLK. This is the max UART clock frequency …

drivers:platform:maxim:max32670 Initial implementation of UART platform drivers

---

drivers/platform/stm32/stm32_gpio_irq.c

EXTI->PR is availabe on most but not all stm32 MCU's. L4 family
for example defines PR1 and PR2 registers instead of just PR
hence the build fails without this modification.

stm32 gpio irq: use HAL macro instead of EXTI->PR

---

drivers/platform/stm32/stm32_gpio.c

GPIO_MODE is defined in stm32l5xx_hal_gpio.c instead of stm32l5xx_hal_gpio.h so it has to be redefined in stm32_gpio.c before it is being used.
MODE_INPUT and MODE_OUTPUT are not defined in STM32 L5 hal, instead GPIO_MODE_INPUT and GPIO_MODE_OUTPUT_PP have to be used to obtain the same functionality.

drivers:platform:stm32:stm32_gpio.c Fix build for L5 family

---

drivers/platform/stm32/stm32_gpio.c
drivers/platform/stm32/stm32_gpio.h
projects/adxrs290-pmdz/src/platform/stm32/parameters.c

Use the pull field from the no_os_gpio_param to initialize the GPIO
controller instead of the one from stm32_gpio_init_param.

Remove pull field from STM32 GPIO extra param

---

drivers/platform/maxim/max32670/maxim_gpio_irq.c
drivers/platform/maxim/max32670/maxim_gpio_irq.h
drivers/platform/maxim/max32670/maxim_irq.c
drivers/platform/maxim/max32670/maxim_irq.h

The IRQ platform drivers for MAX32670 are same as that of MAX32660.
The source files are copied from MAX32660 folder and below changes made:
1. Renamed 'max32660.h' include header with 'max32670.h'.
Rest of the code is unchanged. The code is tested on MAX32670 EVKIT for generating GPIO based IRQ event.
Original author information is kept as-is.

drivers:platform:maxim:max32670 Initial implementation of IRQ platform drivers

---

drivers/adc/ad7779/ad7779.c
drivers/adc/ad7779/ad7779.h

1) Added a parameter- 'read_from_cache' in the dev and init structure
2) Updated 'read_from_cache' of the dev structure, in the init function
3) The above parameter when set false, would perform an SPI query to read the bitfield value
4) read_from_cache when set true, would follow the existing flow of implementation by reading from the dev structure.
5) Corrected the mask value for DCLK_DIV set in the function and in the macro definition
Signed-off-by: Janani Sunil <janani.sunil@analog.com>

drivers:adc:ad7779:Updated getter functions with SPI read query

---

drivers/platform/stm32/stm32_gpio.h
drivers/platform/stm32/stm32_spi.c
drivers/platform/stm32/stm32_spi.h
drivers/platform/stm32/stm32_tdm.c
drivers/platform/stm32/stm32_tdm.h
drivers/platform/stm32/stm32_timer.h
drivers/platform/xilinx/gpio_extra.h
drivers/platform/xilinx/i2c_extra.h
drivers/platform/xilinx/spi_extra.h
drivers/platform/xilinx/xilinx_gpio.c
drivers/platform/xilinx/xilinx_i2c.c
drivers/platform/xilinx/xilinx_spi.c
projects/adrv9009/src/app/headless.c
projects/iio_demo/src/platform/stm32/parameters.h

Remove typedefs for the platform drivers since they are no longer supported on the no-os repository.

platform: typedefs remove

---

drivers/platform/stm32/stm32_gpio.c
drivers/platform/stm32/stm32_gpio.h
drivers/platform/stm32/stm32_spi.c

Add a field of type GPIO_InitTypeDef for the stm32 platform specific
gpio descriptor, instead of storing each of the structure's fields.
This fixes 3d616520f6fe03f8c34ea8e009eb9e942f1d1dd3.

drivers:platform:stm32:Restructure extra gpio desc

---

drivers/platform/stm32/stm32_timer.h

Remove family specific includes and simply use stm32_hal.h header file.

drivers:platform:stm32:stm32_timer.h: Fix includes

---

projects/adxrs290-pmdz/src/platform/stm32/parameters.c

Change pin mode from GPIO_MODE_IT_RISING to GPIO_MODE_INPUT

projects:adxrs290-pmdz: Fix SYNC pin mode for stm platfom

---

drivers/platform/stm32/stm32_spi.c
drivers/platform/stm32/stm32_spi.h

Previously, the stm32_spi_write_and_read function did not
configure the spi peripheral with the settings stored in the
spi device descriptor. This means that it was impossible to use
the driver to drive multiple slaves with different spi settings (
bus speed, spi mode, bit order) on the same spi bus.
This commit changes the behavior of spi_write_and_read on stm32
platform to reconfigure the spi peripheral before each transfer if
needed.
The condition to assess the need for reconfiguration is based on
- spi instance
- chip select
If any of the above changes between consecutive transfers, the
reconfiguration takes place. If they stay the same, reconfiguration
is not performed (optimization).
Tested on hardware with adxrs290 project, …

stm32 spi: configure peripheral before transfer

---

drivers/platform/maxim/max32670/maxim_delay.c

The maxim_delay.c file is reused from the existing max32660 folder, as delay functionality for
both max32660 and max32670 is identical.

drivers:platform:maxim:max32670 Implementation of delay platform drivers

---

drivers/frequency/adf4377/adf4377.c

Update init function to use conditional jumps where required, instead of
just returning the error code.

drivers: frequency: adf4377: update init

---

drivers/platform/maxim/max32670/maxim_gpio.c
drivers/platform/maxim/max32670/maxim_gpio.h

The GPIO drivers implementation is referred from the MAX32670 folder as both parts of identical GPIO implementation.
Few minor file edits done w.r.t. code styles and comments but the actual functionality is unaltered.

drivers:platform:maxim:max32670 Initial implementation of GPIO platform drivers

---

drivers/adc/adaq8092/adaq8092.c

Fix header comment return values for the getter function.

drivers: adc: adaq8092: fix header comm

---

tools/scripts/platform/xilinx/build_project.tcl

In Vitis, the created projects look like this in project explorer:
app_system
├── app
└── bsp
Previously we only built app, which also built bsp as a dependency.
But if we pass the -all flag, app_system is built too, and by doing so, a post-build rule is run that generates the BOOT.BIN every time.

xilinx: build Vitis workspace to generate BOOT.BIN

---

iio/iio.c
iio/iiod.c
iio/iiod.h
iio/iiod_private.h

- Reset the trigger id assigned to a device when the close command is received.
- Use array of chars instead of pointers for device id, trigger id, channel id and attribute name. With current implementation the pointers point to parser_buf which can change over the execution of the program, leading to unwanted changes for device id, trigger id, channel id or attribute name. This can happen when iiod_read_line reads a few characters, modifying parser_buf, but then returns an error (because not all data has been yet received). In this scenario iiod_parse_line is not called and device id, trigger id, channel id or attribute name will have garbage values until iiod_parse_line is called again.

IIOD pointer fix

---

iio/iio.c
iio/iio_types.h
iio/iiod.c
iio/iiod_private.h

Add cyclic buffer support when cyclic flag is given in OPEN command. The cyclic flag is kept until a CLOSE command is received.
When a device is opened in cyclic mode, the first buffer of samples pushed by the client, will be pushed continuously to the iio driver. submit function will be called continuously with the given samples.

iio: Add cyclic buffer support

---

iio/iio_app/iio_app.c

wifi.h should only be included if the used platform is ADUCM3029

iio:iio_app: Fix wifi include

---

drivers/adc/ad717x/ad717x.c
drivers/adc/ad717x/ad717x.h

1) Added an element for AD4116 in the ad717x_device_type enum 
2) Added a case for AD4116 in the ad717x_connect_analog_input() switch case 
3) Updated doxygen file headers
Signed-off-by: Janani Sunil <janani.sunil@analog.com>

drivers:adc:ad717x:Add support to AD4116

---

drivers/platform/pico/pico_spi.c
drivers/platform/pico/pico_spi.h

Add support for spi driver on pico platform such that communication is supported with multiple spi slaves, with different bus configuration.

drivers:platform:pico:pico_spi: Add support for multiple slaves

---

drivers/platform/generic/delay.c
drivers/platform/generic/generic_gpio.c
drivers/platform/generic/generic_spi.c
drivers/platform/generic/i2c.c
drivers/platform/generic/no_os_timer.c
drivers/platform/generic/no_os_uart.c

Use NO_OS_UNUSED_PARAM macro for the unused parameters in the function
implementations.

platform: generic: use util macros

---

drivers/platform/generic/i2c.c

Rename the i2c functions with `generic_` prefix.
Use the available i2c platform ops functions.

platform: generic: i2c: update implementation

---

drivers/platform/generic/generic_axi_io.c
drivers/platform/generic/generic_delay.c
drivers/platform/generic/generic_i2c.c
drivers/platform/generic/generic_timer.c
drivers/platform/generic/generic_trng.c
drivers/platform/generic/generic_uart.c

Add `generic_prefix` to all generic platform driver implementations.

platform: generic: add generic prefixes

---

drivers/platform/pico/pico_i2c.c

Add dynamic configuration for baud-rate to be able to support multiple I2C devices on the same I2C hardware instance.

drivers:platform:pico:pico_i2c: Add dynamic config for baud rate

---

iio/iio.c
iio/iio.h
iio/iio_types.h

In previous implementation of IIO context attributes, the attributes were tied-up with IIO device. However, the context attributes must be global and independent of devices/triggers. In case if none of the device is present (or not initialized), context attributes must be populated into IIO client to convey IIO/firmware global information.
Updated code to remove device dependency for context attributes and tested with IIO oscilloscope client.

iio: Updates and issue fixes related to IIO context attributes

---

drivers/platform/mbed/mbed_timer.cpp
drivers/platform/mbed/mbed_timer.h

1. Renamed the function names to start with prefix 'mbed_'
2. Added mbed_timer_ops platform operations structure

drivers:platform:mbed Added platform ops structure for timer platform drivers

---

drivers/platform/maxim/max32660/maxim_timer.c

Due to an SDK update, some fields were removed from the mxc_tmr_cfg_t struct. Do not set these since they are now undefined.

Fix timer driver (MAX32660)

---

projects/iio_demo/src/platform/linux/platform_src.mk

Fix the uart, delay platform driver source file paths.

projects: iio_demo: linux: fix platform paths

---

drivers/platform/generic/generic_timer.c

- add `get_elapsed timer` function
- use platform ops

platform: generic: timer: update driver

---

drivers/platform/maxim/max32650/maxim_spi.c
drivers/platform/maxim/max32655/maxim_spi.c
drivers/platform/maxim/max32660/maxim_spi.c
drivers/platform/maxim/max32665/maxim_spi.c
drivers/platform/maxim/max32670/maxim_spi.c
drivers/platform/maxim/max78000/maxim_spi.c

- implement SPI reconfiguration before transfers.
- replace `spi_write_and_read()` with a `spi_transfer()` call.

Maxim SPI reconfiguration

---

drivers/platform/mbed/mbed_i2c.cpp

Added mbed API call to set the I2C frequency set in init parameters.

drivers:platform:mbed Added I2C frequency set function call

---

iio/iio_app/iio_app.c

Initialize iio_init_param.cntx_attrs to NULL to avoid undefined behavior when accessing iio_init_param.cntx_attrs.

iio_app: Initialize iio_init_param.cntx_attrs

---

drivers/eeprom/24xx32a.c
drivers/eeprom/24xx32a.h

Added basic functions for byte by byte read and write of 24XX32A EEPROM. The I2C interface is required for this EEPROM. The low level initialization is done with the help of I2C platform drivers and currently tested for mbed platform.

drivers:eeprom: Added initial drivers for Microchip 24AA32A/24LC32A EEPROM

---

drivers/axi_core/jesd204/axi_adxcvr.c

The checking of status bits [5] and [6] introduced in the ADXCVR HDL and the synchronization with the Linux driver for staus check.

Addition of ADXCVR status bits for more specific check

---

drivers/platform/pico/pico_spi.c
drivers/platform/pico/pico_uart.c
projects/eval-adxl355-pmdz/src.mk
projects/eval-adxl355-pmdz/src/platform/pico/main.c
projects/eval-adxl355-pmdz/src/platform/pico/parameters.c
projects/eval-adxl355-pmdz/src/platform/pico/parameters.h
projects/eval-adxl355-pmdz/src/platform/pico/platform_src.mk
tools/scripts/pico.mk

- Initialize uart with stdio API to be able to use stdio related functions (e.g. printf).
- Remove wrap function for ldivmod to avoid linker errors when no_os_util is used.
- Rework spi driver for pico platform: use CS as GPIO (if used as SPI function the CS is deasserted by
default after every 8 bits), use pico_spi_transfer in pico_spi_write_and_read to remove duplicated code, use only chip_select for the slave_id creation
- Add support for pico platform for eval-adxl355-pmdz for dummy example, iio example and iio example with gpio trigger.

Pico support for adxl355 and pico platform changes

---

drivers/platform/stm32/stm32_gpio.h

Fix ifndef and define for stm32_gpio header file.

drivers: stm32: gpio: fix header defines

---

projects/adxrs290-pmdz/builds.json
projects/eval-adxl355-pmdz/builds.json

- Add pico platform to builds.json for eval-adxl355-pmdz project.
- Remove _max32655 from file name for pico platform in builds.json for adxrs290-pmdz project.

Add support for pico platform in builds.json for eval-adxl355-pmdz project

---

projects/ad9371/src/app/headless.c

The removal of the cpll_enable member from adxcvr_init and addition of member names in initialization.
Problem signaled by issue https://github.com/analogdevicesinc/no-OS/issues/1496

projects:ad9371:src:headless.c ADXCVR init fix

---

tools/scripts/platform/xilinx/util.tcl

The update of the make run command so that it accepts arbitrary bit file names for programming the FPGA (other than system_top.bit).

tools:scripts:platform:xilinx:util.tcl make run command update

---

drivers/eeprom/24xx32a/24xx32a.c

As per datasheet, the stop condition is not expected after sending address bytes. Instead, repeated start condition needs to be generated (which would be done by subsequent i2c_read function call). Therefore, set stop bit to 0.

drivers:eeprom:24xx32a setting i2c stop bit during eeprom address write

---

iio/iio.c

Corrected the for loop condition while copying context attr values into IIO xml string.

iio: Fixed bug in storing context attrs into xml string

---

drivers/platform/maxim/max32665/maxim_uart.c

Set the UART mapping, so that the RX/TX signals will be routed to the JTAG header on the MAX32665 FTHR board. Even though this is board specific, I think it would be useful to have these changes applied, as it's the only MAX32665/6 board we're using right now.
The MAP_X sets the GPIOs that will be configured as UART.
MAP_A: pins 20, 21.
MAP_B: pins 12, 13.

MAX32665: change UART pins mapping

---

tools/scripts/maxim.mk

To find the serial number of the CMSIS-DAP interface:
lsusb -v
lsusb -v | grep iSerial
Then pass the serial number to the run command:
make run JTAG_CABLE_ID=0123456789abcdef
This allows to target one particular CMSIS-DAP programmer if several of them are connected to the PC.

JTAG_CABLE_ID specifier for maxim platform

---

tools/scripts/aducm.mk
tools/scripts/generic.mk
tools/scripts/maxim.mk

Move part of the logic to generic.mk (previously in maxim.mk). Use the generated .id file to specify the JTAG device serial no for both aducm3029 and maxim platforms.

JTAG_CABLE_ID for aducm3029 platform

---

drivers/platform/maxim/max32650/maxim_spi.c
drivers/platform/maxim/max32655/maxim_spi.c
drivers/platform/maxim/max32660/maxim_spi.c
drivers/platform/maxim/max32665/maxim_spi.c
drivers/platform/maxim/max32670/maxim_spi.c
drivers/platform/maxim/max78000/maxim_spi.c

Either the TX or RX buffer may be NULL in case only one direction is required. Set the transfer length to 0 in such case.

Maxim RX/TX SPI transfer length

---

drivers/platform/xilinx/xilinx_irq.c
projects/ad9361/src/main.c
projects/ad9361/src/parameters.h

Specify correct callbacks for tx_dmac and rx_dmac.

projects:ad9361:src:main.c IRQ example fix

---

projects/adv7511/src/main.c

Use proper timer init structure when assigning the xil_timer_ops structure.
Fixes: 62bf63b ("platform: xilinx: timer: use platform ops")

projects: adv7511: fix platform ops init

---

iio/iio.c

@pcercuei confirmed that the behavior of the regular IIOD is to leave the trigger assigned to the device even after a close command is received.
Thus reverting the changes in which the trigger id was unassigned when a close command is received.
https://github.com/analogdevicesinc/no-OS/pull/1553 is no longer needed if this revert is merged.

Revert "iio:iio.c: Reset trigger id of the device when closing device"

---

jesd204/jesd204-core.c

jesd204_copy_link_params() copy the SYSREF settings form source to destination.

drivers: jesd204 :jesd204-core: copy_link_params() sysref param fix

---

jesd204/jesd204-core.c

jesd204_copy_link_params() copy the SYSREF settings form source to destination.
Fixes: 08747d9 (jesd204: Adding jesd204-fsm support on no-OS)

drivers: jesd204 :jesd204-core: copy_link_params() sysref param fix 2021_R2

---

drivers/adc/adc_demo/iio_adc_demo.c

Fix ext_buf memory access in iio_adc_demo.
Fixes: c81e7eab ("drivers: adc: adc_demo: fix syntax error")

adc: adc_demo: iio_adc_demo: Fix memory access

---

iio/iio.c
util/no_os_circular_buffer.c

Corrected the size of the circular buffer allocated in the iio_open_dev function.
Signed-off-by: Gudla <Saikiran.Gudla@analog.com>

iio: fix the issue with buffer size allocation

---

drivers/afe/ad413x/ad413x.c
drivers/afe/ad413x/ad413x.h

Updated chip ID to 0x4 as released silicon has configured same

drivers:afe:ad413x Updated chip ID

---

drivers/adc/ad463x/ad463x.c

The function was present in the header file but its implementation was missing from the source file.

adc: ad463x: Implement ad463x_spi_reg_read_masked()

---

drivers/adc/ad7768/ad7768.h

Fix bit definition for the AD7768 power mode.
Fixes: 825a83f ("ad7768: Initial commit")
Issue: #1582

drivers: adc: ad7768: fix pwr mode bit def

---

drivers/platform/xilinx/xilinx_uart.c

Replace legacy_callback with callback for specifying UART interrupt handler.

drivers:platform:xilinx:xilinx_uart.c set callback

---

network/tcp_socket.c

Update the true random generator fill buffer function with the correct naming.
Fixes: 44cdc3e ("include:*.h Add "no_os_" prefix to /include files")

network: tcp_socket: fix config rng

---

drivers/adc/ad713x/ad713x.c

The output data frame for the ad4134 device was missing.
Fixes: 6eda224 ("drivers:adc:ad713x: update driver to work with new silicon")
Related issue: #1568

drivers: adc: ad713x: add ad4134 data format

---

projects/ad74413r/src/common/common_data.c
projects/ad74413r/src/platform/maxim/parameters.h
projects/ad74413r/src/platform/stm32/parameters.h
projects/ad7746-ebz/src/app/headless.c
projects/adt7420-pmdz/src/common/common_data.c
projects/adt7420-pmdz/src/platform/maxim/parameters.h
projects/aducm3029_flash_demo/src/main.c
projects/eval-adxl313z/src/common/common_data.c
projects/eval-adxl313z/src/platform/stm32/parameters.h
projects/eval-adxl355-pmdz/src/common/common_data.c
projects/eval-adxl355-pmdz/src/platform/maxim/parameters.h
projects/eval-adxl355-pmdz/src/platform/pico/parameters.h
projects/eval-adxl355-pmdz/src/platform/stm32/parameters.h
projects/iio_aducm3029/src/main.c
projects/max11205pmb1/src/common/common_data.c
projects/max11205pmb1/src/platform/maxim/parameters.h

Add missing platform_ops entry to struct no_os_uart_init_param.
Fixes: f6f2df33 ("drivers:platform: Add UART platform ops")

projects: Add platform_ops entry to struct no_os_uart_init_param

---

projects/ad9361/src/main.c

Disable swap-ports-enable for CMOS Mode in case ofad9364 device.

ad9361:src:main Set swap ports to 0 for ad9364

---

drivers/temperature/adt7420/adt7420.c
drivers/temperature/adt7420/adt7420.h

1) Changes with SPI/I2C write function structuring
2) Changes with num_bytes calculation in SPI register read function
3) Updates with temperature register read function
4) Updated all register addresses for SPI to uint16_t as the 9th bit is set to represent that it is a 16 bit register in certain cases.
5) Added switch cases for I2C for determining the register size

Adt7420 driver corrections

---

drivers/api/no_os_uart.c
drivers/platform/aducm3029/aducm3029_uart_stdio.c
drivers/platform/aducm3029/aducm3029_uart_stdio.h
drivers/platform/maxim/max32650/maxim_stdio.c
drivers/platform/maxim/max32650/maxim_stdio.h
drivers/platform/maxim/max32655/maxim_stdio.c
drivers/platform/maxim/max32655/maxim_stdio.h
drivers/platform/maxim/max32660/maxim_stdio.c
drivers/platform/maxim/max32660/maxim_stdio.h
drivers/platform/maxim/max32665/maxim_stdio.c
drivers/platform/maxim/max32665/maxim_stdio.h
drivers/platform/maxim/max78000/maxim_stdio.c
drivers/platform/maxim/max78000/maxim_stdio.h
drivers/platform/stm32/stm32_uart_stdio.c
drivers/platform/stm32/stm32_uart_stdio.h
include/no_os_uart.h
projects/ad74413r/src/platform/maxim/main.c
projects/ad74413r/src/platform/stm32/main.c
projects/ad7746-ebz/src/app/headless.c
projects/adt7420-pmdz/src/platform/maxim/main.c
projects/aducm3029_flash_demo/src/main.c
projects/cn0565/src/app/main.c
projects/eval-adxl313z/src/platform/stm32/main.c
projects/eval-adxl355-pmdz/src/platform/maxim/main.c
projects/eval-adxl355-pmdz/src/platform/stm32/main.c
projects/max11205pmb1/src/platform/maxim/main.c

This functionality was scattered around platforms under different names. Fix that, use a common name.
Because this is an optional feature, no_os_uart.c imlplements an empty version with weak linkage. This means that platforms that implement this feature override the weak function whereas the rest of them can simply not implement it.

no_os_uart_stdio common API across platforms

---

drivers/rf-transceiver/hmc630x/hmc630x.c
drivers/rf-transceiver/hmc630x/hmc630x.h

HMC6300 is a millimeterwave transmitter within 57 and 64 GHz.
HMC6301 is a millimeterwave receiver within 57 and 64 GHz.
This initial driver version supports reading/writing registers,
reading/writing the whole register map, setting a few specific
parameters and setting the VCO frequency and making sure the
PLL is locked.

add hmc6300 and hmc6301 driver

---

drivers/platform/maxim/max32650/maxim_uart_stdio.c
drivers/platform/maxim/max32650/maxim_uart_stdio.h
drivers/platform/maxim/max32655/maxim_uart_stdio.c
drivers/platform/maxim/max32655/maxim_uart_stdio.h
drivers/platform/maxim/max32660/maxim_uart_stdio.c
drivers/platform/maxim/max32660/maxim_uart_stdio.h
drivers/platform/maxim/max32665/maxim_uart_stdio.c
drivers/platform/maxim/max32665/maxim_uart_stdio.h
drivers/platform/maxim/max78000/maxim_uart_stdio.c
drivers/platform/maxim/max78000/maxim_uart_stdio.h
projects/ad74413r/src/platform/maxim/parameters.h
projects/ad74413r/src/platform/maxim/platform_src.mk
projects/adt7420-pmdz/src/platform/maxim/parameters.h
projects/adt7420-pmdz/src/platform/maxim/platform_src.mk
projects/adxrs290-pmdz/src/platform/maxim/parameters.h
projects/adxrs290-pmdz/src/platform/maxim/platform_src.mk
projects/eval-adxl355-pmdz/src/platform/maxim/parameters.h
projects/eval-adxl355-pmdz/src/platform/maxim/platform_src.mk
projects/iio_demo/src/platform/maxim/parameters.h
projects/iio_demo/src/platform/maxim/platform_src.mk
projects/max11205pmb1/src/platform/maxim/parameters.h
projects/max11205pmb1/src/platform/maxim/platform_src.mk

to make it consistent with the other platforms imlpementing this feature.

rename maxim_stdio.c/.h to maxim_uart_stdio.c/.h

---

drivers/platform/maxim/max32670/maxim_rtc.c
drivers/platform/maxim/max32670/maxim_rtc.h
drivers/platform/maxim/max32670/maxim_spi.c

Adding rtc modules
Copying RTC modules from max32660 as-is, as they are required in irq module
Fixed typo with spi desc
Fixed the typo with spi descriptor in init function

drivers:platform:maxim:max32670 Max32670 platform driver updates

---

drivers/api/no_os_irq.c

Return EINVAL only if pltform_ops is not defined.
Fixes: c2f01550 ("drivers: api: Fix the API pointer checks")

drivers: api: no_os_irq: Fix check in no_os_irq_set_priority

---

drivers/accel/adxl355/adxl355.c

Include no_os_delay.h in adxl355.c
Fixes: 22ffa3c1 ("drivers: accel: adxl355: Add delay after soft reset")

drivers: accel: adxl355: Include no_os_delay.h

---

drivers/platform/xilinx/xilinx_delay.c
projects/ad5758-sdz/src.mk
projects/ad7124-4sdz/src.mk
projects/ad719x/src.mk

Remove use of float in microsecond calculation.

xilinx:xilinx_delay.c Remove use of float

---

drivers/platform/mbed/mbed_uart.cpp
drivers/platform/mbed/mbed_uart.h

1. Created separate APIs and platform ops for UART and VCOM functionality
2. Updated to init structure to better handle selection of stdio console port

drivers:platform:mbed Split functionality for VCOM and UART

---

drivers/platform/maxim/max32650/maxim_spi.c

Fix the CS pin vssel selection for the MAX32650.

CS vssel fix on MAX32650

---

iio/iio.c
tools/scripts/generic_variables.mk

Add the NO_OS_VERSION compiler define that contains:
- git branch name
- git hash
- optionally, the -modified suffix
Examples:
master-9271c4ee2-modified
2019_r2-abcdef123

NO_OS_VERSION: git branch, hash and modified

---

projects/adt7420-pmdz/src/platform/maxim/parameters.c

Declare the adt7420_i2c_extra for both the DUMMY and IIO examples, since it's used in both cases.

ADT7420 declare i2c_extra for all examples

---

drivers/platform/maxim/max32650/maxim_init.c
drivers/platform/maxim/max32655/maxim_init.c
drivers/platform/maxim/max32660/maxim_init.c
drivers/platform/maxim/max32665/maxim_init.c
drivers/platform/maxim/max32670/maxim_init.c
drivers/platform/maxim/max78000/maxim_init.c

Add MXC_Delay to Maximi init function so that the en state of the SysTick timer is saved.
Fixes: 2355712e2be55e019070b

platform:maxim:max*:maxim_init.c Add delay to init

---

drivers/dac/max538x/max538x.c
drivers/dac/max538x/max538x.h

added initial driver implementation for max538x family.
For more info: https://www.analog.com/media/en/technical-documentation/data-sheets/MAX5380-MAX5382.pdf
Signed-off-by: Jose Ramon San Buenaventura <jose.sanbuenaventura@analog.com>

drivers:dac: added max538x family support

---

projects/adt75/src/examples/iio_example/iio_example.c

Add missing parameters for the iio_app_run function call.
Fixes: 52e38c6 ("projects: adt75: ADT75 project")

projects: adt75: fix iio_example

---

drivers/dac/ltc2672/ltc2672.c
drivers/dac/ltc2672/ltc2672.h

Added driver implementation for ltc2672.
More information: https://www.analog.com/media/en/technical-documentation/data-sheets/ltc2672.pdf
Signed-off-by: Jose Ramon San Buenaventura <jose.sanbuenaventura@analog.com>

drivers:dac: added ltc2672 support.

---

iio/iio_app/iio_app.c

Replace `ADUCM3029_PLATFORM` with the current flag used on the no-OS repository (`ADUCM_PLATFORM`).

iio: iio_app: fix aducm cflag

---

tools/scripts/maxim.mk

There are some cases in which the MaximSDK doesn't provide the ARM compiler. In such a situation, the sdkopen command will fail, since the ARM_COMPILER_PATH variable is empty. Assign it to the path of the ARM none-eabi toolchain, in case there is one in a different directory.

tools:scripts:maxim.mk: Alternative compiler path

---

drivers/platform/stm32/stm32_uart.c

Populate all the members of no_os_uart_desc in stm32_uart_init.

drivers:platform:stm32:stm32_uart.c Fill desc

---

iio/iio.c
tools/scripts/generic_variables.mk

Rewrite the NO_OS_VERSION compiler define and modify iio.c so that it is correctly included in the xml header.
Fixes: fdfaea1c8a6e

scripts:generic_variables.mk Fix NO_OS_VERSION

---

drivers/platform/stm32/stm32_i2c.c

In order to read the board info from 24xx32a eeprom on the adi eval boards, repeated start condition is required. Hence, implemented I2C transaction with repeated start or stop bit option for stm32 platform.

drivers:platform:stm32 Stop bit implementation.

---

drivers/photo-electronic/adpd188/iio_adpd188.c

Add scan_index property to the iio adpd188 channel definition such that the iio channels are properly indexed.

drivers:photo-electronic:iio_adpd188: scan index

---

projects/iio_adpd1080/src/main.c

Fix the timer ops initialization structure by passing the proper platform ops.

projects: iio_adpd1080: add timer ops

---

network/tcp_socket.c
network/tcp_socket.h

- network:tcp_socket: set hostname
- network:tcp_socket: init SSL context
- network:tcp_socket: do not force cert verify

network: tcp_socket: initialization updates

---

drivers/platform/maxim/max32650/maxim_irq.c
drivers/platform/maxim/max32655/maxim_irq.c
drivers/platform/maxim/max32660/maxim_irq.c
drivers/platform/maxim/max32665/maxim_irq.c
drivers/platform/maxim/max32670/maxim_irq.c
drivers/platform/maxim/max78000/maxim_irq.c
projects/ad74413r/src/platform/maxim/platform_src.mk
projects/adt75/src/platform/maxim/platform_src.mk
projects/adxrs290-pmdz/src/platform/maxim/platform_src.mk
projects/eval-adxl313z/src/platform/maxim/platform_src.mk
projects/eval-adxl355-pmdz/src/platform/maxim/platform_src.mk
projects/iio_demo/src/platform/maxim/platform_src.mk
projects/max11205pmb1/src/platform/maxim/platform_src.mk

None of the no-OS specific RTC API was used for the interrupt driver, thus this dependency should be removed.

Remove IRQ dependency on RTC

---

drivers/platform/stm32/stm32_gpio.c
drivers/platform/stm32/stm32_gpio.h
drivers/platform/stm32/stm32_spi.c
drivers/platform/stm32/stm32_spi.h
projects/ad74413r/src/platform/stm32/parameters.h
projects/adxrs290-pmdz/src/platform/stm32/parameters.c
projects/adxrs290-pmdz/src/platform/stm32/parameters.h
projects/cn0565/src/app/main.c
projects/cn0565/src/app/parameters.h
projects/eval-adxl313z/src/platform/stm32/parameters.h
projects/eval-adxl355-pmdz/src/platform/stm32/parameters.h

Use port in no_os_gpio_init_param in GPIO initialization for STM32 platforms and remove port from stm32_gpio_init_param.

Use port in no_os_gpio_init_param in STM32 platforms

---

tools/scripts/libraries.mk

Use the proper lib target variable for the mbedtls library.
Fixes: d842815 ("tools:scripts: Move libraries code to libraries.mk")

tools: scripts: fix mbedtls integration

---

projects/ad9361/src/parameters.h

Set  baudrate of 115200 for IIO application on MB platforms.

Set correct baud for iio application for the ad9361 project

---

drivers/rtc/pcf85263/pcf85263.c
drivers/rtc/pcf85263/pcf85263.h

The PCF85263 is a CMOS Real-Time Clock (RTC) and calendar optimized for low power consumption and with automatic switching to battery on main power loss.

drivers: rtc: pcf85263: initial commit

---

drivers/platform/pico/pico_gpio.c

Fix implementation for setting gpio direction.
Use gpio_set_dir API instead of gpio_set_input_enabled.
Fixes: 8db5be8 ("platform:pico Add gpio driver")

platform: pico: pico_gpio: Fix implementation for gpio dir set

---

drivers/rf-transceiver/hmc630x/hmc630x.c
drivers/rf-transceiver/hmc630x/hmc630x.h
drivers/rf-transceiver/hmc630x/iio_hmc630x.c
drivers/rf-transceiver/hmc630x/iio_hmc630x.h

Make some changes to the hmc630x device driver (new features, mainly getter functions and more init params).
Add the hmc630x iio device implementation that exposes the device driver to iio clients through iiod.

hmc630x iio device

---

drivers/platform/linux/linux_spi.c
drivers/platform/stm32/stm32_spi.c

- platform: stm32: stm32_spi: Add transfer API with delays support
- platforms: linux: linux_spi: Add cs_change_delay for SPI transfer

SPI transfer delay STM32 and Linux

---

drivers/display/nhd_c12832a1z/nhd_c12832a1z.c

Call `no_os_spi_remove` function for the spi descriptor.
Fixes: e88cc38 ("drivers: display: nhd_c12832a1z: initial commit")

display: nhd: fix function call for spi

---

drivers/platform/maxim/max32650/maxim_gpio.h
drivers/platform/maxim/max32650/maxim_spi.h
drivers/platform/maxim/max32655/maxim_gpio.h
drivers/platform/maxim/max32655/maxim_i2c.h
drivers/platform/maxim/max32655/maxim_spi.h
drivers/platform/maxim/max32655/maxim_uart.h
drivers/platform/maxim/max32660/maxim_gpio.h
drivers/platform/maxim/max32660/maxim_i2c.h
drivers/platform/maxim/max32660/maxim_spi.h
drivers/platform/maxim/max32660/maxim_uart.h
drivers/platform/maxim/max32665/maxim_gpio.h
drivers/platform/maxim/max32665/maxim_i2c.h
drivers/platform/maxim/max32665/maxim_spi.h
drivers/platform/maxim/max32665/maxim_uart.h
drivers/platform/maxim/max32670/maxim_gpio.h
drivers/platform/maxim/max78000/maxim_gpio.h
drivers/platform/maxim/max78000/maxim_i2c.h
drivers/platform/maxim/max78000/maxim_spi.h
drivers/platform/maxim/max78000/maxim_uart.h

The gpio.h header is required for the vssel configuration.

Add missing header

---

tools/scripts/libraries.mk

Add extra CFLAG entry required for the noos_mbedtls_config.h include.

tools: scripts: mbedtls: add custom setting

---

projects/ad74413r/src/examples/iio_trigger_example/iio_trigger_example.c
projects/adxrs290-pmdz/src/examples/iio_timer_trigger_example/iio_timer_trigger_example.c
projects/adxrs290-pmdz/src/examples/iio_trigger_example/iio_trigger_example.c
projects/iio_demo/src/examples/iio_timer_trigger_example/iio_timer_trigger_example.c

Remove iio_desc pointer assignment: double pointer was removed in 2df74e4 ("iio::iio_trigger.* Rem double pointer in trig struct"), leave simple pointer assignation after iio_app_init is performed.
Fixes: 62db110 ("projects Update iio examples with iio_app_desc")

projects: Remove iio_desc pointer assignment

---

drivers/platform/linux/linux_spi.c

Return 0 instead of positive value in case spi_transfer is successful to align with the rest of the platforms.

platform: linux: linux_spi: Return 0 in case of transfer success

---

drivers/platform/maxim/max32650/maxim_i2c.c
drivers/platform/maxim/max32655/maxim_i2c.c
drivers/platform/maxim/max32660/maxim_i2c.c
drivers/platform/maxim/max32665/maxim_i2c.c

The `current_freq` variable is not used.

platform: maxim: i2c: remove unused variable

---

drivers/rtc/pcf85263/pcf85263.c

Remove unused variable `chip_id`.

drivers:rtc:pcf85263: remove unused var

---

drivers/rtc/pcf85263/pcf85263.h

Fix the type of the i2c_desc declaration.
Fixes: 03b470d ("drivers: rtc: pcf85263: initial commit")

drivers: rtc: fix i2c desc declaration

---

libraries/mqtt/mqtt_client.c
libraries/mqtt/mqtt_client.h
libraries/mqtt/mqtt_noos_support.c
libraries/mqtt/mqtt_noos_support.h

Instead of allowing the user to configure only partially the timer for the mqtt, pass the entire init_param structure since some parameters might differ based on the platform used aside the platform ops.

mqtt: expose timer init params

---

drivers/adc/ad7779/ad7779.c

1) Added a delay after enabling clocks to the enabled channels. This is done to ensure that the next operation happens after the clocks are successfully enabled for every channel. 
2) Set and cleared AD7779_REG_SRC_UPDATE bit to reflect on the updated output data rate

drivers:adc:ad7779:Update initialization sequence

---

network/wifi/at_parser.c
network/wifi/wifi.c

The type of ret should be signed int when passed to the `NO_OS_IS_ERR_VALUE` which checks if the variable is < 0.

network: wifi: fix ret type

---

network/tcp_socket.c
network/tcp_socket.h

With the addition of the `cert_verify_mode` parameter (575a80c), macros defined inside `mbedtls/ssl.h` are used at initialization.
To avoid reincluding the ssl.h header file inside the application implemetation, move the include inside tcp_socket.h

network: tcp_socket: move mbedtls ssl header

---

.gitmodules
tools/scripts/azure_sdk_for_c.mk
tools/scripts/libraries.mk

Integrate azure-sdk-for-c into the no-os framework.

libraries: add azure-sdk-for-c support

---

tools/scripts/libraries.mk

mbedtls library can be build based on custom configuration file defined by the user. Although there is already a "generic" configuration file provided for the no-os framework (noos_mbedtls_config.h), allow the user to create its own custom config file since these are applications specific rather than framework specific.

tools: scripts: allow custom mbedtls config

---

include/no_os_pid.h
util/no_os_pid.c

This PID supports:
- setting Kp, Ki, Kd gains
- clipping output to a certain range to match the range of whatever PID is controlling (for example, for an 8-bit PWM, the algorithm would clip the output to a range between 0 and 255).
- hysteresis
- clipping internal integrator to a certain range to avoid overflow
The no_os_pid_control() must be caled in a loop and user is responsible for detecting when the control should stop by not calling it anymore.
This can be done either by characterizing the algorithm for a particular set of configuration parameters and finding a minimum number of iterations that make the output stable or by looking at the output and detecting when it sits within a satisfactory tolerance from the set point.

add PID control utility to no-OS

---

tools/scripts/maxim.mk

Currently only the header files from the Maxim SDK are linked. Add the SDK source files to the SRCS variable instead of the PLATFORM_SRCS so that they too will be linked/copied in the build directory.

Link Maxim source files

---

projects/ad4110/builds.json
projects/ad4110/src.mk

Add no_os_util.c to sources. Required after the addition of timestamps.

ad4110:src.mk Add no_os_util.c to sources

---

drivers/platform/pico/pico_spi.c
drivers/platform/stm32/stm32_spi.c

Use rx_buff and tx_buff in spi_transfer only if they are not null.
Fixes for stm32 and pico platform.

spi_transfer null buffers fix

---

drivers/frequency/adf4106/adf4106.c

Add prescaler init value to adf4106_init_latch_method.
Tested with adf4106.

adf4106:adf4106.c Add prescaler to the init latch initialization method.

---

.gitmodules
libraries/azure/noos-azure-toolchain.cmake
tools/scripts/azure_sdk_for_c.mk
tools/scripts/libraries.mk

- move submodule under `libraries/azure` folder
- add custom no-os cmake toolchain file for the azure library
Should fix the build issues related to: #1682

azure library updates

---

iio/iio.c
iio/iio.h

Added local backend support to provide IIO communication interface to non-PC based clients. Example is local display library packaged into application binary, where display acts as an IIO client and communicate with IIO library using internal events.

iio: Local backend support

---

drivers/platform/maxim/max32650/maxim_spi.c
drivers/platform/maxim/max32655/maxim_spi.c
drivers/platform/maxim/max32660/maxim_spi.c
drivers/platform/maxim/max32665/maxim_spi.c
drivers/platform/maxim/max32670/maxim_spi.c
drivers/platform/maxim/max78000/maxim_spi.c

Spi mode 1 and 2 are reversed compared to the no-os framework.

platform: maxim: spi: fix spi modes

---

drivers/adc/ad7779/ad7779.c
drivers/adc/ad7779/ad7779.h

According to the datasheet (page 78), the ADC reference is set using the ADC_MUX_CONFIG register, REF_MUX_CTRL bits.
Fixes: 2b8c1f7 ("ad7779: Initial Preliminary Version")
NOTE: the implementation was done according to the driver previous implementation (mask defines, bit defines, etc)

drivers: adc: ad7779: fix reference set

---

tools/scripts/libraries.mk

Besides the static libraries and the object files, there are also source dependency files generated due to the usage of custom mbedtls configuration files. Make sure that these files are also removed when calling the clean operation.

tools: scripts: mbetls: clean generated files

---

libraries/mbed/mbed_app.json
projects/adt7420-pmdz/src/platform/mbed/main.c
projects/adt7420-pmdz/src/platform/mbed/parameters.c
projects/adt7420-pmdz/src/platform/mbed/parameters.h
projects/adt7420-pmdz/src/platform/mbed/platform_src.mk
tools/scripts/generic.mk
tools/scripts/libraries.mk
tools/scripts/mbed.mk

- Added Mbed code support for adt7420-pmdz project.
- Modified iio_app.c file to support iio_example for Mbed platform.
- Created new mbed directory in libraries for mbed-os related files.
- Added mbed-os as the submodule to no-OS repository.
- Added make based build support for Mbed platform.
Note: For make based Mbed build we need to install some tool like mbed-cli1 and we need to set up some environment variables.

add Mbed platform support to no-OS

---

drivers/platform/maxim/max32650/maxim_spi.c
drivers/platform/maxim/max32650/maxim_spi.h
drivers/platform/maxim/max32655/maxim_spi.c
drivers/platform/maxim/max32655/maxim_spi.h
drivers/platform/maxim/max32660/maxim_spi.c
drivers/platform/maxim/max32660/maxim_spi.h
drivers/platform/maxim/max32665/maxim_spi.c
drivers/platform/maxim/max32665/maxim_spi.h
drivers/platform/maxim/max32670/maxim_spi.c
drivers/platform/maxim/max32670/maxim_spi.h
drivers/platform/maxim/max78000/maxim_spi.c
drivers/platform/maxim/max78000/maxim_spi.h
projects/ad74413r/src/platform/maxim/parameters.c
projects/adxrs290-pmdz/src/platform/maxim/parameters.c
projects/eval-adis/src/platform/maxim/parameters.c
projects/eval-adxl313z/src/platform/maxim/parameters.c
projects/eval-adxl355-pmdz/src/platform/maxim/parameters.c
projects/max11205pmb1/src/platform/maxim/parameters.c

For the number of slaves parameter camel case is used.
Switch to snake case to align with the rest of the parameters and comply to the current approach used in the no-OS framework.

drivers: maxim: spi: use snake case

---

.gitignore

For stm platform there are some extra source files generated. Make sure that these are ignored by git.

.gitignore: ignore generated files

---

projects/eval-ade9430/Makefile
projects/eval-ade9430/README.md
projects/eval-ade9430/builds.json
projects/eval-ade9430/src.mk
projects/eval-ade9430/src/app/iot_sample_common.c
projects/eval-ade9430/src/app/iot_sample_common.h
projects/eval-ade9430/src/app/main.c
projects/eval-ade9430/src/app/noos_mbedtls_config.h
projects/eval-ade9430/src/app/parameters.h

Add support for EVAL-ADE9430 Energy Meter project.
More information is provided in the [README.md](https://github.com/analogdevicesinc/no-OS/blob/staging/ade9430_prj/projects/eval-ade9430/README.md) file.
**NOTES:**
- Most of the parameters related to the Azure IoT and secure connection (such as certificates) were left populated with custom user specific values with the intention of providing proper example on how the formatting (i.e. cretificates) / configuration / server related values should look.
- The project is using the old structure (since it consists a lot of initializations / re-initializations, splitting it into way too many files it is pretty hard to follow, in my opinion 😄 )

projects: eval-ade9430: add support

---

projects/eval-ade9430/src/app/main.c

After the merge of cea0997, the num slaves parameter naming was changed.
Adapt the project accordingly.

projects: eval-ade9430: fix spi param

---

iio/iio_app/iio_app.c

Remove compilation warning related to format specifier in sprintf function.

iio:iio_app:iio_app.c Remove formatting warning

---

drivers/net/mdio_bitbang.c
drivers/net/mdio_bitbang.h

no_os_mdio API can have ops pointing to specific implementations.
This is one of many possible implementations of the API, by using
no_os_gpio in big banging fashion to create the MDC and MDIO signals.

add mdio implementation using gpio bit banging 

---

drivers/rf-transceiver/ad9361/ad9361.c

Charge Pump Current value is 6 bits wide, therefore the VCO Bias Tcf value for profile6 needs to be shifted with 6 bits instead of 3.
Fixes: a180216 ("ad9361: Add Fastlock Profile Support")

drivers: ad9361: fix fast lock addressing

---

projects/cn0561/builds.json

Rename hardware files used for building cn0561 to match the latest hdl releases.

projects: cn0561: update hardware files namings

---

projects/eval-adxl355-pmdz/src/platform/maxim/parameters.h

For the MAX32650FTHR board, the exposed SPI interface is SPI1. Modify the macro accordingly.

projects: eval-adxl355-pmdz: Fix SPI interface id

---

drivers/platform/aducm3029/aducm3029_delay.c
drivers/platform/aducm3029/aducm3029_timer.c
drivers/platform/aducm3029/aducm3029_timer.h
projects/adxrs290-pmdz/src/platform/aducm3029/parameters.h
projects/iio_adpd1080/src/main.c

Align the timer ops structure naming with the rest of the platform ops specific structures for aducm3029. All the other interfaces: spi, gpio, i2c, irq are using `aducm_` prefix, the timer being the only one using `aducm3029_` prefix.

aducm3029: timer: update timer ops naming

---

drivers/temperature/max31865pmb1/max31865.c
drivers/temperature/max31865pmb1/max31865.h

Add provisions for N-wire, filter, and RC time constant indicators.

drivers:temperature:max31865pmb1: add enchancements

---

iio/iio.c
iio/iio_types.h

When using the statically allocated buffer with circular buffer, make sure the used size is a multiple of the total requested number of bytes from the iio client.
This has to be done because the circular buffer cannot handle memory wrapping.

iio: iio.c: Fix buffer maximum length based on received request

---

drivers/temperature/max31865pmb1/max31865.c
drivers/temperature/max31865pmb1/max31865.h

Added provisions for N-wire,filter, and RC time constant indicators in init_param and device descriptor. Includes formatting corrections.

drivers:temperature: Enhancements and corrections for max31865.

---

drivers/platform/chibios/chibios_alloc.c
drivers/platform/chibios/chibios_delay.c
drivers/platform/chibios/chibios_gpio.c
drivers/platform/chibios/chibios_gpio.h
drivers/platform/chibios/chibios_i2c.c
drivers/platform/chibios/chibios_i2c.h
drivers/platform/chibios/chibios_spi.c
drivers/platform/chibios/chibios_spi.h

PR:
- add platform support for ChibiOS (https://www.chibios.org/dokuwiki/doku.php)
- added api implementations: i2c, gpio, spi, memory allocation, delay
- currently build is done within the ChibiOS sdk
- example projects: https://github.com/rbudai98/chibiOS-drivers

add chibios platform support

---

projects/dc2903a/Makefile
projects/dc2903a/builds.json
projects/dc2903a/src.mk
projects/dc2903a/src/common/common_data.c
projects/dc2903a/src/common/common_data.h
projects/dc2903a/src/examples/basic_example/basic_example.c
projects/dc2903a/src/examples/basic_example/basic_example.h
projects/dc2903a/src/examples/examples_src.mk
projects/dc2903a/src/platform/maxim/main.c
projects/dc2903a/src/platform/maxim/parameters.c
projects/dc2903a/src/platform/maxim/parameters.h
projects/dc2903a/src/platform/maxim/platform_src.mk
projects/dc2903a/src/platform/platform_includes.h

add example project for dc2903a/ltc2672 eval-board.
Signed-off-by: Marc Paolo Sosa <marcpaolo.sosa@analog.com>

projects: add dc2903a example project

---

projects/adt7420-pmdz/src/platform/maxim/parameters.h

Choose the I2C device id based on the target number.

projects: adt7420: fix parameters for various targets

---

drivers/rf-transceiver/ad9361/ad9361_api.c

Set the direction of the SYNC GPIO as output for achieving correct multichip synchronization.

ad9361:ad9361_api.c Set gpio_desc_sync as output

---

.gitignore
.gitmodules

The library is required to build projects for the mbed platform in
conjunction with https://github.com/analogdevicesinc/no-OS/commit/f8b147b38ba70c1e2541b9a3a5d0009776e8f8d7 .

libraries: add mbed-os submodule

---

drivers/axi_core/axi_dac_core/axi_dac_core.c
drivers/axi_core/axi_dac_core/axi_dac_core.h
projects/ad9081/src/app.c
projects/ad9172/src/main.c
projects/ad9361/src/main.c
projects/ad9371/src/app/headless.c
projects/ad9739a-fmc-ebz/src/ad9739a_fmc_ebz.c
projects/adrv9001/src/app/headless.c
projects/adrv9009/src/app/headless.c
projects/fmcdaq2/src/app/fmcdaq2.c
projects/fmcdaq3/src/app/fmcdaq3.c

Add effective rate setting of the DAC initialization parameters.
The default rate was set to 3, causing faulty transmissions. Details in: https://ez.analog.com/microcontroller-no-os-drivers/f/q-a/568422/adrv9364-adc_dma_example-and-dac_dma_example

drivers:axi_core:axi_dac_core Add rate member to init params

---

iio/iio_app/iio_app.c

The current implementation doesn't check the status value, thus making the scenario where the iio_app_desc is freed in the callback function (with the intent to stop the server) impossible.

Exit iio_app on callback error

---

projects/adt7420-pmdz/builds.json
tools/scripts/build_projects.py

- [tools:scripts:build_projects: add mbed support](https://github.com/analogdevicesinc/no-OS/commit/3a56a0a3a993606aee19ee50522d791f21be14f4)
- [projects: adt7420-pmdz: add mbed build support](https://github.com/analogdevicesinc/no-OS/commit/53f25a56cb06d6216886037531c43ee9ef4c3908)

mbed platform : add build support

---

drivers/platform/chibios/chibios_gpio.c

In file chibios_gpio.c:110 the ret val, should be inverse
Fixes: 26f0005("drivers/platform/chibios: chibios_gpio")

Chibios/gpio: init ret guard bug fix

---

projects/adrv9001/Makefile
projects/adrv9001/src.mk
tools/scripts/generic.mk
tools/scripts/generic_variables.mk
tools/scripts/mbed.mk

1. Added commands to create text files which contains cflags, cppflags and as flags which can be used in compilation step to avoid path length issues in window's.
2. If FLAGS contains \" then it is replaced by \\\" so that flgs text file can contain \"
3. Used := variable assignment for CFLAGS to avoid repeating of flags in compilation step. So we must use CFLAGS after inclusion of generic variable makefile.
4. Provided method to exclude source file from a directory in build.

Using no os scripts

---

drivers/api/no_os_pwm.c
drivers/axi_core/axi_pwmgen/axi_pwm.c
drivers/axi_core/axi_pwmgen/axi_pwm_extra.h
drivers/platform/aducm3029/aducm3029_pwm.c
drivers/platform/aducm3029/aducm3029_pwm.h
drivers/platform/aducm3029/iio_aducm3029.c
drivers/platform/mbed/mbed_pwm.cpp
drivers/platform/mbed/mbed_pwm.h
drivers/platform/stm32/stm32_gpio.c
drivers/platform/stm32/stm32_pwm.c
drivers/platform/stm32/stm32_pwm.h
include/no_os_pwm.h
projects/ad463x_fmcz/src.mk
projects/ad463x_fmcz/src/ad463x_fmc.c
projects/ad469x_fmcz/src.mk
projects/ad469x_fmcz/src/ad469x_fmcz.c
projects/ad713x_fmcz/src.mk
projects/ad713x_fmcz/src/ad713x_fmc.c
projects/adaq7980_sdz/src.mk
projects/cn0561/src.mk
projects/cn0561/src/cn0561.c
projects/iio_aducm3029/src.mk
projects/iio_aducm3029/src/main.c

* Additionally the gpio pin for pwm requires to be configured as alternate functionality.

drivers/platform/stm32: stm32 pwm support.

---

drivers/platform/xilinx/xilinx_timer.c

Since the platform ops are populated in the generic timer api after the platform specific timer initialization, the `no_os_timer_count_clk_set` won't work properly when called inside the platform specific init function. Instead use directly the `xilinx_timer_count_clk_set` function.

platform:xilinx:timer: fix init function

---

drivers/platform/xilinx/xilinx_gpio_irq.c

Replace callback_desc by no_os_callback_desc.

drivers:platform:xilinx:xilinx_gpio_irq.c Typo fix

---

drivers/afe/ad4110/ad4110.c
drivers/platform/xilinx/xilinx_gpio_irq.c
drivers/platform/xilinx/xilinx_irq.c
include/no_os_irq.h

Remove legacy_callback and legacy_config members in the callback descriptor structure.

Irq rem legacy members

---

projects/ad4110/src/app/parameters.h

Specify JB1 as DRDY pin for the AD4110 project. A connection between DOUT and JB1 will be required.

Ad4110 drdy pin set

---

drivers/dac/ad5791/ad5791.c
drivers/dac/ad5791/ad5791.h
legacy/device_commands/AD5791/Command.c
projects/cn0531/src/main.c

Add SPI read/write mask functions, linearity error compensation select API support.

drivers: dac: ad5791: Add spi mask functions, APIs

---

drivers/platform/stm32/stm32_tdm.c

Fixed typo in the stm32_resume_tdm_transfer() function

drivers:platform:stm32:Fix typo in stm32_tdm.c

---

drivers/frequency/ltc6953/ltc6953.c
drivers/frequency/ltc6953/ltc6953.h

Added driver implementation for LTC6953
More information: https://www.analog.com/media/en/technical-documentation/data-sheets/ltc6953.pdf
Signed-off-by: Mariel Tinaco <mariel.tinaco@analog.com>

drivers: frequency: add ltc6953 support.

---

drivers/platform/stm32/stm32_tdm.c

Fixed the typo with assigning the half complete callback

drivers:platform:stm32:Fixed typo in callback function

---

drivers/adc-dac/ad74416h/ad74416h.c

Make sure that the second frame from the 2-stage readback is a NOP sequence.

drivers: ad74416h: update read sequence

---

drivers/adc/ad469x/ad469x.h

For ad469x devices with WLCSP packaging set_busy is used to configure the bsy gpio output port.

drivers:adc:ad469x: exposed set_busy api.

---

drivers/platform/maxim/max78000/maxim_uart.c

Two changes needed on the MAX78000. These issues were encountered after trying the EVAL-ADE9430 with MAX78000.
1. The UART blocking Transmit for MAX78000 in no-OS do not have a check on the TX FIFO. This causes long strings to be cut during transmission when TX FIFO is hit.
2. MAX78000 driver init uses SetFlowCtrl for all UART IDX, however the MaximSDK SetFlowCtrl returns an error for non-UART0 which can cause the no-OS platform driver to error on UART init.

drivers:platform:max78000: Fixes on uart driver.

---

drivers/adc-dac/ad74413r/ad74413r.c

Make sure that the second frame from the 2-stage readback is a NOP sequence as stated in the datasheet, page 52 of 70.
Fixes: 402288e ("drivers:adc-dac:ad74413r Added AD74413r driver")
Similar to: #1789

drivers: adc-dac: ad74413r: update read sequence

---

drivers/adc/ad713x/ad713x.c

Added a delay after the GPIO operations as the device needs a 10 ms delay to come out of power down state. The power down operation has been added as a part of the ad713x_init_gpio().

drivers:adc:ad713x:Added a delay after GPIO operations

---

tests/README.md
tests/drivers/imu/project.yml
tests/drivers/imu/test/support/test_adis.c
tests/drivers/imu/test/test_adis16505.c
tests/drivers/imu/test/test_adis1657x.c

Add unit tests for adis drivers using ceedling yml file. 
adis_generic_tests.c contain all tests in order to test adis.c file while test_adis16505 and test_adis1657x contain the specific tests for each device.

tests: drivers: imu: Add unit tests for adis drivers

---

projects/demo_esp/src.mk
projects/demo_esp/src/platform/maxim/main.c
projects/demo_esp/src/platform/maxim/parameters.c
projects/demo_esp/src/platform/maxim/parameters.h
projects/demo_esp/src/platform/maxim/platform_src.mk

Add support for maxim platform within the demo_esp project.
NOTE: Tested with esp8266.

projects: demo_esp: add maxim paltform support

---

drivers/imu/adis.c

Add chip select change after 3rd byte write in a
32-bit register write.
Fixes: dbc9265 ("drivers: imu: adis: Add first draft for adis generic driver")

drivers: imu: adis: Add chip select after for 3rd byte

---

tools/scripts/generic.mk

Adding condition on adding more backslashs for flags. 
We need add extra backslashes when the macro contains the quotes. like if macro is CFLAGS=\"flag\" then we need to add extra backslashes in linux machine so that it become CFLAGS=\\\"flag\\\". when we put this macro in text file it finally becomes CFLAGS=\"flag\" in text file. This only occur in linux machines, in windows we don't need to add extra backslashes.

tools:scripts: cflags issue fix

---

iio/iio.c

Currently the xml decriptor is not freed when iio_remove() is called, which causes a memory leak. Free desc->xml_desc to fix the issue.

Free the IIO xml desc

---

drivers/adc/ad9081/ad9081.c
drivers/axi_core/jesd204/jesd204_clk.c
drivers/axi_core/jesd204/jesd204_clk.h
drivers/frequency/hmc7044/hmc7044.c
drivers/frequency/hmc7044/hmc7044.h
projects/ad9081/src.mk
projects/ad9081/src/app_clock.c
projects/ad9081/src/app_jesd.c
projects/ad9172/src.mk
projects/ad9208/src.mk
projects/adrv9009/src.mk

Use no-os Clock infrastructure for the AD9081 project. 
- non-QUAD_MXFE devices

Ad9081 clocks

---

drivers/adc/ad9081/ad9081.c

Use clock descriptor as parameter in no-os clock ops.
Fixes: 6790984

adc:ad9081:ad9081.c Use clk_desc in clk ops

---

drivers/platform/maxim/max32650/maxim_uart.c
drivers/platform/maxim/max32655/maxim_uart.c
drivers/platform/maxim/max32660/maxim_uart.c
drivers/platform/maxim/max32665/maxim_uart.c
drivers/platform/maxim/max32690/maxim_uart.c
drivers/platform/maxim/max78000/maxim_uart.c

Currently, when setting the voltage level of the UART interface, it is done by changing the vssel field of a struct defined in the SDK (which is used to configure some GPIOs as UART alternate function). However, these structs are defined as const, and as such, modifying it's fields is undefined behavior.
The initialization sequence is still correct, since the voltage level is set after the UART interface is configured.
Fixes: 269807a ("platform: maxim: Remove discarded const warning")

drivers:platform:maxim: Fix UART UB

---

network/wifi/at_parser.c

For some modules after performing the wifi module reset the first AT command is not sent properly.
Since the disable echo command is the first step in the wifi initialization, retry to send it again if first time it throws an error.

network: wifi: update echo disable procedure

---

drivers/platform/maxim/max32650/maxim_uart.c
drivers/platform/maxim/max32655/maxim_uart.c
drivers/platform/maxim/max32660/maxim_uart.c
drivers/platform/maxim/max32665/maxim_uart.c
drivers/platform/maxim/max32690/maxim_uart.c
drivers/platform/maxim/max78000/maxim_uart.c

Apply 75cdb79("drivers:platform:max78000: Fix blocking UART Tx") for all the other Maxim targets.

Maxim UART blocking

---

drivers/power/ltc3337/ltc3337.c
drivers/power/ltc3337/ltc3337.h
projects/ltc3337/Makefile
projects/ltc3337/builds.json
projects/ltc3337/src.mk
projects/ltc3337/src/common/common_data.c
projects/ltc3337/src/common/common_data.h
projects/ltc3337/src/examples/basic/basic_example.c
projects/ltc3337/src/examples/basic/basic_example.h
projects/ltc3337/src/examples/examples_src.mk
projects/ltc3337/src/platform/maxim/main.c
projects/ltc3337/src/platform/maxim/parameters.c
projects/ltc3337/src/platform/maxim/parameters.h
projects/ltc3337/src/platform/maxim/platform_src.mk
projects/ltc3337/src/platform/platform_includes.h

Initial implementation of the LTC3337 no-OS Driver. This adds support for the LTC3337 Primary Battery SOH Monitor and Coulomb Counter.
This driver is derived from the stand-alone demonstration application maintained at [LTC3337 Demo](https://github.com/BrentK-ADI/Demo-Projects/tree/main/ltc3337_demo)
The original driver source code at the above repo includes unit testing for verification of data type conversions and calculations.  
No-Os driver and provided example tested against a MAX32655FTHR board paired with a Mikroe BATT-4-MON Click (LTC3337).
New driver directory "power" created, mirroring the location of battery monitors/fuel gauges in the Linux kernel.

drivers:power:ltc3337 Initial Implementation

---

drivers/platform/maxim/max32650/maxim_i2c.c
drivers/platform/maxim/max32655/maxim_i2c.c
drivers/platform/maxim/max32660/maxim_i2c.c
drivers/platform/maxim/max32665/maxim_i2c.c
drivers/platform/maxim/max32690/maxim_i2c.c
drivers/platform/maxim/max78000/maxim_i2c.c

Similar to 468f2789("drivers:platform:maxim: Fix UART UB"), create a new variable for gpio vssel configuration, instead of pointing to the SDK (const) declared one.

drivers:platform:maxim: Fix I2C UB

---

drivers/adc-dac/ad74416h/ad74416h.c

[drivers: adc-dac: ad74416h: add delay after reset](https://github.com/analogdevicesinc/no-OS/commit/2f7fd2fe8b25bf30acee20483fc450b376bb359c)
[drivers: adc-dac: ad74416h: update readback](https://github.com/analogdevicesinc/no-OS/commit/dbff40de93c763ebe97330939a4dac810a917d17)

drivers: adc-dac: ad74416h: updates

---

drivers/Makefile

Similar to other drivers that have external api, ignore from the drivers build.
Should fix issues related to #1824

drivers: Makefile: ignore ad9081

---

drivers/adc/ad9081/api/adi_ad9081.h
drivers/adc/ad9081/api/adi_ad9081_adc.c
drivers/adc/ad9081/api/adi_ad9081_config.h
drivers/adc/ad9081/api/adi_ad9081_dac.c
drivers/adc/ad9081/api/adi_ad9081_device.c
drivers/adc/ad9081/api/adi_ad9081_jesd.c
drivers/adc/ad9081/api/adi_ad9081_sync.c
drivers/adc/ad9081/api/adi_cms_api_common.h

version 1.5.0
* Power savings optimizations and access to Rx Power Controllers
* Ability to bypass JESD204c calibration and load coefficients manually
* Support for half rate 2D eye scan
version 1.4.0
* Optimized ADC bypass path for FBW mode
* New function adi_ad9081_sync_sysref_input_config_set()
* Configure the sysref input receiver circuit based on AC/DC coupling, signal type, etc.
* Quarter rate eye scan debug functionality
version 1.3.1
* Changed reference name for sysref clock source in adi_adxxxx_device_t struct from clk_src to sysref_clk
version 1.3.0
* Update missing JES204B lcpll values, adi_adxxxx_jesd_tx_pll_startup, Missing JES204B lcpll values leads to PLL startup issues
* Added call to bitfield JRX_SYSREF_FOR_STARTUP_I NFO, adi_adxxxx_jesd_rx_link_config_set, …

adc: ad9081: Update API to Version 1.5.0

---

drivers/platform/maxim/max32670/maxim_i2c.c
drivers/platform/maxim/max32670/maxim_i2c.h

i2c platform driver for max32670. Tested using MAX32670EVKIT + MAX20361EVKIT for device id 0, 1, and 2 at MAX_I2C_STD_MODE only.

drivers:platform:maxim:max32670: Add i2c platform driver

---

build_projects.yml

After recent restructure of the projects build infrastructure, multiple
jobs produce artifacts under the same $(ARTIFACT_NAME) path.
This causes errors in the PublishPipelineArtifact stage of each job.
Similar to the logs handling for each job, add a platform suggestive
prefix for the artifacts.
Fixes: https://github.com/analogdevicesinc/no-OS/commit/5490fa4598801b4f5581fdbd447b662d91c6971e ("CI:configure new agent for projects build")

build_projects.yml: fix publish artifacts issues 

---

iio/iio.c
tools/scripts/generic_variables.mk

Add no-OS project name to the iio context description.
libiio v0.25 now handles the context description correctly with the serial backend by displaying it as-is instead of replacing it with other information.
This is useful to iio apps that need to know what firmware is running on the board (project name, git tag, revision).

add no-OS project name to iio context description

---

legacy/scripts/xilinx_capture.tcl

Add support for Versal in the script that downloads memory contents from the device.

Dma example support versal

---

projects/ad3552r_fmcz/srcs/main.c

Update project following driver changes: function ad3552r_ldac_trigger now has an extra input parameter.
Fixes: 6718061 ("drivers:dac:ad3552r: Update ad3552r driver")

ad3552r_fmcz:srcs:main.c Update project

---

projects/fmcdaq2/src.mk

Add the no_os_clk files to the fmcdaq2 project's sources.

fmcdaq2:src.mk Add no_os_clk to sources

---

drivers/adc-dac/ad74416h/ad74416h.c

Add the missing 19k2 sampling rate for the ADCs conversion rates.
Indent the code accordingly to fit the maximum nr of characters per line.

drivers: adc-dac: ad74416h: add missing conv rate

---

tools/scripts/aducm.mk
tools/scripts/altera.mk
tools/scripts/generic.mk
tools/scripts/linux.mk
tools/scripts/maxim.mk
tools/scripts/mbed.mk
tools/scripts/pico.mk
tools/scripts/stm32.mk
tools/scripts/xilinx.mk

Print the executable size (for .hex and .elf) after the compilation for Maxim platform.

Print binary size for Maxim

---

tools/scripts/platform/maxim/maxfla.sh

This commit adds a standalone script that can program a Maxim micro using CMSIS-DAP and swd:
maxfla.sh file.elf
One can also specify the swd programmer id from dmesg:
maxfla.sh file.elf 1234567896d9088800000000000000000000000097969906
Please try it out and on your system and let me know if you have any issues.

add maxim programming script (openocd based)

---

tools/scripts/release_projects.sh

Add standalone bash script used as intermediate stage in the remote release pipeline following the new CI infrastructure for building the projects.
The script gets all platform specific binaries and merge them into project specific archives that are subsequent published as github releases.

tools: scripts: release projects script

---

drivers/digital-io/max14906/iio_max14906.c
drivers/digital-io/max14906/iio_max14906.h
drivers/digital-io/max14906/max14906.c
drivers/digital-io/max14906/max14906.h

The MAX14906 is an IEC 61131-2 compliant, high-speed, four-channel industrial digital output, digital input device
that can be configured on a per-channel basis as a high-side (HS) switch, push-pull (PP) driver, or a Type 1 and 3,
or Type 2 digital input. The MAX14906 is specified for operation with a supply voltage up to 40V and is tolerant to
65V.

MAX14906 driver

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
.gitignore

This PR adds:
1.  CODEOWNERS
Code owners are automatically added as reviewers whenever new PRs are open. Other reviewers can be added beside code owners. This works in combination with "Minimum number of reviewers" set to one - meaning that at least one code owner must approve the PR to be able to merge it.
2.  PULL_REQUEST_TEMPLATE
PR Template main goal is to standardize the information contributors include when they open new PRs. Whenever a new PR is open, its body will be automatically populated with the content of PULL_REQUEST_TEMPLATE.md file.

Add PR Template and Code Owners

---

drivers/imu/iio_adis.c
drivers/imu/iio_adis.h
iio/iio.c
iio/iio_types.h

Add support for delta angle and delta velocity to be to have the same types as in Linux IIO implementation.
The delta angle is defined as a piece-wise integration of angular velocity data. The delta angle represents the amount of angular displacement between two consecutive measurements and it is measured in radians.
The delta velocity is defined as a piece-wise integration of acceleration data. The delta velocity represents the linear velocity change between two consecutive measurements and it is measured in m / s (meters per second).

iio: Add support for delta angle and delta velocity

---

drivers/dac/ad5754r/ad5754r.c

Fix update_bits method by resetting masked locations before applying mask

drivers:dac:ad5754r: Fix update method

---

iio/iio.c

There is no reason to have the trigger enabled during the post_disable call. Usually, this function is used to disable channels, thus having a data ready interrupt occur during this may lead to bus contention.

iio: Disable trigger before calling post_disable

---

drivers/adc/ad4080/ad4080.c

Fix ad4080 driver init method
1. Prevent premature assignment of device structure instance before reg configuration is successful
2. Return error if ID does not match

drivers:adc:ad4080: Fix driver init

---

drivers/api/no_os_spi.c

initializing pointer to bus to NULL in spi_table when bus is freed.

drivers:api: bug fix in no_os_spibus_remove

---

drivers/adc-dac/ad74413r/ad74413r.c

Fix the order of the conv times, so they'll match the EN_50_60_HZ values in the ADC_CONFIGx register.

drivers:adc-dac:ad74413r: Fix rejection lookup

---

.github/CODEOWNERS

This commits adds extra persons as code owners on CI-related folders/files.
This PR add extra code owners on CI related folders and files.

CODEOWNERS: add owners on ci related folders/files

---

.github/CODEOWNERS

Fix typo in the file name of the build projects yml file.
Fixes: 633ddd0 ("CODEOWNERS: add owners on ci related folders/files")

CODEOWNERS: fix build projects file name

---

build_projects.yml

Instead of going on default case, parametrize the hdl_branch used for projects builds using a an Azure environment variable alongside LOGS_DIR and RELEASE_DIR passed to the build_projects.py script. In this manner we keep under control the versions of the hdl used for building projects and folder structure of the builds.

build_projects.yml: add hdl_branch parameter

---

drivers/adc/adm1177/README.rst
drivers/adc/adm1177/iio_adm1177.c

Removed unused counter variable in the _update_channels functions. 
If memory alocation for the desc fails, it returns -ENOMEM, not desc.

drivers: adc: adm1177 : Fix bug for iio driver

---

tools/scripts/xilinx.mk

Xilinx tools name the .bit file differently. Use wildcard to accomodate the following, regardless of Xilinx tools version:
- system.bit
- system_top.bit

use wildcard when dealing with .bit file

---

ci/doxygen.sh

Prior to pushing new documentation build on gh-pages, create .nojekyll file in the root directory to avoid treating github pages as a Jekyll site.
Sphinx generates documentation in a way that is different from Jekyll, and we want to avoid any potential conflicts. In this specific case, the files from the `_static` are ignored by Jekyll and we don't want that to happen.

ci: doxygen: create .nojekyll file

---

tools/scripts/generic.mk

Fixed the issue with providing custom name to binary file through 'make BINARY_FILE_NAME='name' build rule

tools/scripts: Fixed custom binary file name assign issue

---

drivers/axi_core/jesd204/axi_jesd204_rx.c
drivers/axi_core/jesd204/axi_jesd204_tx.c
projects/ad6676-ebz/src.mk
projects/ad9172/src.mk
projects/ad9208/src.mk
projects/ad9371/src.mk
projects/ad9656_fmc/src.mk
projects/adrv9009/src.mk
projects/fmcadc2/src.mk
projects/fmcadc5/src.mk
projects/fmcdaq3/src.mk
projects/fmcjesdadc1/src.mk

Fix the lane clock initialization in axi_jesd204_rx.c and axi_jesd204_tx.c (set the jesd_rx or jesd_tx member of the jesd204_clock structure to the corresponding AXI jesd structure.
Fixes: https://github.com/analogdevicesinc/no-OS/commit/43da1f0153340d2f849ee3872f842bc860b7d59a ("axi_core: jesd204: axi_jesd204: Add lane clock")

axi_core: jesd204: axi_jesd204_*x.c Fix lane clock

---

drivers/power/ltc3350/ltc3350.c
drivers/power/ltc3350/ltc3350.h

The LTC3350 is a backup power controller that can charge and monitor a series stack of one to four supercapacitors. The LTC3350’s synchronous step-down controller drives N‑channel MOSFETs for constant current/constant voltage charging with a programmable input current limit. In addition, the step-down converter can run in reverse as a step-up converter to deliver power from the supercapacitor stack to the backup supply rail. Internal balancers eliminate the need for external balance resistors and each capacitor has a shunt regulator for overvoltage protection.

ltc3350 driver files for no-OS

---

tools/scripts/generic.mk
tools/scripts/platform/template_c_cpp_properties.json
tools/scripts/platform/template_launch.json
tools/scripts/platform/template_settings.json
tools/scripts/stm32.mk
tools/scripts/vsc_intellisense.mk
tools/scripts/vsc_openocd_debug.mk

This feature update enables the use of the popular VS Code editor for debugging and intellisense.
An update of the no-OS built process is provided to automatically create the necessary config files.
Template config files are filled with the necessary information. These files can be found at $(no-OS-Path)/tools/scripts/templates
To make the intellisense feature of VS Code usable the project dependent include paths 
and defines are derived from the CFLAGS variable and parsed via the template to the c_cpp_properties.json file.
Debugging with VS Code is restricted for now to the stm32 platform and OpenOCD debugger cmsis-dap and stlink-dap. 
The debugging config files are settings.json and launch.json.
The necessary information is mainly collected from already available variables of the …

Stm32 vscode support

---

drivers/adc/ad469x/ad469x.c
drivers/adc/ad469x/ad469x.h

Add an API to get and set the value of VREF_SET in the Reference control register

drivers:adc:ad469x:Add API to configure VREF_SET

---

drivers/resolver/ad2s1210/ad2s1210.c
drivers/resolver/ad2s1210/ad2s1210.h

The AD2S1210 is a 10 to 16 bit resolver-to-digital converter that supports 4 wire SPI or parallel interface.
This adds support for the ad2s1210 in spi mode.
The driver was tested using the SDPK1 "arduino" pins connected to the AD2S1210SDZ EVAL board using the
ADZS-BREAKOUT board.

drivers: Add support for ad2s1210

---

tools/scripts/build_projects.py
tools/scripts/xilinx.mk

For Xilinx projects bootgen_sysfiles archives are created, first were saved as .zip and were changed to .tag.gz, but the pipeline was still looking for .zip file.
Also a new option was added to tar command in order to eliminate concatenation of the parent directory in the path.

tools: scripts: export .tar.gz archive instead of .zip

---

drivers/adc/ad7124/ad7124.c

Adding another variable with data type uint32_t
to hold the value to be written for bipolar mode.
As bool data type was used for bipolar variable it could be assigned to only true or false and didn't hold the intended value 
AD7124_CFG_REG_BIPOLAR (2048).  Made necessary adjustments to code.

drivers:ad7124:Fix for set polarity

---

drivers/resolver/ad2s1210/ad2s1210.c
drivers/resolver/ad2s1210/ad2s1210.h

The work on linux driver currently added some attributes that are not implemented:
* set and get hysteresis
* output channel for excitation frequency 
* a couple of label attributes for channels. 
These patches add setter and getter methods  for hysteresis and excitation frequency
So the corresponding attributes can be implemented on the ad2s1210 project. 
the intention is to keep no-os attributes/channels aligned with the upstream Linux driver,
so that any user application will work without any modifications with either of the two.

ad2s1210: Add methods for hysteresis and excitation frequency

---

drivers/accel/adxl367/adxl367.c

Perform sign extend on the variable x_axis_2 instead of x_axis_1. The sign extend operation for x_axis_1 is already done after the variable is composed.
Fixes: 2e4f0c3 ("drivers:accel: Create ADXL367 Driver")

drivers: accel: adxl367: fix sign extend

---

drivers/meter/ade7913/ade7913.c
drivers/meter/ade7913/ade7913.h

Add driver for the ADE7913 3-Channel, Isolated, Sigma Delta ADC with SPI.
The ADE7913 are isolated, 3-channel Σ-Δ ADCs for a variety of applications such as shunt-based polyphase meters, power quality monitoring, solar inverters, process monitoring and protective devices.

drivers: meter: ade7913: Add driver

---

drivers/axi_core/jesd204/axi_jesd204_rx.c
drivers/axi_core/jesd204/axi_jesd204_rx.h
drivers/axi_core/jesd204/axi_jesd204_tx.c
drivers/axi_core/jesd204/axi_jesd204_tx.h
projects/ad6676-ebz/src/ad6676_ebz.c
projects/ad9081/src/app_jesd.c
projects/ad9083/src/app_jesd.c
projects/ad9172/src/main.c
projects/ad9208/src/main.c
projects/ad9371/src/app/headless.c
projects/ad9656_fmc/src/app/ad9656_fmc.c
projects/adrv9009/src/app/app_jesd.c
projects/fmcadc2/src/fmcadc2.c
projects/fmcadc5/src/fmcadc5.c
projects/fmcdaq2/src/app/app_config.h
projects/fmcdaq2/src/app/fmcdaq2.c
projects/fmcdaq3/src/app/fmcdaq3.c
projects/fmcjesdadc1/src/app/fmcjesdadc1.c

Remove the option to not use JESD FSM for the fmcdaq2 project and rename the jesd init functions (add legacy suffix for non-FSM functions).

Fsm update - rename jesd init functions

---

ci/documentation.sh

In the same manner as the doxygen build, treat warnings as errors.
Sphinx build treats some relevant issues as warnings (such as incorrect links/paths, etc.)
These should be detected by the ci build and not mark the build as successful.

ci: documentation: treat sphinx warnings as errors

---

drivers/platform/maxim/max32650/maxim_uart.c
drivers/platform/maxim/max32655/maxim_uart.c
drivers/platform/maxim/max32660/maxim_uart.c
drivers/platform/maxim/max32665/maxim_uart.c
drivers/platform/maxim/max32670/maxim_uart.c
drivers/platform/maxim/max32690/maxim_uart.c
drivers/platform/maxim/max78000/maxim_uart.c

Fix the fact that the extra field of no_os_uart_desc was not being populated with the maxim specific structure.

save max specific uart descriptor

---

drivers/platform/maxim/max32650/maxim_init.c
drivers/platform/maxim/max32655/maxim_init.c
drivers/platform/maxim/max32660/maxim_init.c
drivers/platform/maxim/max32665/maxim_init.c
drivers/platform/maxim/max32670/maxim_init.c
drivers/platform/maxim/max32690/maxim_init.c
drivers/platform/maxim/max78000/maxim_init.c
projects/adt7420-pmdz/src/platform/maxim/main.c
projects/eval-adxl313z/src/platform/maxim/main.c
projects/eval-ltc4306/src/platform/maxim/main.c
projects/swiot1l/src/platform/maxim/main.c

no_os_init() is supposed to be called for any project running on Maxim. The Board_Init() function is called in the SDK before main(), so we can also do no_os_init().

Call no_os_init() during board init

---

drivers/platform/maxim/max32650/maxim_irq.c
drivers/platform/maxim/max32655/maxim_irq.c
drivers/platform/maxim/max32660/maxim_irq.c
drivers/platform/maxim/max32665/maxim_irq.c
drivers/platform/maxim/max32670/maxim_irq.c
drivers/platform/maxim/max32690/maxim_irq.c
drivers/platform/maxim/max78000/maxim_irq.c

Remove items from list (empty it!) when doing irq_ctrl_remove. Previously, the items were being read with no_os_list_read_first which does not remove the item being read.

maxim_irq: remove from list on irq_ctrl_remove

---

drivers/frequency/admv1013/admv1013.c

Include the corner cases in the computation of the MIXER_VGATE register value.
According to the datasheet: The MIXER_VGATE values follows the VCM such as, that for a 0V to 1.8V VCM, MIXER_VGATE = 23.89 VCM + 81, and for a > 1.8V to 2.6V VCM, MIXER_VGATE = 23.75 VCM + 1.25.
Fixes: a306e3c ("drivers: frequency: admv1013: add support")
Link: https://lore.kernel.org/all/20230807143806.6954-1-antoniu.miclaus@analog.com/

frequency: admv1013: add mixer_vgate corner cases

---

drivers/dac/ad5791/ad5791.c

The `enum ad5791_lin_comp_select` contains values for both ad5781 and ad5791 parts with respect to the voltage spans. Altough, the only value that is valid for both parts is `AD5781_SPAN_UPTO_10V`.
Update the error handling procedure such that incorrect values are not allowed to be set, based on the device type used with the driver.

drivers: dac: ad5791: lin_comp error handling

---

drivers/dac/ad5791/ad5791.c

Correct lin_comp API in accordance with the register map.

drivers: dac: ad5791: Fix linearity compensation API

---

ci/cppcheck.sh
drivers/frequency/hmc7044/hmc7044.c

Download and install specific cppcheck version for the ci builds.
This should fix also the https://github.com/analogdevicesinc/EVAL-ADICUP3029 and https://github.com/analogdevicesinc/EVAL-ADICUP360 buids.

ci: cppcheck: use specific version

---

ci/astyle.sh
ci/cppcheck.sh
ci/documentation.sh
ci/run_build.sh

Add NUM_JOBS variable holding the available number of cpu cores on a build agent.
Use all avaliable cores for all ci builds.

ci: use all cpu cores

---

drivers/frequency/hmc7044/hmc7044.c

Switch to using no_os dedicated memory allocation functions.

drivers: frequency: hmc7044: use no_os_calloc

---

ci/astyle.sh

Astyle command does not support -j<nr_of_threads> option.
The -j option is actually a shortcut for `--add-braces` option for
astyle tool.
Threrefore drop it.
Fixes: 8c5e44f ("ci: use all cpu cores")

ci: drop -j parameter for the astyle command

---

projects/adrv902x/src/examples/basic_example/basic_example.c
projects/adrv902x/src/examples/dma_example/dma_example.c
projects/adrv902x/src/examples/iio_example/iio_example.c

Prevent overwriting the sttaus variable in case and error occurs in the project execution.
Fixes: dd47a433 ("projects: adrv9025: Madura project")

adrv902x: src: examples: Fix error handling

---

drivers/axi_core/iio_axi_adc/iio_axi_adc.c
drivers/axi_core/iio_axi_adc/iio_axi_adc.h

Allow the setting of custom scan type for the AXI ADC channels.
Until now, only a fixed setting of 16 realbists and storagebits was possible.

iio_axi_adc: Allow custom scan type

---

drivers/axi_core/iio_axi_adc/iio_axi_adc.c
drivers/axi_core/iio_axi_adc/iio_axi_adc.h
projects/ad7768-evb/src/ad7768_evb.c

Update the IIO example of the ad7768-evb project so that realbits and storagebits are correctly specified (32 and 24, respectively).

Ad7768 iio update

---

drivers/digital-io/max149x6/max14906.c
drivers/digital-io/max149x6/max14916.c

Call API to remove all GPIOs of the max149x6 descriptor in the max14906 and max14916 remove functions.
To be merged before #1941

drivers: digital-io: max149x6 : Fix driver remove function

---

ci/lib.sh
ci/run_build.sh

The common scripts from lib.sh are using also NUM_JOBS variable when propagated on other repositories which download and use these scripts. (EVAL-ADICUP3029, EVAL-ADICUP360, libtinyiiod, etc.)
Make sure that the variable is populated on other repositories too.

ci: move NUM_JOBS variable to lib.sh

---

drivers/accel/adxl345/adxl345.c

Read from ADXL345_ACT_INACT_CTL instead of ADXL345_INT_ENABLE register address to obtain the state of inactivity control register.
Issue reported: https://github.com/analogdevicesinc/no-OS/issues/1992

drivers: accel: adxl345: Read correct value for inact ctl

---

doc/sphinx/source/drivers/max22190.rst
doc/sphinx/source/drivers_doc.rst
drivers/digital-io/max22190/README.rst
drivers/digital-io/max22190/iio_max22190.c
drivers/digital-io/max22190/iio_max22190.h
drivers/digital-io/max22190/max22190.c
drivers/digital-io/max22190/max22190.h

MAX22190 is an octal industrial digital input device with diagnostics that communicates through a SPI interface.
The files added by this PR have been tested with the MAX22190 PMB connected to a max32690 microcontroller.
The driver has the basic api for init, remove, register read, write and update, but also a custom CRC5 algorithm specific for this device 
alongside its specific api(filter_get, filter_set, chan_state).

drivers: digital-io: max22190 : Add max22190 driver support

---

drivers/digital-io/max22196/README.rst
drivers/digital-io/max22196/iio_max22196.c
drivers/digital-io/max22196/iio_max22196.h
drivers/digital-io/max22196/max22196.c
drivers/digital-io/max22196/max22196.h

The MAX22196 is an industrial octal digital input that translates eight industrial 24V or TTL level inputs to logic level outputs. The device has a serial interface allowing configuration and reading of serialized data through SPI.

drivers: digital-io: max22196 : Add driver support for MAX22196

---

ci/documentation.sh

When a README.rst file is created/modified for a specific driver or project, the documentation CI checks if also the links to the table of contents are properly handled.
If no link is found under drivers_doc.rst or projects_doc.rst for that specific driver/project, the documentation fails.
If no .rst file is found for including the driver/project README.rst specific file, the documentation build fails.

ci: documentation: add extra sphinx checks

---

ci/lib.sh

Remove the `download_common_scripts` function call.
The function should be called only on the repositories that actually need it.
The no-OS repository holds the scripts already, therefore downloading them again is redundant.
This should be merged preferably after:
https://github.com/analogdevicesinc/EVAL-ADICUP360/pull/33
https://github.com/analogdevicesinc/EVAL-ADICUP3029/pull/115
https://github.com/analogdevicesinc/m1k-fw/pull/35
https://github.com/analogdevicesinc/arduino/pull/34
https://github.com/analogdevicesinc/libtinyiiod/pull/49

ci: lib.sh: drop download scripts function call

---

drivers/adc/ad469x/ad469x.c
drivers/adc/ad469x/ad469x.h

Added APIs to get and set the status of analog input high Z mode

drivers:adc:ad469x:Added APIs for analog input high Z mode

---

drivers/digital-io/max22196/max22196.c

In the driver's source file there is a typo in the fault_mask_get function and max22190_reg_read is called
instead of max22196_reg_read.

drivers: digital-io: max22196 : Fix API call in driver source file

---

ci/lib.sh
ci/run_build.sh

There is no need to call ensure_command_exists sudo in lib.sh
Move it to run_build.sh which calls subsequent scripts that actually use sudo.

ci: lib: move ensure command exists to run_build

---

projects/adrv902x/src/examples/basic_example/basic_example.c
projects/adrv902x/src/examples/dma_example/dma_example.c
projects/adrv902x/src/examples/iio_example/iio_example.c

Specify desired SYSREF frequency to LMFC / 2.
If desired SYSREF frequency is 0, then FSM selects SYSREF equal to LMFC, randomly reporting SYSREF alignment error.

adrv902x: src: examples: Specify desired SYSREF

---

tools/scripts/generic.mk

Use NO-OS path value instead of relative path in generic.mk
reported here: https://github.com/analogdevicesinc/no-OS/issues/2012  

scripts: generic.mk: Use NO-OS instead of relative path

---

drivers/platform/stm32/stm32_pwm.c
drivers/platform/stm32/stm32_pwm.h

The value of prescaler can be anything from 0 to 0xFFFF. Application of NO_OS_BIT() to the prescaler value changes the logic behind prescaler calculation.
Fixes: 9264d8983c4e434affd171c7e6b394826089fdb0 ("stm32 pwm support")

drivers:platform:stm32:Fixes to Prescaler calculation

---

drivers/accel/adxl345/adxl345.c
drivers/accel/adxl345/adxl345.h

Add support for adxl346 device in already existing adxl345 driver.
The ADXL346 is a small, thin, ultralow power, 3-axis accelerometer with high resolution (13-bit) measurement at up to ±16 g. Digital output data is formatted as 16-bit twos complement and is acces- sible through either an SPI (3- or 4-wire) or I2
C digital interface.
The ADXL346 is well suited for mobile device applications. It measures the static acceleration of gravity in tilt-sensing appli- cations, as well as dynamic acceleration resulting from motion or shock. Its high resolution (4 mg/LSB) enables measurement of inclination changes of less than 1.0°.
You can tick the checkboxes below with an 'x' between square brackets or just check them …

drivers: accel: adxl345: Add support for adxl346

---

tools/scripts/generic_variables.mk

With ded4e85 the TARGET variable is handled also in the generic variables makefile.
Make sure that the error thrown covers all cases.

scripts: generic: make error more verbose

---

iio/iio_app/iio_app.c

Only free the uart decriptor if it was previously allocated in the init function. Otherwise, this causes the remove to fail.

iio: iio_app: Check if uart_desc is allocated

---

drivers/axi_core/jesd204/axi_adxcvr.c

Fix debug message for the adxcvr_clk_round_rate function.
Fixes: 2b0d85d ("drivers:axi_core:jesd204:axi_adxcvr.* Add FSM ops")

axi_core: jesd204: axi_adxcvr.c: Fix debug message

---

drivers/dac/ad5754r/ad5754r.c
drivers/dac/ad5754r/ad5754r.h

Add function for triggering ldac operation. HW LDAC is prioritized over SW LDAC

drivers:dac:ad5754r: Add fn for ldac trigger

---

projects/max14906/src/examples/basic/basic_example.c
projects/max14906/src/platform/maxim/main.c
projects/max14906/src/platform/maxim/parameters.h

Fix maxim interrupt handling bug consisting of NVIC controller not being properly initialized.
Fixes: '3ceb54f' ("projects: max14906 : Change interrupt support for MAXIM platform")

projects: max14906 : Fix maxim interrupt handling for MAX14906 project

---

ci/run_build.sh

Call `ensure_command_exists wget` prior to running build functions.
The command is used both in `build_astyle` function and `build_documentation`.

ci: run_build: ensure wget command exists

---

projects/adrv902x/src/platform/xilinx/platform_src.mk

Fix the xilinx_uart.c src in the platform_src.mk file.
Fixes: ab393ac ("projects: adrv9025: Madura project")

adrv902x: Fix uart src in platform_src.mk

---

doc/sphinx/source/drivers/max22200.rst
doc/sphinx/source/drivers_doc.rst
drivers/digital-io/max22200/README.rst
drivers/digital-io/max22200/iio_max22200.c
drivers/digital-io/max22200/iio_max22200.h
drivers/digital-io/max22200/max22200.c
drivers/digital-io/max22200/max22200.h

Add driver support for MAX22200.
The MAX22200 is an octal 36V serial-controlled solenoid driver.
Each channel features a low impedance (200mΩ typ) push-pull output stage with sink-and-source driving
capability and up to 1ARMS driving current. A serial interface (SPI) that also supports daisy-chain configurations is
provided to individually control each channel

drivers: digital-io: max22200 : Add driver support for MAX22200

---

drivers/frequency/ad9528/ad9528.c

Set the rate value in ad9528_clk_recalc_rate.
Fixes: ad66d6d ("drivers: frequency: ad9528: Add FSM ops")

frequency: ad9528: ad9528.c: Set correct rate value in ad9528_clk_recalc_rate

---

tools/scripts/generic_variables.mk

If a hardware file exists (.xsa, .hdf, .ioc, etc) even though the max target is specified the build will perform for the first hardware file that is found.
Fixes: ded4e85 ("tools: scripts: generic_variables: handle maxim")

tools: scripts: fix maxim target handling

---

drivers/adc-dac/ad74416h/ad74416h.c

Add missing break statements in the switch cases for device id.
Fixes: 44aa88f ("adc-dac: ad74416h: add dac resolution for ad74414h")

adc-dac: ad74416h: add missing breaks

---

tools/scripts/generic.mk
tools/scripts/stm32.mk
tools/scripts/vsc_intellisense.mk
tools/scripts/vsc_openocd_debug.mk

This is currently only supported on stm32, so limit it to that
platform. This fixes some issues with building for xilinx platform
which has a funky way of detecting the architecture (build/tmp/arch.txt)
which makes the builds fail. The failure is due to a which command
call without arguments and it all comes from vs code support.
https://ez.analog.com/microcontroller-no-os-drivers/f/q-a/576135/no-os-build-ad9081-vitis-2022-2

condition the vs code project configuration

---

projects/ad9361/src.mk
projects/ad9361/src/main.c
projects/ad9361/src/parameters.h

Add the possibility to detect the FPGA board running the project.
Needed for setting the UART baudrate to 115200 instead of 921600 for IIOD in the case of a ZedBoard.

projects: ad9361: Add System ID support

---

ci/gen_dox.sh

Imu folder does not contain any subfolder, therefore the linking is different from other drivers.

ci: gen_dox: handle imu folder separately

---

drivers/platform/stm32/stm32_spi.c

On SPI MODE 2, the first bit of data sent by the salve is wrong.
This happens because the platform spi driver disables the SPI HAL after each trasfer reulting on the clk line beeing put back to its default floating state. It may go to 0v or 1.8v depending on the gpio pull configuration. The spi transactions level is 3.3v.
Because of the software controlled CS, the CS pin is active when HAL is enabled for the next xfer creating an invalid clk edge seen by the slave. The result is that the fist bit of the data transfer is wrong.
Keep the HAL enabled and avoid enabling and disabling on each trasfer.
You can tick the checkboxes below with an 'x' between square brackets or just check them after publishing the PR. …

SPI: STM32: Dont enable/disable HAL on transfer

---

drivers/api/no_os_i2c.c

The intent is to set i2c_table[bus_number] to NULL, so that we know the memory has been freed. However, the current implementation just makes the bus variable point to NULL, while i2c_table[bus_number] remains unchaged.
Running the init(), remove(), init() sequence will result in using freed memory after the second init. Fix this by correctly setting the i2c_table array element to NULL.
Fixes: d4a9723 ("spi and i2c: added slave counter for deallocation check")

drivers: api: Fix variable assignment

---

drivers/platform/maxim/max32650/maxim_spi.c
drivers/platform/maxim/max32655/maxim_spi.c
drivers/platform/maxim/max32660/maxim_spi.c
drivers/platform/maxim/max32665/maxim_spi.c
drivers/platform/maxim/max32690/maxim_spi.c
drivers/platform/maxim/max78000/maxim_spi.c

msgs is an array of structs, so its fields should be accessed as msgs[i].field instead.
Fixes: b46faa65227 ("drivers: platform: maxim: Update spi_transfer")

Fix SPI struct field access

---

tools/scripts/stm32.mk

stm32: prioritize system gcc over IDE gcc
Some users may not have the arm-none-eabi-gcc in their system so
test this first.
If it does not exist, Fallback to ST toolchain arm-none-eabi-gcc.
stm32 .ioc handling: force STM32CubeIDE
For the STM32CubeIDE project type generation in case .ioc files
specify otherwise because we don't support others.

Stm32 build fixes

---

drivers/platform/maxim/max32650/maxim_spi.c
drivers/platform/maxim/max32655/maxim_spi.c
drivers/platform/maxim/max32660/maxim_spi.c
drivers/platform/maxim/max32665/maxim_spi.c
drivers/platform/maxim/max32670/maxim_spi.c
drivers/platform/maxim/max78000/maxim_spi.c

This workaround is no longer needed since the SPI modes were fixed in the Maxim SDK.
https://github.com/Analog-Devices-MSDK/msdk/commit/50e0979357700daeea48fcd38b900148b1621ad4
This reverts commit 2032bde0e80468723c443def0def2a79fd21e31d.
Requires an SDK update on the build server

Revert "platform: maxim: spi: fix spi modes"

---

network/lwip_raw_socket/lwip_socket.c
projects/apard32690/Makefile
projects/swiot1l/Makefile
projects/swiot1l/builds.json
tools/scripts/lwip.mk

Add compile flags for IP, netmask and gateway. These take effect when using the networking layer based on lwip sockets and allow the user to configure these parameters, instead of using the predefined ones we currently have. Change project makefiles in order to keep the current IP settings.
The format should be (similar for the other ones): NO_OS_IP = A.B.C.D

Allow for IP setting at compile time

---

iio/iio.c

1. Use no_os_cb_read even in cyclic mode to check if there are samples available to be read
2. Refactor the function implementation

iio:iio.c: Add cyclic mode size checks in pop scan

---

drivers/platform/maxim/max32670/maxim_uart.c

Apply a fix similar to 6437cd6e12 ("drivers:platform:maxim: Fix UART TX") for the UART writes using the MAX32670.
Reported in https://github.com/analogdevicesinc/no-OS/issues/2055.

drivers: maxim: Fix UART write for MAX32670

---

drivers/digital-io/max22190/max22190.c
drivers/digital-io/max22196/iio_max22196.c
drivers/digital-io/max22196/max22196.c

MAX22190 has compliation warnings consisting of unused variables in the max22190.c source file.
MAX22196 has compliation warnings in both max22196.c and iio_max22196 source files consisting of :
- Unincluded header files.
- Bad API calls of no_os_util.h API.

drivers: digital-io : Fix compliation warnings for MAX22190 and MAX22196.

---

doc/sphinx/source/drivers/max14919.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/max14919.rst
doc/sphinx/source/projects_doc.rst
drivers/digital-io/max14919/README.rst
drivers/digital-io/max14919/max14919.c
drivers/digital-io/max14919/max14919.h
projects/max14919/Makefile
projects/max14919/README.rst
projects/max14919/builds.json
projects/max14919/src.mk
projects/max14919/src/common/common_data.c
projects/max14919/src/common/common_data.h
projects/max14919/src/examples/basic/basic_example.c
projects/max14919/src/examples/basic/basic_example.h
projects/max14919/src/examples/examples_src.mk
projects/max14919/src/platform/maxim/main.c
projects/max14919/src/platform/maxim/parameters.c
projects/max14919/src/platform/maxim/parameters.h
projects/max14919/src/platform/maxim/platform_src.mk
projects/max14919/src/platform/platform_includes.h

The MAX14919/MAX14919A industrial-protected quad-channel lowside switch features 140mΩ (typ) on-resistance (RON) per channel with integrated ±1kV/42Ω surge protection for robust operation.
Resistor-settable accurate current limiting provides guaranteed operating currents in the range of 100mA to 800mA. Loads that draw large activation or inrush currents are supported using the 2x inrush load-current option. The outputs can be connected in parallel to achieve higher load currents. The four switches are pin-controlled to allow for simple and fast switching of up to 500kHz.
The MAX14919/MAX14919A features reverse current detection. The MAX14919 implements reverse-current protection by driving an external FET for non-capacitive loads. The MAX14919A has reverse current indication.
The device …

drivers: digital-io: max14919 : Add MAX14919 driver support

---

drivers/adc/ad719x/ad719x.c

Fixed bridge switch return check to
not return error for ad7194
Updated channel select API
for ad7194 as previous mask didn't apply
for ad7194.
The modification in channel select API is needed as previous mask applied was not for ad7194. 
The return check after bridge switch had to be updated since in bridge switch API if it was ad7194 device it returned an error and the whole no-os initialization failed.

drivers:ad719x: Minor Updates

---

tools/scripts/generic.mk

The flag is probably here from the initial development of the generic.mk file and used for debugging purposes.
(ae7ad15)
Drop it completely.

tools: scripts: generic: drop unused flag

---

doc/sphinx/source/Makefile
doc/sphinx/source/conf.py

Adds the default Sphinx Makefile with vars `SOURCEDIR` and `BUILDDIR` set.
I need this file to exist because [doctools](https://github.com/analogdevicesinc/doctools/blob/8192817d818b9fe0cd34dc69034619f9936d930d/adi_doctools/cli/aggregate.py#L157) needs to know the source and build paths.
Set values are consistent with the ones at [documentation.sh](https://github.com/analogdevicesinc/no-OS/blob/0f275e683906480b9478e4a01f2d8d983f328ff9/ci/documentation.sh#L113).
Created it in the `doc/sphinx/source` path instead of `doc/sphinx`  because it would be the only file at the latter path.
Also, includes `repository` var to `conf.py`, also used by doctools.

doc: Add Makefile and repository to conf.py

---

doc/sphinx/source/projects/ad7091r8-sdz.rst
doc/sphinx/source/projects_doc.rst
drivers/adc/ad7091r8/ad7091r8.c
drivers/adc/ad7091r8/ad7091r8.h
drivers/adc/ad7091r8/iio_ad7091r8.c
drivers/adc/ad7091r8/iio_ad7091r8.h
drivers/adc/ad7091r8/iio_ad7091r8_trig.c
projects/ad7091r8-sdz/Makefile
projects/ad7091r8-sdz/README.rst
projects/ad7091r8-sdz/builds.json
projects/ad7091r8-sdz/src.mk
projects/ad7091r8-sdz/src/common/common_data.c
projects/ad7091r8-sdz/src/common/common_data.h
projects/ad7091r8-sdz/src/examples/basic/basic_example.c
projects/ad7091r8-sdz/src/examples/basic/basic_example.h
projects/ad7091r8-sdz/src/examples/examples_src.mk
projects/ad7091r8-sdz/src/examples/iio_example/iio_example.c
projects/ad7091r8-sdz/src/examples/iio_example/iio_example.h
projects/ad7091r8-sdz/src/examples/iio_timer_trigger_example/iio_timer_trigger_example.c
projects/ad7091r8-sdz/src/examples/iio_timer_trigger_example/iio_timer_trigger_example.h
projects/ad7091r8-sdz/src/platform/maxim/main.c
projects/ad7091r8-sdz/src/platform/maxim/parameters.c
projects/ad7091r8-sdz/src/platform/maxim/parameters.h
projects/ad7091r8-sdz/src/platform/maxim/platform_src.mk
projects/ad7091r8-sdz/src/platform/platform_includes.h

Initial implementation of the ad7091r8 no-OS driver. This adds support for ad7091r-2/-4/-8 devices which roughly support the same operations as ad7091r5, but are interfaced through SPI.
Driver has now been tested with Maxim78000FTHR and ad7091r8-sdz evaluation board.
Other meaningful differences between ad7091r8 and ad7091r5 are:
- ad7091r8 has a normal mode which comprises ad7091r5's sample and command modes
- ad7091r8 has no autocycle mode
- ad7091r8 and ad7091r5 have slightly different register fields and contrast most on their configuration register
- ad7091r8 protocol requires a pulse in the CONVST pin and so the driver requests a GPIO for that during initialization

Add AD7091R-2/-4/-8 driver and project

---

drivers/imu/adis.c

Maxim Platform needs tx_buff != NULL even if only receiving data, thus adding tx_buff to message.

drivers: imu: adis: Add tx_buff for all messages

---

build_projects.yml

The default timeout for azure jobs is 60 minutes but when hardware files from hdl are seen as new, the build will take almost 3 hours.

build_projects.yml: increase timeout for Xilinx job

---

tools/scripts/platform/xilinx/util.tcl

Enables remote flash capability for xilinx platform when both
`XSCT_REMOTE_HOST` and `XSCT_REMOTE_PORT` to a host running `hw_server`

tools: xilinx: util.tcl: Add remote flash

---

drivers/digital-io/max22196/README.rst
drivers/digital-io/max22196/iio_max22196.c
drivers/digital-io/max22196/max22196.c
drivers/digital-io/max22196/max22196.h

MAX22194 is the same as MAX22196 except it doesn't have the 5 to 8 channels and channel counting functionality, therefore
the first commit handles the compatibility of the driver for MAX22194 as well as the MAX22196 using a chip_id enum inside of the device descriptor as well as the initialization parameter.
The second commit only uses the new approach for avoiding memory leaks at initialization of the driver.
The third commit updates the README.rst file so any MAX22194 extra related documentation is included and therefore be found in the no-OS repository.

drivers: digital-io: max22196 : Add support for MAX22194

---

tools/scripts/generic_variables.mk
tools/scripts/maxim.mk

This is a small suggestion for improvement.
Currently when using uppercase letters for specifying the maxim target an unrelated error is thrown.
Allow users to use both lower case and uppercase letters when specifying the target.
For maxim targets we already have uppercase and lowercase variables initialized with `TARGET_UCASE`, `TARGET_LCASE` so they can be directly used for this feature.
With this patch both versions work, for example:
`make TARGET=max32650`
`make TARGET=MAX32650`

tools: scripts: make TARGET case insensitive

---

drivers/platform/maxim/max32690/maxim_i2c.h
drivers/platform/maxim/max32690/maxim_spi.h
drivers/platform/maxim/max32690/maxim_uart.h

Currently, the gpio.h header is not included in some header files which use GPIO specific data types. This may or may not result in compilation errors depending if a header which includes gpio.h is included before in a specific source file.
Fix this by explicitly including gpio.h whenever necessary.

platform: maxim: max32690: Include gpio.h

---

tools/scripts/build_projects.py

Two next_stable folders were created in artifactory for hdl project and the valid one is found now under releases path in artifactory.
In order to access the new folder the search needs to be done first in releases path.

tools: scripts: change hdl_branch search in artifactory

---

drivers/adc/ad713x/ad713x.c

Bug fix to ensure that number of array elements dont exceed the array size
fixes: e1161fa ("drivers:adc:ad713x:add ad7134 data format")

drivers:adc:ad713x:Bug fix with AD7134 driver

---

drivers/platform/maxim/max32650/maxim_irq.c
drivers/platform/maxim/max32655/maxim_irq.c
drivers/platform/maxim/max32660/maxim_irq.c
drivers/platform/maxim/max32665/maxim_irq.c
drivers/platform/maxim/max32690/maxim_irq.c
drivers/platform/maxim/max78000/maxim_irq.c

Currently max_irq_register_callback() explicitly uses an event name instead of callback_desc->event for no reason. This results in having to repeat the create/update callback list seqence for each event type. Fix this by accesing callback_desc->event instead.
Also, in case we already have an action registered, make sure the MCU specific configuration successfully completes before updating the action.

drivers: platform: maxim: Simplify irq_register_callback

---

drivers/rf-transceiver/madura/adrv9025.c

The phy->clks ops allow for just the redaing of the rx_iqRate_kHz and tx_iqRate_kHz members of adrv9025_rf_phy.

madura: adrv9025.c: Specify correct clks ops

---

drivers/platform/maxim/max78000/maxim_dma.c
drivers/platform/maxim/max78000/maxim_dma.h

This change was not applied for the max78000 in https://github.com/analogdevicesinc/no-OS/commit/b2775b22b47ac1109adf166863bb0a033ef8de92 , even though it's required.

Remove dma files symlinks for max78000

---

drivers/rf-transceiver/madura/adrv9025_conv.c

Set the clock_hz value for the tx_dac structure.
Fixes: 9a11234 ("drivers: rf-transceiver: madura: Add driver")

madura: adrv9025_conv.c: Set tx_dac clock value

---

drivers/axi_core/axi_pwmgen/axi_pwm.c
drivers/axi_core/axi_pwmgen/axi_pwm_extra.h

This introduces support for the AXI PWM Gen. IP Core v2, which has been released in the HDL repository. It includes a runtime check within the driver to ensure compatibility with v1.  This does not affect the existing projects.

Add support for AXI PWM Generator v2

---

drivers/platform/stm32/stm32_pwm.c

The PWM polarity was being hardcoded to TIM_OCPOLARITY_HIGH, despite there being a no-OS structure member for polarity
Fixes: 9264d89 ("stm32 pwm support")

drivers:platform:stm32:Fixes to PWM driver

---

drivers/platform/stm32/stm32_i2c.c
drivers/platform/stm32/stm32_i2c.h

An STM32F4 macro check has been added for usage two structure members in the stm32_i2c.c, that aren't a part of STM32L5, STM32H5 family.

drivers:platform:stm32:Update STM32 I2C Drivers

---

projects/adrv9009/src/app/headless.c

Set DMA data type for DAC in the case of DMA example.
Fixes: f9992d9 ("projects: adrv9009: Add an example for using DAC DMA")

adrv9009: headless.c: Set DMA data type for DAC DMA example

---

projects/ad7091r8-sdz/README.rst
projects/ad7616-st/README.rst
projects/adp1050/README.rst
projects/eval-adis1646x/README.rst
projects/eval-adis1647x/README.rst
projects/eval-adis1650x/README.rst
projects/eval-adis1657x/README.rst
projects/max14914/README.rst
projects/max14919/README.rst
projects/max2201x/README.rst

The syntax used to create Table of Contents for .rst files does not require adding extra string.
Both sphinx generated files and github previews parse this approach in an odd/redundant manner since all these filest already contain a header named "Contents" which is generated via syntax.
Example on how it currently looks:
After this patch the automatically generated "Contents" string will be displayed only.

README.rst: drop redundant ToC string

---

drivers/platform/maxim/common/maxim_dma.c

no_os_free() only has to be called once for the entire channels array, otherwise, a double free will occur.

drivers: platform: maxim: Fix DMA remove

---

drivers/platform/maxim/max32670/maxim_uart_stdio.c
drivers/platform/maxim/max32670/maxim_uart_stdio.h

This PR is to have the maxim_uart_stdio available for max32670 platform. Upon inspection, the same file is used for all maxim platforms and so the same file is used for max32670.

drivers: platform: maxim: add uart_stdio for max32670

---

drivers/api/no_os_timer.c
drivers/platform/aducm3029/aducm3029_timer.c
drivers/platform/generic/generic_timer.c
drivers/platform/linux/linux_timer.c
drivers/platform/maxim/max32650/maxim_timer.c
drivers/platform/maxim/max32655/maxim_timer.c
drivers/platform/maxim/max32660/maxim_timer.c
drivers/platform/maxim/max32665/maxim_timer.c
drivers/platform/maxim/max32690/maxim_timer.c
drivers/platform/maxim/max78000/maxim_timer.c
drivers/platform/xilinx/xilinx_timer.c
include/no_os_timer.h

Some platforms are missing the const qualifier in timer_init APIs. This commit adds the qualifier where needed, to fix compilation warnings.

drivers: api: no_os_timer: Add const qualifier to timer init param

---

doc/sphinx/source/drivers/ltc4296.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/ltc4296.rst
doc/sphinx/source/projects_doc.rst
drivers/power/ltc4296/README.rst
drivers/power/ltc4296/ltc4296.c
drivers/power/ltc4296/ltc4296.h
projects/ltc4296/Makefile
projects/ltc4296/README.rst
projects/ltc4296/builds.json
projects/ltc4296/src.mk
projects/ltc4296/src/common/common_data.c
projects/ltc4296/src/common/common_data.h
projects/ltc4296/src/examples/basic/basic_example.c
projects/ltc4296/src/examples/basic/basic_example.h
projects/ltc4296/src/examples/examples_src.mk
projects/ltc4296/src/platform/maxim/main.c
projects/ltc4296/src/platform/maxim/parameters.c
projects/ltc4296/src/platform/maxim/parameters.h
projects/ltc4296/src/platform/maxim/platform_src.mk
projects/ltc4296/src/platform/platform_includes.h

The LTC4296-1 is an IEEE 802.3cg-compliant, five port, single-pair
power over Ethernet (SPoE), power sourcing equipment (PSE)
controller. SPoE simplifies system design and installation with
standardized power and Ethernet data over a single-pair cable. The
LTC4296-1 is designed for interoperability with 802.3cg powered
devices (PDs) in 24 V or 54 V systems.

power: ltc4296: add driver & appplication

---

drivers/platform/maxim/max32670/maxim_timer.c
drivers/platform/maxim/max32670/maxim_timer.h

max32670 has similarities with 32655/32690/7800. checked w/ SDK API's as well
adding timer platform driver support for max32670. Upon checking, max32655, 32690, 78000,
and 32670 have similar implementation i.e., cfg parameters based on SDK codes. The code for
max32670 timer platform driver is based on max32690 platform driver implementation.

platform: maxim: add timer support for max32670

---

drivers/adc/ad7124/ad7124.c
drivers/adc/ad7124/ad7124.h

Removed comment to change device ID by user for new silicon and added macros for the same. Also updated the device ID checks in ad7124_setup function.

drivers: adc: ad7124: Updating the Device IDs

---

doc/sphinx/source/drivers/ad405x.rst
doc/sphinx/source/drivers_doc.rst
drivers/adc/ad405x/README.rst
drivers/adc/ad405x/ad405x.c
drivers/adc/ad405x/ad405x.h

1. Add support for sample, averaging and burst averaging modes
2. Add support for spi read-write
3. Add bitfield definitions and apis for modifying and accessing bitfields

drivers:adc: Add ad405x no-OS drivers

---

projects/ad5460/src/platform/mbed/main.c

There is no IIO_EXAMPLE usage currenly in the project.
Fixes: dac70d6 ("projects: ad5460: add initial example")

projects: ad5460: drop IIO_EXAMPLE

---

tools/scripts/maxim.mk
tools/scripts/stm32.mk

(Referencing issue #2181, the following content is copied from there)
The `$(PROJECT_TARGET)_configure` targets in [tools/scripts/stm32.mk](https://github.com/analogdevicesinc/no-OS/blob/main/tools/scripts/stm32.mk) and [tools/scripts/maxim.mk](https://github.com/analogdevicesinc/no-OS/blob/main/tools/scripts/maxim.mk) use the [GNU Make `file` function](https://www.gnu.org/software/make/manual/html_node/File-Function.html) to set up a default VS Code configuration for projects, with no regard to the contents of those files.
https://github.com/analogdevicesinc/no-OS/blob/3cb5f58f6815c4fa63b732bb5072d42483ad6f81/tools/scripts/maxim.mk#L139-L143
For context, the content of the files is generated in [vsc_intellisense.mk](https://github.com/analogdevicesinc/no-OS/blob/main/tools/scripts/vsc_int …

Don't overwrite .vscode config if it already exists

---

doc/sphinx/source/drivers/ad796x.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/ad796x_fmcz.rst
doc/sphinx/source/projects_doc.rst
drivers/adc/ad796x/README.rst
drivers/adc/ad796x/ad796x.c
drivers/adc/ad796x/ad796x.h
drivers/axi_core/axi_dmac/axi_dmac.c
drivers/axi_core/iio_axi_adc/iio_axi_adc.c
projects/ad796x_fmcz/Makefile
projects/ad796x_fmcz/README.rst
projects/ad796x_fmcz/builds.json
projects/ad796x_fmcz/src.mk
projects/ad796x_fmcz/src/common/common_data.c
projects/ad796x_fmcz/src/common/common_data.h
projects/ad796x_fmcz/src/examples/basic_example/basic_example.c
projects/ad796x_fmcz/src/examples/basic_example/basic_example.h
projects/ad796x_fmcz/src/examples/examples_src.mk
projects/ad796x_fmcz/src/examples/iio_example/iio_example.c
projects/ad796x_fmcz/src/examples/iio_example/iio_example.h
projects/ad796x_fmcz/src/platform/platform_includes.h
projects/ad796x_fmcz/src/platform/xilinx/main.c
projects/ad796x_fmcz/src/platform/xilinx/parameters.c
projects/ad796x_fmcz/src/platform/xilinx/parameters.h
projects/ad796x_fmcz/src/platform/xilinx/platform_src.mk

This adds driver files and a project test the ad796x series of pulsar Differential ADC.
The HDL for this project is still not merged, and probably its why CI is failing.
perhaps review can start without the HDL 
this was tested using the HDL binary at https://github.com/adi-ses/sea-misc/tree/main/AD796x-PRJ

ad796x: Add project and driver for ad796x-fmc

---

tools/scripts/generic.mk
tools/scripts/maxim.mk
tools/scripts/stm32.mk

After 86d407b("tools:scripts: Don't overwrite .vscode config if it already exists") the vscode configuration files (contents of the .vscode directory) are no longer overwritten on every make build. This may lead to confusion if the build was acciedentally done for a different platform than the one intended.
Such a situation may occur if the user runs "make build" (without the PLATFORM variable), resulting in generating the vscode configurations for the STM32 platform. From this point there is no way to change the target to another platform using the build system. Fix this by removing the .vscode directory on "make reset".
You can tick the checkboxes below with an 'x' between square brackets or just check them …

tools: scripts: Delete .vscode on reset

---

projects/swiot1l/src/common/swiot.c

Currently, the channel configuration attributes of the swiot virtual IIO device are reset when the context is switched from runtime to config. Keep the device and function attribute values and set enabled to false instead. This improves usability when IIO clients are involved.

projects: swiot1l: Save channel configuration

---

projects/ad9361/src/main.c

Set tx_dac rate to 1 for 1r1t mode fo AD9361.
Problem signaled and solved in the following two EZ threads:
https://ez.analog.com/microcontroller-no-os-drivers/f/q-a/581897/no-os-1r1t-dac-dma
https://ez.analog.com/microcontroller-no-os-drivers/f/q-a/571313/ad9364-dac-rate/498804?queryID=92a6dba6aaea82ca5f95812696f18cc2&objectId=0479fa6a-6177-4c34-8bc3-cd9264901e12&eztype=Forum%20Reply

ad9361: src: main.c: Set DAC rate for 1r1t mode

---

drivers/meter/ade9113/ade9113.c
drivers/meter/ade9113/ade9113.h

Remove silicon revision check in ADE9113 driver.
Remove the comparison to known silicon revisions, since the value in the register is subject to change with each silicon revision.

AD9113 remove silicon revision check

---

projects/ad-acevsecrdset-sl/src/pilot/pilot.c
projects/ad-acevsecrdset-sl/src/state_machine/state_machine.c

Update project so that mains measurement works correctly. Problem appeared when using latest Maxim SDK (August 7, 2022 Release).

Switch to latest Maxim SDK

---

drivers/axi_core/spi_engine/spi_engine.c

If data_width value is lower than 8 bits, the word length is set to zero and no data is transfered. Rounding Up the word length also fixes undersampling problem when data_width is not a multiple of 8.

spi-engine: fix word length zero 

---

projects/ad-acevsecrdset-sl/src/platform/parameters.h
projects/ad-acevsecrdset-sl/src/state_machine/state_machine.c

Print state and charging current only when entering the state. This will allow faster execution of the state machine and remove redundant debug messages.

ad-acevsecrdset-sl: state_machine.c: Print state once

---

doc/sphinx/source/drivers/ltc2992.rst
doc/sphinx/source/drivers_doc.rst
drivers/power/ltc2992/README.rst
drivers/power/ltc2992/ltc2992.c
drivers/power/ltc2992/ltc2992.h

The LTC2992 is a rail-to-rail system monitor that measures current,
voltage, and power of two supplies. It features an operating range of
2.7V to 100V and includes a shunt regulator for supplies above 100V.
Minimum and maximum values are stored and an overrange alert with
programmable thresholds minimizes the need for software polling. Data is
reported via a standard I2C interface.

drivers: power: ltc2992: Add LTC2992 driver

---

drivers/platform/stm32/stm32_spi.h

The pwm init parameters is of the wrong type.
it should be no_os_pwm_init_param and not no_os_pwm_init.

drivers: platform: stm32_spi: Fix pwm init parameters

---

drivers/rf-transceiver/ad9361/ad9361.c

The author wrote FORCE_VCO_TUNE instead of FORCE_VCO_TUNE_ENABLE. FORCE_VCO_TUNE is the 8th (MSB) of the VCO capacitor tune word. FORCE_VCO_TUNE_ENABLE is indeed the bit that forces or not the usage of the VCO capacitor tune word.
Closes #2211

ad9361: fix FORCE_VCO_TUNE_ENABLE typo

---

projects/iio_demo/builds.json

With https://github.com/analogdevicesinc/hdl/pull/1208 the ad40xx hdl project was renamed to pulsar adc, therefore the hdl artifacts have a different name now, althought this should not have an impact on the functionality of the project for xilinx platform.

projects: iio_demo: update xilinx hw file

---

drivers/platform/maxim/max32650/maxim_delay.c
drivers/platform/maxim/max32655/maxim_delay.c
drivers/platform/maxim/max32660/maxim_delay.c
drivers/platform/maxim/max32665/maxim_delay.c
drivers/platform/maxim/max32670/maxim_delay.c
drivers/platform/maxim/max32690/maxim_delay.c
drivers/platform/maxim/max78000/maxim_delay.c

Fix the following issues related to the systick counter to no_os_time conversion:
- The systick couter is decreasing from SysTick->LOAD to 0 every millisecond (and generating an interrupt once it reaches 0), thus we need to use SysTick->LOAD - SysTick->VAL instead of only SysTick->VAL in order to count microseconds in the [0, 999] in the correct order. The current implmentation assumes the SysTick is increasing it's value.
- For the [0, 999] microsecond range, rewrite the expression in order to make it clearer what is being computed.
- Capture the values of _system_ticks and SysTick->VAL before computing the time since those operations are not atomic, and the systick's value will change in the meantime. This will result in invalid s and us values.
- Disable the systick counter before …

drivers: platform: maxim: Fix no_os_time computation

---

build_projects.yml

Similar to the Xilinx job, increase all the platform timeouts to a custom value of 200.

buid_projects.yml: set timeout for all platforms

---

drivers/platform/maxim/max32650/maxim_irq.c
drivers/platform/maxim/max32655/maxim_irq.c
drivers/platform/maxim/max32660/maxim_irq.c
drivers/platform/maxim/max32665/maxim_irq.c
drivers/platform/maxim/max32670/maxim_irq.c
drivers/platform/maxim/max32690/maxim_irq.c
drivers/platform/maxim/max78000/maxim_irq.c

Currently, there may be multiple interrupt controllers allocated, even though there is only one hardware instance (NVIC). The issue is that is no_os_irq_ctrl_remove() is called for an interrupt controller with ref = 0, all the callback functions will be removed, even those which were registered using another controller.
Fix this by turning the interrupt controller into a shared reference, thus max_irq_ctrl_remove() will only be called once ref = 0.

drivers: platform: maxim: Fix irq_desc removal

---

projects/adrv9009/src/app/app_transceiver.c

Set the deinit function to remove the rx_adxcvr component for ADRV9009 and ADRV9008-1 devices (ADRV9008-2 does not have Rx).
Fixes: b013932 ("projects:adrv9009:add support for adrv9008-1/2")

adrv9009: src: app: app_transceiver.c: Fix deinit

---

projects/adrv9009/src/app/headless.c

Remove the Obs Rx ADC for the ADRV9008-1 device.
Fixes: 926a732 ("adrv9009: Add ADRV9008_2 Rx obs components")

adrv9009: headless.c: Remove ObsRx for ADRV9008-1

---

drivers/platform/maxim/max32650/maxim_irq.c
drivers/platform/maxim/max32655/maxim_irq.c
drivers/platform/maxim/max32660/maxim_irq.c
drivers/platform/maxim/max32665/maxim_irq.c
drivers/platform/maxim/max32670/maxim_irq.c
drivers/platform/maxim/max32690/maxim_irq.c
drivers/platform/maxim/max78000/maxim_irq.c

Assign the user's no_os_irq_ctrl_desc instead of the local one.
Fixes: 353a1bf57 ("drivers: platform: maxim: Fix irq_desc removal")

platform: drivers: maxim: Assign the proper irq_ctrl_desc

---

projects/adv7511/src/main.c

Initialize the  I2C device id in the adv7511_i2c_init structure.

projects: adv7511: src: main.c: Add I2C dev id

---

drivers/accel/adxl313/adxl313.h

The datasheet specifies a 48.83 mg/LSB scale factor, and not 4.883 mg/LSB.
Fixes: 48d3db8 ("drivers:accel_adxl313: ADXL313 driver update")

accel: adxl313: adxl313.h: Fix ADXL314 scale factor

---

drivers/platform/maxim/max32650/maxim_pwm.c
drivers/platform/maxim/max32650/maxim_pwm.h
drivers/platform/maxim/max32655/maxim_pwm.c
drivers/platform/maxim/max32655/maxim_pwm.h
drivers/platform/maxim/max32660/maxim_pwm.c
drivers/platform/maxim/max32660/maxim_pwm.h
drivers/platform/maxim/max32665/maxim_pwm.c
drivers/platform/maxim/max32665/maxim_pwm.h
drivers/platform/maxim/max32670/maxim_pwm.c
drivers/platform/maxim/max32670/maxim_pwm.h
drivers/platform/maxim/max32690/maxim_pwm.c
drivers/platform/maxim/max32690/maxim_pwm.h
drivers/platform/maxim/max78000/maxim_pwm.c
drivers/platform/maxim/max78000/maxim_pwm.h

This PR contains the commit adding the Maxim PWM driver.
- Extra field from no_os_pwm_desc is used as the timer's prescaler used to calculate the ticks for both period and duty cycle.
- The prescaler for both should be the same and is calculated depending on the duty cycle since it is always smaller than
the period, therefor a good resolution of the PWM will be obtained.

drivers: platform: maxim: pwm: Add Maxim PWM platform driver

---

projects/ad400x-fmcz/src/examples/examples_src.mk

The flag to enable offload for the xilinix platform is wrong. Correct this so that offload is enabled by default for the xilinx platform.

projects: ad400x_fmcz: Fix enable offload flag

---

drivers/adc/ad400x/ad400x.c
drivers/axi_core/axi_dmac/axi_dmac.c
drivers/axi_core/axi_dmac/axi_dmac.h
drivers/axi_core/spi_engine/spi_engine.c

The bytes that are transfered on dma per sample depend
on the DMA_DATA_WIDTH_SRC of the dma IP not on the data_width
bytes sent by the spi_engine on the spi bus.

Fix spi engine offload

---

drivers/axi_core/spi_engine/spi_engine.c

The rx offload size can be 2, 4 or more bytes, it should use the size read from the IP and not be hardcoded to 4.

drivers: spi_engine: Dont hardcode rx dma size

---

projects/ad-acevsecrdset-sl/src/self_test/self_test.c

Removed v1(Vin) ADE rms value and v2(relay voltage) from the debug message.
Changed the "Test supply" debug message. Removed two values and left only the rms supply voltage.

projects: ad-acevsecrdset-sl: Changed "Test supply ..." debug message

---

drivers/adc/ad400x/ad400x.c
drivers/adc/ad400x/ad400x.h
projects/ad400x-fmcz/src/common/common_data.c

Add more parts to the list of supported parts by the ad4000 drivers
the ad400x driver might need to be renamed to pulsar_adc at some point. 
- [x ] I have signed off all commits from this PR

drivers: ad400x: Support more pulsar parts

---

drivers/axi_core/spi_engine/spi_engine.c
drivers/axi_core/spi_engine/spi_engine_private.h

It's only the lower 16 bits that are actually the data-width in register 0xC.
Bits 23:16 are NUM_SDI.
```
8'h03: up_rdata_ff <= {8'b0, NUM_OF_SDI, DATA_WIDTH};
```
Link:
https://github.com/analogdevicesinc/hdl/blob/d95528a533cefc6d82b9fdebd30ee85b3e10c880/library/spi_engine/axi_spi_engine/axi_spi_engine.v#L348

spi-engine: fix data_width read from HDL

---

drivers/axi_core/spi_engine/spi_engine.c

During commit c24331264 ("drivers: axi_core: Fix offload xfer size") this was omitted (for removal).
Fixes: c24331264 ("drivers: axi_core: Fix offload xfer size")

drivers: spi-engine: remove unused variable

---

drivers/adc/ad7606/ad7606.c

The ad7606_reset() function will clear the channel gain/offset/phase parameters.
As such, the ad7606_init() function will never initialize these parameters.
To fix that, we just memcpy() them right after a call to ad7606_reset().
Fixes: c5ce09e9c0 ("ad7606: Add basic support for AD7606 family of devices")

drivers: ad7606: pass channel init params to dev struct

---

drivers/axi_core/spi_engine/spi_engine.c
drivers/axi_core/spi_engine/spi_engine.h
projects/ad713x_fmcz/src/ad713x_fmc.c
projects/cn0561/src/cn0561.c

The 'dma_flags' field in the spi_engine_offload_init_param struct is a pointer to an uint32_t.
This seems a bit much; if this field is 0 (not initialized), the default behavior (or CYCLIC DMA) is maintained.
It mostly looks like un-necessary reference/dereference.
Also, there are only 2 projects that use this field. Changing them to the new behavior looks simple.

spi-engine: de-pointerize the dma_flags field in init params

---

drivers/adc/ad7606/ad7606.c
drivers/adc/ad7606/ad7606.h

This is just a preliminary change that can go in before others, to add AXI/SPI-engine support to the driver.

ad7606: add PWM and AXI clock-gen support for driver

---

drivers/dac/ltc2672/ltc2672.c

Fix overflow of intermediate conversion value of
current in uA to code.
Fixes: 51f92f898c950b8e317cce2daca11da153ea6a10 ("dac: ltc2672: Remove float type usage")

drivers:dac:ltc2672: Fix current_to_code api

---

tools/scripts/stm32.mk

**stm32: Enable Windows support** 
Passing the correct .jar file to java and using the relative paths instead of full paths are the required changes to enable the Windows building.
To avoid incompatibility issues, use the Java Runtime Environment provided by STM32CubeMX.
e.g.:
export PATH=$PATH:/c/STMicroelectronics/STM32CubeMX/jre/bin
The other 2 environment variables required (similar to Linux) are STM32CUBEMX and STM32CUBEIDE.
e.g.:
export STM32CUBEMX=/c/STMicroelectronics/STM32CubeMX
export STM32CUBEIDE=/c/STMicroelectronics/STM32CubeIDE
**stm32: Fix STM32CUBEIDE build (Linux and Windows)**
generic.mk is linking $(ASM_SRCS), so, the startup file ends up being included
twice. This breaks the build of the project in STM32CUBEIDE.
Use a different name (e.g., STARTUP_FILE instead of …

stm32: Enable Windows support and fix STM32CUBEIDE build

---

include/no_os_util.h
util/no_os_util.c

APIs added:
no_os_field_max_u64
no_os_mul_u64_u32_div
no_os_find_first_set_bit_u64
no_os_field_prep_u64
no_os_greatest_common_divisor_u64
no_os_rational_best_approximation_u64

util: add APIs for 64 bits variables

---

build_projects.yml
tools/scripts/build_projects.py

After the modifications for stm32 platform to support windows builds the BUILD_DIR variable from make won't be used anymore, always the build will be made in the project directory under build folder.
Changed also the relative path to absolute ones for python script.

tools:scripts:build_projects.py: update build dir for stm32 projects

---

drivers/platform/maxim/max32650/maxim_irq.c

This line was deleted by mistake in commit https://github.com/analogdevicesinc/no-OS/commit/a508f9bce73b2f7c7739435b2b561bac852bcb44
("drivers: platform: maxim: DMA API implementation"). Add it back.

max32650: Set IRQ action list as NULL on remove

---

tools/scripts/stm32.mk

warning: cannot find entry symbol Reset_Handler; defaulting to 0000000008000000
Fixes: 420753309317 ("stm32: Fix STM32CUBEIDE build (Linux and Windows)")

stm32: Fix build

---

drivers/filter/admv8818/admv8818.c
drivers/filter/admv8818/admv8818.h

The reg address size should be 16 bits wide and not 8.
Fixes: 3755205 ("drivers:filter: add admv8818 support")

filter: admv8818: fix reg addr size

---

drivers/platform/stm32/stm32_dma.c

The DMA drivers specific to STM32 did not have support for STM32H5 which lead to build errors in certain projects.
In this Pull Request, we can find changes made according to the DMA handler of STM32H5 for proper initialization in the driver.

drivers:platform:stm32:Added support for STM32H5 in the DMA driver

---

drivers/adc/ad7606/ad7606.c
drivers/adc/ad7606/ad7606.h
projects/ad7606x-fmc/Makefile
projects/ad7606x-fmc/builds.json
projects/ad7606x-fmc/src.mk
projects/ad7606x-fmc/src/basic_example.c
projects/ad7606x-fmc/src/common_data.c
projects/ad7606x-fmc/src/common_data.h
projects/ad7606x-fmc/src/parameters.h

This change-set adds a `basic_example` for collecting samples from the AD7606x series using SPI-Engine.
It also contains the last additions to the AD7606 driver to be able to operate with HDL (SPI-Engine, AXI-ADC, AXI-PWM)

projects: ad7606x-fmc: add initial revision of project (just basic_example now)

---

drivers/dac/ad5791/ad5791.c
drivers/dac/ad5791/ad5791.h

According to the datasheet, AD5791_CTRL_RBUF_MASK needs to be clared when an external amplifier is connected in a gain of two configuration. Added support for this feature.

drivers: ad5791: add support for rbuf gain of two config

---

doc/sphinx/source/drivers/max31827.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/max31827-evkit.rst
doc/sphinx/source/projects_doc.rst
drivers/temperature/max31827/README.rst
drivers/temperature/max31827/iio_max31827.c
drivers/temperature/max31827/iio_max31827.h
drivers/temperature/max31827/max31827.c
drivers/temperature/max31827/max31827.h
projects/max31827-evkit/Makefile
projects/max31827-evkit/README.rst
projects/max31827-evkit/builds.json
projects/max31827-evkit/src.mk
projects/max31827-evkit/src/common/common_data.c
projects/max31827-evkit/src/common/common_data.h
projects/max31827-evkit/src/examples/basic/basic_example.c
projects/max31827-evkit/src/examples/basic/basic_example.h
projects/max31827-evkit/src/examples/examples_src.mk
projects/max31827-evkit/src/examples/iio_example/iio_example.c
projects/max31827-evkit/src/examples/iio_example/iio_example.h
projects/max31827-evkit/src/platform/maxim/main.c
projects/max31827-evkit/src/platform/maxim/parameters.c
projects/max31827-evkit/src/platform/maxim/parameters.h
projects/max31827-evkit/src/platform/maxim/platform_src.mk
projects/max31827-evkit/src/platform/platform_includes.h

The MAX31827 is a ±1°C accuracy from -40°C to +125°C (12 bits) local temperature switch and sensor with I2C/SMBus interface. The combination of small 6-bump wafer-level package (WLP) and high accuracy makes this temperature sensor/switch ideal for a wide range of applications. It can be used as a temperature switch with preconfigured thresholds and/or as a temperature sensor with I2C interface. When the part operates as an independent temperature switch, the I2C interface doesn't have to be used. This enables use of the part in systems that require thermal protection implemented in hardware, without the need for reconfiguration or use of software/firmware during normal operation.
The driver also supports MAX31828 and MAX31829.

drivers: temperature: max31827: Add driver support for MAX31827/MAX31828/MAX31829

---

iio/iio_app/iio_app.c

This reverts commit 47e4fd3f239d82fd3266bd0f4a56e5a983a77fe5.
The print_uart_hello_message() function initializes the uart descriptor used subsequently in the iio app initialization phase (it is passed to iio_init_param.uart_desc).

Revert "iio: iio_app: print hello message later"

---

drivers/axi_core/axi_dmac/axi_dmac.c
drivers/rf-transceiver/madura/README.rst
projects/ad713x_fmcz/src/ad713x_fmc.c
projects/ad9081/src/app.c
projects/ad9361/src/main.c
projects/ad9371/src/app/headless.c
projects/adrv9001/src/app/headless.c
projects/cn0561/src/cn0561.c
projects/fmcadc2/src/fmcadc2.c
projects/fmcadc5/src/fmcadc5.c

Address Alignment
Software must program the SRC_ADDRESS and DEST_ADDRESS registers to be multiple of the corresponding MM data bus. The following conditions must hold:
SRC_ADDRESS MOD (DMA_DATA_WIDTH_SRC/8) == 0
DEST_ADDRESS MOD (DMA_DATA_WIDTH_DEST/8) == 0 
https://wiki.analog.com/resources/fpga/docs/axi_dmac

Align buffers for DMA transfers

---

drivers/motor/tmc7300/tmc7300.c
drivers/motor/tmc7300/tmc7300.h

The TMC7300 is a low voltage driver for one or two DC motors up to 2A (2.4A peak).  Its two full-bridges allow either control of two DC motors, PWM-control of LEDs, or protected standalone peripheral driving, using a polarity signal per half-bridge. The communication with the host MCU is done via a UART interface.

drivers: motor: Add TMC7300

---

drivers/platform/stm32/stm32_dma.c

Channel number is assigned via the Instance for MCU families other than STM32F2, STM32F4 and STM32F7.
In this Pull Request, we can find changes made to support the DMA handlers of all MCUs.

STM32 DMA driver issue fix

---

projects/eval-pqmon/src/common/afe_config.c
projects/eval-pqmon/src/common/iio_pqm.c

* Fix: tinyIIO has to return harmonics for current different from voltage
* For Harmonics calculation Waveform half buffer full should be the enabled interrupt in order to maintain the correct calculation of the FFT, otherwise the RMSONE interrupt remains the main input from ade9430 since it has the highest frequency

Pqmon bugfix

---

iio/iio_app/iio_app.c

Two changes done during the development of the `ad7606x-fmc` project

iio: iio_app: don't overwrite status-code in iio_app_init() on the error path

---

drivers/platform/maxim/max32650/maxim_pwm.c
drivers/platform/maxim/max32655/maxim_pwm.c
drivers/platform/maxim/max32660/maxim_pwm.c
drivers/platform/maxim/max32665/maxim_pwm.c
drivers/platform/maxim/max32670/maxim_pwm.c
drivers/platform/maxim/max32690/maxim_pwm.c
drivers/platform/maxim/max78000/maxim_pwm.c

When setting the PWM using Maxim's SDK, the pulse's off state ticks are actually being set, therefore compute the duty_ticks in an inverted sort of way in order to obtain the correct values to the PWM.
Needs to be merged before #2310 .

drivers: platform: maxim : maxim_pwm.c

---

doc/sphinx/source/drivers/max42500.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/max42500.rst
doc/sphinx/source/projects_doc.rst
drivers/power/max42500/README.rst
drivers/power/max42500/max42500.c
drivers/power/max42500/max42500.h
projects/max42500/Makefile
projects/max42500/README.rst
projects/max42500/builds.json
projects/max42500/src.mk
projects/max42500/src/common/common_data.c
projects/max42500/src/common/common_data.h
projects/max42500/src/examples/basic/basic_example.c
projects/max42500/src/examples/basic/basic_example.h
projects/max42500/src/examples/examples_src.mk
projects/max42500/src/platform/maxim/main.c
projects/max42500/src/platform/maxim/parameters.c
projects/max42500/src/platform/maxim/parameters.h
projects/max42500/src/platform/maxim/platform_src.mk
projects/max42500/src/platform/platform_includes.h

The MAX42500 is a SoC power-system monitor with up to seven voltage monitor inputs that will be SIL 3-Certified. Each input has programmable OV/UV thresholds of between 2.5% and 10% with ±1.3% accuracy over the full temperature range. Two of the inputs have a separate remote ground-sense input and support DVS through the integrated I2C interface.
The MAX42500 contains a programmable flexible power sequence recorder (FPSR). This recorder stores power-up and power-down timestamps separately, and supports on/off and sleep/standby power sequences. The MAX42500 also contains a programmable challenge/response watchdog, which is accessible through the I2C interface, along with a configurable RESET output.
The MAX42500 improves reliability while significantly reducing system size and component …

Add max42500 driver and sample project

---

doc/sphinx/source/drivers/max25603.rst
doc/sphinx/source/drivers_doc.rst
drivers/led/max25603/README.rst
drivers/led/max25603/max25603.c
drivers/led/max25603/max25603.h
projects/max25603/Makefile
projects/max25603/builds.json
projects/max25603/src.mk
projects/max25603/src/common/common_data.c
projects/max25603/src/common/common_data.h
projects/max25603/src/examples/basic/basic_example.c
projects/max25603/src/examples/basic/basic_example.h
projects/max25603/src/examples/examples_src.mk
projects/max25603/src/platform/maxim/main.c
projects/max25603/src/platform/maxim/parameters.c
projects/max25603/src/platform/maxim/parameters.h
projects/max25603/src/platform/maxim/platform_src.mk
projects/max25603/src/platform/platform_includes.h

The MAX25603 is a synchronous four-switch, buckboost LED driver controller suitable for multifunction automotive combination head lamps. The controller regulates the LED current for LED string voltages from 0V to 60V. The MAX25603 can be used as a seamless buck-boost LED driver for applications that require an efficient buck-boost LED driver with synchronous rectification. The MAX25603 is ideal for high-power applications that require a current source with PWM dimming capability.
1st commit : driver files
2nd commit : driver documentation file
3rd commit : project files
Needs to be merged after #2327 .

drivers: led: max25603 : Add support for MAX25603

---

iio/iio.c

Fix wrong parsing for cases when fractional part has leading zeros, when fractional part exceeds subunit limit, and when values to parse are between 0 and -1.

iio: fix string-to-value parsing in iio_parse_value.

---

doc/sphinx/source/drivers/ltp8800.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/ltp8800.rst
doc/sphinx/source/projects_doc.rst
drivers/power/ltp8800/README.rst
drivers/power/ltp8800/iio_ltp8800.c
drivers/power/ltp8800/iio_ltp8800.h
drivers/power/ltp8800/ltp8800.c
drivers/power/ltp8800/ltp8800.h
projects/ltp8800/Makefile
projects/ltp8800/README.rst
projects/ltp8800/builds.json
projects/ltp8800/src.mk
projects/ltp8800/src/common/common_data.c
projects/ltp8800/src/common/common_data.h
projects/ltp8800/src/examples/basic/basic_example.c
projects/ltp8800/src/examples/basic/basic_example.h
projects/ltp8800/src/examples/examples_src.mk
projects/ltp8800/src/examples/iio_example/iio_example.c
projects/ltp8800/src/examples/iio_example/iio_example.h
projects/ltp8800/src/platform/maxim/main.c
projects/ltp8800/src/platform/maxim/parameters.c
projects/ltp8800/src/platform/maxim/parameters.h
projects/ltp8800/src/platform/maxim/platform_src.mk
projects/ltp8800/src/platform/platform_includes.h

The LTP8800 is a family of step-down μModule regulators that provides
microprocessor core voltage from 54V power distribution architecture. LTP8800
features remote configurability and telemetry monitoring of power management
parameters over PMBus—an open standard I2C-based digital interface protocol.

drivers: power: ltp8800: Add LTP8800 driver

---

doc/sphinx/source/drivers/lt7170.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/lt7170.rst
doc/sphinx/source/projects_doc.rst
drivers/power/lt7170/README.rst
drivers/power/lt7170/iio_lt7170.c
drivers/power/lt7170/iio_lt7170.h
drivers/power/lt7170/lt7170.c
drivers/power/lt7170/lt7170.h
projects/lt7170/Makefile
projects/lt7170/README.rst
projects/lt7170/builds.json
projects/lt7170/src.mk
projects/lt7170/src/common/common_data.c
projects/lt7170/src/common/common_data.h
projects/lt7170/src/examples/basic/basic_example.c
projects/lt7170/src/examples/basic/basic_example.h
projects/lt7170/src/examples/examples_src.mk
projects/lt7170/src/examples/iio_example/iio_example.c
projects/lt7170/src/examples/iio_example/iio_example.h
projects/lt7170/src/platform/maxim/main.c
projects/lt7170/src/platform/maxim/parameters.c
projects/lt7170/src/platform/maxim/parameters.h
projects/lt7170/src/platform/maxim/platform_src.mk
projects/lt7170/src/platform/platform_includes.h

The LT7170/LT7170-1 are monolithic DC/DC synchronous step-down regulators that 
deliver up to 20 A of continuous output current. The LT7170-1 option has two 
switching phases that are connected to two inductors to drive a 
single-regulated output supply.
Similarly, the LT7171/LT7171-1 are monolithic PolyPhase DC/DC synchronous 
step-down regulators that also deliver up to 20A of continuous output current. 
The LT7171-1 option has two switching phases that are connected to two 
inductors to drive a single-regulated output supply.
Both series offer quick, clean, low-overshoot switching edges deliver high 
efficiency while minimizing electromagnetic interference (EMI) emissions.
An I2C-based PMBus 1.3-compliant serial interface allows control of device 
functions while providing telemetry …

Add driver for LT7170/LT7170-1, LT7171/LT7171-1

---

drivers/adc/ad405x/ad405x.c
drivers/adc/ad405x/ad405x.h

According to the [ad4052 datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/ad4052-ad4058.pdf)
```
PRODUCT_ID_L.PRODUCT_ID        value is 0x72                          (p. 54)
ADC_MODES.DATA_FORMAT    reset value is 0x01 Twos Complement (Signed) (p. 58)
```
For the data_fomat, the ad405x iio driver on pcf [always write this register on init](https://github.com/analogdevicesinc/precision-converters-firmware/blob/main/projects/ad405x_iio/app/ad405x_iio.c#L1507-L1511), so this mistake only affects users leveraging the no-OS driver directly.
The first should affect all.

adc: ad405x: Fix AD4052 Production ID and Data format reset value.

---

doc/sphinx/source/drivers/lt8491.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/dc2703a.rst
doc/sphinx/source/projects_doc.rst
drivers/power/lt8491/README.rst
drivers/power/lt8491/iio_lt8491.c
drivers/power/lt8491/iio_lt8491.h
drivers/power/lt8491/lt8491.c
drivers/power/lt8491/lt8491.h
projects/dc2703a/Makefile
projects/dc2703a/README.rst
projects/dc2703a/builds.json
projects/dc2703a/src.mk
projects/dc2703a/src/common/common_data.c
projects/dc2703a/src/common/common_data.h
projects/dc2703a/src/examples/basic/basic_example.c
projects/dc2703a/src/examples/basic/basic_example.h
projects/dc2703a/src/examples/examples_src.mk
projects/dc2703a/src/examples/iio_example/iio_example.c
projects/dc2703a/src/examples/iio_example/iio_example.h
projects/dc2703a/src/platform/maxim/main.c
projects/dc2703a/src/platform/maxim/parameters.c
projects/dc2703a/src/platform/maxim/parameters.h
projects/dc2703a/src/platform/maxim/platform_src.mk
projects/dc2703a/src/platform/platform_includes.h

The LT8491 is a buck-boost switching regulator battery charger that implements a constant-current constant-voltage (CCCV) charging profile used for most battery types, including sealed lead-acid (SLA), flooded, gel and lithium-ion.
The device operates from input voltages above, below or equal to the output voltage and can be powered by a solar panel or a DC power supply. On-chip logic provides automatic maximum power point tracking (MPPT) for solar powered applications. The LT8491 can perform automatic temperature compensation by sensing an external thermistor thermally coupled to the battery. The STATUS pin can be used to drive an LED indicator lamp. The device is available in a low profile (0.75mm) 7mm x 11mm 64-lead QFN package.

Add support for LT8491

---

doc/sphinx/source/drivers/ade7816.rst
doc/sphinx/source/drivers_doc.rst
drivers/meter/ade7816/README.rst
drivers/meter/ade7816/ade7816.c
drivers/meter/ade7816/ade7816.h
drivers/meter/ade7816/ade7816_i2c.c
drivers/meter/ade7816/ade7816_spi.c
projects/ade7816/Makefile
projects/ade7816/builds.json
projects/ade7816/src.mk
projects/ade7816/src/common/common_data.c
projects/ade7816/src/common/common_data.h
projects/ade7816/src/examples/basic/basic_example.c
projects/ade7816/src/examples/basic/basic_example.h
projects/ade7816/src/examples/examples_src.mk
projects/ade7816/src/platform/maxim/main.c
projects/ade7816/src/platform/maxim/parameters.c
projects/ade7816/src/platform/maxim/parameters.h
projects/ade7816/src/platform/maxim/platform_src.mk
projects/ade7816/src/platform/platform_includes.h

The ADE7816 is a highly accurate, multichannel metering
device that is capable of measuring one voltage channel and up
to six current channels. It measures line voltage and current and
calculates active and reactive energy, as well as instantaneous rms
voltage and current. The device incorporates seven sigma-delta
(Σ-Δ) ADCs with a high accuracy energy measurement core.
The six current input channels allow multiple loads to be measured
simultaneously. The voltage channel and the six current channels
each have a complete signal path allowing for a full range of
measurements.

drivers: meter: ade7816 : Add support for ADE7816

---

drivers/platform/stm32/stm32_dma.c

DMA desc now takes the interrupt handler which is assigned to DMA init parameter

sg_handler issue fix during initialization

---

drivers/platform/stm32/stm32_pwm.c

Zero initialized the structure as some of the parameters with garbage values were behaving in an undesirable manner in the stm32_init_timer() function when called

STM32 PWM driver issue fix

---

drivers/adc/ad7606/ad7606.c
drivers/adc/ad7606/ad7606.h

add a new function ad7606_data_correction_serial to correct spi read serial raw data for
1. sign extend for hardware/bipolar mode in case of negative value
2. split data and status information into 2 arrays.
- [x ] New feature (change that adds new functionality)
- [x ] I have followed the [Coding style guidelines](http://analogdevicesinc.github.io/no-OS/drivers_guide.html#coding-style)
- [x ] I have performed a self-review of the changes
- [x ] I have commented my code, at least hard-to-understand parts
- [x ] I have tested in hardware affected projects, at the relevant boards
- [x ] I have signed off all commits from this PR

 add spi read data correction feature for  sign extend and split status 

---

drivers/platform/stm32/stm32_spi.c

1. The length parameter of Tx channel is reverted back to take bytes_number.
2. SPI Tx DMA is enabled

 Minor fixes to support DAC streaming

---

tools/scripts/generic.mk

In case CFLAGS,CPPFLAGS,ASFLAGS and OBJS lists change, their respective
files will also change. This should re-trigger a build.
The 'pre_build' rule is run via the 'update' build rule, which is now
getting called everything we build 'all'.
When the 'pre_build' gets run, we re-generate all flags.txt files, and
overwrite them if they changed.
When they change, the object file will rebuild.

tools: generic.mk: re-generate object files if flags.txt files have changed

---

projects/ad7606x-fmc/src.mk
tools/scripts/generic.mk

This is inspired by the SRC_DIRS build variable, but only focuses on
include files. Using the SRC_DIRS can be problematic, as it pulls
every .c & .h file from a directory.
But in some cases, we just want to pull in the header files. These header
files will only get compiled if a .c file pulls them in.
If this build variable is unspecified, it will be empty, so nothing will be
done (to potentially affect current projects).

tools: generic.mk: add NO_OS_INC_DIRS build var for pulling header files tools

---

tools/scripts/git-bash-paths.sh

When sourcing an environment script such as the Xilinx's settings64.sh, PATH entries need to be converted to Unix compatible paths. This script can be used to perform the conversion like this:
source tools/scripts/git-bash-paths.sh /c/Xilinx/Vitis/2022.2/settings64.sh
It's not necessarily specific to Xilinx platform but we're currently using it only for this purpose with possibility to extend it for other platforms.
Tested with Vitis 2022.2 on various projects for various targets such as zynq7000, microblaze, ultrascale.

add script to convert Windows to Unix paths

---

drivers/platform/maxim/max32660/maxim_uart.c
drivers/platform/maxim/max32660/maxim_uart.h
drivers/platform/maxim/max32665/maxim_uart.c
drivers/platform/maxim/max32665/maxim_uart.h

This adds max_uart_map in the init_param of the MAX32665 UART driver.
By default, the console UART for the MAX32665FTHR uses MAP_B, while the
EvKit_V1's uses MAP_A based on their corresponding BSPs [here](https://github.com/analogdevicesinc/msdk/blob/main/Libraries/Boards/MAX32665/FTHR/Source/board.c#L98) and [here](https://github.com/analogdevicesinc/msdk/blob/main/Libraries/Boards/MAX32665/EvKit_V1/Source/board.c#L248).
The sys_map_t is undocumented in the MSDK docs but it appears it sets
specific GPIO configs which varies with different board form factors according
to [here](https://github.com/analogdevicesinc/msdk/blob/main/Libraries/PeriphDrivers/Source/UART/uart_me14.c#L64). This change will allow users to access EvKit_V1 UART at the application
level without touching the platform …

Add uart_map in MAX32665 uart extras.

---

drivers/dac/ad5421/ad5421.c
drivers/dac/ad5421/ad5421.h

AD5421 driver had a bug when integrating into a custom example:
- SPI R/W status checks check against an expected length, rather than 0/-1 which is what the No-OS API comments indicate it should return.
- Very minor: I added the "No-Op" code from AD5421 datasheet (0x09). Currently the driver sends 0x00 which should suffice for reading data back, but I added 0x09 to match what the AD5421 GUI sends.

Fix AD5421 driver bugs

---

drivers/adc-dac/ad74416h/ad74416h.h
drivers/api/no_os_uart.c
drivers/platform/ftd2xx/mpsse/ftd2xx_uart.c

-Added Initialization for no_os_uart_init() function 
-Added separate GPIO definitions.

Segmentation fault for no_os_uart fix

---

drivers/platform/maxim/max32670/maxim_uart.c

MSDK board support packages and all other MAX32 No-OS drivers use APB CLK to initialize the UART, while MAX32670 uses IBRO. This caused issues printing to stdio/serial port on a project for me, so I'm submitting a fix to change this to APB CLK to match other implementations. This fix solved my problems with printing.

Change MAX32670 UART to Initialize with APB CLK

---

drivers/api/no_os_i3c.c
drivers/platform/stm32/stm32_i3c.c
drivers/platform/stm32/stm32_i3c.h
include/no_os_i3c.h

Some new boards from STM32 add a new protocol called I3C.
This pr adds an I3C API layer and STM32 I3C platform implementation.
This resource from STM32 gives a good overview on the protocol:
https://www.st.com/resource/en/application_note/an5879-introduction-to-i3c-for-stm32-mcus-stmicroelectronics.pdf
The specification is available at:
https://www.mipi.org/mipi-i3c-hci-download
The API was tested on the following boards:
nucleo-h503rb (mainly) nucleo-h563zi
focusing on the transactions and IBI feature

drivers: api: add i3c ; drivers: platform: stm32

---

doc/sphinx/source/drivers/ltm4686.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/ltm4686.rst
doc/sphinx/source/projects_doc.rst
drivers/power/ltm4686/README.rst
drivers/power/ltm4686/iio_ltm4686.c
drivers/power/ltm4686/iio_ltm4686.h
drivers/power/ltm4686/ltm4686.c
drivers/power/ltm4686/ltm4686.h
projects/ltm4686/Makefile
projects/ltm4686/README.rst
projects/ltm4686/builds.json
projects/ltm4686/src.mk
projects/ltm4686/src/common/common_data.c
projects/ltm4686/src/common/common_data.h
projects/ltm4686/src/examples/basic/basic_example.c
projects/ltm4686/src/examples/basic/basic_example.h
projects/ltm4686/src/examples/examples_src.mk
projects/ltm4686/src/examples/iio_example/iio_example.c
projects/ltm4686/src/examples/iio_example/iio_example.h
projects/ltm4686/src/platform/maxim/main.c
projects/ltm4686/src/platform/maxim/parameters.c
projects/ltm4686/src/platform/maxim/parameters.h
projects/ltm4686/src/platform/maxim/platform_src.mk
projects/ltm4686/src/platform/platform_includes.h

This adds driver and IIO support for LTM4686, LTM4686B and LTM4673.
The LTM4686 is a dual 10A (12A Peak) or single 20A (24A Peak) step-down
µModule DC/DC regulator with 39ms turn-on time.
The LTM4686B is a dual 14A (17A peak) or single 28A (34A peak) step-down
µModule DC/DC regulator with 39ms turn-on time.
The LTM4673 is a quad output, dual 12A and dual 5A, switching mode DC/DC
step-down μModule regulator.
It features remote configurability and telemetry-monitoring of power
management parameters over PMBus.

Add support for LTM4686

---

drivers/power/lt7182s/lt7182s.c
drivers/power/lt7182s/lt7182s.h

The LT7184S is a dual-output monolithic PolyPhase DC/DC synchronous step-down 
regulator that delivers up to 7A of continuous current from both channels
simultaneously and supports loads from -8A to +9A in either channel. LT7184S
contains the same set of registers with the LT7182S. Current and voltage ratings 
are the major differences.

drivers: power: lt7182s: Add support for LT7184S

---

drivers/adc/ad4170/ad4170.c
drivers/adc/ad4170/ad4170.h

According to a software support request, AD4190-4 and AD4195-4 have the same functionality/features.
Since AD4190 is already supported, add an option to indicate AD4195 is also supported.

Add option to support AD4195-4

---

drivers/dac/ad3530r/ad3530r.c
drivers/dac/ad3530r/ad3530r.h

Add header and source files for AD3530R driver.

drivers: dac: ad3530r: Add driver support for Ad3530R

---

doc/sphinx/source/drivers/ad8460.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/eval-ad8460.rst
doc/sphinx/source/projects_doc.rst
drivers/dac/ad8460/README.rst
drivers/dac/ad8460/ad8460.c
drivers/dac/ad8460/ad8460.h
drivers/dac/ad8460/iio_ad8460.c
drivers/dac/ad8460/iio_ad8460.h
projects/eval-ad8460/Makefile
projects/eval-ad8460/README.rst
projects/eval-ad8460/builds.json
projects/eval-ad8460/src.mk
projects/eval-ad8460/src/common/common_data.c
projects/eval-ad8460/src/common/common_data.h
projects/eval-ad8460/src/examples/basic/basic_example.c
projects/eval-ad8460/src/examples/basic/basic_example.h
projects/eval-ad8460/src/examples/examples_src.mk
projects/eval-ad8460/src/examples/iio_example/iio_example.c
projects/eval-ad8460/src/examples/iio_example/iio_example.h
projects/eval-ad8460/src/platform/maxim/main.c
projects/eval-ad8460/src/platform/maxim/parameters.c
projects/eval-ad8460/src/platform/maxim/parameters.h
projects/eval-ad8460/src/platform/maxim/platform_src.mk
projects/eval-ad8460/src/platform/platform_includes.h

Note: IIO Driver was patterned to the mainline AD8460 Linux driver
The AD8460 is a “bits in, power out” high voltage, high-power, high-speed driver optimized for large output current (up to ±1 A) and high slew rate (up to ±1800 V/μs) at high voltage (up to ±40 V) into capacitive loads. Combining a 14-bit high-speed DAC, a high voltage, high output current (HV-HI) analog driver, and fault monitoring and protection circuits, the AD8460 is ideally suited for high power applications such as arbitrary waveform generation (AWG), programmable power supplies, and high voltage automated test equipment (ATE).
A proprietary high-voltage BCDMOS process, novel high voltage architecture, and thermally enhanced package from Analog Devices Inc. enable this high-performance driver. A digital engine …

Add driver for AD8460

---

drivers/dac/ad9152/ad9152.h

The register definitions in AD9152.h have been updated to match the datasheet - registers that aren't in the datasheet have been removed, and registers missing from the header file that were in the datasheet have been added.  A few registers have also been renamed to match the datasheet.
- [N/A] I have tested in hardware affected projects, at the relevant boards
- [N/A] I have updated the documentation (wiki pages, ReadMe etc), if applies

AD9152.h Register Definition Updates

---

tools/scripts/maxim.mk

Since commit [1], the user may choose between two versions of the SPI driver for the MAX32690 and MAX78002. Currently, we're not defining this anywhere during the build and as such we get a linker error. Fix this by selecting v1 as a default value. At this time, the No-OS SPI drivers for the Maxim platform are based on the v1 version.
The issue first appeared in the v2024_10 release of msdk.
[1] - https://github.com/analogdevicesinc/msdk/commit/755e6ffa0d4627880fcd053435df295e780a742a

tools:scripts:Set the SPI driver version for Maxim

---

drivers/adc-dac/ad5592r/ad5592r-base.c
drivers/adc-dac/ad5592r/ad5592r-base.h
drivers/adc-dac/ad5592r/ad5592r.c
drivers/adc-dac/ad5592r/ad5592r.h
drivers/adc-dac/ad5592r/ad5593r.c
drivers/adc-dac/ad5592r/ad5593r.h

1. Added driver apis for adc range, dac range, power down,set internal reference and set adc buffer to the base driver.
2. Added API to enable busy indicatir on AD5592r
3. Removed static for spi nop API for visibilty.
4. Moved some macros from ad5593.c to header file for visibility.
- [] Bug fix (change that fixes an issue)

drivers:adc-dac:ad5592r: Driver Enhancement

---

drivers/net/adin1110/adin1110.c

no-OS has functions for handling memory allocation, so the adin1110 driver should use these functions for managing memory. 
- [  ] Bug fix (change that fixes an issue)
- [ x ] New feature (change that adds new functionality)

Use no-OS memory allocation functions for memory management

---

doc/sphinx/source/drivers/ltc7871.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/ltc7871.rst
doc/sphinx/source/projects_doc.rst
drivers/power/ltc7871/README.rst
drivers/power/ltc7871/iio_ltc7871.c
drivers/power/ltc7871/iio_ltc7871.h
drivers/power/ltc7871/ltc7871.c
drivers/power/ltc7871/ltc7871.h
projects/ltc7871/Makefile
projects/ltc7871/README.rst
projects/ltc7871/builds.json
projects/ltc7871/src.mk
projects/ltc7871/src/common/common_data.c
projects/ltc7871/src/common/common_data.h
projects/ltc7871/src/examples/basic/basic_example.c
projects/ltc7871/src/examples/iio_example/example.mk
projects/ltc7871/src/examples/iio_example/iio_example.c
projects/ltc7871/src/platform/maxim/main.c
projects/ltc7871/src/platform/maxim/parameters.c
projects/ltc7871/src/platform/maxim/parameters.h
projects/ltc7871/src/platform/maxim/platform_src.mk

Add support for ltc7871

---

doc/sphinx/source/drivers/admfm2000.rst
doc/sphinx/source/drivers_doc.rst
drivers/frequency/admfm2000/README.rst
drivers/frequency/admfm2000/admfm2000.c
drivers/frequency/admfm2000/admfm2000.h
drivers/frequency/admfm2000/iio_admfm2000.c
drivers/frequency/admfm2000/iio_admfm2000.h

The ADMFM2000 is a dual-channel microwave downconverter, with input RF and local oscillator (LO) frequency ranges covering 5 GHz to 32 GHz, with an output intermediate frequency (IF) frequency range from 0.5 GHz to 8 GHz. Added driver and iio_support.

drivers: frequency: add support for ADMFM2000

---

projects/ad7616-sdz/src/parameters.h

This fix compilation with recent HDL changes

projects: ad7616-sdz: Fix defines for HDL

---

drivers/platform/freeRTOS/freertos_alloc.c

Add freeRTOS memory functions for no-OS implementation.
Added memory allocation functions for use in freeRTOS platform.

drivers:platform:freeRTOS:Added mem functions

---

doc/sphinx/source/drivers/ltc7841.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/ltc7841.rst
doc/sphinx/source/projects_doc.rst
drivers/power/ltc7841/README.rst
drivers/power/ltc7841/iio_ltc7841.c
drivers/power/ltc7841/iio_ltc7841.h
drivers/power/ltc7841/ltc7841.c
drivers/power/ltc7841/ltc7841.h
projects/ltc7841/Makefile
projects/ltc7841/README.rst
projects/ltc7841/builds.json
projects/ltc7841/src.mk
projects/ltc7841/src/common/common_data.c
projects/ltc7841/src/common/common_data.h
projects/ltc7841/src/examples/basic/basic_example.c
projects/ltc7841/src/examples/iio_example/iio_example.c
projects/ltc7841/src/examples/iio_example/iio_example.mk
projects/ltc7841/src/platform/maxim/main.c
projects/ltc7841/src/platform/maxim/parameters.c
projects/ltc7841/src/platform/maxim/parameters.h
projects/ltc7841/src/platform/maxim/platform_src.mk

add support for LTC7841

---

doc/sphinx/source/drivers/ades1754.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/ades1754.rst
doc/sphinx/source/projects_doc.rst
drivers/power/ades1754/README.rst
drivers/power/ades1754/ades1754.c
drivers/power/ades1754/ades1754.h
projects/ades1754/Makefile
projects/ades1754/README.rst
projects/ades1754/builds.json
projects/ades1754/src.mk
projects/ades1754/src/common/common_data.c
projects/ades1754/src/common/common_data.h
projects/ades1754/src/examples/basic/basic_example.c
projects/ades1754/src/examples/spi_uart_bridge/example.mk
projects/ades1754/src/examples/spi_uart_bridge/spi_uart_bridge_example.c
projects/ades1754/src/platform/maxim/main.c
projects/ades1754/src/platform/maxim/parameters.c
projects/ades1754/src/platform/maxim/parameters.h
projects/ades1754/src/platform/maxim/platform_src.mk

The ADES1754/ADES1755/ADES1756 are flexible
data-acquisition systems for the management of high-
voltage and low-voltage battery modules. The systems
can measure 14 cell voltages and a combination of six
temperatures or system voltage measurements with fully
redundant measurement engines in 162μs, or perform
all inputs solely with the ADC measurement engine in
99μs. Fourteen internal balancing switches rated
for >300mA for cell-balancing current support extensive
built-in diagnostics. Up to 32 devices can be daisy-
chained to manage 448 cells and monitor 192
temperatures.
This PR includes examples that use other device drivers, therefore it needs to be merged after #2428

power: ades1754 : Add support for ADES1754

---

util/no_os_mutex.c
util/no_os_semaphore.c

Adding the inline keyword to a weak function results in the symbol to not actually be defined as weak. Thus, the compilation will fail for platforms which define their own version of those functions (FreeRTOS for example).
__attribute__((weak)) inline:
arm-none-eabi-nm build/objs/iio_demo_freeRTOS/build/app/noos/util/no_os_semaphore.o 00000000 T no_os_semaphore_give
00000000 T no_os_semaphore_init
00000000 T no_os_semaphore_remove
00000000 T no_os_semaphore_take
__attribute__((weak)):
arm-none-eabi-nm build/objs/iio_demo_freeRTOS/build/app/noos/util/no_os_mutex.o 00000000 W no_os_mutex_init
00000000 W no_os_mutex_lock
00000000 W no_os_mutex_remove
00000000 W no_os_mutex_unlock
00000000 n wm4.0.2fb1d36208757ad46d380e25c322250d
Please replace this with a detailed description and motivation …

util: Remove the inline attribute

---

build_projects.yml

The ceedling framework used inside the Unit Tests job has released a new version (>1.0.0) which isn't backwards compatible. This is a hot fix that sets the version to 0.31.1 (latest working version). 
This issue was also reported to the Ceedling repo
(ThrowTheSwitch/Ceedling#939) where porting to the latest versions is explained.
I don't have the expertise to *correctly* update Ceedling to latest, but I recommend that it should be done in the future. This fix was done to make the CIs for unit tests pass.

build_projects.yml: Fix Unit Tests job

---

doc/sphinx/source/drivers/max17851.rst
doc/sphinx/source/drivers_doc.rst
drivers/power/max17851/README.rst
drivers/power/max17851/max17851.c
drivers/power/max17851/max17851.h

The MAX17851 SPI to UART safety monitoring bridge
translates communication from SPI format to universal
asynchronous receiver transmitter (UART) format special-
ly designed to interface with Maxim's Battery Management
Data Acquisition System. The safety monitoring bridge en-
ables robust communication with baud rates extending up
to 4Mbps in both single and dual daisy-chain system archi-
tectures. High throughput, dual UART systems can read
96 cells of battery voltages within 1173us.
The UART is ISO26262 compliant for automotive safety
integrity level (ASIL) D systems providing detection of
message corruption, delay, loss, and insertion through the
embedded UART communication lock step safety mea-
sure state machine (LSSM). The MAX17851 self verifies
all communication within the message …

power: max17851 : Add MAX17851 support

---

drivers/api/no_os_irq.c
drivers/platform/stm32/stm32_irq.c
include/no_os_irq.h

Added a function to get the priority of an interrupt into STM32 platform api. This will provide better visibility of the already set interrupt priority and will provide the ability to dynamically adjust the priorities, if needed.

drivers:irq: support to get the interrupt priority 

---

doc/sphinx/source/drivers/lt3074.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/lt3074.rst
doc/sphinx/source/projects_doc.rst
drivers/power/lt3074/README.rst
drivers/power/lt3074/iio_lt3074.c
drivers/power/lt3074/iio_lt3074.h
drivers/power/lt3074/lt3074.c
drivers/power/lt3074/lt3074.h
projects/lt3074/Makefile
projects/lt3074/README.rst
projects/lt3074/builds.json
projects/lt3074/src.mk
projects/lt3074/src/common/common_data.c
projects/lt3074/src/common/common_data.h
projects/lt3074/src/examples/basic/basic_example.c
projects/lt3074/src/examples/iio_example/example.mk
projects/lt3074/src/examples/iio_example/iio_example.c
projects/lt3074/src/platform/maxim/main.c
projects/lt3074/src/platform/maxim/parameters.c
projects/lt3074/src/platform/maxim/parameters.h
projects/lt3074/src/platform/maxim/platform_src.mk

The LT3074 is a low voltage, ultralow noise, and ultrafast transient
response linear regulator with a PMBus serial interface. The device
supplies up to 3A with a typical dropout voltage of 45mV.
This pull request adds the no-OS and IIO driver, as well as examples
and documentations, to quickly evaluate the LT3074.

drivers: power: lt3074: add driver for LT3074

---

drivers/power/adp1050/README.rst
drivers/power/adp1050/adp1050.c
drivers/power/adp1050/adp1050.h
drivers/power/adp1050/iio_adp1050.c
projects/adp1050/README.rst

The ADP1051 is an advanced digital controller with a PMBusTM interface targeting high density, high efficiency dc-to-dc power
conversion. This controller implements voltage mode control with high speed, input line feedforward for enhanced transient and improved noise performance. Some of the added support to the adp1050 driver to support adp1051 include extra pwm output, light load mode, and deep light load mode.

drivers: power: adp1050: add support for adp1051

---

doc/sphinx/source/drivers/adp1055.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/adp1055.rst
doc/sphinx/source/projects_doc.rst
drivers/power/adp1055/README.rst
drivers/power/adp1055/adp1055.c
drivers/power/adp1055/adp1055.h
drivers/power/adp1055/iio_adp1055.c
drivers/power/adp1055/iio_adp1055.h
projects/adp1055/Makefile
projects/adp1055/README.rst
projects/adp1055/builds.json
projects/adp1055/src.mk
projects/adp1055/src/common/common_data.c
projects/adp1055/src/common/common_data.h
projects/adp1055/src/examples/basic/basic_example.c
projects/adp1055/src/examples/iio_example/example.mk
projects/adp1055/src/examples/iio_example/iio_example.c
projects/adp1055/src/platform/maxim/main.c
projects/adp1055/src/platform/maxim/parameters.c
projects/adp1055/src/platform/maxim/parameters.h
projects/adp1055/src/platform/maxim/platform_src.mk

The ADP1055 is a flexible, feature-rich digital secondary side controller that targets ac-to-dc and isolated dc-to-dc secondary side applications. The ADP1055 is optimized for minimal component count, maximum flexibility, and minimum design time. Features include differential remote voltage sense, primary and secondary side current sense, pulse-width modulation (PWM) generation, frequency synchronization, redundant OVP, and current sharing.

drivers: power: adp1055: add support for adp1055

---

projects/eval-pqmon/src/platform/maxim/platform_src.mk

The header files "maxim_delay.h" and "maxim_init.h" do not exist. In some cases, build errors are generated because of this. This commit removes them from the list of included headers.

projects: eval-pqmon: remove inexistent headers

---

drivers/platform/stm32/stm32_dma.c
drivers/platform/stm32/stm32_dma.h
drivers/platform/stm32/stm32_gpdma.c

Added support for circular DMA using nodes and linked lists, enabling continuous data transfer without manual intervention, which enhances efficiency for repetitive tasks. Additionally, implemented triggering support for DMA, allowing precise control over data transfer initiation based on specific events or conditions

drivers:platform:stm32:dma Circular DMA and Trigger Support

---

drivers/filter/admv8818/admv8818.c

When a weak pull-up is present on the SDO line, spi_update_bits fails to write both the SOFTRESET and SDOACTIVE bits because it incorrectly reads them as already set.
Since the soft reset disables the SDO line, performing a read-modify-write operation on ADI_SPI_CONFIG_A to enable the SDO line doesn't make sense. This change directly writes to the register instead of using spi_update_bits.
Fixes: 3755205246724f658a89eae985266bcc0185ae48 ("drivers:filter: add admv8818 support")

filter: admv8818: force initialization of SDO

---

doc/sphinx/source/conf.py

The documentation we provide contains also examples of commands which take input parameters with the double dash prefix (--). Due to the smartquotes being enabled by default in the sphinx configuration, the double dash is converted to typographical en-dash (–).
Example:
Disable smartquotes such that the commands provided into the documentation can be used properly without any confusion.

doc: sphinx: conf.py: disable smartquotes

---

projects/ad74416h/builds.json

Fix build name for the digital output.
Fixes: 10602f926674 ("projects: ad74416h: add digital output example")

projects: ad74416h: fix builds.json naming

---

projects/eval-pqmon/src/platform/maxim/platform_src.mk

Add fallback for new Maxim library path.
The path for libarm_cortexM4l_math.a is now MaximSDK/Libraries/CMSIS/5.9.0/DSP/1.16.2/Lib. Add fallback for this path. Keep old path for compatibility (?).

projects: eval-pqmon: add fallback path

---

drivers/platform/stm32/stm32_dma.h

The GPDMA code required trigger configuration and private data descriptor to be defined in the stm32_dma_channel structure to work. This definition was missing and has been added here.

drivers:platform:stm32:stm32_dma.h: Fixed the trigger and private data

---

drivers/dac/ad9152/ad9152.c

Fixing AD9152.c register definitions/removing undefined registers.
Fixed astyle in https://github.com/analogdevicesinc/no-OS/pull/2450

dac: ad9152: ad9152.c register definition updates

---

drivers/rf-transceiver/ad9361/ad9361.c

Return error in case TX_QUAD_CAL or RFDC_CAL fail.

rf-transceiver: ad9361: ad9361.c: Return calib err

---

drivers/platform/maxim/max32650/maxim_spi.c

Fix spi chip select configuration for MAX32650.
For device_id==3 use spi3 configuration.

drivers: platform: maxim: max32650: Fix spi config

---

projects/adrv9009/Makefile
projects/adrv9009/src/app/app_talise.c

Do not enable lane clock for ORx and Tx paths in case of an ADRV9008-1 device.

adrv9009: app_talise.c: Do not enable ORx, Tx

---

drivers/adc/ad9656/ad9656.c
drivers/adc/ad9656/ad9656.h
projects/ad9656_fmc/src/app/ad9656_fmc.c

Fixed an issue which would throw a message that said that the PN9 and PN23 check sequences don't match. The issue was present because the chip has two registers which need to be written with the desired PN sequence in order to test the PN mechanism. Only one register was written, thus prompting the mismatch error. The changes affect the driver & the project.
HDL PR regarding AD9656: https://github.com/analogdevicesinc/hdl/pull/1622

drivers: adc: ad9656: Fixed PN mismatch error

---

projects/ad9656_fmc/src/app/ad9656_fmc.c

Add a 10ms delay so that messages have time to be displayed before starting the iio server.

ad9656_fmc: src: app: ad9656_fmc.c: Add delay

---

projects/aducm3029_flash_demo/src/main.c

Fix a runtime bug where the ops were not initialized.

projects: aducm3029_flash_demo: fix missing irq ops

---

drivers/adc/ad7124/ad7124.c
drivers/adc/ad7124/ad7124.h

I noticed that all functions and structs were implemented to be able to set all the fields in the "CHANNEL_x" and "CONFIG_x" registers, apart from the "PGA" and "Burnout" fields of the "CONFIG_x" registers. The aim of this PR is to add functions which allow the user to set those bit fields, and to initialise them in the `ad7124_setup()` function by adding to the `ad7124_init_param` struct.
I have tested these changes on a custom board with a AD7124_8 chip.

Add burnout current and PGA gain functionality to ad7124 driver

---

projects/fmcdaq2/src/app/fmcdaq2.c

Add text indicating location and structure of ADC data in memory.
Add a 100ms delay so that the device has enough time to start sending data.

projects: fmcdaq2.c: Add debug text

---

drivers/api/no_os_i3c.c
drivers/platform/stm32/stm32_i3c.c
drivers/platform/stm32/stm32_i3c.h
include/no_os_i3c.h

I added DMA transfer and abort support for the I3C interface. This allows efficient data transfers and the ability to stop transfers when needed. The DMA transaction of multiple transfers occur sequentially and I3C data complete callback waits for the DMA callback to be completed and the next transfer to be configured before proceeding to configure the next write to control register.

I3C DMA Transfer and Abort Support

---

drivers/digital-io/max22200/max22200.h

Fix register address values.
Closes #2532.
Fixes : a1e0ae616758 ("drivers: digital-io: max22200 : Add driver support for MAX22200")
Signed-off-by: Radu Sabau <radu.sabau@analog.com>

drivers: digital-io: max22200 : Fix register address

---

drivers/adc/ad7606/ad7606.c
drivers/adc/ad7606/ad7606.h

Add compile time checks for AXI function calls
Move the device structure to ad7606.h
Remove static keyword in SPI reg read/write/write mask APIs as it is being used outside the drivers

drivers:adc:ad7606: Fix build failures for platforms other than xilinx

---

build_projects.yml
tests/drivers/imu/project.yml

Do not force to an older ceedling version, adapt the current test
infrastructure instead.
The new update on the ruby version does not comply with older ceedling
versions, causing the current unit-tests to fail.
Fixes: https://github.com/analogdevicesinc/no-OS/commit/b8e1efd1a3e1836735b9d6c4511d0ebd1843361d ("build_projects.yml: Fix Unit Tests job")
Update the tests configuration file to match the latest ceedling syntax.
See: https://github.com/ThrowTheSwitch/Ceedling/blob/master/docs/BreakingChanges.md

fix unit-tests build job

---

drivers/api/no_os_i3c.c

Harmonize the behavior with the i2c abstraction of removing the bus if no device is attached anymore.
Since the specification foresees hot-join events,
the original thought was that it made sense to keep bus allocated during the execution life-time, even if no device is attached. Revisiting it, for a hot-join implementation would make more sense to have a device attached with a "may_join" flag, and have some sort of init defer mechanism on the part drivers.
Change error code from -EFAULT to -EBUSY as in "the bus is busy because there are devices attached please remove them first and try again later"
Slightly related to #2460 and discussed with @SwaroopPKADI

i3c: Remove bus in case no device is attached on the bus

---

ci/documentation.sh

Due to a misspelling, errors_found didn't exist if no error was caught. Still, double quote to ensure bash never expands into an invalid `if [ -eq 1 ]`, instead, ensure `if [ "" -eq "1" ]`
Fixes cluttering the log with 
```
./ci/documentation.sh: line 82: [: -eq: unary operator expected
```

ci: documentation.sh: Fix unary operator

---

drivers/platform/ftd2xx/mpsse/ftd2xx_gpio.c

Fix same variable name for different variables in GPIO driver.
Fix syntax error in gpio function.

drivers: platform: ftd2xx : Fix GPIO driver

---

ci/documentation.sh
ci/run_build.sh
doc/doxygen/Doxyfile.in

Use harmonic theme.
Use SVGs instead of PNGs.
Remove hard-coded `/home/vsts/work/1` from doxyfile.
Tested locally using the CI steps under a Ubuntu 24.04 container, doxygen 1.13.2 from source.
I am not the code owner of the theme, and I mirrored the tar.gz on doctools/release/latest because I needed to make it accessible somehow.
build size:
* base commit: 869MB
* head commit: 597MB

doc: doxygen: Use harmonic theme, remove hardcoded variable, use SVG

---

projects/adrv9001/src/app/headless.c

Update of the adrv9001 project solving the problem of buffer overlapping.

Adrv9001 buffers update

---

drivers/platform/stm32/stm32_gpdma.c

Re-configuration of the DMA and the List should only configure the list with the new nodes but should not de-initialize the DMA.

drivers:platform:stm32:stm32:stm32_gpdma.c: Removed List De-Init

---

drivers/adc/ad738x/ad738x.c
drivers/adc/ad738x/ad738x.h
projects/ad738x_fmcz/src/common/common_data.c
projects/ad738x_fmcz/src/platform/xilinx/parameters.c
projects/ad738x_fmcz/src/platform/xilinx/parameters.h

Add compile time checks for AXI function calls and header includes

drivers:adc:ad738x: Fix build failures for platforms other than xilinx

---

drivers/dac/ad917x/ad9172.c

Set the chip name displayed when initializing to AD917x.

drivers: dac: ad917x: ad9172.c: Update dev name

---

drivers/accel/adxl367/adxl367.c
drivers/accel/adxl367/adxl367.h

adxl366 is backwards compatible with adxl367. It has a few extra features which will be added later, but simply list it as compatible in the existing driver for now.
adxl366 is backwards compatible with adxl367. It has a few extra features which will be added later, but simply list it as compatible in the existing driver for now.

adxl367: add adxl366 as compatible to the driver

---

drivers/adc/ad9083/ad9083.c
drivers/adc/ad9083/ad9083.h
projects/ad9083/src/app.c
projects/ad9083/src/app_ad9083.c
projects/ad9083/src/app_ad9083.h
projects/ad9083/src/app_jesd.c
projects/ad9083/src/app_jesd.h

Use no_os_clk_desc instead of no_os_clk for the jesd receive clock.

Ad9083 work

---

drivers/adc/ad717x/ad7177_2_regs.h

1)Modified the name of ad71772 regs
2)Modified the configuaration to the default register configuaration 3)changed the int32_t to uint32_t to support the adc resolution to the 32 bits

drivers:ad717x:Modified the ad71772 regs

---

.gitmodules
tools/scripts/libraries.mk
tools/scripts/lvgl.mk

libraries: add lvgl

---

tools/scripts/generic.mk

Remove if condition in generic.mk that checks for platform being FTD2XX.
Fix : 08cf3ff ("tools: scripts: ftd2xx.mk : Add FTD2XX as library instead of platform")

tools: scripts: generic.mk : Fix ftd2xx platform check

---

drivers/adc/ad7779/ad7779.c

Cached memory update fixed for dec_rate_dec member

drivers:adc:ad7779: Bug fixes to ad7779_set_dec_rate()

---

projects/eval-pqmon/src.mk

The eval-pqmon project currently fails to compile because the ADIN1110 driver depends on the oa_tc6 files, which are not included in the build. Fix this by adding them to the source list.

projects: eval-pqmon: Include the OA TC6 files

---

drivers/frequency/adf4030/README.rst
drivers/frequency/adf4368/README.rst
drivers/frequency/adf4382/README.rst
drivers/frequency/adf5611/README.rst

Broken Links in the Drivers Readme files fixed.
Updated product page links in the ReadMe file.
Issue link : https://github.com/analogdevicesinc/no-OS/issues/2609

Fix Readme Links: driver: frequency: adf4030, adf4368, adf4382, adf5611

---

drivers/potentiometer/ad5246/ad5246.c
drivers/potentiometer/ad5246/ad5246.h

Device driver for the AD5246 potentiometer with 128-position adjustment. This device works with I2C as interface.
- [x ] New feature (change that adds new functionality)
- [x ] I have build all projects affected by the changes in this PR
- [ x] I have signed off all commits from this PR

drivers: Potentiometer: ad5246

---

projects/adrv902x/README.rst

I noticed that the headings levels for this page were one left off, causing the subtitles to appear in the left sidebar.
While at it, also fix levels and lists, use git and dokuwiki roles, and minor misspellings.
To better support the no-OS doc, for [doctools v0.4.10](https://analogdevicesinc.github.io/doctools/v0.4.10/cli.html#serve), [adoc serve](https://analogdevicesinc.github.io/doctools/cli.html#serve):
* now tracks included files, so edits to projects/adrv902x/README.rst trigger and reload the live server webpage.
* touching a page will redirect the visible live server to the current file (so you don't have to open once in the browser and once in the editor, just open in the editor and save the file) (only actual pages, doesn't work for includes (e.g. works for drivers/ad405x.rst …

projects: adrv902x: README.rst: Formatting

---

drivers/platform/linux/linux_i2c.c
drivers/platform/linux/linux_i2c.h
projects/adt7420-pmdz/src/examples/dummy/dummy_example.c
projects/adt7420-pmdz/src/platform/linux/main.c
projects/adt7420-pmdz/src/platform/linux/parameters.c
projects/adt7420-pmdz/src/platform/linux/parameters.h
projects/adt7420-pmdz/src/platform/linux/platform_src.mk

Relevant Issue: [2518](https://github.com/analogdevicesinc/no-OS/issues/2518)
- Added ADT7420 Linux platform support
- Re-implementation of Linux I2C read and write APIs for `stop_bit` handling
Tested with the adt7420-pmdz dummy example and an ADT7420 + RPI CM5 (RPI OS) setup.

ADT7420 Linux Support and Linux I2C API Fix

---

include/no_os_util.h
util/no_os_util.c

Add the following APIs in no_os_utils:
- `no_os_put_unaligned_be64`
- `no_os_get_unaligned_be64`
- `no_os_put_unaligned_le64`
- `no_os_get_unaligned_le64`

Add 64-bit support for put/get unaligned APIs

---

drivers/temperature/max31889/max31889.c
drivers/temperature/max31889/max31889.h

Adding support for max31889 I2C temp sensor

drivers: temperature: add max31889

---

drivers/platform/ftd2xx/mpsse/ftd2xx_gpio.c
drivers/platform/ftd2xx/mpsse/ftd2xx_gpio.h
tools/scripts/ftd2xx.mk

Instead of making FTD2XX GPIO dependent on either I2C/SPI, it should be independent of those by using the
base D2XX driver device access functions.
Therefore make a PR that adds support for using the mentioned functions, and use the inside the ftd2xx_gpio drivers.

drivers: platform: ftd2xx : Fix FTD2XX GPIO drivers

---

drivers/net/oa_tc6/oa_tc6.c
drivers/net/oa_tc6/oa_tc6.h

Implement the protected mode for the oa_tc6 driver. In this mode, control transactions include the register's value in 1's complement in order to verify the data integrity.

drivers: net: oa_tc6: Support protected mode

---

doc/sphinx/source/drivers/ad7490.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/eval-ad7490sdz.rst
doc/sphinx/source/projects_doc.rst
drivers/adc/ad7490/README.rst
drivers/adc/ad7490/ad7490.c
drivers/adc/ad7490/ad7490.h
drivers/adc/ad7490/iio_ad7490.c
drivers/adc/ad7490/iio_ad7490.h
projects/eval-ad7490sdz/Makefile
projects/eval-ad7490sdz/README.rst
projects/eval-ad7490sdz/builds.json
projects/eval-ad7490sdz/src.mk
projects/eval-ad7490sdz/src/common/common_data.c
projects/eval-ad7490sdz/src/common/common_data.h
projects/eval-ad7490sdz/src/examples/basic/basic_example.c
projects/eval-ad7490sdz/src/examples/iio_example/iio_example.c
projects/eval-ad7490sdz/src/examples/iio_example/iio_example.mk
projects/eval-ad7490sdz/src/platform/maxim/main.c
projects/eval-ad7490sdz/src/platform/maxim/parameters.c
projects/eval-ad7490sdz/src/platform/maxim/parameters.h
projects/eval-ad7490sdz/src/platform/maxim/platform_src.mk

The AD7490 is a 12-bit high speed, low power, 16-channel, successive
approximation ADC.
The part operates from a single 2.7 V to 5.25 V power supply and
features throughput rates up to 1 MSPS.
The part contains a low noise, wide bandwidth track-and-hold
amplifier that can handle input frequencies in excess of 1 MHz.
This PR includes :
- no-OS driver for AD7490
- no-OS IIO driver for AD7490
- no-OS driver documentation
- no-OS example project (basic and IIO examples) for EVAL-AD7490SDZ (AD7490 evaluation board)
- no-OS example project documentation

drivers: adc: ad7490 : Add support for AD7490

---

drivers/dac/ltc2672/ltc2672.c
drivers/dac/ltc2672/ltc2672.h
projects/dc2903a/src.mk

1. Add support for LTC2662_12 and LTC2662_16 devices
2. Add support for functions ltc2672_remove_gpio(), ltc2672_cfg_reset(), ltc2672_reset(), ltc2672_write_input_register_channel(), ltc2672_write_input_register_all_channels(), ltc2672_update_channel(), ltc2672_update_all_channels(), ltc2672_hw_ldac_update()
3. Generate 32 bits command instead of 24 bits

drivers:dac:ltc2672: Add support for LTC2662 devices

---

projects/adrv902x/src/examples/dma_example/dma_example.c

adrv902x: dma_example: Set clkgen rates early
Move clkgen setup earlier in the project flow so that
phy->tx_dac->clock_hz is set correctly in phy->tx_dac->clock_hz.
Add delay before clkgen setup so that clkgen PLL lock.

Madura set clkgen rates early in DMA_EXAMPLE

---

drivers/platform/maxim/max32660/maxim_uart.c
drivers/platform/maxim/max32662/maxim_uart.c
drivers/platform/maxim/max32665/maxim_uart.c

During uart initialization check for memory allocaiton of maxim_uart

drivers: platform: maxim

---

drivers/eeprom/m24512/m24512.c
drivers/eeprom/m24512/m24512.h

The M24512 is a 512-Kbit I2C-compatible EEPROM (electrically erasable programmable memory) organized as 64 K × 8 bits.

drivers: eeprom: add m24512
