analogdevicesinc/no-OS

- ad9361/sw/ad9361_api.c
Must subtract 75 from init_params->lvds_bias_mV before dividing by 75 in order to agree with the register definition which states: LVDS driver amplitude control. |VOD| = 75 mV to 450 mV; 75 mV/LSB.
> Fix lvds_bias_ctrl

- device_drivers/ADF4156/ADF4156.c
- device_drivers/ADF4157/ADF4157.c
- drivers/adf4350/adf4350.c
- fmcomms1/ADF4351/ADF4351.c
This improves the efficiency of the gcd() function which returns the
greatest common divisor of two numbers.
Signed-off-by: Dan Nechita <Dan.Nechita@analog.com>
> Use the Euclidean algorithm in gcd() function across all drivers

- adum7701_fmc/adc_core.c
- adum7701_fmc/adc_core.h
- adum7701_fmc/adum7701.c
- adum7701_fmc/adum7701.h
- adum7701_fmc/adum7701_fmc.c
- adum7701_fmc/clkgen_core.c
- adum7701_fmc/clkgen_core.h
- adum7701_fmc/platform_drivers.c
- adum7701_fmc/platform_drivers.h
This patch adds support for ADuM7701/ADuM7702 and AD7405 16-bit sigma-delta
modulators.
Datasheet:
http://www.analog.com/media/en/technical-documentation/data-sheets/AD7405.pdf
Signed-off-by: Stefan Popa <stefan.popa@analog.com>
> iio: adc: Add support for ADuM7701 sigma-delta modulator

- drivers/adgs1408/adgs1408.c
- drivers/adgs1408/adgs1408.h
The ADGS1408 contains four independent single pole/single-throw switches,
with a SPI interface for communication.
This driver also supports the adgs1409 and daisy chain mode.
It is derived from adgs5412, with Round Robin functionality added for
enabling individual switches just with a toggle on the CNV pin and no other
serial communication.
It also follows the linux style formatting.
> ADGS1408: Initial commit

- common_drivers/xcvr_core/xcvr_modules/xilinx_qpll.c
Fix typo, 44 should be 40 here.
This fixes using a feedback divider of 40, which e.g. happens when the
reference clock is 1/40 of the lane rate.
Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
> xilinx_qpll: Fix using a feedback divider of 40

- common_drivers/jesd_core/jesd_core.c
These symbols are not meant to be used outside this compilation unit. Make
them static.
Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
> jesd_core: Make unexported symbols static

- drivers/ad9144/ad9144.c
- drivers/ad9144/ad9144.h
- fmcdaq2/fmcdaq2.c
Updates for the AD9144 driver that bring it closer in sync with the Linux version.
* Add 4-wire support
* Add support for all link modes
* Update recommended write sequences according to latest datasheet
Tested on the FMCDAQ2.
> Updates for the AD9144 driver

- ad6676-ebz/ad6676_ebz.c
SPI type must correspond to the current carrier. Add initialization for
MICROBLAZE, ZINQ_PSU and NIOS_II.
> ad6676-ebz: add SPI type initialization for multiple carriers

- ad9371/sw/platform_xilinx/platform_drivers.h
Reported via EZ:
https://ez.analog.com/thread/109040-ad9375-platformdriversh-modification-using-microblaze
The GPIOs for Microblaze are part of 2 x 32 bit registers, so there cannot
be a GPIO number higher than 63.
The GPIO_OFFSET is a left-over from the implementation of the driver for
the Zynq platform.
> ad9371: platform_xilinx: fix GPIO_OFFSET for Microblaze

- ad9371/sw/platform_xilinx/platform_drivers.h
Reported via EZ:
https://ez.analog.com/thread/109040-ad9375-platformdriversh-modification-using-microblaze
The GPIOs for Microblaze are part of 2 x 32 bit registers, so there cannot
be a GPIO number higher than 63.
The GPIO_OFFSET is a left-over from the implementation of the driver for
the Zynq platform.
> [2018_R1] ad9371: platform_xilinx: fix GPIO_OFFSET for Microblaze

- drivers/ad9144/ad9144.c
- drivers/ad9144/ad9144.h
- fmcdaq2/fmcdaq2.c
Add support for the internal PLL in the AD9144. It can be used to synthesize a DAC clock from a slower external reference clock.
Also add an example to the DAQ2 project that shows how to use the PLL mode.
> AD9144 PLL support

- drivers/ad9144/ad9144.c
Currently when calling the ad9144_setup() function there is a certain
chance that the AD9144 will not be correctly initialized. The symptoms can
range from the AD9144 not reporting any errors, but also not generating any
signal at the DAC output, to recording a lot of JESD204 character errors
and constantly restarting the link.
This appears to be caused by the link being enabled while the link is being
configured. Make sure that the link is kept disabled during link
configuration.
After this patch has been applied erratic behavior after converter
initialization can no longer be observed and the AD9144 properly
initializes every time.
Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
> ad9144: Keep link disabled during configuration

- drivers/ad5592r/ad5592r-base.c
- drivers/ad5592r/ad5592r-base.h
- drivers/ad5592r/ad5592r.c
- drivers/ad5592r/ad5592r.h
- drivers/ad5592r/ad5593r.c
- drivers/ad5592r/ad5593r.h
The ad5592r/ad5593r has 8 I/Ox pins that can be independently configured as
digital-to-analog converter outputs (DAC), analog-to-digital converter
inputs (ADC) or digital inputs.
> ad5592r: Initial driver for ad5592r/ad5593r

- drivers/ad9152/ad9152.c
- fmcdaq2/fmcdaq2.c
- fmcdaq3/config.h
- fmcdaq3/fmcdaq3.c
Currently on both DAQ2 and DAQ3 the DAC JESD204 startup fails every now and then (maybe 1 in 10 to 20 times).
This series fixes the remaining issues to ensure that the link starts up reliably. No issues have been observed while continuously restarting the application every 10 seconds for a few hours.
(At least in the default configuration, more things to come to fix dynamic reconfiguration.)
> Fix DAQ2/DAQ3 DAC JESD204 link startup

- drivers/ad717x/ad4111_regs.h
- drivers/ad717x/ad717x.c
- drivers/ad717x/ad717x.h
Make small fixes to the AD717X driver and add AD4111 support to the AD717X driver.
The AD4111 is a low power, low noise, 24-bit, sigma delta (Σ-Δ) analog-to-digital converter (ADC) that integrates an analog front end (AFE) for fully differential or single-ended rail-to-rail, buffered bipolar, ±10 V voltage inputs, and 0 mA to 20 mA current inputs.
The AD4111 is very similar to the AD717X family so support for it is added to that family driver instead of creating new driver with duplicate code.
> Ad4111 driver dev

- drivers/ad5755/ad5755.c
Values lower than negative full scale caused the output to swing to positive full scale instead of clamping to negative full scale.
The return value was not calculated using the value written to the data register.
> AD5755 extreme case fix.

- ci/scripts/astyle.sh
- drivers/ad7124/ad7124.h
Set of minor fixes in the header file of the AD7124 driver and fix astyle_config file path for travis.
> AD7124 driver - minor fixes

- drivers/ad5686/ad5686.c
- drivers/ad5686/ad5686.h
The driver now supports AD5683R/AD5682R/AD5681R/AD5683/AD5693R/AD5692R/AD5691R/AD5693 DACs.
For these devices the shift register is 24 bits wide, first bits being the command bits followed by the 16-bit/14-bit/12-bit data input code. Therefore, the last 4 bits don't care in this situation and the
'register_map' attribute is added to these devices. The attribute is checked in the functions that are device dependent in order to adjust the differences of the input code.
> ad5686: Extend functionality for AD5683

- drivers/ad5592r/ad5592r-base.c
- drivers/ad5592r/ad5592r-base.h
Variable in which to read the register value should be passed by reference.
> drivers: ad5592r: Fix read value reference

- ad-fmcjesdadc1-ebz/ad_fmcjesdadc1_ebz.c
- ad6676-ebz/ad6676_ebz.c
- common_drivers/platform_drivers/platform_drivers.c
- common_drivers/xcvr_core/xcvr_core.c
- common_drivers/xcvr_core/xcvr_core.h
- common_drivers/xcvr_core/xcvr_modules/xilinx_xcvr_channel.c
- fmcadc2/fmcadc2.c
- fmcadc4/fmcadc4.c
- fmcadc5/fmcadc5.c
- fmcdaq2/fmcdaq2.c
- fmcdaq3/fmcdaq3.c
After the xcvr_core updates some structure members changed names making projects using xcvr_core incorrect. Adjust new names, apply AStyle on the sources and tow minor bugs: one introduced with the xcvr_core update and one missing semicolon.
> Ultrascale xcvr projects update

- ci/scripts/astyle.sh
Remove astyle path from PATH env var and access it directly from folder.
This solves the issue of finding the "astyle" command which fails the
Travis build.
> general: fix astyle path

- ad400x-fmcz/ad400x.c
- ad400x-fmcz/ad400x.h
- ad400x-fmcz/ad400x_fmcz.c
- ad400x-fmcz/spi_engine.c
- ad400x-fmcz/spi_engine.h
The ad400x is an is a low noise, low power, high speed analog-to-digital
converter. The driver enables the use of the hdl design along side the SPI
engine.
> ad400x: Initial version

- drivers/ad7606/ad7606.c
- drivers/ad7606/ad7606.h
The AD7606/AD7606-6/AD7606-4 is a 16-bit 8/6/4 channel Analog to
Digital Converter (ADC). It can accommodate ± 10V and ±5V true bipolar
inputs. The AD7605-4 is part of the same family, the main difference is
that it does not support oversampling.
This patch adds basic serial support for these devices.
Datasheet:
Link: https://www.analog.com/media/en/technical-documentation/data-sheets/ad7606_7606-6_7606-4.pdf
Link: https://www.analog.com/media/en/technical-documentation/data-sheets/ad7605-4.pdf
Signed-off-by: Stefan Popa <stefan.popa@analog.com>
> ad7606: Add basic support for AD7606 family of devices

- ci/travis/astyle.sh
Similar to .gitignore file, the user can now specifiy files that astyle
ignores through .astyleignore file found in the root folder
> add astyle ignore

- ad7768-evb/ad7768_evb.mk
The issue was discovered by:
https://github.com/analogdevicesinc/no-OS/issues/132
> ad7768-evb: ad7768_evb.mk: Typo fix

- drivers/ad717x/ad717x.h
The AD4112 is almost identical to the AD4111, the only difference being
that the AD4112 does not have Open Wire Detection capabilities.
Adding support for this part amounts to mentioning it in the header
comments and separating the Open Wire Detection bit for the two devices.
More information about AD4112:
https://www.analog.com/media/en/technical-documentation/data-sheets/AD4112.pdf
For comparison purposes the datasheet for AD4111:
https://www.analog.com/media/en/technical-documentation/data-sheets/AD4111.pdf
> drivers:ad717x: add support for AD4112

- drivers/ad7606/ad7606.c
- drivers/ad7606/ad7606.h
The AD7606B is a 16-bit ADC that supports simultaneous sampling of 8
channels. It is pin compatible to AD7606, but adds extra modes by
writing to the register map.
The AD7606B can be configured to work in software mode by setting all
oversampling pins to high. The oversampling ratio is configured from the
OS_MODE register (address 0x08) with the addition of OS=128 and OS=256
that were not available in hardware mode.
Moreover, in software mode, the range gpio has no longer its function.
Instead, the scale can be configured individually for each channel from
the RANGE_CH registers (address 0x03 to 0x06). Besides the already
supported ±10 V and ±5 V ranges, software mode can also accommodate the
±2.5 V range.
Signed-off-by: Stefan Popa <stefan.popa@analog.com>
> ad7606: Add support for AD7606B ADC

- ad9361/sw/ad9361.c
Supersedes PR #32 
The comment of the commit is a bit more descriptive.
--------------------------------------------------------
When an invalid value/ratio would occur for the DAC frequency, the
displayed value on the error path would be erroneous.
This patch updates the printed-out values to the correct ones.
> ad9361: fix DAC debug ouput

- .cppcheckignore
- ci/travis/cppcheck.sh
The user can now define in the root directory of the repo a file called
".cppcheckignore" containing all the paths that will be ignored by the
static analysis tool.
> travis: add .cppcheckignore option

- .cppcheckignore
Use "//" instead of "#" for comments.
This change supports all versions of cppcheck.
> cppcheckignore: minor fix

- drivers/ltc2312/ltc2312.c
- drivers/ltc2312/ltc2312.h
The LTC2312-14 is a 14-bit or 12-bit, 500ksps, serial sampling A/D
converter that draws only 3.2mA from a single 3V or 5V supply.
This driver is a modified LTC legacy driver and adds support for both
the 14-bit and 12-bit versions. The change from the original is only the
addition of the no-OS style API (setup and remove functions).
Part datasheet:
https://www.analog.com/media/en/technical-documentation/data-sheets/231214fa.pdf
Original driver:
https://github.com/analogdevicesinc/Linduino/tree/master/LTSketchbook/libraries/LTC2315
> drivers:ltc2312: Add support

- projects/drivers/clk_axi_clkgen/clk_axi_clkgen.c
- projects/drivers/jesd204/axi_adxcvr.c
- projects/drivers/jesd204/xilinx_transceiver.c
- projects/drivers/jesd204/xilinx_transceiver.h
This set of patches enables the use of FPGA_INFO from the new ip cores for clkgen and xcvr. 
This will change vco_min and vco_max values according to FPGA technology, family, speed grade and device package.
> Add fpga info

- drivers/ad9144/ad9144.c
- fmcdaq2/fmcdaq2.c
Current AD9144 code provides a place in the ad9144_init_param struct for
this field, but setup code ignores it. I recommend either honouring the
field, or removing the placeholder. I have tested this code lightly on a
FMCDAQ2 setup.
> RFC: For AD9144, honour the JESD204 crossbar settings.

- projects/ad9361/src/ad9361_api.c
The location is wrong since clocks are not enabled yet. This is done in
ad9361_setup(),  with the following call:
ad9361_spi_write(spi, REG_CLOCK_ENABLE,
DIGITAL_POWER_UP | CLOCK_ENABLE_DFLT | BBPLL_ENABLE |
(pd->use_extclk ? XO_BYPASS : 0)); /* Enable Clocks */
> ad9361: move the location where axiadc_init() is called

- projects/drivers/axi_dac_core/axi_dac_core.c
- projects/drivers/axi_dac_core/axi_dac_core.h
Implement axi_dac_datasel() function.
Function selects between DDS and DMA
> axi_dac_core: implement axi_dac_datasel() function

- scripts/microblaze.mk
- scripts/xsct.tcl
- scripts/zynq.mk
For MICROBLAZE platforms most projects require an increase in HEAP size
for the application to function properly. Increase the size of the heap and
the stack on the MICROBLAZE platforms to match the default sizes of the
ZYNQ platforms.
> Update xstc.tcl script to increase heap size for MICROBLAZE

- projects/ad9371/src/app/headless.c
Commit f9992d9 offers an example of how to send custom data using the
DMA and adrv9009.
This patch updates the headless file in the same manner in order to work
with the ad9371 project. The main difference is that the configuration
for ad9371 uses the FIFO, while adrv9009 bypasses it. At the moment, the
DMA cyclic mode is not supported in the hdl.
> Master ad9371 dac dma example

- projects/ad9361/src/ad9361.c
- projects/ad9361/src/ad9361.h
- projects/ad9361/src/ad9361_conv.c
Use stdint types, for consistency 
This will fix some cppcheck warnings
> ad9361: use stdint types

- projects/ad9371/src/app/headless.c
Use the generic DDR_MEM_BASEADDR macro.
> projects: ad9371: Fix MicroBlaze compilation error

- ad9361/sw/ad9361.h
- ad9361/sw/ad9361_api.c
In this way, ad9361 gain table will be reconfigured, as before calling
"ad9361_set_no_ch_mode()" function.
> d9361: Clear ad9361 state, when channels mode is selected

- fmcomms2/kcu105/Makefile
Add project folder for KCU105 plaform for FMCOMMS2 to match the HDL
version.
> fmcomms2:kcu105: add project folder

- projects/ad9361/src/ad9361.h
- projects/ad9361/src/ad9361_api.c
By calling "ad9361_set_no_ch_mode()" function, to reconfigure the number of
channels, ad9361 device, receives a reset command. It's state should be
also cleared by calling "ad9361_clear_state()" function (this sets
"phy->current_table" value to "NO_GAIN_TABLE").
In this way, ad9361 gain table will be reconfigured when "ad9361_load_gt()"
is called, since "phy->current_table" has "NO_GAIN_TABLE" value
> projects/ad9361: Clear ad9361 state, when channels mode is configured

- projects/ad9361/src/ad9361_parameters.h
- projects/ad9371/src/devices/adi_hal/common.c
- projects/adrv9009/src/devices/adi_hal/parameters.h
- projects/drivers/xilinx_platform/platform_drivers.c
When writing to SPI, some mask is applied to chip_select value. This seems
to be wrong.
> Platform drivers spi

- drivers/hmc7044/hmc7044.c
The Phase Frequency Detector (PFD) frequency is calculated as VCXO/N1.
This bug has caused undesirable low PFD values.
> hmc7044: Fix PLL1 PFD calculation

- projects/drivers/util/util.h
Necessary for ad9172 driver implementation
> projects/drivers/util: Add additional macros

- ad713x-fmcz/spi_engine.c
- ad713x-fmcz/spi_engine.h
Signed-off-by: Istvan Csomortani <istvan.csomortani@analog.com>
Signed-off-by: Stefan Popa <stefan.popa@analog.com>
> ad713x: spi_engine: Pass init structure by reference instead of by value

- drivers/ad7124/ad7124.c
Hi!
The RDY bit of the status register is cleared when data is ready to be read and the code does the opposite.
It seems that this is the same issue but in another part https://github.com/analogdevicesinc/no-OS/issues/31 and this was the fix https://github.com/analogdevicesinc/no-OS/commit/8251dfc96b85e1b1f3875dcd8a35633cea075e42
Tested with hardware.
> drivers: ad7124: Fix ad7124_wait_for_conv_ready()

- projects/drivers/xilinx_platform/platform_drivers.c
- projects/drivers/xilinx_platform/platform_drivers.h
Add AXI I2C implementation to the xilinx platform drivers. The
implementation is for the ZYNQ PS7 family.
> projects:drivers:xilinx_platform: add AXI I2C implementation

- drivers/adc-dac/ad5592r/ad5592r-base.h
- drivers/adc-dac/ad5592r/ad5592r.c
- drivers/adc-dac/ad5592r/ad5592r.h
- drivers/adc-dac/ad5592r/ad5593r.c
- drivers/adc-dac/ad5592r/ad5593r.h
The internal reference is a core feature for the AD5592R and AD5593R
devices. The driver must have the posibility to initialize the internal
reference so that applications can activate it or leaving it deactivated in
a transparent manner. This helps applications to deliver a more complete
out-of-the-box experience.
> drivers:ad5592/3r: initialize internal reference

- projects/ad9172/src/main.c
Set "jesd_subclass" value to 1, since AD9172 supports this mode.
In Subclass 1, the latency of the JESD204B system is deterministic and
allows synchronization across multiple devices, if desired.
> ad9172: Fix "ad9172_param" configuration

- projects/ad9172/src/README
- projects/ad9172/src/main.c
Select AXI_DAC_DATA_SEL_DMA as source for DAC. In this way custom data can
be sent at the output of AD9172.
> ad9172: Add DAC_DMA_EXAMPLE

- projects/drivers/xilinx_platform/platform_drivers.c
The "platform_drivers" source and header do not compile at the moment with
a Microblaze platform as the implementation is not present. Add compiler
switches to fix compilation problem. The Microblaze implementation will be
added in a later patch.
> projects:drivers:xilinx_platform: fix compilation

- ci/travis/astyle_config
Avoid generating additional files when running astyle locally.
> travis: astyle_config: do not retain original file

- projects/drivers/xilinx_platform/platform_drivers.c
The current I2C implementation is for the AXI IIC core. As such it would
make more sense to use the inclusion guard of the driver as a compile
switch instead of the inclusion guard of another, potentially unrelated,
header. This can cause problems if the current header is present, but with
no Xilinx AXI IIC core in the design.
> drivers:platform:xilinx: fix compile switches

- ad9361/sw/ad9361.c
When using external LO, the ENSM should ignore the RF tuner ready signal.
This can be accomplished by setting the Rx/Tx Synth Ready Mask,
otherwise the ENSM would not leave ALERT state, even when instructed
by pin control or SPI writes.
> iio: adc: ad9361: Fix external LO mode in TDD mode

- projects/drivers/xilinx_platform/platform_drivers.c
- projects/drivers/xilinx_platform/xil_drivers.h
Include shared header files.
Reorganize platform drivers using the sturctures available in shared
header files.
Use `extra` pointers to access platforms specific attributes.
> projects: drivers: xilinx: update platform drivers

- .gitattributes
This attributes enables and controls the EOL normalization. This is set to
auto and the line endings are converted to LF on checkin.
> Add .gitattributes to no-OS

- drivers/adc/ad7124/ad7124.c
need to make sure CRC is disabled after a reset, otherwise there may be communication issues.
> ad7124: Ensuring CRC is disabled after reset

- drivers/adc/ad7124/ad7124_regs.c
- drivers/adc/ad7124/ad7124_regs.h
> ad7124: Adding ADI license to register setting files

- projects/ad9361/src/main.c
Fix initialization for xilinx specific spi extra parameters.
> ad9361 project: fix spi extra init params

- drivers/frequency/hmc7044/hmc7044.c
- drivers/frequency/hmc7044/hmc7044.h
Extend interface, with equivalent functions, found in linux driver.
They will be needed in the JESD autoconfiguration project.
> hmc7044: Extend interface

- projects/ad9371/src/README
Replace `ifndef` with correct condition for Altera platforms.
> ad9371: README: fix condition

- drivers/adc/ad7124/ad7124.h
> ad7124: Adding #defines for configuration registers bits

- projects/adrv9009/src/devices/ad9528/ad9528.c
- projects/adrv9009/src/devices/adi_hal/no_os_hal.c
- projects/drivers/altera_platform/altera_platform_drivers.h
- projects/drivers/altera_platform/delay.c
- projects/drivers/altera_platform/gpio.c
- projects/drivers/altera_platform/i2c.c
- projects/drivers/altera_platform/spi.c
- projects/drivers/axi_adc_core/axi_adc_core.c
- projects/drivers/axi_dac_core/axi_dac_core.c
- projects/drivers/axi_dmac/axi_dmac.c
Update platform drivers to current structure (spi, i2c, gpio, delay).
DAC Core: Fix write function for Altera .
Update "platform_drivers.h".
Add platform specific header file `altera_platform_drivers.h`.
Update project drivers to work both with Altera and Xilinx Platform.
> Adrv9009 Altera update

- drivers/platform/altera/axi_io.c
- drivers/platform/xilinx/axi_io.c
- include/axi_io.h
Add AXI IO header file in `include` folder
- function headers for AXI IO read/write.
Add AXI IO source files in `drivers/platfom` folder
- platform specific (Xilinx/Altera) read/write function implementation for AXI IO.
> Add AXI IO

- projects/ad9361/src/main.c
In the latest version of AD9361 project found in the root of the no-OS
repository, the axi read/write function contained a switch which used
either RX0TX0/RX1TX1 base addresses by checking the`id_no`parameter. Since the current
implementation of ADC/DAC core is platform agnostic, the base addresses
for RX1/TX1 are now initialized in the FMCOMMS5 configuration of AD9361 project main function.
> ad9361: fix fmcomms5 implemetation

- ad-fmcjesdadc1-ebz/ad9250.c
- ad-fmcjesdadc1-ebz/ad9517.c
- ad-fmcjesdadc1-ebz/ad_fmcjesdadc1_ebz.c
Fix SPI init value for spi_init.type
This parameter is platform dependent and some compiler switch has been
added.
> Ad fmcjesdadc1 ebz fix

- drivers/adc/ad9208/ad9208.h
- drivers/adc/ad9208/ad9208_api/ad9208_adc_api.c
- drivers/adc/ad9208/ad9208_api/ad9208_api.c
- drivers/adc/ad9208/ad9208_api/ad9208_jesd_api.c
- drivers/adc/ad9208/ad9208_api/ad9208_reg.c
- drivers/adc/ad9208/ad9208_api/ad9208_signal_monitor_api.c
Replace <> with "" for local header files to avoid build errors.
Use integer types provided by <stdint.h> lib.
> drivers: ad9208: fixes

- projects/drivers/xilinx_platform/spi.c
Use xilinx descriptor when passing the `instance` attribute.
> drivers: xilinx_platform: use xilinx descriptor

- projects/ad9208/main.c
Use Xilinx platform specific spi parameters.
NOTE: Both ad9208 devices (0 and 1) are using the same `xil_spi_param`
structure since both `SPI_DEVICE_ID` and `SPI_0_DEVICE_ID` have the same
definition: 0U.
Add `axi_io` support for read/write function wrappers.
> projects: ad9208: update main function

- drivers/dac/ad917x/ad9172.c
- projects/ad9172/src/main.c
Use Xilinx platform specific spi parameters.
Add `axi_io` support for read/write function wrappers.
> Ad9172 update

- drivers/frequency/hmc7044/hmc7044.c
- drivers/frequency/hmc7044/hmc7044.h
Add `high_performance_mode_dis`, `start_up_mode_dynamic_enable`,
`output_control0_rb4_enable` parameters to channel spec structure.
These parameters are required for ad9028 project located at
`projects/ad9208` in the no-OS repository.
> drivers: hmc7044: add channel parameters

- projects/adrv9009/src/app/headless.c
- projects/adrv9009/src/devices/ad9528/ad9528.c
- projects/adrv9009/src/devices/ad9528/t_ad9528.h
- projects/adrv9009/src/devices/adi_hal/adi_hal.h
- projects/adrv9009/src/devices/adi_hal/no_os_hal.c
- projects/drivers/axi_adc_core/axi_adc_core.c
- projects/drivers/axi_adc_core/axi_adc_core.h
- projects/drivers/axi_dac_core/axi_dac_core.c
- projects/drivers/axi_dac_core/axi_dac_core.h
- projects/drivers/axi_dmac/axi_dmac.c
- projects/drivers/axi_dmac/axi_dmac.h
- projects/drivers/jesd204/axi_jesd204_rx.c
- projects/drivers/jesd204/axi_jesd204_rx.h
- projects/drivers/jesd204/axi_jesd204_tx.c
- projects/drivers/jesd204/axi_jesd204_tx.h
1. Update drivers using `axi_io` wrapper functions. Make drivers platform agnostic.
2. Update ADRV9009 main function using `axi_io` functions and platform specific initialization parameters.
> Drivers & ADRV9009 project updates.

- projects/ad9371/src/README
- projects/ad9371/src/app/headless.c
- projects/ad9371/src/devices/adi_hal/common.c
- projects/drivers/clk_axi_clkgen/clk_axi_clkgen.c
Add initialization for device structures using `axi_io` wrappers.
Initialize devices with Xilinx platform specific parameters.
Update README.
Include required Xilinx header file.
> Ad9371 update project

- projects/ad9172/src/README
- projects/ad9208/README
- projects/adrv9009/src/README
This patch adds the new source file paths required by some no-OS projects
after spliting platform drivers into separate modules and making drivers
platform agnostic.
> projects:  update README

- projects/drivers/util/fifo.c
- projects/drivers/util/fifo.h
This is used in UART communication for tinyiiod project.
Save data received from UART, into a fifo as soon as they arrive, so that the UART buffer
doesn't get overwritten.
> fifo: add fifo implementation

- projects/adrv9009/src/devices/adi_hal/parameters.h
- projects/drivers/altera_platform/spi.c
Fixes: 0d2fe781d389cae5d160c38db796f98eb9885cf1
The updates for chip select values supported by Microblaze/ARM
plafrorms affect the behavior of Altera platform based projects.
The spi impementation for altera platforms is updated to handle the
correct chip select values.
This patch fixes the AD9371 project for altera platform.
CS values for ADRV9009 are updated to match the current altera spi
implementation.
> projects:altera: fix chip select value in function

- ad9361/sw/ad9361.c
- ad9361/sw/util.c
- projects/ad9361/src/ad9361.c
- projects/ad9361/src/ad9361_util.c
> ad9361: Fix missing breaks in switch statements

- projects/drivers/xilinx_platform/xilinx_platform_drivers.h
XIIC is the AXI IIC Bus Interface LogiCORE IP. Its presence is not
dependent of _XPARAMETERS_PS_H_.
> drivers: xilinx_platform: Fix XIIC presence check

- projects/drivers/util/xml.c
- projects/drivers/util/xml.h
This is used in tinyiiod project to generate xml configuration string that
describes a device: channels, attributes.
This string is sent to iio-oscilloscope(libiio) when a "PRINT"
command is received.
> xml: Add xml generator

- drivers/platform/xilinx/irq.c
- drivers/platform/xilinx/irq_extra.h
- include/irq.h
This allows:
- interrupt activation/deactivation;
- register/deregister interrupt handlers.
> irq: Add interrupt handling implementation

- drivers/platform/generic/uart.c
- drivers/platform/xilinx/uart.c
- drivers/platform/xilinx/uart_extra.h
- include/uart.h
This is used in tinyiiod project to communicate with iio-oscilloscope.
This version uses a fifo when receiving, data since there is no handshake
for smaller chunks of data.
> uart: Add UART implementation for Xilinx platform

- projects/drivers/axi_adc_core/axi_adc_core.c
- projects/drivers/axi_adc_core/axi_adc_core.h
This is needed in tinyiiod project.
> axi_adc_core: Add "axi_adc_get_sampling_freq()" function.

- drivers/platform/xilinx/i2c.c
- drivers/platform/xilinx/i2c_extra.h
- drivers/platform/xilinx/platform_drivers.h
- projects/ad9172/src/README
- projects/ad9208/README
- projects/ad9371/src/README
- projects/adrv9009/src/README
Removed platform_drivers.h dependency and updated compiler
switches to support both PS and PL implementation of a i2c
controller.
The driver is now updated to use the platform agnostic extra
features passed in the i2c descriptor.
Changed 'stop_bit' param to 'options'.
Signed-off-by: Sergiu Cuciurean sergiu.cuciurean@analog.com
> drivers: platform: xilinx: Updated i2c driver

- projects/ad9172/src/main.c
- projects/ad9208/main.c
- projects/ad9361/src/main.c
- projects/ad9371/src/app/headless.c
- projects/adrv9009/src/app/headless.c
- projects/drivers/axi_adc_core/axi_adc_core.c
- projects/drivers/axi_adc_core/axi_adc_core.h
- projects/drivers/axi_dac_core/axi_dac_core.c
- projects/drivers/axi_dac_core/axi_dac_core.h
- projects/drivers/axi_dmac/axi_dmac.c
- projects/drivers/axi_dmac/axi_dmac.h
- projects/drivers/jesd204/axi_jesd204_rx.c
- projects/drivers/jesd204/axi_jesd204_rx.h
- projects/drivers/jesd204/axi_jesd204_tx.c
- projects/drivers/jesd204/axi_jesd204_tx.h
Remove function pointers from device structures.
Use `axi_io` read/write functions directly inside drivers.
> projects: remove axi_io function pointers

- projects/ad9172/src/README
Use correct path for ad917x driver.
> projects: ad9172: fix README

- projects/ad9172/src/main.c
- projects/ad9371/src/app/headless.c
Remove `axi_io` function pointers from DAC DMA examples.
Related to:  #296
> projects: remove axi_io from dac dma example

- iio/iio_types.h
Add "iio_interface_init_par" structure.
This structure will be used together with "iio_register_interface" function
and contains the mapping between a device instance and a "iio_device", that
describes the channels and attributes of a device. Callbacks for read/write
operations, to device instance are also contained here.
> Iio types update

- projects/ad9172/src/README
- projects/ad9208/README
- projects/ad9371/src/README
- projects/ad9371/src/app/headless.c
- projects/ad9371/src/devices/adi_hal/common.c
- projects/ad9371/src/devices/adi_hal/parameters.h
- projects/adrv9009/src/README
- projects/adrv9009/src/app/headless.c
- projects/adrv9009/src/devices/ad9528/ad9528.c
- projects/adrv9009/src/devices/ad9528/t_ad9528.h
- projects/adrv9009/src/devices/adi_hal/adi_hal.h
- projects/adrv9009/src/devices/adi_hal/no_os_hal.c
- projects/adrv9009/src/devices/adi_hal/parameters.h
- projects/drivers/axi_adc_core/axi_adc_core.c
- projects/drivers/axi_dac_core/axi_dac_core.c
- projects/drivers/clk_altera_a10_fpll/clk_altera_a10_fpll.c
- projects/drivers/clk_axi_clkgen/clk_axi_clkgen.c
- projects/drivers/jesd204/altera_adxcvr.c
- projects/drivers/jesd204/axi_adxcvr.c
- projects/drivers/jesd204/axi_jesd204_rx.c
- projects/drivers/jesd204/axi_jesd204_tx.c
- projects/drivers/jesd204/xilinx_transceiver.c
Remove `platform_drivers.h` header file from projects.
Use header files available in `/include` folder instead.
> projects: remove platform drivers header 

- drivers/platform/xilinx/i2c.c
The AXI IIC driver functions XIic_Send and XIic_Recv use the options
argument to control if the transmission ends with a STOP bit or a REPEATED
START. To use the repeated start enum the platform driver must send a 1
value for repeated start and 0 for a stop bit. Fix the implementation to do
that.
> drivers:platform:xilinx: fix options for AXI IIC

- projects/ad9371/src/devices/adi_hal/common.c
Add gpio header file in `common.c` source file.
> projects: ad9371: add gpio

- drivers/axi_core/axi_adc_core/axi_adc_core.c
- drivers/axi_core/axi_dac_core/axi_dac_core.c
- drivers/axi_core/axi_dmac/axi_dmac.c
- drivers/axi_core/clk_axi_clkgen/clk_axi_clkgen.c
- drivers/axi_core/jesd204/axi_adxcvr.c
- drivers/axi_core/jesd204/axi_jesd204_rx.c
- projects/ad9361/src/main.c
- projects/ad9371/src/app/headless.c
- projects/ad9371/src/devices/adi_hal/common.c
- projects/adrv9009/src/app/headless.c
- projects/adrv9009/src/devices/ad9528/ad9528.c
- projects/adrv9009/src/devices/adi_hal/no_os_hal.c
Add delay header file for `mdelay/udelay` function recognition.
> projects & drivers: Add delay header file

- iio/iio_types.h
In this way number of channels is set only once, when a "iio_device" is
created.
> iio_types: Get xml from device.

- common_drivers/jesd_core/jesd_core.c
- common_drivers/platform_drivers/platform_drivers.c
- drivers/dac/ad9144/ad9144.h
This patch adds the latest modifications stated in the outdated PR: #79 
- improve consistency - use spi descriptor base address for all platforms.
Fix array size macro definition used by ad9144 driver.
> Update platform drivers & ad9144 minor fix

- iio/iio_types.h
Add "mask" parameter to function prototypes, that specifies opened
channels. This is necessary for data multiplexing/demultiplexing, in case
that not all channels of a device are opened.
> iio_types: Update read/write and transfer functions.

- tools/scripts/Makefile
Previously, on a Linux gnome-terminal, the output of the make
command was uncoloured and contained the explicit color codes like
$ make clean
\e[32m[17:09:49]\e[39m Cleaning build workspace \n
> Added -e switch to echo for backslash escapes

- iio/iio_types.h
This is necessary to differentiate, between input and output channels, with
the same name, but have different lists of attributes. This is useful when
reading or writing all the attributes of a channel.
> iio_types: Add channel type information to "struct iio_channel".

- drivers/adc/ad717x/ad7172_2_regs.h
- drivers/adc/ad717x/ad7172_4_regs.h
- drivers/adc/ad717x/ad7173_8_regs.h
- drivers/adc/ad717x/ad7175_2_regs.h
- drivers/adc/ad717x/ad7175_8_regs.h
- drivers/adc/ad717x/ad7176_2_regs.h
- drivers/adc/ad717x/ad7177_2_regs.h
- drivers/adc/ad7768/ad7768.c
- drivers/adc/ad9208/ad9208.c
- drivers/platform/linux/platform_drivers.c
This patch applies astyle on remaning drivers.
The aim is to help in avoiding large code modifications due to code
style issues when only a few code lines are changed for
funcionality/fix purposes.
> drivers: apply standard code style

- iio/iio.c
- iio/iio.h
This module implements read/write ops, required by libtinyiiod and further
calls show/store functions, corresponding to device/channel/attribute.
> iio: add iio core

- drivers/frequency/hmc7044/hmc7044.c
- drivers/frequency/hmc7044/hmc7044.h
The `hmc7044_read` function is not used within the driver.
It can be useful to access it in the upper layers of the
applications/for debug.
> drivers:freq:hmc7044: make function non-static

- drivers/frequency/adf4106/adf4106.c
- drivers/frequency/adf4153/adf4153.c
Fix warnings detected by travis when building drivers according to the
C89 standard.
Force unsigned values.
> drivers: fix issues for ISO C89 standard

- drivers/dac/ad5686/ad5686.c
- drivers/dac/ad5686/ad5686.h
1. Replace undefined macros for i2c stop bit.
2. Fix gpio init param types.
> drivers:dac:ad5686: fix driver

- iio/iio_axi_adc/iio_axi_adc.c
- iio/iio_axi_adc/iio_axi_adc.h
This permits readding/writing of "axi_adc" parameters and capture of data
from it using "axi_dmac".
This layer is placed over "axi_adc_core" and under "iio" core.
> iio_axi_adc: Add "iio_axi_adc" module.

- iio/iio_axi_dac/iio_axi_dac.c
- iio/iio_axi_dac/iio_axi_dac.h
This permits readding/writing of "axi_dac" parameters and writing of data
to it using "axi_dmac".
This layer, is placed over "axi_dac_core" and under "iio" core.
> iio_axi_dac: Add "iio_axi_dac" module.

- drivers/accel/adxl372/adxl372.c
- drivers/adc/ad7193/ad7193.c
- drivers/adc/ad7280a/ad7280a.c
- drivers/adc/ad74xx/ad74xx.c
- drivers/adc/ad7606/ad7606.c
- drivers/adc/ad7768/ad7768.c
- drivers/adc/ad7779/ad7779.c
- drivers/adc/ad7780/ad7780.c
- drivers/adc/ad7980/ad7980.c
- drivers/afe/ad4110/ad4110.c
- drivers/afe/ad4110/ad4110.h
- drivers/dac/ad5421/ad5421.c
- drivers/dac/ad5446/ad5446.c
- drivers/dac/ad5449/ad5449.c
- drivers/dac/ad5629r/ad5629r.c
- drivers/dac/ad5686/ad5686.c
- drivers/dac/ad5755/ad5755.c
- drivers/dac/ad5761r/ad5761r.c
- drivers/dac/ad5766/ad5766.c
- drivers/dac/ad5791/ad5791.c
- drivers/frequency/ad9833/ad9833.c
- drivers/frequency/adf4106/adf4106.c
- drivers/frequency/adf4153/adf4153.c
- drivers/frequency/adf4156/adf4156.c
- drivers/frequency/adf4157/adf4157.c
- drivers/potentiometer/ad525x/ad525x.c
- drivers/rf-transceiver/adf7023/adf7023.c
With the new structure of gpio driver, init param values should be
passed by reference.
> drivers: gpio: pass value by reference

- drivers/Makefile
This patch contains the following modifications for the drivers Makefile:
1. Fix adc_core files path
2. Use `INCLUDES` variable for include files
3. Disable `Wformat` flag
4. Add `SKIPDIR` variable for folders that are skipped from build
5. Skip `axi_core` build (require aditional BSP specific header files)
> drivers: Makefile rework

- projects/ad9172/src/README
- projects/ad9208/README
- projects/ad9371/src/README
- projects/adrv9009/src/README
After the restructure of the platform specific drivers, README files for
Xilinx platform were not properly updated.
This patch fixes the Xilinx platform drivers file paths.
> projects: update Xilinx README file paths

- ci/travis/run_build.sh
With the new restructure of Travis integration, the function is no
longer used.
> travis: remove build_default

- tools/scripts/Makefile
- A wrong conditional was causing an error.
https://www.gnu.org/software/make/manual/make.html#Conditional-Syntax
- xil-pre-cleanup was performed twice
- SDK build .log was removed in the wrong rule
> Makefile fixes

- drivers/platform/generic/uart.c
- drivers/platform/xilinx/uart.c
- include/uart.h
This is necessary, for consistency with other modules: spi, irq, i2c.
> uart: Rename structure to "uart_ini_param" and parameter to "param".

- drivers/platform/altera/spi.c
- drivers/platform/generic/spi.c
- drivers/platform/linux/platform_drivers.c
- drivers/platform/xilinx/spi.c
- include/spi.h
Modify parameter type of _bytes_number_ from _uint8_t_ to _uint16_t_ in
function _spi_write_and_read_. Modify file in includes and in all platform
files.
_Uint8_t_ data type is not enough to represent the size of a data block
(512 bytes) for reading and writing data in a SD card over SPI.
This modification doesn't affect the existing spi drivers because in the
implementation there are no constrains for this parameter to be _uint8_t_
Signed-off-by: Chindris <Mihail.Chindris@analog.com>
> Drivers: platform: modify type of parameter bytes_number from uint8_t to uint16

- projects/ad9371/src/app/headless.c
For some carriers the data samples were transferred erroneously from
memory to the DAC.
Perform cache flush before DMAC initialization and transfer procedure.
> projects: ad9371: fix dac_dma_example

- drivers/axi_core/axi_dmac/axi_dmac.c
- drivers/axi_core/clk_axi_clkgen/clk_axi_clkgen.c
- drivers/axi_core/jesd204/axi_adxcvr.c
- drivers/platform/xilinx/gpio.c
- drivers/platform/xilinx/spi.c
- util/util.c
Fixed adrv9009 xilinx compilation warnings coming from our own code.
Some warnings (related to talise and the autogenerated talise_config) could not be fixed at this point, they need to be fixed upstream.
> adrv9009 warnings fix

- drivers/platform/generic/timer.c
- include/timer.h
Add generic timer platform driver and the generic header file for it.
This generic driver includes no implementation, but serves as a form factor
for implementing the platform-specific timer drivers that many no-OS
projects use, for example: AD9172, ADV7511, many of the ADICUP3029 projects, etc.
Signed-off-by: Drimbarean <Andrei.Drimbarean@analog.com>
> drivers:platform:generic: add timer driver

- iio/iio_ad9361/iio_ad9361.c
- iio/iio_ad9361/iio_ad9361.h
This permits reading/writing of AD9361 attributes.
> iio_ad9361: Add iio wrapper for AD9361.

- drivers/platform/altera/i2c.c
- drivers/platform/generic/i2c.c
- drivers/platform/linux/platform_drivers.c
- drivers/platform/linux/platform_drivers.h
With #285, i2c R/W function headers changed.
This patch replaces `stop_bit` parameter with the `option` parameter
for all i2c source files.
> platform: i2c: update

- tools/scripts/linux.mk
The upload script was moved in the xilinx platform folder but the path
wasn't updated. This commit fixes this path.
> tools: scripts: linux.mk: Fixed wrong scripts path

- drivers/platform/xilinx/gpio.c
- drivers/platform/xilinx/i2c.c
Change `init_param` to `param` matching all init function headers from `/include` folder and other platform drivers implementations.
Fixes unmatching parameter name warnings generated by Doxygen integration.
> drivers: platform: change init_param variable

- drivers/adc/ad7779/ad7779.c
Implement user fixes, address the pull request comments and avoid merge
commit. User pull request:
https://github.com/analogdevicesinc/no-OS/pull/250
Add one commit with the message:
"
Update ad7779.c
Spurious deactivation of channels
Correction  register address in ad7779_set_dclk_div.
Correction of bit manipulation in ad7779_set_state
"
Co-Developed-by: F.HÉRÉSON <franck.hereson@secad.fr>
> drivers:adc:ad7779: add user commit with review changes

- projects/ad9361/src/config.h
- projects/ad9361/src/main.c
- projects/ad9361/src/parameters.h
ad9361: Add iio application.
This will allow reading/writing and parametrization of axi_adc, axi_dac and
ad9361 devices through UART, using IIO-Oscilloscope application.
> Iio ad9361

- projects/ad9361/src.mk
Update "src.mk" with the renamed file "parameters.h".
> ad9361: Fix makefile

- projects/ad9361/src/ad9361_conv.c
- projects/ad9361/src/ad9361_util.h
Fix comparisons between signed and unsigned variables.
> ad9361: Fix warnings.

- projects/ad9371/src/devices/ad9528/ad9528.c
- projects/ad9371/src/devices/ad9528/ad9528.h
- projects/ad9371/src/devices/ad9528/t_ad9528.h
- projects/ad9371/src/devices/adi_hal/common.c
- projects/ad9371/src/devices/adi_hal/common.h
- projects/ad9371/src/devices/mykonos/mykonos.c
- projects/ad9371/src/devices/mykonos/mykonos.h
- projects/ad9371/src/devices/mykonos/mykonosMmap.c
- projects/ad9371/src/devices/mykonos/mykonos_debug/mykonos_dbgjesd.c
- projects/ad9371/src/devices/mykonos/mykonos_debug/mykonos_dbgjesd.h
- projects/ad9371/src/devices/mykonos/mykonos_debug/t_mykonos_dbgjesd.h
- projects/ad9371/src/devices/mykonos/mykonos_gpio.c
- projects/ad9371/src/devices/mykonos/mykonos_gpio.h
- projects/ad9371/src/devices/mykonos/mykonos_macros.h
- projects/ad9371/src/devices/mykonos/mykonos_user.c
- projects/ad9371/src/devices/mykonos/mykonos_user.h
- projects/ad9371/src/devices/mykonos/mykonos_version.h
- projects/ad9371/src/devices/mykonos/t_mykonos.h
- projects/ad9371/src/devices/mykonos/t_mykonos_gpio.h
- projects/adrv9009/src/devices/ad9528/ad9528.c
- projects/adrv9009/src/devices/ad9528/ad9528.h
- projects/adrv9009/src/devices/ad9528/t_ad9528.h
Remove page/mainpage Doxygen commands for specific projects.
Doxygen mainpage will contain general information about the entire no-OS
repository.
> projects: remove project specific page

- projects/adrv9009/src/README
Add new source files paths after rf-transciever/talise driver migration.
PR: #364
> adrv9009: update readme

- drivers/sd-card/sd.c
- drivers/sd-card/sd.h
This interface supports byte read and write operations for SD cards
that meet the following conditions:
*   	Version 2.00 or later
*   	High capacity or extended capacity (SDHX or SDXC)
*   	Supply voltage of 3.3V
> drivers: sd_card: Add SD card read/write support

- drivers/platform/xilinx/uart.c
- drivers/platform/xilinx/uart_extra.h
Change `bytes_reveived` parameter to `bytes_received`.
> platform: xilinx: fix typo

- drivers/frequency/ad9528/ad9528.c
- drivers/sd-card/sd.c
- drivers/sd-card/sd.h
- AD9528: Add missing parameter `dev` for doxygen integration.
- SD Card: Update code documentation to comply with Doxygen format.
> doxy: drivers: sd-card update doc & ad9528 minor fix

- projects/adrv9009/profiles/tx_bw100_ir122p88_rx_bw100_or122p88_orx_bw100_or122p88_dc122p88/talise_config.c
- projects/adrv9009/profiles/tx_bw200_ir245p76_rx_bw200_or245p76_orx_bw200_or245p76_dc245p76/talise_config.c
- projects/adrv9009/profiles/tx_bw400_ir491p52_rx_bw200_or245p76_orx_bw400_or491p52_dc245p76/talise_config.c
Fix Doxygen warnings: "Reached end of file while still inside a
(nested) comment."
> doxy: adrv9009: fix warnings

- ci/travis/patch_doxy.patch
- doc/CMakeLists.txt
- doc/Doxyfile.in
- doc/drivers_page.dox
- doc/mainpage.dox
- doc/projects_page.dox
1. Update doxygen patch to ignore invalid warnings.
2. Integrate code documentation for `include`, `drivers` and `projects`.
3. Populate drivers and projects doxygen pages.
4. Update doxygen mainpage with link to no-OS generic header files.
> Update Doxygen Integration

- drivers/axi_core/axi_dac_core/axi_dac_core.c
- drivers/axi_core/axi_dac_core/axi_dac_core.h
- projects/ad9172/src/main.c
- projects/ad9361/src/main.c
- projects/ad9371/src/app/headless.c
- projects/adrv9009/src/app/headless.c
Previous implementation did not permit customization of the dac channels
by the user.
This patch allows the user setup the dac channels using the
`axi_dac_channel` structure.
The default configuration is used if the channel is not defined.
> drivers: axi_dac_core: add channel customization

- drivers/frequency/hmc7044/hmc7044.c
- drivers/frequency/hmc7044/hmc7044.h
The following linux kernel commits implement changes that are needed for the
hmc7044 to work on the adrv9009-zu11eg.
f316710d44554
51bdb91c6a767
d540768ae9fed
178195fff0f3b
74f76eb464fcc
7648a18bebb74
4ad15b25e6e5d
8053df102f877
f73b7874486d0
55e449589c1de
9d6a091391599
7ae263475cf15
618128a3c0976
ddb8a1978b4e6
b4b05318100da
e10ad36e2f7b1
c7c6e9053e4fd
ea0e697da6988
bb13250bbb211
> sync hmc7044 no-os driver with the linux driver

- libraries/fatfs/adi_diskio.c
Fatfs needs the implementation of physical device drivers.
This is our implementation of the Low level disk I/O module for FatFs.
> libraries:fatfs: Add wrapper for sd driver

- iio/iio_app/iio_generic_app.c
- iio/iio_app/iio_generic_app.h
This will permit to add a device, where custom read/write functions are
registered.
> iio: Add iio generic application.

- projects/adrv9009/Makefile
- projects/adrv9009/src.mk
- tools/scripts/linux.mk
This PR adds makefile support for tinyiiod and sets the functionality as default in adrv9009 .
> libraries: libtinyiiod: Add makefile support

- drivers/platform/xilinx/uart.c
It was working fine for platforms: ZC702, ZCU102, ZC706, but not working
on ZedBoard.
Send buffer in multiple "XUartPs_Send" calls.
> uart: Fix uart_write function.

- projects/ad9361/Makefile
- projects/ad9361/src.mk
This will allow to build IIO_EXAMPLE from application.
> ad9361: Add iio support in build process.

- doc/CMakeLists.txt
- doc/mainpage.dox
- iio/iio.c
- iio/iio_ad9361/iio_ad9361.c
- iio/iio_app/iio_app.c
- iio/iio_app/iio_app.h
- iio/iio_app/iio_axi_adc_app.c
- iio/iio_app/iio_axi_adc_app.h
- iio/iio_app/iio_axi_dac_app.c
- iio/iio_app/iio_axi_dac_app.h
- iio/iio_app/iio_generic_app.c
- iio/iio_axi_adc/iio_axi_adc.c
- iio/iio_axi_dac/iio_axi_dac.c
- iio/iio_axi_dac/iio_axi_dac.h
- iio/iio_types.h
Include iio application and interfaces to the Doxygen build.
Adapt current code documentation to the required format.
**NOTE**: This patch is required due to future IIO implementations that should comply the current doc format. 
> iio: add support for doxygen integration

- projects/adrv9009/Makefile
- projects/adrv9009/src.mk
adrv9009 src.mk: Fix TINYIIOD build option.
Build was failing with: "TINYIIOD = n".
> Adrv9009 iio make

- projects/ad9371/Makefile
- projects/ad9371/src.mk
This will allow to build IIO_EXAMPLE from application.
> ad9371: Add iio support in build process.

- doc/CMakeLists.txt
- drivers/photo-electronic/adpd188/adpd188.c
- drivers/photo-electronic/adpd188/adpd188.h
Add the no-OS driver for the ADPD188BI part. The ADPD188BI is a complete integrated
optical module for smoke detection using optical dual wavelength technology.
More information about the part at:
https://www.analog.com/media/en/technical-documentation/data-sheets/ADPD188BI.pdf
> drivers:photo-electronic:adpd188: initial commit

- drivers/platform/aducm3029/gpio.c
Add GPIO support for ADuCM3029
> drivers:platform:aducm3029:gpio Add GPIO support

- drivers/platform/aducm3029/i2c.c
This driver wrap the functions of the I2C driver for ADuCM3029
(adi_i2c.h) and make them fit to the no-OS SPI driver functions
from includes/i2c.h
> drivers: platform: Add I2C support for ADuCM3029

- drivers/platform/aducm3029/i2c.c
- drivers/platform/altera/i2c.c
- drivers/platform/generic/i2c.c
- drivers/platform/linux/platform_drivers.c
- drivers/platform/xilinx/i2c.c
- include/i2c.h
There is no need for i2c_transfer_mode enum. To fix that:
- Rename option to stop_bit from function header
- Make needed modification in i2c xilinx implementation
> Remove unneeded i2c_transfer_mode enum from i2c.h

- projects/ad9361/Makefile
- projects/ad9371/Makefile
- projects/adrv9009/Makefile
In this way we don't need to modify the Makefile corresponding to project,
if we want to build with TINYIIOD.
> projects makefile: Send 'TINYIIOD" option from command line.

- projects/adrv9009/src.mk
- projects/adrv9009/src/app/app_clocking.c
- projects/adrv9009/src/app/app_talise.h
- projects/adrv9009/src/app/headless.c
- projects/adrv9009/src/devices/adi_hal/adi_hal.h
- projects/adrv9009/src/devices/adi_hal/no_os_hal.c
Add no-OS support for adrv9009-zu11eg which features two adrv9009 devices.
To test this code, one needs to:
- insert some loopback wires between TX/RX connectors
- compile the code with ZU11EG define
- read with a .tcl script from address 0x800000 size 16384 * 16 bytes or 16384 * 8 samples and observe the sinewave on all channels.
> Dual talise

- ad9739a-fmc-ebz/ad9739a_fmc_ebz.c
- drivers/platform/xilinx/spi.c
- fmcadc2/fmcadc2.c
- fmcdaq2/fmcdaq2.c
- fmcdaq3/fmcdaq3.c
- projects/ad9361/src/main.c
- projects/ad9371/src/devices/adi_hal/common.c
- projects/adrv9009/src/devices/adi_hal/no_os_hal.c
max_speed_hz field of spi_desc was not taken into account and the SPI prescaler value was hardcoded to 64.
This pull request handles the max_speed_hz field and computes the closest possible prescaler that yields a clock speed as close as posible to max_speed_hz.
> xilinx spi prescaler based on max_speed_hz

- drivers/platform/aducm3029/i2c.c
This is needed beacause the driver return SUCCESS and FAILURE
but the include is missing.
> driver:platform:aducm:i2c add #include "error.h"

- projects/adrv9009/src/app/app_talise.c
This seems to cut about 100ms off the calibration time.
> sync talise calibration flags with linux

- drivers/platform/xilinx/irq.c
- drivers/platform/xilinx/uart.c
- drivers/platform/xilinx/uart_extra.h
- include/irq.h
- projects/ad9361/src/main.c
- projects/ad9371/src/app/headless.c
- projects/adrv9009/src/app/headless.c
This is necessary to eliminate confusion between interrupt controller ID
and interrupt ID.
> irq: Rename to a more significant name: "struct irq_ctrl_desc"

- include/timer.h
This will allow us to specify a specific hardware timer, that needs to be
initialised.
> timer: Add id element into timer structures.

- README.md
Use codacy badge linked to the analogdevices organization instead of
personal account.
> readme: replace codacy badge

- drivers/platform/aducm3029/uart.c
- drivers/platform/aducm3029/uart_extra.h
This driver wrap the functions of the UART driver for ADuCM3029
(adi_uart.h) and make them fitto the no-OS SPI driver functions
from includes/uart.h
> drivers: platform: Add UART support for ADuCM3029

- doc/CMakeLists.txt
- doc/Doxyfile.in
Use `EXCLUDE` tag from Doxygen configuration file to exclude
undocumented/unwanted paths.
> doxy: add exclude paths

- drivers/axi_core/axi_dac_core/axi_dac_core.c
Use `axi_dac_sel_datasel` to select internal data sources for customized dac
channels.
> axi_dac_core: use appropriate datasel function

- drivers/axi_core/axi_adc_core/axi_adc_core.c
- drivers/axi_core/axi_adc_core/axi_adc_core.h
Add implementation for pseudo-random noise sequence monitoring.
Function is required/used within multiple projects implementations.
> axi_adc_core: add `axi_adc_pn_mon` implementation

- drivers/platform/aducm3029/delay.c
- drivers/platform/aducm3029/timer.c
- drivers/platform/aducm3029/timer_extra.h
Add both timer and delay support for aducm 3029.
I put both in the same pull request because the delay uses the timer
> drivers: platform:timer and delay

- doc/Doxyfile.in
Disable creating subdirectories in the output directory where the
generated files are stored.
Ease the usage of doxygen links when integrated on external pages.
> doxyfile: disable CREATE_SUBDIRS tag

- projects/ad9361/src/main.c
Use appropriate device descriptor `ad9361_phy_b` when performing dac
core initialization and internal data source selection in the FMCOMMS5
configuration of the ad9361 project.
> ad9361: fmcomms5: use appropriate device descriptor

- iio/iio.c
- iio/iio.h
- iio/iio_app/iio_ad9361_app.c
- iio/iio_app/iio_ad9361_app.h
- iio/iio_app/iio_axi_adc_app.c
- iio/iio_app/iio_axi_adc_app.h
- iio/iio_app/iio_axi_dac_app.c
- iio/iio_app/iio_axi_dac_app.h
- iio/iio_types.h
iio: Release resources properly. 
"iio_unregister" function should return the interface and further more, the
resources allocated should be released in "iio_*_app_remove" functions.
> Iio unregister

- drivers/axi_core/axi_dac_core/axi_dac_core.c
- drivers/axi_core/axi_dac_core/axi_dac_core.h
- projects/ad9361/src/main.c
This patch provides the following modifications:
1. Replace `axi_dac_datasel` function with `axi_dac_set_datasel` which is properly selecting the internal data sources.
2. Remove incorrect function implementation (`axi_dac_datasel`).
> axi_dac_core: use correct implementation for internal data source selection

- drivers/platform/aducm3029/irq.c
- drivers/platform/aducm3029/irq_extra.h
This driver enables the user to create instances for the hardware
interrupts in ADuCM3029 and associate a callback to them.
> drivers: platform: Add IRQ support for ADuCM3029

- ad9739a-fmc-ebz/ad9739a_fmc_ebz.c
- fmcadc2/fmcadc2.c
- fmcdaq2/fmcdaq2.c
- fmcdaq3/fmcdaq3.c
This patch fixes 635c6b9eda56a9eff95e9c025757c8eb4fd28a96 .
Remove `max_speed_hz` initialization from projects that use old platform
drivers where the attribute is not available and avoid compiling errors.
> spi: remove max_speed_init from root projects

- projects/adrv9009/src/README
Add ad9528 driver paths in the adrv9009 readme file after latest
updates.
> projects: adrv9009: readme: add ad9528

- projects/ad9172/src/main.c
- projects/ad9371/src/app/headless.c
Minor typos found in main functions of ad9172 and ad9371 projects.
> projects: fix typos

- drivers/platform/xilinx/spi.c
Add check for XSpiPs component implementation when initializing the
prescaler min, max, default values.
The macros `XSPIPS_CLK_PRESCALE_64`, `XSPIPS_CLK_PRESCALE_64`,
`XSPIPS_CLK_PRESCALE_64` are not defined when XSpi component
implementation is used (Microblaze platform).
Fixes: b0269818a2ff691f72331e34d2c00ca91ab917b2
> drivers: xilinx: spi: add check for XSpiPs

- ad7768-1fmcz/ad77681evb.c
HDL project removed 2nd ADC, reflecting that change here
Removed base addresses #defines for second DMA and spi engine
Removed #defines for 2nd ADC GPIOs
> projects: ad7768-1fmc ad77681evb.c: remove 2nd ADC

- drivers/platform/xilinx/spi.c
While merging the conflicts on #437, the naming of the platform specific
descriptor (spi PL desriptor) remained umodified.
This commit fixes the naming and compiling errors
Signed-off-by: Sergiu <sergiu.cuciurean@analog.com>
> drivers: platform: xilinx: Fix descriptor typo

- include/crc.h
- include/crc8.h
- util/crc8.c
This is code compatible with linux crc8.h although the implementation is
somewhat different.
This implementation is supposed to replace all crc-8 implementations in no-OS
drivers which are all duplicates of each other.
By comparing the performance of this new implementation with the old one on
an x86 machine and on large sample sizes, it seems the new implementation is
faster by a factor of 13.
I suggest to review but not merge this until we have a working projects/ad7768-1 to test it on. I did test it on x86 and gives the same result as our existing algorithm.
> lookup table based crc-8 implementation

- drivers/platform/xilinx/spi.c
- the driver assumed 100MHz speed for the prescaler calculation which may not be the case
- fix corner case in prescaler calculation
> spi ps clock/prescaler fixes

- drivers/platform/xilinx/spi.c
BSP does not define SPI1 related defines if it's not used.
The build for MPSoC was crashing due to not finding the defines.
> fix mpsoc build due to missing spi1

- drivers/axi_core/jesd204/altera_a10_atx_pll.c
Fix `altera_a10_atx_pll_round_rate` function by applying the correct
formulas.
The reference for this fix can be found in
/common_drivers/xcvr_core/xcvr_modules/altera_a10_atx_pll.c
Fixes: e1b717fb576ab9e3776271f8aa49a0c5689a1e03
> axi_core: altera_a10_atx_pll: fix round rate

- include/error.h
With this macros, checking the result of no-os functions will be more readable:
Old:
if (SUCCESS != spi_init())
goto handle_fail;
New:
if (RET_FAIL(spi_init())
goto handle_fail;
> include:error.h Create define to check function result

- drivers/platform/xilinx/i2c.c
- drivers/platform/xilinx/i2c_extra.h
The I2C driver needs to accustom devices on the same I2C bus. Add support
to init and remove multiple instances of the driver on the same bus without
re-initializing the core or BSP driver. Add support to change transmission
parameters like bit rate and slave address at every transmission, if
necessary.
> drivers:platform:xilinx: update I2C driver for multiple instances

- drivers/frequency/ad9528/ad9528.c
- drivers/frequency/ad9528/ad9528.h
- projects/adrv9009/src/app/app_clocking.c
Not all projects that use ad9528 driver have a gpio connected to the
reset pin of the device.
This patch adds a `hw_reset_en` parameter to the device initialization
structure that is used to verify if hardware reset can be performed.
Update adrv9009 project to use the latest feature of the driver.
Fixes: a223f817f40aed7a33ade8b472855f0632171f73
> drivers: freq: ad9528: check if hw reset enabled

- include/circular_buffer.h
- util/circular_buffer.c
This library will be used in the wifi driver.
It is useful to write data into the buffer from one task and read
it from another task.
This will also be useful for other future applications or drivers
> util: Add circular buffer library

- drivers/dac/ad5770r/ad5770r.c
- drivers/dac/ad5770r/ad5770r.h
The CH_ENABLE register is not implemented and is not documented in the
data sheet. This removes the #defines and associated functions.
Signed-off-by: Michael Bradley <Michael.Bradley@analog.com>
> drivers: ad5770r: remove ch_enable register

- drivers/platform/xilinx/gpio.c
Add implementation for the `gpio_get_value` function in the Xilinx GPIO
driver.
> xilinx: gpio: add get_value implementation

- tools/scripts/platform/xilinx/environment.sh
Since Xilinx SDK can be installed standalone too, the Vivado dependency
should be removed.
> tools: scripts: xilinx: Remove Vivado dependency

- drivers/dac/ad5770r/ad5770r.c
- drivers/dac/ad5770r/ad5770r.h
Adds two new driver functions: to get interface status of device and remove device, freeing spi and device memory.
Updates the device struct after writing input, dac values and issuing a SW LDAC command
Fixes typo in function name for set_hw_ladc to ...ldac to match device pin naming.
> AD5770R: adds new functions, updates device struct, fixes function name type

- drivers/platform/xilinx/spi.c
xdesc->instance should be initialized to zero, otherwise
XSpi_Initialize can fail reporting that the device is
started (return XST_DEVICE_IS_STARTED). calloc() was used
instead of malloc() for preventing this.
> drivers: platform: xilinx: Fix SPI_PL initialization

- drivers/dac/ad5770r/ad5770r.c
User proper parameter name in the header comment of function
`ad5770r_remove`.
> dac: ad5770r: minor doxygen fix

- drivers/platform/aducm3029/irq.c
- drivers/platform/aducm3029/irq_extra.h
- drivers/platform/xilinx/irq.c
- drivers/platform/xilinx/uart.c
- include/irq.h
I didn't test modifications on xilinx.
Integration of the uart irq will be done in an other pull request.
Later Edit:
The last commit didn't looks good because of how git works. The changes I have done in xilinx/irq.c are:
- Make static irq_unregister
- Move irq_unregister before irq_register_callback (will be used inside it)
- Add this in irq_register_callback:
```
if (!callback_desc)
return irq_unregister(desc, irq_id);
```
> include:irq Modification decided on no-os meeting

- drivers/platform/xilinx/gpio.c
undefined reference to `XGpioPs_getDirectionPin'
> drivers: xilinx: gpio: Typo fix

- drivers/platform/aducm3029/gpio.c
If the gpio was set as output, the gpio_read_value wasn't working.
> drivers:platform:aducm: gpio Fix gpio_read_value

- drivers/platform/xilinx/timer.c
- drivers/platform/xilinx/timer_extra.h
Add timer driver implementation for Xilinx platforms. This covers AXI timer
as well as the SCUTIMER core in the Zynq systems.
> drivers:platform:xilinx: add timer driver implementation

- drivers/platform/xilinx/timer.c
It was not the same name as in the timer.h file and the new pull requests ar failng
the doxygen build
> drivers:platform:xilinx: Fix doxygen

- drivers/platform/xilinx/timer.c
This parameter was renamend in the function declaration but not inside the function
> Drivers:Platform:xilinx:timer Rename init_param -> param

- drivers/frequency/ad9528/ad9528.c
- drivers/frequency/ad9528/ad9528.h
- drivers/platform/aducm3029/gpio.c
- drivers/platform/altera/gpio.c
- drivers/platform/generic/gpio.c
- drivers/platform/xilinx/gpio.c
- include/gpio.h
- projects/adrv9009/src/app/app_clocking.c
- projects/fmcdaq3/src/app/fmcdaq3.c
- add `gpio_get_optional` function
- ad9528: update gpio reset handling
> GPIO updates

- projects/fmcadc2/src/app/fmcadc2.c
Use the macro definition from `parameters.h`
> fmcadc2: use `RX_XCVR_BASEADDR` define

- iio/iio_demo/iio_demo.c
Remove unnecessary attributes. This was causing iio_info to fail.
> iio_demo: Fix demo device xmls.

- drivers/platform/aducm3029/uart.c
When an error ocurrs, the is_non_blocking flag should be set to 0 in order to let the application submit an other buffer.
> drivers:platform:aducm: uart: unset non_blockin flags on error

- .cppcheckignore
- doc/CMakeLists.txt
- drivers/Makefile
- drivers/adc/ad9081/ad9081.c
Fix latest introduced TravisCI build issues:
1. cppcheck: ignore ad9081 api.
2. drivers build: include ad9081 required paths.
3. Doxygen: fix doc for `ad9081_remove` function; exclude ad9801
api from documentation check.
> travis: build fixes

- drivers/adc/ad7779/ad7779.c
- drivers/adc/ad7779/ad7779.h
Call `ad7779_set_power_mode` when performing device initialization.
Fix `ad7779_pwr_mode` enum.
Fixes: #552
> drivers: adc: ad7779: fix power mode

- scripts/xilinx_capture.tcl
Changed the filter's regular experssion for the target setting instruction in the m_type=ZYNQ_PSU context. Changed from "ARM*#0*" to "*A53*#0*".
> xilinx_capture script: regular expression fix for target setting in m_type=ZYNQ_PSU context

- drivers/adc/ad713x/ad713x.c
- drivers/adc/ad713x/ad713x.h
In certain applications the GPIOs are not going to be software controlled.
Make the GPIO usage optional for this use case.
> drivers:adc:ad713x make GPIOs optional

- include/util.h
- util/util.c
find_closest() - Locate the closest element in an array.
field_prep() - Shift the value and apply the specified mask.
> util: Add find_closest() and field_prep()

- util/util.c
When one of the given numbers is 0, the greatest common divisor is the
maximum between the two numbers.
> util: Fix greatest_common_divisor() when one given number is 0

- network/application/mqtt_client.c
timer_id  was not added in previosu changes and the function use it
> network: application: mqtt_client: Add missing parameter

- projects/ad713x_fmcz/gpio.c
- projects/ad713x_fmcz/spi.c
Fix latest introduced doxygen build issues.
Use same naming for gpio_init_param as in the gpio header file.
> projects: ad713x: fix doc

- include/error.h
- network/application/MQTT_eclipse_paho/mqtt_noos_support.c
- network/data_link/at_parser.c
- This is needed in order to implement secure tcp socket with mbedtls.
- EAGAIN will be returned when socket_recv is called but there is no data available. If 0 is returned doesn't work with mbedtls.
- An other other error name can be used, depending what noos team decides.
- Changes have been made in mqtt_noos_read and in at_read_buffer to adapt them to the new change.
> Add EAGAIN error to error.h

- include/util.h
For abs(40 - 52) the previous version would expand to:
((40 - 52) < 0 ? (-40 - 52) : (40 - 52))
((-12) < 0 ? (-92) : (-12))
Giving the result of -92 instead of 12.
C macros are tricky, this is why one should always enclose usages of the
macro parameters with parantheses.
> fix abs() function

- drivers/adc/ad9250/ad9250.c
- drivers/adc/ad9250/ad9250.h
Updated device initialization structure by adding `ad9250_st_init`
structure to the device initialization parameters.
The user will now configure the device settings inside the
main application.
> ad9250: update device init struct

- .gitmodules
- network/transport/noos_mbedtls_config.h
- tools/scripts/linux.mk
- Add mbedtls library that will be used for tls sockets.
- Add config file to build mbedtls library
- Add dummy makefile of how mbedtls should be integrated
> Add mbedtls library

- drivers/platform/aducm3029/irq.c
- drivers/platform/aducm3029/irq_extra.h
Add support for the GPIO group interrupt for ADuCM3029. This interrupt
complements the external interrupts, but have lower priority and can be
assigned to any GPIO.
> drivers:platform:aducm3029: add GPIO group interrupt support

- ci/travis/cppcheck.sh
Exclude mbedtls library from static analysis check.
> travis: cppcheck: exclude mbedtls

- iio/iio_ad713x/iio_ad713x.c
- iio/iio_ad713x/iio_ad713x.h
- projects/ad713x_fmcz/ad713x_fmc.c
This will allow a capturing data from the converter using a libiio client,
such us iio-oscilloscope.
> ad7134: Add iio support

- drivers/platform/aducm3029/irq.c
- drivers/platform/aducm3029/uart.c
- drivers/platform/aducm3029/uart_extra.h
This change is related to
https://github.com/analogdevicesinc/EVAL-ADICUP3029/pull/49
In the PR is an adicup project that builds noos as a static library and a new project
that uses the library doesn't have this include in the include directory.
The irq_enable and disable implementation was changed to support this change.
> drivers:platform:aducm3029: Remove #include <drivers/uart/adi_uart.h>

- drivers/platform/aducm3029/uart.c
desc->device_id was accesed after desc was deallocated resulting in unconsistent data.
> drivers:platform:aducm3029: Small uart fix

- drivers/frequency/ad9517/ad9517.c
I am currently working with the AD9467 eval board and wanted to use an external 10 MHz reference to generate the ADC sampling clock using the on-board AD9517-4. It didn't work out of the box by just setting the correct values in ad9517_cfg.h, and after a lot of digging in the datasheet, I found that the PLL is not enabled by default or in the driver. This makes no sense in my opinion, as using the VCO without the PLL enabled is not possible as far as I can tell. So it should be enabled by the driver when vco_clk_sel is enabled I think.
Also, the VCO must be calibrated in order for the PLL to lock. That should definitely also be kicked off by the driver.
> AD9517: Activate PLL and calibrate when using VCO

- ad9361/sw/platform_linux/parameters.h
To match Linux kernel versions 4.14 and 4.19.
> ad9361: linux: Update SPIDEV_DEV path

- projects/adrv9009/src/devices/adi_hal/no_os_hal.c
Recent changes in SPI broke the adrv9009 build. This fixes the project.
I checked all the projects modified by 463a16fb8, they all include "spi_extra.h" so they should build correctly.
> fix xil_platform_ops not defined in adrv9009

- drivers/platform/xilinx/gpio.c
From XGpio_GetDataDirection documentation:
Bits set to 0 are output and bits set to 1 are input.
no-OS (and also xilinx PS) convention is:
GPIO_IN = 0
GPIO_OUT = 1
Fixes #608
> fix gpio_get_direction output when using PL

- drivers/platform/xilinx/timer.c
Changes this patch:
- fix compile error generated by undefined variable;
- fix runtime memory access error by allocating memory for BSP handler;
- make frequency get function not dependent on HDL naming.
> Xilinx AXI timer drive fix

- drivers/platform/xilinx/irq.c
Update irq driver to handle the special case of the AXI timer which has
a special interrupt handler that must be attached to the interrupt vector
and the custom application routine is attached via API in the timer driver
and not the irq one.
> drivers:platform:xilinx: update IRQ driver

- tools/scripts/platform/xilinx/upload.tcl
This commit adds system wide reset on zynqmp platform and
allows for using `make run` with zynqmp which didn't previously
work.
> xilinx upload.tcl can now upload to zynqmp too

- drivers/frequency/ad9517/ad9517.c
- drivers/frequency/ad9517/ad9517.h
- projects/fmcjesdadc1/src.mk
- projects/fmcjesdadc1/src/README
- projects/fmcjesdadc1/src/app/fmcjesdadc1.c
1. Add part type check for ad9517.
2. Integrate ad9517 driver from `drivers/frequency` folder.
> AD9517 update & fmcjesdadc1 driver integration

- projects/fmcjesdadc1/src/app/app_config.h
- projects/fmcjesdadc1/src/app/app_iio.c
- projects/fmcjesdadc1/src/app/app_iio.h
- projects/fmcjesdadc1/src/app/fmcjesdadc1.c
Allow the used to read, write and edit axi_adc parameters via UART.
IIO-Oscilloscope application is now compatible with the fmcjesdadc1
project.
> fmcjesdadc1: add iio application

- projects/adrv9009/src/app/app_config.h
- projects/adrv9009/src/app/app_jesd.c
- projects/adrv9009/src/app/app_jesd.h
- projects/adrv9009/src/app/app_talise.c
- projects/adrv9009/src/app/app_talise.h
- projects/adrv9009/src/app/headless.c
Various adrv9009 related improvements:
- add some scripts to visualize the DAC_DMA_EXAMPLE data
- get the talise_setup procedure in sync with linux (FRAMER_B was uninitialized in the old procedure!)
- fix DAC_DMA_EXAMPLE (cyclic tx DMA and pl-fifo were overwriting each other)
- MCS sync seems to be working, i see constant near zero offsets across reboots
> Talise MCS sync

- projects/ad713x_fmcz/src/ad713x_fmc.c
This will allign the naming with the rest of the projects that support
IIO integration.
> ad7134: Use `IIO_EXAMPLE` naming for the iio application.

- projects/ad713x_fmcz/src/ad713x_fmc.c
- projects/ad9361/src/app_config.h
- projects/ad9361/src/main.c
- projects/ad9371/src/app/app_config.h
- projects/ad9371/src/app/headless.c
- projects/adrv9009/src/app/app_config.h
- projects/adrv9009/src/app/headless.c
- projects/fmcjesdadc1/src/app/app_config.h
- projects/fmcjesdadc1/src/app/fmcjesdadc1.c
- tools/scripts/linux.mk
Replace 'IIO_EXAMPLE' macro naming from no-OS projects with 'IIO_SUPPORT'.
This name is more suggestive since the implementations represent more
than an IIO example. They help the users interface with the boards via
IIO Oscilloscope app.
> projects: change macro naming for IIO apps

- projects/fmcadc2/src.mk
Build iio application files only if the TINYIIOD feature is enabled in
the makefile.
> adc2: build app_iio only if TINYIIOD enabled

- projects/fmcadc2/src/app/fmcadc2.c
- projects/fmcjesdadc1/src/app/fmcjesdadc1.c
The `Xil_DCacheInvalidateRange` function is not valid for PL based
platforms.
> projects: iio: enable .dcache only for PS

- projects/fmcdaq2/src/app/fmcdaq2.c
Fix devices' spi_param structures for the daq2 project.
Issue was introduced when the spi generic layer support was added.
> daq2: fix device spi_param.

- libraries/mqtt/Makefile
- tools/scripts/aducm.mk
- Initialize mqtt repository if not initialized
- Add libs rule
- use variables instead of duplicated paths
- fix CLEAN_MBEDTLS for windows
- Add noos_mbedtls_config.h as dependency for mbedtls
- Refactor CFLAGS
- Add reset_ADuCM3029.s in build
> Aducm small makefile fixes

- network/network_interface.h
- network/tcp_socket.c
- network/tcp_socket.h
- network/wifi/wifi.c
This will allow the user to choos the buffer size for each socket.
> network: wifi move CONNECTION_BUFFER_SIZE to init_param

- projects/iio_demo/src.mk
- tools/scripts/linux.mk
- tools/scripts/platform/xilinx/create_project.tcl
This will be used to extract variable values and define them into the sdk
project, allowing us to create a functional iio sdk project.
This commit has to be approved first: 
https://github.com/analogdevicesinc/libtinyiiod/pull/27
> make: Add defines into the xsdk iio project

- projects/ad9172/src/main.c
The Microblaze platforms are not supported by the HDL for this specific
project.
> ad9172: remove PLATFORM_MB from project

- projects/ad9172/Makefile
- projects/ad9172/src.mk
- projects/ad9172/src/app_config.h
- projects/ad9172/src/app_iio.c
- projects/ad9172/src/app_iio.h
- projects/ad9172/src/main.c
Add IIO support for ad9172 project.
Allow the user to read/write via UART using IIO-Oscilloscope app.
> projects: ad9172: add iio support

- drivers/platform/xilinx/gpio.c
For the PL GPIO scenario, if an error occurs at initialization, the
memory is freed but the return code will be SUCCESS, since the switch
case statement will break.
This patch makes sure that if an error occurs, the code will jump to
the default case and return the FAILURE error code.
Fixes #659.
> platform: xilinx: gpio: fix error handling

- projects/ad9361/src/ad9361_api.c
The `phy->tx_dac_init = init_param->tx_dac_init` line is duplicated
within the API driver.
Fixes #660.
> ad9361: remove redundant code

- projects/ad9361/src/ad9361_api.c
Memory allocation for spi descriptor is already done in the main function
when `spi_init(default_init_param.spi, &spi_param)` function is called.
Solves #665.
> ad9361_api: remove redundant spi mem alloc

- tools/scripts/platform/xilinx/environment.bat
- tools/scripts/platform/xilinx/environment.ps1
Update windows script to not create duplicates PATH environment variables
and only affect the variable locally to avoid permanently corrupting it.
The way to use it is the same, only the extension has been changed.
> tools:scripts:platform:xilinx: update windows script

- projects/fmcdaq2/src/app/app_iio.c
- projects/fmcdaq3/src/app/app_iio.c
Initialize the IRQ interrupts before any other iio related operation.
This patch fixes the IIO osc occasional hanging for PS platforms.
> daq2 & daq3 iio: perform irq_ctrl_init first

- projects/ad9361/src/ad9361_api.c
Use comparison operator instead of assignment operator when checking the
selected LO.
Fixes: #680
> projects: ad9361: fix EXT_LO comparison

- tools/scripts/windows.mk
Add dummy variables when calling "create_project.tcl" that generates SDK
project. This is a temporary fix, until iio support is added in windows
build.
> windows.mk: Fix makefile

- projects/ad9208/src/main.c
The hdl for ad9208 supports only Microblaze platforms.
Remove PS support from main application since it is redundant.
> projects: ad9208: remove PS support

- drivers/platform/generic/gpio.c
Update `gpio_get` function in the GPIO generic driver to align it with
the gpio header file from `/include`.
> platform: generic: gpio: update gpio_get

- drivers/dac/ad5755/ad5755.c
The 200 msec delay is not required when changing the channel range. This
commit removes it from the code.
This change has been tested on EVAL-AD575xSDZ board with AD5755-1.
> drivers: dac: ad5755: Remove delay when changing range

- projects/ad9208/Makefile
- projects/ad9208/src.mk
- projects/ad9208/src/app_iio.c
- projects/ad9208/src/app_iio.h
- projects/ad9208/src/main.c
Add IIO support for ad9208 project.
Allow the user to read/write via UART using IIO oscilloscope app.
> projects: ad9208: add iio support

- include/error.h
EAGAIN and EINVAlL are inside errno.h and other error codes that can be used.
This way we don't need to redefine each error code.
> includes:error.h: Include <errno.h>

- include/list.h
Comment description of stack was used for queue and viceversa.
> inlucde:list: Fix comment

- iio/iio_app/iio_app.c
- iio/iio_app/iio_app.h
During new libraries/iio modification iio_app shouldn't have been modified
in order to keep functional current iio_projects. These file were changed in
https://github.com/analogdevicesinc/no-OS/commit/64c0b509a70e093961e8cdd95dcfb81a38db2b03
and these changes are now reverted back to fix projects build.
> iio:iio_app: Revert changes to fix build

- include/circular_buffer.h
- include/error.h
- util/circular_buffer.c
Circular buffer will be used for wifi implementation instead of the custom implementation that is used right now.
This change was done in order to implement server operations to be used in iio.
Wifi changes will be in a new PR
> iio_wifi_backend 1: Update circular buffer implementation

- drivers/adc/ad7768-1/ad77681.c
- drivers/adc/ad7768-1/ad77681.h
Added ad77681_programmable_filter function. This function allows the user to upload its own set of filter coefficients.
Signed-off-by: JohnNeeko Garlitos <JohnNeeko.Garlitos@analog.com>
> drivers:ad7768-1: Added ad77681_programmable_filter function

- iio/iio_demo/demo_dev.c
- iio/iio_demo/demo_dev.h
- iio/iio_demo/iio_demo_dev.h
- libraries/iio/iio.c
By implementing this attribute, register can be read or written from iio_oscilloscope
> iio_demo: add direct_reg_access attribute

- network/wifi/at_parser.c
- network/wifi/at_parser.h
- network/wifi/wifi.c
This way, at_parser can write to the cb and wifi read from cb letting the
wifi to manage the connection buffers.
> iio_wifi_backend 2: wifi: Replace custom circular buffer with new implementation 

- drivers/adc/ad9081/ad9081.c
- projects/ad9081/src.mk
- projects/ad9081/src/app.c
- projects/ad9081/src/app_clock.c
- projects/ad9081/src/app_iio.c
- projects/ad9081/src/app_parameters.h
HDL design for zcu102 exists, this commit performs necessary
modifications to make no-OS/projects/ad9081 work on zcu102.
Tested, works well on vcu118 + ad9081-fmca-ebz and zcu102 + ad9081-fmca-ebz.
> ad9081: add zcu102 support

- network/noos_mbedtls_config.h
MBEDTLS_CONFIG_H  was used by an other mbedtls file and
makes the file noos_mbedtls_config.h to not be included.
> network:noos_mbedtls_config: Fix multiple inclusion check

- network/wifi/at_parser.c
The command AT_DISONNECT_NETWORK may return an error if the
module is not connected to a network. This will make the reset command
to fail event it isn't really an error.
> network:wifi:at_parser: Remove return check

- tools/scripts/windows.mk
The windows makefile has to call the "xsdk.bat" batch script instead of the
"xsdk" on which is a shell script.
> tools:scripts: fix bug in the windows.mk makefile

- drivers/adc/ad7799/ad7799.c
- drivers/adc/ad7799/ad7799.h
Add driver implementation for the AD7798/AD7799 ADC.
More information:
https://www.analog.com/media/en/technical-documentation/data-sheets/AD7798_7799.pdf
> drivers: adc: add AD7798/AD7799 driver

- drivers/platform/aducm3029/platform_init.c
- drivers/platform/aducm3029/platform_init.h
This module contains a piece of code used by all ADICUP3029 projects to
initialize the main and peripheral clock of the chip.
> drivers:platform:aducm3029: add power driver

- tools/scripts/linux.mk
- tools/scripts/windows.mk
CFLAGS was being overwritten in linux and windows makefiles.
This commit adds the possibility to use CFLAGS defined in
projects/xyz/Makefile or projects/xyz/src.mk in the build
process.
> propagate CFLAGS from project Makefile or src.mk

- drivers/adc/ad9081/ad9081.c
ad9081_work_func() can execute the same ad9081_multichip_sync() step (3),
generating an infinite loop. Don't call ad9081_work_func() only if the
ad9081_jesd_rx_link_status_print() returns errors.
> drivers: ad9081: Fix possible infinite loop

- tools/scripts/aducm.mk
If dfp files are from the default directory, their path are not
replace with a relative path to the build directory.
This change replace the full with a relative path to the build folder
Signed-off-by: Mihail Chindris <Mihail.Chindris@analog.com>
> tools:scripts:aducm.mk: Fix dfp relative path

- projects/ad9656_fmc/Makefile
- projects/ad9656_fmc/src.mk
- projects/ad9656_fmc/src/README
- projects/ad9656_fmc/src/app/ad9508.c
- projects/ad9656_fmc/src/app/ad9508.h
- projects/ad9656_fmc/src/app/ad9553.c
- projects/ad9656_fmc/src/app/ad9553.h
- projects/ad9656_fmc/src/app/ad9656_fmc.c
- projects/ad9656_fmc/src/app/app_config.h
- projects/ad9656_fmc/src/devices/adi_hal/parameters.h
Added new reference project for ad9656 eval board coupled with the zcu102 carrier.
Signed-off-by: Dan Hotoleanu <dan.hotoleanu@analog.com>
> ad9656: add reference project for the ad9656 eval board

- drivers/axi_core/axi_adc_core/axi_adc_core.c
- drivers/axi_core/axi_adc_core/axi_adc_core.h
These functions are required for porting the ad9467_fmc project.
Reference: https://github.com/analogdevicesinc/no-OS/commit/570893fb1b333d5abee930430d429a8087460141
> axi_adc_core: add delay_set and delay_calibration

- tools/scripts/linux.mk
- tools/scripts/windows.mk
When exporting NO-OS it is set as empty variable and the ?= attribution doesn't work as intended.
So the export was moved before the attribution
> tools:scripts: Fix makefile

- include/pwm.h
Send pointer to "polarity" parameter, so we get the value in the exterior
of the function.
> pwm.h: Change interface for "pwm_get_polarity".

- drivers/axi_core/axi_pwmgen/axi_pwm.c
- drivers/axi_core/axi_pwmgen/axi_pwm_extra.h
This patch adds support for the AXI PWM Generator. This device is an
FPGA-implemented peripheral used as PWM signal generator and can be
interfaced with AXI4. The register map of this peripheral makes possible
the configuration of the output signal, in terms of period and duty
cycle.
> axi_pwm: Add support for AXI PWM generator.

- drivers/Makefile
Required by new driver implementations.
For example: #746 
> drivers: makefile: include clk_axi_clkgen

- drivers/platform/aducm3029/gpio.c
- drivers/platform/generic/gpio.c
- include/gpio.h
Suggestion on how to implement a method to disable output and input buffers for GPIOs after they have been enabled.
This approach makes a new API, which seems logical to me considering there are two different APIs to enable input and output direction.
Any thoughts or suggestions?
> GPIO tristate API

- drivers/adc/ad6676/ad6676.c
The octets/frame parameter F is dependent on the number of lanes.
See Table 19 from:
https://www.analog.com/media/en/technical-documentation/data-sheets/AD6676.pdf
Fixes: #743
> adc:ad6676: adjust F based on nr. of lanes

- drivers/i2c/i2c.c
- drivers/platform/altera/altera_i2c.c
- drivers/platform/altera/i2c_extra.h
- drivers/platform/xilinx/i2c_extra.h
- drivers/platform/xilinx/xilinx_i2c.c
- include/i2c.h
- projects/adv7511/src.mk
- projects/adv7511/src/main.c
Add generic i2c_platform_ops structure that aims to point to the i2c
platform specific functions.
Implement the generic I2C functions based on the new interface.
Update the I2C dependent projects from the `/projects` folder.
> I2C: add generic interface

- tools/scripts/generic.mk
This will enable set NO-OS variable anywhere and don't brake
the build. The first usecase for the change is the adicup repository
which uses noos as submodule
Signed-off-by: Mihail Chindris <Mihail.Chindris@analog.com>
> tools:scripst:generic.mk: Refer to mk files relative to noos path

- drivers/photo-electronic/adpd410x/adpd410x.c
- drivers/photo-electronic/adpd410x/adpd410x.h
Add ADPD410x device driver for the no-OS platform.
More information on the part at:
https://www.analog.com/media/en/technical-documentation/data-sheets/adpd4100-4101.pdf
The pull request is marked as draft to only be merged after the related [GPIO API update](https://github.com/analogdevicesinc/no-OS/pull/729) is merged.
Open new pull request on old branch because it was updated with force push and [old pull request](https://github.com/analogdevicesinc/no-OS/pull/707) cannot be reopened that way.
> drivers:photo-electronic: add ADPD410x driver

- projects/ad469x_fmcz/src.mk
- projects/ad469x_fmcz/src/ad469x_fmcz.c
Add files for gpio generic interface.
Fixes: 4e38848
> ad469x: Update makefile according to gpio changes

- projects/ad400x-fmcz/src.mk
The gpio driver is not used by the project, nor the driver.
Fixes: 95e03af
> projects: ad400x: remove gpio from makefile

- tools/scripts/src_model.mk
The generic.mk file actually looks for the variable IGNORED_FILES instead
of IGNORE_FILES. https://github.com/analogdevicesinc/no-OS/blob/master/tools/scripts/generic.mk#L47
Change example accordingly.
> tools:scripts:src_model: fix IGNORED_FILES variable

- drivers/gpio/gpio.c
The check of the initialization parameters should be
performed properly before accessing the platform specific function.
The check is kept also inside each platform specific function to make
sure that the drivers still work if used independently on the generic
gpio interface.
> drivers: gpio_get_optional fix

- drivers/axi_core/jesd204/axi_adxcvr.c
Reported here: https://github.com/analogdevicesinc/no-OS/pull/772
> drivers: axi_adxcvr: Typo fix

- drivers/adc/ad469x/ad469x.c
Fix memory deallocation inside `ad469x_init` function.
Fix `ad469x_spi_read_mask` function.
> Ad469x fixes

- drivers/axi_core/jesd204/axi_adxcvr.c
In a case where the adxcvr_clk_set_rate() will fail to find a satyisfying
lane rate, the function will return an error code, without saving the xcvr
descriptor to the given address.
This change first assigns the descriptor and returns the error code after.
> drivers: jesd204: axi_adxcvr: Fix adxcvr_init return

- iio/iio_demo/iio_demo_dev.h
- libraries/iio/iio.c
- libraries/iio/iio_types.h
This attribute is necessary only for channels that allows reading or
writing data streams. It specifies the way data is packed, endianness,util
bits, sign, shift ...
> iio: Generate "scan-element" only for streaming channels

- iio/iio_axi_adc/iio_axi_adc.c
- iio/iio_axi_adc/iio_axi_adc.h
- projects/adrv9001/src/app/headless.c
It is sometimes not possible to get the exact sampling frequency from
HDL registers. Application may know more about the number of lanes and
other parameters that affect the true sampling rate of an ADC.
By adding this function pointer to iio_axi_adc, the user may provide a
custom function that knows how to get the exact sampling rate if an axi_adc.
This PR also updates the Navassa project to make use of the new function
pointer in iio_axi_adc.
Depends on #771 , only last 2 commits are relevant for review here.
> iio_axi_adc: get true sampling frequency

- include/print_log.h
Add debug/error/warning messages helpers used when running
projects/drivers.
Example of usage inside main application source files:
`#define LOG_LEVEL 4`
`#include "print_log.h"`
> include: print_log: add messages helpers

- .gitignore
These files are binary file and there is no need to be tracked by git.
> .gitignore: Add more files to be excluded

- iio/iio_axi_dac/iio_axi_dac.c
The location of the "%" was wrong
Fix: 2bb9ef5
> iio_axi_dac: Fix printf

- drivers/adc/ad400x/ad400x.c
- drivers/adc/ad469x/ad469x.c
- drivers/adc/ad7768-1/ad77681.c
- drivers/axi_core/spi_engine/spi_engine.c
Do not skip the first byte. This implies shifting the data byte in each
driver that uses SPI Engine when performing a read operation.
> spi_engine: update write/read function

- drivers/adc/ad7768-1/ad77681.c
- drivers/adc/ad7768-1/ad77681.h
Remove the function since it uses `spi_read_cont_data` function that is
not implemented in the no-OS spi drivers.
An example of using the driver in continous mode with SPI Engine offload
transfer is available at:
https://github.com/analogdevicesinc/no-OS/blob/master/projects/ad7768-1fmcz/src/ad77681evb.c
> adc: ad7768-1: remove `spi_read_interrupt_data`

- drivers/adc/ad7768-1/ad77681.c
The CRC should be enabled at read/write operations only after the
corresponding register is set accordingly.
> drivers: adc: ad7768-1: fix CRC

- libraries/iio/iio.c
- libraries/iio/iio_types.h
Added channel properties to make it as close as possible to linux iio:
- .channel
- .channel2
- .modified
- .indexed
The modified is a property used in linux iio on the channel spec that 
when set to true, the channel2 property is used as the selector for the
modifier. For example, if the type is IIO_ANGL_VEL this will use 
"anglvel" as the channel type. If modified is true and channel2 is set 
to IIO_MOD_X, the type becomes "anglvel_x".
This also affects the indexing which uses the channel and indexed 
property were added. if channel indexed is true, the value set in the 
channel property is attached to the channel. For example, "altvoltage1"
is channel type altvoltage, channel=1 and indexed=true.
Signed-off-by: Kister Jimenez <kister.jimenez@analog.com>
> libraries:iio: Add modifier to channel type.

- ad9361/sw/ad9361.c
This allows the caller to decide what to do when the requested gain
cannot be set.
> ad9361: Return an error code when split gain cannot be set.

- include/print_log.h
Replace pr_info with pr_debug for the debug log level.
> include: print_log: fix typo

- drivers/platform/xilinx/xilinx_gpio.c
The 'xil_gpio_get_optional' method should use 'xil_gpio_get' instead of the
outdated 'gpio_get'.
> drivers:platform:xilinx: fix gpio_get_optional bug

- .travis.yml
- ci/travis/run_build.sh
With #810 the old makefiles for ad9361 project were removed.
The build jobs ad9361_generic and ad9361_linux are no longer valid.
> travis: remove build jobs for ad9361 project

- drivers/Makefile
The file is required by the rf-transciver/ad9361 driver.
> drivers: makefile: include axi_dac_core.h

- drivers/rf-transceiver/ad9361/ad9361_api.c
Replace `attenuation_db` with `attenuation_mdb` to allign the function
headers in ad9361_api.c and ad9361_api.h .
> ad9361_api: fix ad9361_get_tx_attenuation typo

- libraries/iio/iio.c
Some iio library changes:
- removed unused function: int32_t iio_get_channel_number(const char *ch)
- added channel name checking before printing name field in xml. This makes the name field optional so tools like iio-osc and iio_info will use the channel id as names if not provided.
> Remove unused function and add ch name checking in xml.

- iio/iio_ad9361/iio_ad9361.c
- libraries/iio/iio.c
Add missing channel type. This fixes some channel attributes reading when
using iio-osc
> iio_ad9361: Add channel type

- projects/adv7511/src.mk
The SPI and GPIO drivers have changed format to pointer implementation
and the platform specific implementation. Update the paths to the
sources.
> projects:adv7511: update source paths on make

- drivers/axi_core/spi_engine/spi_engine.c
- drivers/axi_core/spi_engine/spi_engine.h
Allow the user to configure the dma flags.
The default value is DMA_CYCLIC.
> spi_engine: expose dma flags attribute

- include/gpio.h
With e610bcd the gpio `number` can take also negative values.
> include: gpio: switch `number` param to integer

- drivers/axi_core/spi_engine/spi_engine.c
- rearrange SPI commands order 
- start SPI transfer before the DMA 
Changes required for ad7616-sdz project update.
**NOTE:** changes tested on https://github.com/analogdevicesinc/no-OS/tree/master/projects/ad738x_fmcz
> spi_engine: driver updates

- drivers/gyro/adxrs290/adxrs290.c
- drivers/gyro/adxrs290/adxrs290.h
- iio/iio_adxrs290/iio_adxrs290.c
- iio/iio_adxrs290/iio_adxrs290.h
- projects/adxrs290-pmdz/Makefile
- projects/adxrs290-pmdz/pinmux_config.c
- projects/adxrs290-pmdz/src.mk
- projects/adxrs290-pmdz/src/app_config.h
- projects/adxrs290-pmdz/src/main.c
- projects/adxrs290-pmdz/src/parameters.h
- Adding driver for ADXRS290.
- Adding tinyiio project for ADXRS290.
- Buffer-enabled channel is not yet used since there is no trigger feature yet.
- Tested with iio_reg, iio_attr, iio_info, and iio-oscilloscope.
> Adxrs290 support

- projects/ad400x-fmcz/Makefile
- projects/ad7124-4sdz/Makefile
- projects/ad7768-1fmcz/Makefile
- projects/ad9656_fmc/Makefile
and generic.mk. This solves build issues of the project:
make[2]: *** No rule to make target 'libs'.  Stop.
> Projects Makefile: Update projects makefile to use generic_variables.mk

- iio/iio_adxrs290/iio_adxrs290.c
- iio/iio_adxrs290/iio_adxrs290.h
- iio/iio_demo/demo_dev.c
- iio/iio_demo/demo_dev.h
- iio/iio_demo/iio_demo_dev.h
- libraries/iio/iio.c
- libraries/iio/iio_types.h
This PR makes posible to enable Register Map Settings from iio Oscilloscope by just setting the deriver register access functions
to iio_device descriptor.
> Support for direct register access

- tools/scripts/platform/altera/environment.sh
- tools/scripts/platform/xilinx/environment.sh
Fix attempt for https://ez.analog.com/microcontroller-no-os-drivers/f/q-a/538213/error-building-no-os-driver-ad4696x-fmcz-ad40xx-fmcz-projects-error-in-linux-mk-or-windows-mk-files/397816#397816
> environment.sh: append paths to beggining of PATH

- drivers/adc/ad7091r5/ad7091r5.c
- drivers/adc/ad7091r5/ad7091r5.h
AD7091R5 is a 4 channel ultra low power, 12 bit ADC.
https://www.analog.com/media/en/technical-documentation/data-sheets/ad7091r-5.pdf
> ad7091r5: Add AD7091R5 driver implementation

- projects/ad738x_fmcz/src/ad738x_fmc.c
- projects/ad7616-sdz/src/ad7616_sdz.c
The address of the buffers is set now to the DDR base address
instead of RAM.
> projects: change buffer address to DDR

- projects/ad9434-fmc-500ebz/src.mk
- projects/ad9434-fmc-500ebz/src/ad9434_fmc_500ebz.c
- projects/ad9434-fmc-500ebz/src/app_config.h
- projects/ad9434-fmc-500ebz/src/app_iio.c
- projects/ad9434-fmc-500ebz/src/app_iio.h
Allow the user to read/write via UART using IIO oscilloscope.
> projects: ad9434: add IIO support

- libraries/iio/iio.c
- libraries/iio/iio_types.h
Add differential channel identifier as it is in the Linux
implementation. This is done to help integrate no-OS IIO with pyadi-iio.
> libraries:iio: add differential channel identifier

- projects/ad9265-fmc-125ebz/src.mk
- projects/ad9265-fmc-125ebz/src/ad9265_fmc_125ebz.c
- projects/ad9265-fmc-125ebz/src/app_config.h
- projects/ad9265-fmc-125ebz/src/app_iio.c
- projects/ad9265-fmc-125ebz/src/app_iio.h
Allow the user to read/write via UART using IIO Oscilloscope.
> projects: ad9265: add IIO support

- iio/iio_ad9361/iio_ad9361.c
- iio/iio_adxrs290/iio_adxrs290.c
- iio/iio_adxrs290/iio_adxrs290.h
- iio/iio_axi_adc/iio_axi_adc.c
- iio/iio_axi_dac/iio_axi_dac.c
- iio/iio_demo/demo_dev.c
- iio/iio_demo/demo_dev.h
- iio/iio_demo/iio_demo_dev.h
- libraries/iio/iio.c
- libraries/iio/iio_types.h
- priv field was added to be able to set the same function for multiple attributes
- attributes are now set as array of structures not array of pointers. This will avoid to create structures just to pass a reference
- minimal attributes test on ad9361 was done using iio-osciloscope
> IIO attributes update

- iio/iio_ad9361/iio_ad9361.c
- iio/iio_adxrs290/iio_adxrs290.h
- iio/iio_axi_adc/iio_axi_adc.c
- iio/iio_axi_adc/iio_axi_adc.h
- iio/iio_axi_dac/iio_axi_dac.c
- iio/iio_axi_dac/iio_axi_dac.h
- iio/iio_demo/iio_demo_dev.h
- libraries/iio/iio.c
- libraries/iio/iio_types.h
This approach is similar to linux and channels can be added using
defines
It was tested on ad9361 and it generates the same output of iio_info as the current master
> libraries:iio: Make channels as array

- drivers/platform/linux/linux_uart.c
> drivers: platform: linux: uart: Logical operator fix

- drivers/platform/stm32/stm32_delay.c
- drivers/platform/stm32/stm32_gpio.c
- drivers/platform/stm32/stm32_gpio.h
With this modification it's possible to use functions from gpio.h and delay.h on stm32 microcontrollers.
> platform/stm32: gpio and delay 

- .gitignore
- tools/scripts/generic_variables.mk
When LOCAL_BUILD is set to y, variables from an ignored local file
local_variables.mk will be used. So, LOCAL_BUILD can be set in
system path and in local_variables.mk add options like LINK_SRCS=y
or change BUILD_DIR to $(PLATFORM)_build in order to have projects
for diferent platforms at the same time
> tools:scripts: Add development feature

- drivers/dac/ad5629r/ad5629r.c
There is a small typo in drivers/dac/ad5629r/ad5629r.c.
Should read `structure` rather than `structue`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, structue -> structure

- projects/ad9739a-fmc-ebz/src/ad9739a_fmc_ebz.c
- projects/ad9739a-fmc-ebz/src/app_config.h
Add DAC DMA example for the ad9739a project.
> projects: ad9739a: add DMA support

- .gitmodules
- tools/scripts/generic.mk
- tools/scripts/generic_variables.mk
- tools/scripts/stm32.mk
This adds the possibility to build a project for the STM32
microcontrollers using:
make PLATFORM=stm32
The family is detected automatically from file names.
The build/ directory is used only to store the .o, .elf
and other build artifacts and, unlike for xilinx and intel
projects, it is not used to store an SDK project. The reason
behind this is that STM32CubeIDE does not support project
creation from command line. Therefore the build is entirely
maintained by us using our build system.
A new rule was added specifically for this platform, which is:
make PLATORM=stm32 debug
This rule has as prerequisite that the shell PATH contains
OPENOCD_BIN
OPENOCD_SCRIPTS
environment variables. If they are properly configured, the
rule creates an .openocd and a .gdb config script, starts
an openocd …
> stm32 (stm32f4) support in makefiles

- .gitmodules
When adding the submodule, the new file mode change was not included
by mistake and the submodule was not checking out out on repo cloning.
> add stm32f4 submodule directory too

- .gitmodules
- tools/scripts/aducm.mk
- tools/scripts/generic.mk
- tools/scripts/stm32.mk
- tools/scripts/xilinx.mk
See commit descriptions for more info.
Tested on Linux (xilinx + stm32) and Windows (xilinx) since this PR modifies generic.mk, xilinx.mk and aducm.mk. Didn't explicitly test aducm because the change is identical to xilinx so it was "implicitly" tested.
> Remove stm32 submodule, use environment variable instead

- drivers/platform/stm32/stm32_spi.c
- drivers/platform/stm32/stm32_spi.h
Implements the link between our spi layer to the stm32 HAL_SPI layer.
The stm32 project in the projects/ folder must have a stm32_hal.h file
that includes specific headers for the chip family in-use.
> platform/stm32: spi

- drivers/platform/stm32/stm32_uart.c
- drivers/platform/stm32/stm32_uart.h
- drivers/platform/stm32/stm32_uart_stdio.c
- drivers/platform/stm32/stm32_uart_stdio.h
- include/uart.h
Add the UART layer and stdio redirection for stm32 platform.
Example usage:
```
struct uart_desc *uart;
// stm32 specific stuff
struct stm32_uart_init_param uip_extra = {
.Mode = UART_MODE_TX_RX,
.HwFlowCtl = UART_HWCONTROL_NONE,
.OverSampling = UART_OVERSAMPLING_16,
};
// generic stuff
struct uart_init_param uip = {
.device_id = 2,
.baud_rate = 115200,
.size = UART_CS_8,
.parity = UART_PAR_NO,
.stop = UART_STOP_1,
.extra = &uip_extra,
};
ret = uart_init(&uart, &uip);
if (ret < 0)
return ret;
// bind stdout and stdin to the uart instance and have printf/scanf use uart as their operating medium
stm32_uart_stdio(uart); 
```
> stm32 uart

- ci/travis/doxygen.sh
Required for debugging further doxygen build issues.
> ci: doxygen: remove /dev/null from git push

- ci/travis/doxygen.sh
After Azure-Pipelines migration, to keep the git credentials within the
VMs, perform git fetch instead of git clone for the gh-pages branch.
> ci: doxygen: fix gh-pages branch update

- drivers/Makefile
Required for future IIO drivers that will be placed inside the `drivers`
folder.
> drivers: Makefile: include libraries/iio

- drivers/adc/ad7799/iio_ad7799.c
- drivers/adc/ad7799/iio_ad7799.h
Add minimal implementation of the ad7799 IIO driver.
The functions implemented are tested, while the driver is subject for
further extension.
> drivers: adc: add AD7799 IIO driver

- drivers/adc/ad9680/iio_ad9680.h
- drivers/dac/ad9144/iio_ad9144.h
- projects/fmcdaq2/src.mk
- projects/fmcdaq2/src/app/app_iio.c
- projects/fmcdaq2/src/app/app_iio.h
- projects/fmcdaq2/src/app/fmcdaq2.c
- ad9680: add IIO driver
- ad9144: add IIO driver
- fmcdaq2: add IIO support for ADC/DAC reg access
> fmcdaq2: ADC/DAC IIO direct reg access.

- drivers/adc/ad7616/ad7616.c
Fix minor build warning regarding delay functions.
> drivers: adc: ad7616: fix build warning

- drivers/dac/ad9152/iio_ad9152.h
- projects/fmcdaq3/src.mk
- projects/fmcdaq3/src/app/app_iio.c
- projects/fmcdaq3/src/app/app_iio.h
- projects/fmcdaq3/src/app/fmcdaq3.c
- ad9152: add IIO driver
- fmcdaq3: add IIO support for ADC/DAC reg access
> fmcdaq3: ADC/DAC IIO direct reg access

- tools/scripts/xilinx.mk
It seems that only the first branch of the if is executed when
running make. This seems to be beacause the if is evaluated before
ARCH is available.
Anyway, both replacements can be executed because only one will take
have effect, the one that matches the HEAP value.
> tools:script:xilinx.mk: Fix heap replacement

- libraries/iio/iio.c
If a debug_reg_read functions with parameters smaller than uint32_t
was provided, then the MS bits were allways set to 1.
Now they will be set to 0 and smaller types for debug_reg_read will
work.
> libraries:iio: Fix reg acces

- drivers/adc/ad7124/ad7124.c
- drivers/adc/ad7124/ad7124.h
Add register get and set functions wrappers to give them an appropriate
modern signature and call scheme.
Using the old get/set register functions means accessing the driver
handlers inner workings which is usually not desirable. Those wrappers
avoid this issue and maintain backwards compatibility.
Add convenient functions to the driver to use with IIO driver.
> drivers:adc:ad7124: add register methods wrappers

- drivers/adc/ad7124/iio_ad7124.c
- drivers/adc/ad7124/iio_ad7124.h
Add AD7124 IIO driver. Closely resembles the Linux driver to maintain
compatibility with tools that use it:
https://github.com/analogdevicesinc/linux/blob/master/drivers/iio/adc/ad7124.c
Do not merge before https://github.com/analogdevicesinc/no-OS/pull/904
> iio:iio_ad7124: initial commit

- drivers/platform/aducm3029/adc.c
- drivers/platform/aducm3029/adc.h
- drivers/platform/aducm3029/iio_aducm3029.c
- drivers/platform/aducm3029/iio_aducm3029.h
- drivers/platform/aducm3029/platform_init.c
- drivers/platform/aducm3029/platform_init.h
- drivers/platform/aducm3029/pwm.c
- include/pwm.h
- libraries/iio/iio.c
- projects/iio_aducm3029/Makefile
- projects/iio_aducm3029/pinmux_config.c
- projects/iio_aducm3029/src.mk
- projects/iio_aducm3029/src/main.c
- projects/iio_aducm3029/src/parameters.h
A minimal driver for the built-in adc in the aducm uc was developed and in order to don't die locally a sample project was created too.  Maybe the project can be added to the adicup repository but that is just the last commit.
In order to capture some data on the adc a pwm driver was also created.
The project support also iio and a simple gpio controller was added to the iio device to be able to control gpios from iio clients.
The firsts 3 commits are small fixes that can be moved to a separate commit if needed.
Some screen shots:
osc:
uart:
> Create aducm3029_adc and iio project

- azure-pipelines.yml
Branches that have `dev/` prefix will be build before creating PRs.
> azure-pipelines: add custom branch build support

- doc/CMakeLists.txt
- doc/Doxyfile.in
The user can now exclude files/folders using specific patterns.
For now, all `/hal/stm32/` folders will be excluded for doxygen build.
> doxygen: add EXCLUDE_PATTERNS

- drivers/platform/stm32/stm32_spi.c
CPHA = 1 corresponds to sampling on 2nd clock edge.
> stm32/spi: fix inverted CPHA

- drivers/gyro/adxrs290/adxrs290.c
- drivers/gyro/adxrs290/adxrs290.h
- iio/iio_adxrs290/iio_adxrs290.c
- iio/iio_adxrs290/iio_adxrs290.h
- projects/adxrs290-pmdz/src.mk
- projects/adxrs290-pmdz/src/main.c
To make this tinyiio demo as close as possible to the linux version, buffered channels has been added. The following are added:
1. Added buffered channel reading in the iio\iio_adxrs290 and the project.
2. Added the sync pin support to the driver to be able to check if the device has data available. 
3. Added a data_ready function from the driver and use this when getting data for the read_dev. This enables the read_dev to get the data only if it is available. Since TRIGGER is not yet supported by tinyiio, this acts as the throttling mechanism to ensure a minimum data reading interval.
This is how it will look like in IIO-OSC capture window (Auto scale disabled: Ymax: 30000, Ymin:-30000):
> Adxrs290 Buffered channel support.

- projects/adv7511/Makefile
Update makefile to work with new freamwork. Replace windows.mk and linux.mk
with generic.mk and standardise the makefile.
> projects:adv7511: update makefile

- drivers/axi_core/axi_dmac/axi_dmac.c
- drivers/axi_core/axi_dmac/axi_dmac.h
- drivers/platform/xilinx/irq.c
- include/irq.h
- projects/ad9361/src.mk
- projects/ad9361/src/main.c
This is a first draft on using interrupts with DMA.
The AXI DMA driver will now get the maximum transfer size by reading the transfer size register and use interrupts to split up the transfer if it is bigger than that.
The example project with AD9361 has a maximum transfer size of 16kb and a 32kb transfer is successfully done.
- investigate working with cyclic mode
- cyclic mode is a transfer that runs endlessly until stopped; interrupt does not seem necessary here
- investigate working with DAC
- The DMA interrupt seems to work well with the DAC as well as ADC
> AXI DMAC IRQ

- drivers/adc/adc_demo/adc_demo.c
- drivers/adc/adc_demo/adc_demo.h
- drivers/adc/adc_demo/iio_adc_demo.h
- drivers/dac/dac_demo/dac_demo.c
- drivers/dac/dac_demo/dac_demo.h
- drivers/dac/dac_demo/iio_dac_demo.h
Add virtual adc and dac drivers. Useful for testing purposes
and for better structuring the iio_demo project.
Signed-off-by: ranechita <Ramona.Nechita@analog.com>
> drivers: adc_demo&dac_demo: Initial commit

- .astyleignore
- .cppcheckignore
The `legacy` folder is skipped for static analysis and code style check
within the build jobs.
> ci: ignore legacy folder

- drivers/platform/stm32/stm32_tdm.c
- drivers/platform/stm32/stm32_tdm.h
- drivers/tdm/tdm.c
- include/tdm.h
- tools/scripts/stm32.mk
This PR implements a generic TDM interface that may be used to send/receive data using serial audio peripherals of several microcontrollers. TDM slave implementation on STM32 is also given in this PR.
> TDM generic + stm32 TDM using SAI

- include/print_log.h
- projects/ad5766-sdz/src/ad5766_sdz.c
- projects/ad6676-ebz/src/ad6676_ebz.c
- projects/ad738x_fmcz/src/ad738x_fmc.c
- projects/ad7616-sdz/src/ad7616_sdz.c
- projects/ad9265-fmc-125ebz/src/ad9265_fmc_125ebz.c
- projects/ad9434-fmc-500ebz/src/ad9434_fmc_500ebz.c
- projects/ad9739a-fmc-ebz/src/ad9739a_fmc_ebz.c
- Remove FILE, LINE and FUNCTION information from the low priority log
levels.
- Print code line before function name.
- Set default log level to 6 inside `print_log.h`.
- Remove the log level defines from projects where the default one is
used.
> Print Log update

- tools/scripts/libraries.mk
- tools/scripts/mqtt_srcs.mk
There is a bug in CCES and libraries can't be added
to the project and it has to be done manually.
So using the source will solve that issue.
Make standalone will work for projects using mqtt now.
For debug purposes it will be useful to have mqtt sources.
> tools:scripts: use mqtt source instead of library

- tools/scripts/generic.mk
- tools/scripts/stm32.mk
rwildcard from generic have some issues. For example, for SRC_DIRS with
drivers/adc/ad7768 will find also ad7768-1
It seems that rwildcard from stm32.mk fix the issue so it is moved to
generic.mk
> tools:scripts: Fix rwildcard

- projects/iio_demo/src.mk
- projects/iio_demo/src/app/main.c
Add the iio_adc_demo.c and iio_dac_demo.c in the src.mk to explicitly
specify them in the build and link process.
> projects:iio_demo: add new source files in src.mk

- drivers/adc/ad7768-1/ad77681.h
> drivers: adc: ad7768-1: fix typo

- drivers/adc/ad7689/ad7689.c
- drivers/adc/ad7689/ad7689.h
Initial version of the driver for these four PulSAR ADC's.
The driver uses the Read After Conversion (RAC) mode for
communication with the device.
This could be improved by using the Read Spanning Conversion
(RSC) mode to allow even slower hosts to be able to retrieve
data at maximum sample rate.
However, RAC was chosen due to it being standard and easy to
implement on any platform (bare-metal microcontrollers, SoC's
running linux etc.) that no-OS can run on.
> ad7689, ad7682, ad7949, ad7699 driver

- README.md
Build guide is from now on available only on wiki.analog.com.
> README: update build guide link

- projects/ad7768-evb/src.mk
Remove trailing slash from the driver path. In this way, the build
script can find the driver sources without problems.
> projects: ad7768-evb: src.mk: Fix driver path

- projects/ad9361/src/main.c
Fix error: `ad9351_rf_phy` has no member named `tx_dac_init`.
> ad9361: fix fmcomms5 build issue

- drivers/instr-amplif/ada4250/ada4250.c
- drivers/instr-amplif/ada4250/ada4250.h
- projects/ada4250_ardz/src/ada4250_ardz.c
Use enums instead of defines where needed.
Allign data types between device attributes and function parameters.
> ada4250: improve readability & minor fixes

- drivers/adc/ad7606/ad7606.h
Added util.h into include search path in ad7606.h file as GENMASK macro is defined in util.h file
> Added util.h into include search path in ad7606.h file as GENMASK macro

- projects/ad9371/src/app/headless.c
Change IIO namings `ad9361` -> `ad9371`.
> projects: ad9371: fix namings

- drivers/amplifiers/ada4250/ada4250.c
- drivers/amplifiers/ada4250/ada4250.h
- projects/ada4250_ardz/src.mk
- projects/ada4250_ardz/src/ada4250_ardz.c
Pin strap version of ADA4250.
Gain and Reference buffer are controlled via GPIOs.
Calibration features not available.
> drivers: amplifiers: ada4230 support

- projects/iio_demo/src.mk
Remove demo_dev from src.mk because it no longer exists in the project
> projects: iio_demo: src.mk fix

- drivers/platform/aducm3029/i2c.c
Bitrate/Address may not be initialized when last_address (global)
or last_bitrate (global) are equal to the new address/bitrate.
This change uses impossible values for address or bitrate to "mark"
them as uninitialized on driver removal.
---------------
For a bit more context, address 0xff is not possible on classical I2C (0-127 addresses only) and a bitrate of 0 doesn't make sense, hence those values.
> aducm i2c bug fix: bitrate/address may not be init

- drivers/adc/ad713x/iio_ad713x.c
- drivers/adc/ad713x/iio_ad713x.h
- drivers/adc/ad713x/iio_dual_ad713x.c
- drivers/adc/ad713x/iio_dual_ad713x.h
- drivers/adc/ad7799/iio_ad7799.c
- iio/iio_ad9361/iio_ad9361.c
- iio/iio_app/iio_app.c
- libraries/iio/iio.c
- libraries/iio/iio_types.h
- projects/ad713x_fmcz/src.mk
- projects/ad713x_fmcz/src/ad713x_fmc.c
- projects/ad713x_fmcz/src/parameters.h
Remove old transfer_dev_to_mem function and use new one. Then remove it from iio.
Add support for register access.
Use iio_app
> Remove old transfer_dev_to_mem and update ad7134 to use iio_app

- drivers/frequency/adf5355/adf5355.c
- drivers/frequency/adf5355/adf5355.h
Add no-OS support for ADF5355, ADF4355, ADF4355-2, ADF4355-3, ADF5356.
More info: https://www.analog.com/media/en/technical-documentation/data-sheets/ADF5355.pdf
Note: `adf5355_clk_recalc_rate`, `adf5355_clk_set_rate` and `adf5355_clk_round_rate` function were added to align the driver with the linux version and ease the integration with certain projects.
> drivers:frequency:adf5355: initial commit

- drivers/adc/ad7746/ad7746.c
- drivers/adc/ad7746/ad7746.h
- projects/ad7746-ebz/Makefile
- projects/ad7746-ebz/builds.json
- projects/ad7746-ebz/pinmux_config.c
- projects/ad7746-ebz/src.mk
- projects/ad7746-ebz/src/app/headless.c
- projects/ad7746-ebz/src/app/parameters.h
Based on the work of @dbogdan  here:
https://wiki.analog.com/resources/tools-software/uc-drivers/renesas/ad7746?s[]=ad7746
Basically, the driver had a facelift and is now compatible with no-OS.
The demo project was translated to work over simple UART.
The demo is not functional on ADUCM now because scanf is broken on ADUCM. Once that gets fixed, demo will work out of the box.
This PR also depends on #1006 to work properly due to a bug in aducm/i2c implementation.
Here's what the demo prints over UART:
```
[INIT] AD7746 initialization ok.
[CALIB] 1. Remove the ruler and press ENTER. 
[CALIB] 2. Place ruler to 51mm (2inch) and press ENTER.
[DEMO] Move the ruler around, its position will is read and displayed every 2 seconds.
Position: 51 mm, Temperature: 23 *C
Position: 50 mm, Temperature: …
```
> Ad7746 driver and demo with ad7746-ebz

- tools/scripts/platform/xilinx/util.tcl
make run was broken on xilinx in de1396b8f.
Signed-off-by: buha <darius@berghe.ro>
> xilinx scripts: fix typo in util.tcl

- drivers/amplifiers/ada4250/ada4250.c
According to the datasheet, 0 corresponds to negative offset values and
1 corresponds to positive offset values. 
> drivers:amplifiers:ada4250: fix polarity meaning

- iio/iio_app/iio_app.c
- libraries/iio/iio.c
- libraries/iio/iio.h
- projects/ad469x_fmcz/src/ad469x_fmcz.c
- projects/ad6676-ebz/src/app_iio.c
- projects/ad7768-evb/src/app_iio.c
- projects/ad9081/src/app_iio.c
- projects/ad9265-fmc-125ebz/src/app_iio.c
- projects/ad9361/src/main.c
- projects/ad9371/src/app/headless.c
- projects/ad9434-fmc-500ebz/src/app_iio.c
- projects/ad9467/src/app/app_iio.c
- projects/ad9656_fmc/src/app/app_iio.c
- projects/ad9739a-fmc-ebz/src/app_iio.c
- projects/adrv9001/src/app/app_iio.c
- projects/adxrs290-pmdz/src.mk
- projects/adxrs290-pmdz/src/main.c
- projects/fmcadc2/src/app/app_iio.c
- projects/fmcadc5/src/app/app_iio.c
- projects/fmcdaq2/src/app/app_iio.c
- projects/fmcdaq3/src/app/app_iio.c
- projects/fmcjesdadc1/src/app/app_iio.c
- projects/iio_demo/src.mk
iio_app will print this message upon startup, this way we solve the problem of having to document the baudrate setting in the wiki - we document it run-time, at the serial terminal.
```
Running TinyIIOD server...
If successful, you may connect an IIO client application by:
1. Disconnecting the serial terminal you use to view this message.
2. Connecting the IIO client application using the serial backend configured as shown:
Baudrate: 921600
Data size: 8 bits
Parity: none
Stop bits: 1
Flow control: none
```
> Iio app message

- drivers/Makefile
With find, ignored directories where also added to SRCS and they
can't and shoulden't be removed.
> drivers:Makefile: Fix make clean

- drivers/adc/ad7768-1/ad77681.h
The driver does not contain any particular spi_engine specific
functions/parameters, therefore it should be independent on the
framework.
> drivers:adc:ad7768-1: include spi

- network/linux_socket/linux_socket.c
As per recv documentation, 0 is returned when requested
size is 0 or if a socket was disconnected by a peer.
Therfore, return error message when necesary.
With this PR (https://github.com/analogdevicesinc/libtinyiiod/pull/41), DAC buffers will work over sockets: 
When merged will add a commit updating the submodule too
> network:linux_sockets: Fix return

- tools/scripts/aducm.mk
- tools/scripts/stm32.mk
As a side effect, this PR enables debugger flags for all aducm builds, this should be fine, we do it anyway on all platforms and we don't have debug/release separation.
> Aducm make debug

- drivers/photo-electronic/adpd410x/adpd410x.c
- drivers/photo-electronic/adpd410x/adpd410x.h
Add getters for operation mode, sampling frequency and last timeslot.
> drivers:adpd410x:add getter functions

- include/error.h
It makes sense for SUCCESS/FAILURE to be redefined using our own
(no-OS) convention rather than mix things up.
One currently known scenario is the aducm3029 platform which
defines FAILURE as 1, contrary to our -1 expectation. This leads
to bad behaviour.
> redefine SUCCESS and FAILURE if necessary

- tools/scripts/platform/xilinx/util.tcl
- tools/scripts/xilinx.mk
This change lets the user specify the target architecture and
adds support for cortexr5.
> tools: scripts: xilinx.mk: Add support for cortexr5

- tools/scripts/linux.mk
- tools/scripts/platform/linux/.vscode/c_cpp_properties.json
- tools/scripts/platform/linux/.vscode/launch.json
- tools/scripts/platform/linux/.vscode/tasks.json
- tools/scripts/platform/linux/config_build.py
After running make, the folder build/app can be selected
from vscode in order to start developing and debugging the
project.
Includes path and flags are set by the config_build.py
script in order to have correct linting.
Files from tools/scripts/platform/linux/.vscode are copied to
the build/app folder and the updated with config_build.py
with the project specific parameters
tools:scripts:linux.mk: Add support for debugging
After running make, the folder build/app can be selected
from vscode in order to start developing and debugging the
project.
Includes path and flags are set by the config_build.py
script in order to have correct linting.
Files from tools/scripts/platform/linux/.vscode are copied to
the build/app folder and the updated with config_build.py
with the project specific …
> tools:scripts:linux.mk: Add support for debugging

- projects/ad713x_fmcz/src/ad713x_fmc.c
Initialize properly the device id required by the spi drivers.
> projects: ad7134: fix spi init

- projects/adrv9009/src/app/headless.c
The order of the parameters passed to the `start_iiod` function was
incorrect.
This patch fixes the addressed issue.
> adrv9009: fix IIO app issue

- drivers/adc/ad717x/ad7172_4_regs.h
Configuration tried to set a register that doesn't exist.
> drivers:adc:ad717x: remove wrong configuration

- projects/fmcjesdadc1/src/app/fmcjesdadc1.c
Perform cache flush after each transfer sequence from device to memory
to get accurate samples data at the specific DDR addresses.
> projects:fmcjesdadc1: perform cache flush

- drivers/cdc/ad7746/iio_ad7746.c
Due to a last minute codereview comment I have introduced an incorrect
dereferencing in the original driver. This commit fixes it and now
the debugging interface works with this device.
> driver/ad7746: iio driver debug interface fix

- tools/scripts/generic.mk
- tools/scripts/platform/xilinx/util.tcl
- tools/scripts/xilinx.mk
This change allows more advanced filtering of the JTAG targets using the
jtag_cable_name filter. This is required when you have multiple JTAG
cables connected to the same machine. Not providing the argument
JTAG_CABLE_ID will fall back to the standard behavior.
This is required for the hardware testing hardness.
Example usage:
```
make run JTAG_CABLE_ID=210299A567FE
```
This has been tested with and without this new argument with ADRV9361-Z7035 boards and the Xilinx SDK 2019.1.
Signed-off-by: Travis F. Collins <travis.collins@analog.com>
> Add parameterized JTAG filtering to PS init

- drivers/adc/ad9081/ad9081.c
Corresponds to linux commit:
18fa16da2d3cf5c78f6c13ec651a667313102813
> ad9081: Fix 4x4 Crossbar Mux0 Mappings for AD9081

- drivers/photo-electronic/adpd410x/adpd410x.c
- drivers/photo-electronic/adpd410x/adpd410x.h
Add function to adpd410x.c to read a specified number of bytes from the
FIFO using the minimum number of register reads. Also add support for
reading a specified number of bytes (up to 255) from a register with one
i2c or spi read.
When reading large amounts of data from the FIFO (on the order of 100 - 512 bytes),
this greatly improves efficiency, as opposed to reading one packet from the FIFO
at a time.
> Add adpd410x support for reading a large number of bytes from the FIFO at once

- drivers/photo-electronic/adpd410x/adpd410x.c
Make sure the Write Bit is set.
> drivers:adpd410x: fix SPI reg write

- iio/iio_app/iio_app.c
For microblaze platforms, the IIO support does not use
the irq interface.
This patch makes sure that projects that use the IIO generic app and
have support for Microblaze platforms will build successfully.
> iio_app: remove irq for platfrom_mb

- drivers/adc/ad7799/ad7799.c
- drivers/adc/ad7799/ad7799.h
- drivers/adc/ad7799/iio_ad7799.c
drivers: ad7799: update ADC channel read
Implementation of the read channel function is no more constrained to
mV.
The data read from the device is now converted based on the precision
attribute in either mV or uV.
> drivers: ad7799: update ADC channel read

- drivers/platform/xilinx/xilinx_i2c.c
XIicPs_SetOptions() expects XIICPS_REP_START_OPTION according to
its documentation and not XIIC_REPEATED_START.
Addresses #1046
> xilinx/i2c: fix incorrect repeated start macro

- drivers/adc/ad717x/ad717x.h
Add support for AD4116 driver and mention it in the comments of the driver.
Changes are limited to register map defines.
> drivers:adc:ad717x: add support and mention for ad4116

- drivers/dac/ltc2688/ltc2688.c
- drivers/dac/ltc2688/ltc2688.h
The LTC2688 is a 16 channel, 16 bit, +-15V DAC with an integrated
precision reference. It is guaranteed monotonic and has built in
rail-to-rail output buffers that can source or sink up to 20 mA.
> drivers: dac: ltc2688: Initial revision

- tools/scripts/generic.mk
For some reason $(LDFLAGS) was added twice to the linker command.
This creates troubles with newer compilers, something like:
arm-none-eabi-gcc: fatal error:
/usr/lib/gcc/arm-none-eabi/11.1.0/../../../../arm-none-eabi/lib/nosys.specs:
attempt to rename spec 'link_gcc_c_sequence' to already defined
spec 'nosys_link_gcc_c_sequence'
> generic.mk: remove double LDFLAGS

- tools/scripts/aducm.mk
Aducm 'make run' command would fail if run after the project is build once
because it would try to make a new project with the same name where one
already exists. 'make ca' was needed in between each 'make run' commands.
> tools:scripts: fix aducm 'make run' command

- drivers/frequency/hmc7044/hmc7044.c
- drivers/frequency/hmc7044/hmc7044.h
- projects/ad9081/src/app_clock.c
- projects/adrv9009/src/app/app_clocking.c
Draws extra current and doesn't improve much.
> drivers: freq: hmc7044: Remove option for High performance PLLs/VCO

- drivers/temperature/adt7420/adt7420.c
- drivers/temperature/adt7420/adt7420.h
1.) Added support to devices from the ADT7xxx family.
2.)The code flow has accommodated selection of devices based on SPI or I2C interfacing, corresponding to the target device selected-  Example: ADT7420 /ADT7320.To achieve this, macros corresponding to the register map information for ADT7320 has also been added.
3.) The individual functions would thus include a communication interface check, depending on which, the  register definitions are passed as arguments to the function calls serving the purpose.
Signed-off-by: Janani Sunil <janani.sunil@analog.com>
> Implemented Support to ADT7xxx Family

- iio/iio.c
- util/list.c
1. Direct operations done on void pointers which causes build failure on IAR compiler. The build works well with GCC and ARMC compiler but not on IAR. Added typecasting to pointers before performing any operations.
> Minor fixes w.r.t. void pointer typecasting

- drivers/frequency/hmc7044/hmc7044.c
- drivers/frequency/hmc7044/hmc7044.h
Previously this function treated the channel number as an index into the channel list, which worked as long as the channel list contained continuous channel numbers starting at zero. This fix looks the channel number up in the list and returns an error if not found.
> hmc7044: fix clk_set_rate if channel numbers aren't continuous

- projects/ad9361/src/main.c
The `adc_capture` function is no longer supported.
Reference: https://ez.analog.com/microcontroller-no-os-drivers/f/q-a/550449/adc_capture-for-ad9361
> projects:ad9361: fix comment

- drivers/platform/xilinx/gpio_irq_extra.h
- drivers/platform/xilinx/xilinx_gpio_irq.c
This option allows the user to disable the nested interrupt.
Previously, if the user wanted to disable the irq pin inside the irq handler,
the nested interrupt would reactivate the pin.
> drivers/platform/xilinx:gpio_irq Added retriggerable option

- drivers/axi_core/jesd204/axi_adxcvr.c
- drivers/axi_core/jesd204/xilinx_transceiver.c
- drivers/axi_core/jesd204/xilinx_transceiver.h
Currently the QPLL output frequency is limited to the maximum
transceiver line rate assuming the QPLL divider is set to 1. This limits
the achievable output frequencies because some valid combinations of
QPLL frequency and divider are not allowed.
This change removes this restriction by replacing the voltage/speed
grade limit on the QPLL frequency with a check on the lane rate before
the PLLs are configured. Then the QPLLs can use their full range
specified by F_QPLL[01]RANGE in the datasheets. An invalid QPLL
configuration with the divider set to 1 is not possible because of the
previous check on the lane rate.
> xilinx_transceiver: allow higher QPLL frequencies

- projects/ad9361/src/main.c
Make sure that SPI_CS2 is used for the second ad9361 device from the
fmcomms5 board.
> projects: ad9361: fix fmcomms5 cs

- drivers/rf-transceiver/ad9361/ad9361.h
- drivers/rf-transceiver/ad9361/ad9361_api.c
- drivers/rf-transceiver/ad9361/ad9361_api.h
- projects/ad9361/src/main.c
The `id_no` parameter is redundant in the latest version
of the driver/project.
> ad9361: remove id_no param

- drivers/afe/ad4110/ad4110.c
- drivers/afe/ad4110/ad4110.h
This PR tries to solve: https://ez.analog.com/microcontroller-no-os-drivers/f/q-a/545992/ad4110-1-no-os-driver-issue-in-spi-library-linux-while-multiple-adc-communication-on-same-chip-select-line
Will be keept as draft after clients confirms that it solves the issue because I didn't test it on hardware.
> drivers:afe:ad4110: Driver fix

- drivers/platform/xilinx/gpio_irq_extra.h
- drivers/platform/xilinx/xilinx_gpio_irq.c
-now GPIO IRQ can be enabled/disabled on each pin individually
> drivers:platform:xilinx: Xilinx GPIO IRQ driver rework

- drivers/amplifiers/ada4250/ada4250.c
drivers:ada4250: minor fixes:
1) Fixed a typo in the code while passing the address of the gpio structure to gpio_direction_output() function. 
2) Added break statements in the switch case for enabling reference buffer.
> drivers:ada4250: minor fixes.

- drivers/adc/ad469x/ad469x.c
- drivers/adc/ad7768-1/ad77681.c
- drivers/axi_core/spi_engine/spi_engine.c
- drivers/platform/xilinx/uart.c
- drivers/platform/xilinx/xilinx_gpio.c
- drivers/platform/xilinx/xilinx_i2c.c
- drivers/platform/xilinx/xilinx_spi.c
If a return statement is followed by a break statement, then the second
one is not reached.
> drivers: remove redundant breaks

- drivers/platform/linux/linux_i2c.c
- drivers/platform/linux/linux_i2c.h
Refactored linux_i2c_platform_ops to linux_i2c_ops.
> Refactoring linux_i2c_platform_ops

- drivers/platform/xilinx/i2c_extra.h
- drivers/platform/xilinx/xilinx_i2c.c
- projects/adv7511/src/main.c
Refactoring xil_i2c_platform_ops to xil_i2c_ops.
> Refactoring xil_i2c_ops refactoring

- drivers/adc/ad7779/ad7779.c
- drivers/adc/ad7779/ad7779.h
The `ad7779` prefix for the dclk_div variable/structure should
be used.
Fix spelling error.
> drivers:adc:ad7779: fix dclk_div variable

- drivers/platform/stm32/stm32_i2c.c
- drivers/platform/stm32/stm32_i2c.h
This is the basic version of the no-OS i2c running on stm32
controllers. This doesn't support i2c transactions without a
stop bit at the end.
> basic no-OS API <-> stm32 i2c HAL translation

- projects/ad7768-evb/src/ad7768_evb.c
Apply correct base AXI ADC base address to the driver. Before the address
was to the memory area dedicated to the DMA transfer.
> projects:ad7768_evb: fix AXI ADC base address

- drivers/afe/ad4110/ad4110.c
- drivers/afe/ad4110/ad4110.h
Seems like a copy-paste issue. Fixed with this commit.
> drivers:afe:ad4110: Fix author name

- drivers/accel/adxl362/adxl362.c
In the original code, the FIFO configurations bits were sent to the incorrect registers, changing interrupt settings as well... Solves #1167
> Fixes FIFO register configuration mistake

- projects/ad469x_fmcz/src/ad469x_fmcz.c
- use buffers for the IIO support of the project
- use less generic naming for the device
> projects:ad469x: use iio buffers + minor naming fix

- projects/ad469x_fmcz/src/ad469x_fmcz.c
Fix typo for the IIO device name.
> projects:ad469x: naming typo

- projects/ad9371/src/devices/mykonos/mykonos.c
Correctly use a bitwise operation to check for the desired ARM state
instead of logical operation.
> drivers:iio:adc:mykonos: fix ARM state check routine

- drivers/frequency/adf4156/adf4156.c
- drivers/frequency/adf4156/adf4156.h
- drivers/frequency/adf4157/adf4157.c
- drivers/frequency/adf4157/adf4157.h
Replace `ad9833` with `adf4156/adf4157`.
> drivers:frequency: fix naming typos

- tools/scripts/platform/xilinx/util.tcl
This is valid for newever versions - tested on Vitis 2021.1.
> tools: scripts: xilinx: Update Vitis template name

- drivers/axi_core/jesd204/xilinx_transceiver.c
GTY4 = Virtex UltraScale+, so ds923 should be used instead of ds893.
> drivers: xilinx_transceiver: Fix GTY4 check_lane_rate()

- drivers/adc/ad7193/ad7193.c
- drivers/adc/ad7193/ad7193.h
* Added other device parameters to device descriptor and init param
* Added functions to configure these additional parameters.
* The channel select function can now enable multiple channels.
* The single read function now samples data with rate defined in the descriptor.
* Update the init function to reset and initialize the device with the init param.
*  All functions now return error status.
* Added Astyle Fix.
> drivers:adc:ad7193: Code Updated

- drivers/dac/ltc2688/ltc2688.c
Added a missing return statement before the error code segment.
> drivers: dac: ltc2688: Minor fix

- projects/ad7124-8pmdz/src/app_config.h
- projects/ad7124-8pmdz/src/parameters.h
- projects/ad9083/src/uc/uc_settings.h
- projects/cn0531/src/app_config.h
- projects/iio_adpd1080/src/app_config.h
- projects/iio_demo/src/app/app_config.h
- projects/iio_demo/src/app/parameters.h
Fix multiple typos in several no-OS projects.
> projects: typos fixes

- iio/iio.c
- iio/iio.h
- iio/iio_app/iio_app.c
- Remove iio_register and use init param. No project use register during runtime. This simplify a lot structures in desc and xml is generated only once.
- Some naming changes.
> "Small" refactor in iio.c

- drivers/platform/stm32/stm32_delay.c
The stm32 delay implementation is based on the DWT timer in order
not to make use of normal timers that may be useful for the user.
There was an error in the prior implementation however - this DWT
was being enabled in its own registers but the
Debug Exception and Monitor Control Register (DEMCR) register did
not enable debugging facilities.
Therefore, when loading a .hex via DAPLink, the program would
hang in delay functions because the DWT wasn't counting. When
debugging via SDK, this wasn't visible, likely because the SDK
debugger enables TRCENA in DEMCR.
This commit fixes this hang.
> stm32 delay DWT enable in DEMCR

- iio/iiod.c
- iio/iiod.h
- iio/iiod_private.h
This is an improvement of libtinyiiod.
https://github.com/analogdevicesinc/libtinyiiod
The main improvments are:
- Non-blocking processing function.
This is needed in order to support triggers in single threaded
enviroment like No-OS.
- Handle multiple connection instances (e.g. Sockets)
- Connections and application instance are passed as ctx
to functions.
It was tested with minor changes in iio on:
- **zed**:  xilinx **sockets** and **uart** with **ad9361** and **adxrs290**
- **zc706**: xilinx **sockets** and **uart** with **fmcdaq2**
Both dac buffer write and plot works.
I will add iio change in an other PR because #1140 needs to be merge before any update
> iio:Create non-blocking iiod

- tools/scripts/generic.mk
Otherwise the following messages are displayed at build time:
The system cannot find the file specified.
make[1]: [../../tools/scripts/generic.mk:351: update_srcs] Error 2 (ignored)
> tools: scripts: generic.mk: Do not remove inexistent folders

- drivers/platform/linux/linux_gpio.c
...instead of returning an error.
> drivers: platform: linux: gpio: Use already exported GPIOs

- drivers/amplifiers/ada4250/ada4250.c
- drivers/amplifiers/ada4250/ada4250.h
Apparently the logic is reversed for this one. When in low BW mode, the BW pin should tied to AVDD and when in high BW mode, the BW pin should be tied to AVSS.
The low BW mode is actually the standard response while the high BW mode is more of a BW boost feature.
> drivers: ada4250: Minor Updates

- .gitignore
Add the `.Xil` folder to the gitignore, so it won't be included
accidentally in no-OS repository commits when building projects.
> gitignore: add .Xil folder

- tools/scripts/aducm.mk
- tools/scripts/altera.mk
- tools/scripts/generic.mk
- tools/scripts/libraries.mk
- tools/scripts/linux.mk
- tools/scripts/stm32.mk
- tools/scripts/xilinx.mk
General solution to ignored error when attempting to delete non-existent file/directory in make. 
Modifications for consistency in names used in *.mk files.
> tools: scripts: *.mk: Naming & typo corrections

- drivers/photo-electronic/adpd410x/iio_adpd410x.c
Add read samples function required by the IIO buffer support of the
device.
> adpd410x_iio: add read samples support

- drivers/dac/ad3552r/iio_ad3552r.c
Replace `prepare_transfer` with `pre_enable` function pointer.
There is no `prepare_transfer` attribute inside iio_device structure.
Example:
https://github.com/analogdevicesinc/no-OS/blob/d6b3591b5af2969818a55795681332f39ac29e1f/drivers/adc/ad713x/iio_dual_ad713x.c#L181
https://github.com/analogdevicesinc/no-OS/blob/d6b3591b5af2969818a55795681332f39ac29e1f/drivers/adc/ad713x/iio_dual_ad713x.c#L97-L106
> ad3552r:iio: fix prepare transfer function

- tools/scripts/stm32.mk
The first line was accidentally added in commit
8a41e11d090cec18d2c81f126ed2b2bfc2a630aa.
> tools: scripts: stm32.mk: remove first line

- drivers/adc/ad7193/ad7193.c
- drivers/adc/ad7193/ad7193.h
AD7193 driver rework including:
-removed CS as gpio (the new SPI driver toggles automatically CS pin)
-range enum added
-op mode enum added
-clock enum added
-restyled
> ad7193 driver rework

- libraries/fatfs/adi_diskio.c
- libraries/mqtt/mqtt_client.c
- libraries/mqtt/mqtt_noos_support.c
Modified some #include directives from mqtt and fatfs libraries with
the correct paths. This change should have been made in #1178.
> libraries: updated include paths to no-os/

- iio/iio_app/iio_app.c
This is a temporary fix, stm32 platform doesn't currently
like no-os/error.h because of name clash with SUCCESS. So
for now we include <errno.h> directly on stm32 platform
until we get rid of SUCCESS.
> iio_app: fix includes for stm32 platform

- iio/iiod.c
The non-blocking version of IIOD doesn't work well with IIO client (e.g. IIO oscilloscope) to write the IIO attribute value and perform debug register read/write operations. The IIO attribute write is a special case where two consecutive commands are sent from IIO client over serial link: 1) Attribute write command with size of data byte  2) Attribute write value
Existing code had bug in reading the attribute write value (i.e. 2nd command was not handled correctly). So updated code to handle this command by initializing payload buffer and length in IIOD command run state.
Verified other operation (attr read/write, data capture, debug register read/write) after this change and nothing is broken.
> IIOD attribute write and debug register read/write issue fix

- drivers/adc/ad7799/iio_ad7799.c
Insead of processing the channel data in the IIO layer of the driver,
just send the raw data in the upper layers to be processed.
> drivers:adc:ad7799_iio: read raw data

- drivers/adc/ad7193/ad7193.c
- drivers/adc/ad7193/ad7193.h
- drivers/adc/ad719x/ad719x.c
- drivers/adc/ad719x/ad719x.h
-reworked AD7193 driver to support AD719X family (AD7190/2/3/4/5)
> AD7193 driver extended to support 0/2/4/5 chips

- drivers/platform/stm32/stm32_gpio.c
MODER register seems to not be present on all stm32 mcu's so
avoid accessing it directly.
This commit changes the gpio_get_direction implementation on stm32
by reading the direction configuration set using the initialization
functions. So it doesn't perform a register access.
Closes #1228
> stm32 gpio: remove MODER access

- drivers/platform/maxim/gpio_extra.h
- drivers/platform/maxim/irq_extra.h
- drivers/platform/maxim/maxim_delay.c
- drivers/platform/maxim/maxim_gpio.c
- drivers/platform/maxim/maxim_irq.c
- drivers/platform/maxim/maxim_rtc.c
- drivers/platform/maxim/maxim_spi.c
- drivers/platform/maxim/maxim_stdio.c
- drivers/platform/maxim/maxim_stdio.h
- drivers/platform/maxim/maxim_uart.c
- drivers/platform/maxim/maxim_uart.h
- drivers/platform/maxim/rtc_extra.h
- drivers/platform/maxim/spi_extra.h
Initial implementation of peripheral drivers for MAX32660 (UART, RTC,
SPI, GPIO and IRQ).
> drivers:platform:maxim Maxim platform drivers

- drivers/adc/ad719x/ad719x.h
Switched from gpio_desc to gpio_init_param.
Signed-off-by:Andrei Porumb <andrei.porumb@analog.com>
> drivers:adc:ad719x: Fix gpio init param

- drivers/platform/mbed/mbed_pwm.cpp
- drivers/platform/mbed/mbed_pwm.h
1. Added functions for pwm_init, pwm period get/set, pwm duty cycle get/set and pwm_remove.
2. Mbed PWM does not support the configuration of PWM polarity and phase as this seems to be low level device specific.
> drivers:platform:mbed: PWM platform drivers implementation

- drivers/platform/stm32/stm32_uart.c
- drivers/platform/stm32/stm32_uart_stdio.c
uart_write() apparently needs to return the number of characters
transmitted for the iio_demo to work.
> fix stm32 uart_write return value

- drivers/adc/ad719x/ad719x.c
- drivers/adc/ad719x/ad719x.h
Previously, the ID mask was set only for the last nibble. AD7195 has a full byte
ID so we need to consider the whole byte. Mask changed to 0xFF for AD7195 case.
> ad719x: Fix ID mask

- drivers/axi_core/jesd204/axi_jesd204_rx.h
- drivers/axi_core/jesd204/axi_jesd204_tx.h
uint8_t cannot accomodate values like 256 which is a valud value
for the JESD K parameter, so increase the storage size to uint16_t.
Related to this EZ thread:
https://ez.analog.com/microcontroller-no-os-drivers/f/q-a/554890/ad9081_fmca_ebz-noos-driver-problem-when-k-is-set-to-256-uint8_t
> jesd frames_per_multiframe uint8_t -> uint16_t

- tools/scripts/stm32.mk
- remove openocd obsolete `tpiu config` command
- remove some makefile comments that were polluting
> Stm32 tpiu

- tools/scripts/xilinx.mk
sdkbuild shouldn't depend on all rule.
> xilinx.mk: remove sdkbuild dependency on all

- drivers/platform/mbed/mbed_uart.cpp
- drivers/platform/mbed/mbed_uart.h
Implemented the UART and USBCDC (VirtualCOM) functionality for Mbed platform to read/write data over serial link.
USBCDC (VCOM) is supported/tested fully on SDP-K1 platform.
> drivers:platform:mbed: UART/VCOM platform drivers implementation

- drivers/platform/maxim/i2c_extra.h
- drivers/platform/maxim/maxim_i2c.c
Add MAX32660 I2C driver allowing for master mode write and read
transactions.
This PR should be merged after https://github.com/analogdevicesinc/no-OS/pull/1207
> drivers:platform:maxim: I2C driver initial commit

- drivers/temperature/max31875/max31875.c
- drivers/temperature/max31875/max31875.h
Add device driver for the MAX31875 device. It allows for quick
initialization and register access using an I2C bus.
More information for the device:
https://datasheets.maximintegrated.com/en/ds/MAX31875.pdf
> drivers:temperature:max31875: initial commit

- drivers/rf-transceiver/ad9361/ad9361_api.c
Implement error checking and return in ad9361_trx_load_enable_fir()
Signed-off-by: Alexander Vickberg <wickbergster@gmail.com>
> drivers:rf-transceiver:ad9361:ad9361_api.c: Add error checking

- include/no-os/util.h
- util/util.c
Add support for 24/32-bit put/get unordered bytes, similar with what we
have on linux.
> util: extend unordered bytes functions

- projects/ad3552r_fmcz/src.mk
If IIO example is not desired the IIO library is not used, but the AD3552R
IIO driver is linked and built. Since the IIO driver for AD3552R depends on
the IIO library, the build throws an error.
> projects:ad3552r_fmcz: add IIO driver conditionally

- drivers/platform/xilinx/xilinx_gpio_irq.c
Before this commit, interrupt callback was executed even if the event
occurred before the interrupt enabling. After this commit, only events which
occur after interrupt enabling will trigger the interrupt.
> Fix xilinx repetitive irq triggering

- drivers/platform/mbed/mbed_timer.cpp
- drivers/platform/mbed/mbed_timer.h
- include/no-os/timer.h
1. Implemented the timer init, timer start, timer stop and timer remove functions.
2. Mbed timer has very limited scope. User can't load the timer with specific value neither can set the
timer frequency as these parameters are dependent upon the low level hardware. The functions such as
timer_clk_get and timer_cnt_get are not supported and implemented in the mbed drivers.
3. New get_elapsed_time_in_nsec() function is created in timer.cpp file to get the elapsed time in nsec
as mbed doesn't have any function to get the elapsed timer count in decimal.
> drivers:platform:mbed: Timer platform driver implementation

- drivers/adc/ad717x/ad717x.c
Added the missing bitwise not operator in clearing the negative analog input
Signed-off-by: Janani Sunil <Janani.Sunil@analog.com>
> drivers:adc:ad717x:bug fix analog input select

- iio/iio_app/iio_app.c
- iio: iio_app: Remove error.h inclusion for all plaforms
- Include error.h only for ADUCM_PLATFORM, XILINX_PLATFORM and LINUX_PLATFORM platforms because for STM32_PLATFORM it generates a compilation error due to redefinition of SUCCESS
> iio: iio_app: Remove error.h inclusion for all plaforms

- drivers/dac/ad9144/ad9144.c
Call to abs() has no effect. Data sheet for AD9144 rev. C pg. 70 says
allowed range is: -180 <= phase < 180.
Signed-off-by: Alexander Vickberg <wickbergster@gmail.com>
> drivers:dac:ad9144:ad9144.c: Fix broken check of NCO phase offset

- drivers/axi_core/iio_axi_adc/iio_axi_adc.c
- drivers/axi_core/iio_axi_dac/iio_axi_dac.c
- drivers/rf-transceiver/ad9361/ad9361.h
- drivers/rf-transceiver/ad9361/iio_ad9361.c
- iio/iio.c
- iio/iio.h
- iio/iio_app/iio_app.c
- iio/iio_app/iio_app.h
- network/linux_socket/linux_socket.c
- projects/ad9361/src/main.c
- projects/ad9361/src/parameters.h
- tools/scripts/generic.mk
- tools/scripts/linux.mk
- util/circular_buffer.c
Hi,
I made a series of patches which fixes a bunch of warnings and enables cross compiling with the generic Makefile:
`no-OS/projects/ad9361$ TINYIIOD="y" PLATFORM="linux" make`
Only warnings left after this series is a couple of
`warning: #warning "TCP socket communication is not secured"`
Only build path tested is projects/ad9361 for Linux.
> RFC: Linux build fixes

- iio/iio.c
- Changes in __iio_str_parse: Given the fact that the received buffer contains data in decimal format, the fractional part should be obtained  using strtol for decimal base. If left as it is, with base 0, a string which contains the first character '0' will be formatted in octal base.
- Changes in iio_parse_value: Added handling for IIO_VAL_FRACTIONAL.
> iio: Changes in __iio_str_parse for fractional part

- drivers/platform/stm32/stm32_hal.h
- drivers/platform/stm32/stm32_uart.c
- drivers/platform/stm32/stm32_uart.h
- iio/iio_app/iio_app.c
- projects/iio_demo/src/app/main.c
- projects/iio_demo/src/app/parameters.h
- tools/scripts/stm32.mk
- open the sdk in background
- patching of the _it.c file (preparation for interrupts)
- stm32_init() common function instead of having the user call SystemClock_Config() and HAL_Init() (& fix broken projects)
- change the way stm32_uart_init_param looks like (& fix broken projects)
> stm32 updates

- drivers/frequency/adf4377/adf4377.h
- projects/adf4377_sdz/src/app/adf4377_sdz.c
Adjust the output amplitude values according to the latest datasheet
version for adf4377.
> adf4377: adjust output amplitude level values

- drivers/frequency/adf4377/adf4377.h
The option was removed from the register map in the latest version of
the datasheet.
> drivers: adf4377: remove MUXOUT_REF_OK

- iio/iio_app/iio_app.c
- iio/iio_types.h
Proposed solution for my issue regarding using iio_app with an existing irq_desc.
If there isn't any existing irq_desc, device.dev_descriptor->irq_desc should be set to NULL.
> Make iio_app accept existing irq_desc

- drivers/platform/mbed/errno.h
The standard "errno.h" file comes with ARMC compiler does not include all the error codes defined
in the "errno.h" file comes with GCC compiler. Some of the error codes used in no-os drivers
are not present in the errno.h file from ARMC compiler. The additional codes are therefore
added in the local errno.h file created inside mbed platform drivers folder based on assumption that
build system will locate this file first and then #include_next will include the standard library
errno.h file.
> drivers:platform:mbed: Error code handling for ARMC compiler

- include/no_os_gpio.h
Added The port member to the GPIO description.
> include:no_os_gpio.h Add port member for GPIOs in the no_os_gpio_desc  and no_os_gpio_init_param structures.

- drivers/amplifiers/ada4250/ada4250.c
- drivers/amplifiers/ada4250/ada4250.h
- projects/ada4250_ardz/src/ada4250_ardz.c
The vlsb and input offset is now represented in nanovolts. The AVDD is now represented in millivolts. This would enable the user to input AVDD in 3.3v and 1.8V.
> drivers: ada4250: offset computation update

- drivers/platform/mbed/mbed_irq.cpp
- drivers/platform/mbed/mbed_irq.h
1. Implemented the IRQ handling for External (GPIO), Ticker and UART Rx IRQs.
2. Callback registration and invokement implementaion is slightly different than the conventional
IRQ platform drivers. Dedicated callback is needed for each IRQ. Callback function in mbed
expects no argument and void return type.
**gpio irq example:**
```
// -------------------------- IRQ callback function ----------------------------------
void ext_int_callback(void *ctx, uint32_t event, void *extra)
{
}
// -------------------------- Platform specific ----------------------------------
/* External interrupt Mbed platform specific parameters */
struct mbed_irq_init_param mbed_ext_int_extra_init_params = {
.int_mode = EXT_IRQ_RISE,
.ext_int_pin = CONV_MON_GPIO,
.int_obj_type = NULL
};
// …
```
> drivers:platform:mbed: IRQ platform drivers implementation

- drivers/accel/adxl355/adxl355.c
- The hpf corner value has to be left shifted 4 times because hpf corner value bits are [6:4] in filter settings reg.
- Even though the hpf settings can be changed when the device is in measurement mode, it has been observed that the measurements are not correct when doing so. Because of this, the device will be set in standby mode also when changing the hpf value.
> ADXL355 fix hpf corner value setting 

- drivers/adc/ad469x/ad469x.c
Fixes mask for the number of active channels when writing the
AD469x_REG_STD_SEQ_CONFIG register.
Fix issue reported at #1294.
Fixes: 0db1a92 ("ad469x: Add channel sequencer implementation")
> drivers: adc: ad469x: fix channel mask

- iio/iio.c
Multiplication with 100000 is only true if only one decimal precision is
used. If the user input more than one decimal precision the resulting
number does not represent micro/nano subdivision anymore.
> iio: fix fractional number interpretation

- drivers/adc-dac/ad5592r/ad5592r.c
- drivers/adc-dac/ad5592r/ad5593r.c
- drivers/adc/ad469x/ad469x.c
- drivers/axi_core/iio_axi_adc/iio_axi_adc.c
- drivers/axi_core/iio_axi_dac/iio_axi_dac.c
- drivers/dac/ad3552r/iio_ad3552r.c
- drivers/platform/aducm3029/adc.c
- include/no_os_util.h
- projects/iio_aducm3029/src/main.c
- util/no_os_util.c
The current hweigth8 function was inconcludent since it was implemented
to support 32-bit size words.
Add separate functions for hweight8/hweigth16/hweight32 similar with the
linux implementation.
Update drivers/projects accordingly.
> util: add proper support for hweigth8/16/32

- drivers/adc/adaq8092/adaq8092.c
- drivers/adc/adaq8092/adaq8092.h
- projects/adaq8092_fmc/src.mk
- projects/adaq8092_fmc/src/adaq8092_fmc.c
Update no-os naming for the platform drivers.
> adaq8092: update no-os functions

- drivers/rf-transceiver/ad9361/ad9361.c
The table contains negative error codes which generates warnings.
https://ez.analog.com/microcontroller-no-os-drivers/f/q-a/556832/compiler-warning-integer-conversion-resulted-in-a-change-of-sign-in-no-os-drivers
> split_gain_table_abs_gain uint8_t -> int8_t

- drivers/gyro/adxrs453/adxrs453.c
Value returned by the register read is actually the result from previous
command.
Reference: #1297 
Fixes: a12fcf7 ("PMODS: Added the DPOT, GYRO2, IA, IOXP and TMP2 demonstration software.")
Signed-off-by: Ryan David <ryandavid773@gmail.com>
> drivers: adxrs453: fix value returned by reg read

- projects/eval-adxl355-pmdz/sdp-ck1z.ioc
- projects/eval-adxl355-pmdz/src/platform/stm32/parameters.h
Add support for UART RX interrupt usage since by default iio_app is using .asynchronous_rx = true.
> projects:eval-adxl355-pmdz: Add support for UART RX interrupt usage

- projects/iio_adpd1080/src/main.c
Increase sample rate in firmware as opposed to pyadi application to work
around IIOD UART bug. This change can be reverted after the IIOD bug is
solved, but will work after that as well and is functionally correct.
> projects:iio_adpd1080: implement sample rate increase

- drivers/platform/mbed/mbed_ain.cpp
- drivers/platform/mbed/mbed_ain_aout.h
- drivers/platform/mbed/mbed_aout.cpp
- include/no_os_ain.h
- include/no_os_aout.h
1. Implemented the Analog Input/Output no-OS header files and added it the include/ directory.
2. Added mbed specific implementation of Analog Input/Output platform drivers.
> drivers:platform:mbed: Analog In/out platform drivers

- drivers/adc/ad713x/ad713x.c
- drivers/adc/ad713x/ad713x.h
- drivers/adc/ad713x/iio_ad713x.c
- drivers/adc/ad713x/iio_ad713x.h
- projects/cn0561/Makefile
- projects/cn0561/builds.json
- projects/cn0561/src.mk
- projects/cn0561/src/README.md
- projects/cn0561/src/cn0561.c
- projects/cn0561/src/parameters.h
Changes this patch:
- add support for AD4134 to the AD713x driver;
- add AD7134/AD4134 IIO driver;
- add cn0561 support for Cora Z7 and Zed board carriers.
> CN0561 example

- drivers/platform/xilinx/xilinx_i2c.c
The removal of the NO_OS_ prefix that was added two times for
the NO_OS_IS_ERR_VALUE macro.
> drivers:platform:xilinx:xilinx_i2c.c NO_OS_ typo correction

- tools/scripts/stm32.mk
For STM32F401xE, the existing regexp was failing because it assumed
the TARGET string should end in xx.
> fix stm32.mk TARGET detection

- iio/iio.c
- iio/iio_types.h
Implemented the changes in no-os IIO library to allow user to set the context attributes and values
from an application code.
> iio: ability to set IIO context attributes from application code

- drivers/platform/stm32/stm32_uart.c
Two possible values may be returned here:
- 0 works ok for our iio implementation, but doesn't play well
with stdio _read which expects negative error code here.
- -EAGAIN works well with both iio and stdio _read expected
return values.
Therefore, use -EAGAIN.
> fix stm32 uart read by returning -EAGAIN

- drivers/platform/aducm3029/aducm3029_irq.c
- drivers/platform/aducm3029/irq_extra.h
- drivers/platform/aducm3029/no_os_rtc.c
- drivers/platform/maxim/maxim_rtc.c
- include/no_os_rtc.h
Use `no_os_` prefix for the device description and initialization
structure.
> rtc: update desc and init param

- iio/iio.c
- iio/iio.h
iio_readdev will always use the following format when -t option is given:
```
SETTRIG <iio_device_id> <iio_trigger_id>
```
Changes have been made such that the SETTRIG command is using the trigger id instead of the trigger name.
The GETTRIG command will still return the name of the trigger.
> iio: Adapt SETTRIG command for libiio readdev usage

- tools/scripts/platform/xilinx/util.tcl
This change replaces the default value assigned by the
auto-generated linker script instead of redefining the HEAP variable.
This commit fixes the file format so it can be interpreted by Vitis's
linker script GUI.
> scripts: util.tcl: Fix HEAP symbol

- drivers/platform/mbed/mbed_delay.cpp
- drivers/platform/mbed/mbed_gpio.cpp
- drivers/platform/mbed/mbed_i2c.cpp
- drivers/platform/mbed/mbed_irq.cpp
- drivers/platform/mbed/mbed_irq.h
- drivers/platform/mbed/mbed_pwm.cpp
- drivers/platform/mbed/mbed_spi.cpp
- drivers/platform/mbed/mbed_uart.cpp
1. Updated the header paths to the correct the no-os header files
2. Updated the mbed_irq_unregister() function prototype to match with irq_platform_ops unregister function pointer.
> drivers:platform:mbed: no-os header path and typo fixes.

- drivers/accel/adxl355/adxl355.c
Add correct measurement unit in function description. Instead of g, the data is returned in m/s^2.
> drivers:accel:adxl355: Add correct measurement unit in description

- drivers/platform/maxim/maxim_uart.c
This change makes the no_os_uart_write to return only when
all the bytes were transmitted. Before this, the function
only blocked until all the bytes were in the TX fifo, which
caused a problem when using a read_nonblocking after the
no_os_uart_write, since that flushes both TX and RX fifos.
Example:
```
uint8_t a[] = "123456789";
no_os_uart_write(uart, a, 9);
// ...
no_os_uart_read_nonblocking(...); // flushes the TX fifo, while just some bytes were transmitted
```
> UART write blocking fix

- drivers/accel/adxl355/adxl355.c
- drivers/accel/adxl355/iio_adxl355.h
- drivers/accel/adxl355/iio_adxl355_trig.c
- iio/iio.c
- iio/iio_types.h
- projects/eval-adxl355-pmdz/src/common/common_data.c
- projects/eval-adxl355-pmdz/src/common/common_data.h
- projects/eval-adxl355-pmdz/src/examples/iio_trigger_example/iio_trigger_example.c
- drivers:accel:adxl355 Moddified return value for error_com label 
- Added doxy comment for is_synchronous field from iio_trigger structure.
- Added null pointer check in iio_adxl355_trigger_init for init_param->iio_desc and init_param->name.
- Added IIO Trigger now support with example on EVAL-ADXL355-PMDZ
> IIO Trigger now support with example on EVAL-ADXL355-PMDZ

- drivers/platform/mbed/mbed_gpio.cpp
- drivers/platform/mbed/mbed_irq.cpp
Updated the function parameters to be passed to the callback function.
Fixed typo in the gpio direction assignment function.
> drivers:platform:mbed: typo fixes.

- build_projects.yml
The current timeout is around 1min and blocks the publishing of the
release artifacts in the releases section.
> build_projects.yml: add specific release timeout

- drivers/filter/admv8818/admv8818.c
- drivers/filter/admv8818/admv8818.h
The ADMV8818-EP is a fully monolithic microwave integrated
circuit (MMIC) that features a digitally selectable frequency of
operation. The device features four independently controlled high-
pass filters (HPFs) and four independently controlled low-pass
filters (LPFs) that span the 2 GHz to 18 GHz frequency range.
Datasheet: https://www.analog.com/en/products/admv8818.html
> drivers:filter: add admv8818 support

- drivers/frequency/adrf6780/adrf6780.c
- drivers/frequency/adrf6780/adrf6780.h
The ADRF6780 is a silicon germanium (SiGe) design, wideband,
microwave upconverter optimized for point to point microwave
radio designs operating in the 5.9 GHz to 23.6 GHz frequency
range.
Datasheet: https://www.analog.com/en/products/adrf6780.html
> drivers: frequency: adrf6780: initial commit
