drivers/AD5676/ad5676.c
drivers/AD5676/ad5676.h

Implementation of AD5676 Driver.

AD5676 driver

---

drivers/ad4110/ad4110.c
drivers/ad4110/ad4110.h

Added terms and conditions text  and other small changes to improve
readability

Added terms and conditions text

---

adaq7980-sdz/adaq7980.c
adaq7980-sdz/adaq7980.h
adaq7980-sdz/adaq7980_sdz.c
adaq7980-sdz/platform_drivers.c
adaq7980-sdz/platform_drivers.h
adaq7980-sdz/spi_engine.c
adaq7980-sdz/spi_engine.h

adaq7980: Initial commit

---

drivers/ad4110/ad4110.c
drivers/ad4110/ad4110.h

Updated to work with the new platform driver and to keep linux coding
style.
Signed-off-by: Andrei Drimbarean <andrei.drimbarean@analog.com>

ad4110: update to new platform driver and coding style

---

common_drivers/xcvr_core/xcvr_core.c
common_drivers/xcvr_core/xcvr_core.h

filalize -> finalize
Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>

xcvr_core: Fix typo

---

ad9361/sw/config.h
ad9361/sw/main.c
ad9361/sw/platform_xilinx/adc_core.c

Extend ADC_DMA_IRQ_EXAMPLE to MicroBlaze.

Ad9361 adc dma

---

drivers/adxl372/adxl372.c
drivers/adxl372/adxl372.h
drivers/adxl372/adxl372_i2c.c
drivers/adxl372/adxl372_spi.c

This series of patches adds support for I2C communication, but also adds a few miscellaneous, no functional changes which should improve readability.

Master adxl372 i2c support

---

Pmods/PmodAD2/AD7991.c
Pmods/PmodDPOT/AD5160.c
ad5766-sdz/ad5766_core.c
ad5766-sdz/spi_engine.c

First set of fixed issues after running cppcheck tool.

Fix issues after running static analysis: part 1

---

ad7616-sdz/spi_engine.c
ad9361/sw/ad9361.c
ad9361/sw/platform_altera/dac_core.c
ad9361/sw/platform_linux/adc_core.c

Second set of fixed issues after running cppcheck tool.

Fix issues after running static analysis: part 2

---

adum7701_fmc/clkgen_core.c
common_drivers/platform_drivers/platform_drivers.c
drivers/adf4350/adf4350.c
drivers/adf4350/adf4350.h
drivers/adgs1408/adgs1408.c
drivers/linux_platform/platform_drivers.c

Fourth set of fixed issues after running cppcheck tool.

Fix issues after running static analysis: part 4

---

LICENSE
LICENSE_ADI_BSD

Add LICENSE files

---

Pmods/PmodCDC1/AD7156.c
ad9361/sw/platform_linux/dac_core.c
ad9361/sw/platform_xilinx/dac_core.c
ad9371/sw/headless.c
adaq7980-sdz/spi_engine.c

Third set of fixed issues after running cppcheck tool.

Fix issues after running static analysis: part 3

---

common_drivers/fru_tools/fru_tools.c
drivers/adxrs453/adxrs453.c
fmcadc5/fmcadc5.c
pzsdr/ccbrk/loopback/loopback.c
pzsdr/ccfmc/loopback/loopback.c

Fifth set of fixed issues after running cppcheck tool.

Fix issues after running static analysis: part 5

---

.travis.yml
CI/travis/before_install_linux
ci/scripts/astyle.sh
ci/scripts/astyle_config
ci/scripts/build_projects.sh
ci/scripts/cppcheck.sh
ci/travis/before_install_darwin
ci/travis/before_install_linux

Checks modified/new source/header files from pull request to determine if they are
properly formatted.
Also, create separate script file for Travis

general: add astyle check to travis

---

drivers/ad5686/ad5686.c
drivers/ad5686/ad5686.h

Fix header comment for set Power-down mode function.

drivers: ad5686: ad5686.c: Fix Header comment

---

common_drivers/xcvr_core/xcvr_core.c
common_drivers/xcvr_core/xcvr_core.h
common_drivers/xcvr_core/xcvr_modules/xilinx_qpll.c
common_drivers/xcvr_core/xcvr_modules/xilinx_qpll.h
common_drivers/xcvr_core/xcvr_modules/xilinx_xcvr_channel.c
common_drivers/xcvr_core/xcvr_modules/xilinx_xcvr_channel.h
fmcdaq3/fmcdaq3.c

- Add Ultrascale and Ultrascale+ support for FMCDAQ3 and by extension to Microblaze projects.
- Fix SPI related bug in the FMCDAQ3 project.
- Do minor refactoring of the code.

FMCDAQ3 Ultrascale Support

---

ad9467-fmc-ebz/ad9467_fmc_ebz.c
ad9467-fmc-ebz/zed/Makefile

Project on master does not work for zed carrier.
Cherry-pick commits from 2018_R1 that solve the problem and do a syntax fix.

ad9467_fmc_ebz merge from 2018_R1

---

.gitignore
ci/scripts/astyle.sh

* Speed-up build-time
* add `build` to `.gitgnore`

astyle: minor updates related to build

---

projects/adrv9009/src/devices/adi_hal/adi_hal.h
projects/adrv9009/src/devices/adi_hal/no_os_hal.c

projects: adrv9009: Implement ADIHAL_writeToLog()

---

ad9361/sw/ad9361.c
ad9361/sw/ad9361.h
ad9361/sw/ad9361_api.c
ad9361/sw/ad9361_api.h

Changes introduced by: https://github.com/analogdevicesinc/linux/commit/8ec38bc1daabd983ac5da35e33d03e0e83c18ebe were missing.

ad9361: Sync no-OS - Linux gain table loading

---

Microchip/PIC32MX320F128H/PmodDA4/Command.c

pmodDA4 - fix array index out of range
Apply astyle on modified file

Minor fixes

---

projects/ad9371/src/devices/adi_hal/common.c
projects/adrv9009/src/devices/adi_hal/no_os_hal.c
projects/drivers/axi_adc_core/axi_adc_core.c
projects/drivers/axi_adc_core/axi_adc_core.h
projects/drivers/axi_dac_core/axi_dac_core.c
projects/drivers/axi_dac_core/axi_dac_core.h
projects/drivers/xilinx_platform/platform_drivers.c
projects/drivers/xilinx_platform/platform_drivers.h

Update common drivers so that they are compatible with ad9361, that will be added later.

Update for ad9361

---

projects/adrv9009/src/devices/adi_hal/parameters.h

According to https://github.com/analogdevicesinc/hdl/commit/0b66b39352171fcab5c60bc23a31278ad89d723e .

projects: adrv9009: Fix SPI selection

---

projects/adrv9009/src/app/headless.c

projects:adrv9009: Fix typo

---

ad713x-fmcz/platform_drivers.c
ad713x-fmcz/platform_drivers.h

Signed-off-by: Istvan Csomortani <istvan.csomortani@analog.com>

ad713x_fmc: Pass init structure by reference

---

drivers/hmc7044/hmc7044.c
drivers/hmc7044/hmc7044.h

hmc7044_read - read device register
hmc7044_remove - release device resources

hmc7044: Extend driver API

---

projects/ad9371/src/devices/adi_hal/common.c

Extend https://github.com/analogdevicesinc/no-OS/commit/0d2fe781d389cae5d160c38db796f98eb9885cf1 .

projects: ad9371: Fix SPI communication

---

drivers/ad5686/ad5686.c
drivers/ad7768/ad7768.c
drivers/ad7768/ad7768.h

drivers: ad5686: Fix compilation error
drivers: ad7768: Update to current platform driver

drivers: ad5686 & ad7768

---

drivers/adc/ad7124/ad7124.c

Refactoring CRC calculation code to meet astyle formatting requirements

Adds STATUS on DATA readback, and fixes issue writing to part after reset

---

drivers/adc/ad7124/ad7124.c

AD7124: Implementation to support STATUS byte appended to ADC DATA register read, taking different approach to #224.

ad7124: add support to read DATA reg with STATUS byte when enabled

---

projects/drivers/xilinx_platform/xilinx_platform_drivers.h

Update header content after file rename.

xilinx_platform: update defs and header comment

---

projects/adrv9009/src/README

projects: adrv9009: Fix README

---

.gitmodules

The library will be used by many no-OS projects soon.

libraries: Add libtinyiiod as submodule

---

ad738x-fmcz/ad738x.c

ad738x: Fix spi_init function

---

projects/ad9361/src/main.c

Add initialization for device structures using `axi_io` wrappers.

ad9361: update main function

---

projects/drivers/util/util.c
projects/drivers/util/util.h

Extend module with functions and macros used in "tinyiiod" project.

util: extend util module.

---

ad9361/sw/ad9361.c
projects/ad9361/src/ad9361.c

ad9361: MCS avoid surplus step

---

projects/adrv9009/src/app/headless.c

Remove remaining wrappers from previous implementations.

projects: adrv9009: remove old wrappers

---

drivers/dac/ad5686/ad5686.c
drivers/dac/ad5686/ad5686.h

While using the ad5686 driver for mbed firmware I added a couple of features and spotted a small bug - please review.

Update ad5686 driver

---

projects/ad9172/Makefile
projects/ad9172/src.mk
projects/ad9208/Makefile
projects/ad9208/src.mk
projects/ad9361/Makefile
projects/ad9361/src.mk
projects/ad9371/Makefile
projects/ad9371/src.mk
projects/adrv9009/Makefile
projects/adrv9009/src.mk
tools/scripts/Makefile
tools/scripts/platform/xilinx/create_project.tcl
tools/scripts/platform/xilinx/read_hdf.tcl

Added Makefile support for the Xilinx platform.

tools: scripts: Added Makefile support

---

drivers/platform/xilinx/irq.c

Add suport for the AXI IRQ controller in the Xilinx platfrom drivers. It is
made in the same form as the I2C driver.
Signed-off-by: Drimbarean <Andrei.Drimbarean@analog.com>

drivers:platform:xilinx: add support for AXI IRQ

---

tools/scripts/Makefile

1) Changed echo to printf
2) Removed language standard specification

tools: scripts: Makefile: Changed echo and languange standard

---

drivers/platform/aducm3029/spi.c
drivers/platform/aducm3029/spi_extra.h

drivers: platform: Add SPI support for ADuCM3029

---

.astyleignore

Add /libraries/fatfs to .astyleignore

---

include/timer.h

Changes in this patch:
- fix variable name and comments in the header file;
- add generic field to the initialization and handler structures.

Timer generic update and fix

---

drivers/platform/xilinx/i2c.c
projects/adrv9009/src/devices/adi_hal/adi_hal.h
projects/adrv9009/src/devices/adi_hal/parameters.h

Fix some comments in preparation for Doxygen integration.

Fix header comments

---

drivers/platform/aducm3029/spi.c
drivers/platform/aducm3029/spi_extra.h
drivers/platform/altera/gpio.c
drivers/platform/altera/i2c.c
drivers/platform/altera/spi.c
drivers/platform/generic/i2c.c
drivers/platform/generic/spi.c
drivers/platform/linux/platform_drivers.c
drivers/platform/xilinx/gpio.c
drivers/platform/xilinx/irq.c
drivers/platform/xilinx/spi.c

Fix header comments for Doxygen integration.

platform: fix comments

---

projects/ad9361/src/ad9361.c
projects/ad9361/src/ad9361_api.c
projects/ad9361/src/ad9361_parameters.h
projects/ad9361/src/ad9361_util.c
projects/ad9361/src/ad9361_util.h
projects/ad9371/profiles/tx_bw100_orx_bw100_rx_bw100/myk.h
projects/ad9371/profiles/tx_bw100_orx_bw100_rx_bw40/myk.h
projects/ad9371/profiles/tx_bw200_orx_bw200_rx_bw100/myk.h
projects/ad9371/src/app/myk.h
projects/ad9371/src/devices/ad9528/ad9528.c
projects/ad9371/src/devices/adi_hal/parameters.h
projects/adv7511/ac701/transmitter.c
projects/adv7511/kc705/transmitter.c
projects/adv7511/vc707/transmitter.c
projects/adv7511/zc702/transmitter.c
projects/adv7511/zc706/transmitter.c
projects/adv7511/zed/transmitter.c

Fix comments for Doxygen integration.

 projects: fix Doxygen comments

---

iio/iio_app/iio_app.c

Remove unnecessary dependency "parameters.h"

iio_app: Remove unnecessary header.

---

include/delay.h
include/error.h
include/fifo.h
include/gpio.h
include/i2c.h
include/irq.h
include/spi.h
include/timer.h
include/uart.h
include/xml.h

1. Add type comments for structs/enums using the decided format.
2. Add brief description for all files.

include: update header files for doxygen integration

---

drivers/adc/ad6673/ad6673.h
drivers/adc/ad9250/ad9250.h
drivers/dac/ad5755/ad5755.h
drivers/dac/ad9739a/ad9739a.h
drivers/frequency/ad9523/ad9523.h
drivers/frequency/ad9528/ad9528.h
drivers/frequency/adf4106/adf4106.h
drivers/frequency/adf4153/adf4153.h
drivers/platform/aducm3029/spi_extra.h
drivers/platform/altera/gpio_extra.h
drivers/platform/altera/i2c_extra.h
drivers/platform/altera/spi_extra.h
drivers/platform/xilinx/gpio_extra.h
drivers/platform/xilinx/i2c_extra.h
drivers/platform/xilinx/irq_extra.h
drivers/platform/xilinx/spi_extra.h
drivers/platform/xilinx/uart_extra.h

Add/update types documentation for Doxygen integration using the appropriate format.

Drivers: add support for Doxygen types format

---

drivers/accel/adxl345/adxl345.h
drivers/accel/adxl362/adxl362.h

Add types documentation for the following drivers:
1. adxl345
2. adxl362

drivers: accel: update types doc

---

doc/CMakeLists.txt
doc/license_page.dox
doc/mainpage.dox

Update License statement on the main page of no-OS repository
documentation.

doxy: mainpage: update license

---

projects/adrv9009/src/app/headless.c

gpio_get API changed and the code was adapted to this change

Fix adrv9009 DMA example

---

projects/ad9361/src.mk
projects/ad9361/src/ad9361.c
projects/ad9361/src/ad9361_api.c
projects/ad9361/src/ad9361_conv.c
projects/ad9361/src/ad9361_util.h
projects/ad9361/src/app_config.h
projects/ad9361/src/main.c
projects/ad9371/src/app/app_config.h
projects/adrv9009/src/app/app_config.h

- ad9361 rename config file
- add IIO_EXAMPLE macro to config 

projects: config files update

---

iio/iio_ad9361/iio_ad9361.c
iio/iio_axi_adc/iio_axi_adc.c
projects/ad9361/src/common.h

iio: Remove warnings caused when building with make

---

drivers/platform/linux/axi_io.c

Implementation of AXI IO through UIO.

drivers: platform: linux: Add axi_io implementation

---

iio/iio_app/iio_axi_adc_app.c
iio/iio_app/iio_axi_adc_app.h
iio/iio_app/iio_axi_dac_app.c
iio/iio_app/iio_axi_dac_app.h
iio/iio_types.h
projects/ad9361/src/main.c
projects/ad9371/src/app/headless.c
projects/adrv9009/src/app/headless.c

Remove platform dependencies, add some comments.

Iio updates

---

ci/travis/gen_dox.sh

ci: travis: gen_dox: fix typo

---

drivers/axi_core/spi_engine/spi_engine.c
drivers/axi_core/spi_engine/spi_engine.h
drivers/axi_core/spi_engine/spi_engine_private.h
drivers/platform/xilinx/spi.c

Added platform-agnostic spi engine inside xilinx platform drivers.

drivers: axi: Add platform agnostic spi engine

---

projects/ad9371/src/app/headless.c

Print correct device structure names.

projects: ad9371: fix typos

---

drivers/platform/aducm3029/timer.c
drivers/platform/aducm3029/uart_extra.h
drivers/platform/generic/timer.c
util/fifo.c

Each fix description if found in its own commit.

Small fixes mixed in one pull request

---

drivers/platform/aducm3029/spi.c
drivers/platform/aducm3029/spi_extra.h
drivers/sd-card/sd.c
drivers/sd-card/sd.h

This drivers will be used in the smoke detector application an this improvements where needed.
More details in each commit message.

Improvements in sd_card and spi

---

include/list.h
util/list.c

This library offer support for store data. This will be useful
in the future to remove the complexity of drivers/applications
to handle data structures
You can also check the documentation at:
https://mchindri.github.io/no-OS/list_8h.html

 util: Add list library

---

drivers/platform/xilinx/gpio.c

1. Add implementation for `gpio_get_direction`
2. Fix `gpio_input_direction` function 
3. Replace `FALSE` macro with `FAILURE`

Xilinx: gpio: updates & fixes

---

drivers/platform/xilinx/i2c.c

The list utility can be used for the I2C driver to manage the initialized
cores table easier.

drivers:platform:xilinx: use list util for I2C driver

---

drivers/platform/altera/gpio.c

Add implementation for `gpio_remove` and `gpio_get_value`.
Move implementation of `gpio_direction_output` to `gpio_set_value`. The
current implementation only sets the gpio value, while the information
regarding the direction of the gpio is contained in the `base_address`.
The `gpio_set_value` is called inside `gpio_direction_output` to avoid
errors within the projects that are using these functions.

altera: gpio: update driver

---

drivers/platform/aducm3029/timer.c

Enable timer to set_counter_value even if it is running.
This is needed in order not to stop the timer when a new
load value is need to be loaded

drivers: platform: aducm: timer: Small feature

---

drivers/platform/xilinx/uart.c

By directly reading/writing the STATUS and FIFO registers.

drivers: xilinx: uart: Improve XUARTLITE read/write speed

---

.astyleignore
network/application/MQTT_eclipse_paho/MQTTClient.c
network/application/MQTT_eclipse_paho/MQTTClient.h
network/application/MQTT_eclipse_paho/MQTTConnect.h
network/application/MQTT_eclipse_paho/MQTTConnectClient.c
network/application/MQTT_eclipse_paho/MQTTConnectServer.c
network/application/MQTT_eclipse_paho/MQTTDeserializePublish.c
network/application/MQTT_eclipse_paho/MQTTFormat.c
network/application/MQTT_eclipse_paho/MQTTFormat.h
network/application/MQTT_eclipse_paho/MQTTPacket.c
network/application/MQTT_eclipse_paho/MQTTPacket.h
network/application/MQTT_eclipse_paho/MQTTPublish.h
network/application/MQTT_eclipse_paho/MQTTSerializePublish.c
network/application/MQTT_eclipse_paho/MQTTSubscribe.h
network/application/MQTT_eclipse_paho/MQTTSubscribeClient.c
network/application/MQTT_eclipse_paho/MQTTSubscribeServer.c
network/application/MQTT_eclipse_paho/MQTTUnsubscribe.h
network/application/MQTT_eclipse_paho/MQTTUnsubscribeClient.c
network/application/MQTT_eclipse_paho/MQTTUnsubscribeServer.c
network/application/MQTT_eclipse_paho/StackTrace.h

Also remove it from astyleignore

Add MQTT paho to network/application/MQTT_eclipse_paho

---

drivers/platform/aducm3029/irq.c
drivers/platform/aducm3029/irq_extra.h
drivers/platform/aducm3029/rtc.c
drivers/platform/aducm3029/rtc_extra.h
include/rtc.h

This pull request adds the RTC header to define the RTC driver API and adds RTC support for the ADuCM3029 platform. Add driver implementation as well as interrupt support for the driver.

RTC platform driver

---

include/mqtt_client.h
network/application/MQTT_eclipse_paho/MQTTClient.h
network/application/MQTT_eclipse_paho/mqtt_noos_support.c
network/application/MQTT_eclipse_paho/mqtt_noos_support.h
network/application/mqtt_client.c

- These pull request is a wrapper over MQTTClient-C from https://www.eclipse.org/paho/clients/c/embedded/
- These layer will be used over the TCP_socket layer so until 
https://github.com/analogdevicesinc/no-OS/pull/549 is merged it will be kept as a draft pull request.
- The file mqtt_example.c serves as usage example and it will be removed before merge.
- After the network folder structure is decided the folder MQTT_eclispe_paho should be removed 
from doxygen and astyle checks.

MQTT noos implementation

---

include/tcp_socket.h
include/wifi.h
network/network_interface/network_interface.h
network/transport/tcp_socket.c

Splitted from Splitted from https://github.com/analogdevicesinc/no-OS/pull/549

Network interface and tcp socket implementation

---

projects/fmcjesdadc1/src/devices/ad9250/ad9250.c
projects/fmcjesdadc1/src/devices/ad9250/ad9250.h
projects/fmcjesdadc1/src/devices/ad9517/ad9517.c
projects/fmcjesdadc1/src/devices/ad9517/ad9517.h

Update fmcjesdadc1 project specific drivers to the latest platform
drivers used.

fmcjesdadc1: update specific drivers

---

include/clk.h
util/clk.c

util: Update generic clock layer to support > ~4.29 GHz rates

---

network/data_link/at_params.h
network/data_link/at_parser.c
network/data_link/at_parser.h
network/data_link/wifi.c

Splitted from https://github.com/analogdevicesinc/no-OS/pull/549

Wifi implementation.

---

drivers/frequency/hmc7044/hmc7044.c
drivers/frequency/hmc7044/hmc7044.h

Corresponding Linux version: https://github.com/analogdevicesinc/linux/blob/master/drivers/iio/frequency/hmc7044.c

Add HMC7043 support

---

projects/ad9081/src.mk
projects/ad9172/src.mk
projects/ad9172/src/README
projects/ad9208/src.mk
projects/ad9208/src/README
projects/ad9361/src.mk
projects/ad9371/src.mk
projects/ad9371/src/README
projects/adrv9009/src.mk
projects/adrv9009/src/README
projects/fmcadc2/src.mk
projects/fmcadc2/src/README
projects/fmcadc5/src.mk
projects/fmcdaq2/src.mk
projects/fmcdaq2/src/README
projects/fmcdaq3/src.mk
projects/fmcdaq3/src/README
projects/fmcjesdadc1/src.mk
projects/fmcjesdadc1/src/README

Update Makefiles and README files to support the new SPI structure.
**NOTE**: PR dependent on #577 

projects: update README & Makefiles

---

projects/ad9081/src.mk
projects/ad9172/src.mk
projects/ad9172/src/README
projects/ad9208/src.mk
projects/ad9208/src/README
projects/ad9361/src.mk
projects/ad9371/src.mk
projects/ad9371/src/README
projects/adrv9009/src.mk
projects/adrv9009/src/README
projects/fmcadc2/src.mk
projects/fmcadc2/src/README
projects/fmcadc5/src.mk
projects/fmcdaq2/src.mk
projects/fmcdaq2/src/README
projects/fmcdaq3/src.mk
projects/fmcdaq3/src/README
projects/fmcjesdadc1/src.mk
projects/fmcjesdadc1/src/README

Reverts analogdevicesinc/no-OS#580

Revert "projects: update README & Makefiles"

---

drivers/platform/aducm3029/trng.c
drivers/platform/generic/trng.c
include/trng.h

Add interface for TRNG and ADUCM implementation. 
This will be needed by TLS socket.

True Random Number Generator support

---

drivers/frequency/ad9517/ad9517.c

1. Update device initialization
2. Fix write operation for LVPECL

Ad9517 update

---

drivers/axi_core/axi_dmac/axi_dmac.c

fix adc_dmac_transfer being stuck when size is 0

---

include/tcp_socket.h
network/transport/tcp_socket.c

Add support for TLS communication over TCP socket using mbedtls

tcp_socket: Add secure tcp_socket implementation

---

drivers/platform/aducm3029/uart.c

The dfp is able to read or write 1024 bytes in each transaction.
With this commit, uart_read and uart_write will run multiple transactions
if bytes_number is bigger than 1024

drivers:platform:aducm3029: Uart read and write more than 1024

---

.gitignore
libraries/fatfs/Makefile
projects/aducm_blinky_example/Makefile
projects/aducm_blinky_example/app_src/blinky_example.c
projects/aducm_blinky_example/pinmux_config.c
projects/aducm_blinky_example/src.mk
tools/scripts/aducm.mk
tools/scripts/platform/aducm3029/startup_ADuCM3029_patch.c
tools/scripts/platform/aducm3029/system.rteconfig

This PR will be a draft until libraries support is added.
Because the makefile can be run both on windows and linux a separated file was created to don't duplicate the code.
There is also a proposed src.mk in the project directory with an approach that can be used in further projects.

Aducm makefile

---

projects/fmcjesdadc1/src/README

Fix path for demux_spi source files.

fmcjesdadc1: README: minor fix

---

tools/scripts/aducm.mk

- Fix library linking
- Build libraries before creating a project

Small aducm Makefile fixes

---

drivers/axi_core/spi_engine/spi_engine.c
drivers/axi_core/spi_engine/spi_engine.h
drivers/platform/xilinx/spi_extra.h
drivers/platform/xilinx/xilinx_spi.c
projects/ad713x_fmcz/src/ad713x_fmc.c

This will allow using it on different platforms. Update related project.

spi_engine: Remove SPI engine platform dependency.

---

drivers/axi_core/spi_engine/spi_engine.c
drivers/axi_core/spi_engine/spi_engine.h
drivers/platform/xilinx/spi_extra.h
drivers/platform/xilinx/xilinx_spi.c
projects/ad713x_fmcz/src/ad713x_fmc.c

This reverts commit aa9c6436fddd23e9751918aba28e570bccae2be4.

Revert "spi_engine: Remove SPI engine platform dependency."

---

drivers/adc/ad9081/ad9081.c
drivers/adc/ad9081/api/adi_ad9081.h
drivers/adc/ad9081/api/adi_ad9081_adc.c
drivers/adc/ad9081/api/adi_ad9081_bf_ad9081.h
drivers/adc/ad9081/api/adi_ad9081_bf_impala_tc.h
drivers/adc/ad9081/api/adi_ad9081_bf_jrxa_des.h
drivers/adc/ad9081/api/adi_ad9081_bf_jtx_dual_link.h
drivers/adc/ad9081/api/adi_ad9081_bf_jtx_qbf_ad9081.h
drivers/adc/ad9081/api/adi_ad9081_bf_lcpll_28nm.h
drivers/adc/ad9081/api/adi_ad9081_bf_main.h
drivers/adc/ad9081/api/adi_ad9081_bf_nb_coarse_nco.h
drivers/adc/ad9081/api/adi_ad9081_bf_nb_ddc_dformat.h
drivers/adc/ad9081/api/adi_ad9081_bf_nb_fine_nco.h
drivers/adc/ad9081/api/adi_ad9081_bf_rx_paging.h
drivers/adc/ad9081/api/adi_ad9081_bf_ser_phy.h
drivers/adc/ad9081/api/adi_ad9081_bf_spi_only_up.h
drivers/adc/ad9081/api/adi_ad9081_config.h
drivers/adc/ad9081/api/adi_ad9081_dac.c
drivers/adc/ad9081/api/adi_ad9081_device.c
drivers/adc/ad9081/api/adi_ad9081_hal.c
drivers/adc/ad9081/api/adi_ad9081_hal.h
drivers/adc/ad9081/api/adi_ad9081_jesd.c
drivers/adc/ad9081/api/adi_cms_api_common.h
drivers/adc/ad9081/api/adi_cms_api_config.h

drivers: adc: ad9081: Update API Version to 1.0.4

---

libraries/iio/Makefile

Last commit is relevant.
On top of https://github.com/analogdevicesinc/no-OS/pull/657

1.1 Add Iio makefile

---

tools/scripts/aducm.mk

Only last commit relevant.
Built on top of #657

2 - tools:scripts:aducm.mk: Add support for new iio library

---

drivers/adc/ad717x/ad717x.c
drivers/adc/ad717x/ad717x.h

Mention all supported ad411x devices in the comments.

drivers:adc:ad717x: update to mention all ad411x devices

---

iio/iio_demo/iio_demo.c
iio/iio_demo/iio_demo.h
projects/iio_demo/pinmux_config.c
projects/iio_demo/src/app_config.h
projects/iio_demo/src/main.c
projects/iio_demo/src/parameters.h

Build on top of: #657 
Just last 2 commit are relevant. The others are from the other pull request.

3 - Aducm support for iio_demo

---

iio/iio_app/iio_app.c
iio/iio_app/iio_app.h
iio/iio_demo/iio_demo.c
libraries/iio/iio.c
libraries/iio/iio.h

Only last commit is relevant.
will be rebased when https://github.com/analogdevicesinc/no-OS/pull/657 after is merged

4 - Change refrence from tiniyiiod to iio_desc

---

libraries/iio/iio.c
libraries/iio/iio.h
libraries/iio/iio_types.h
projects/iio_demo/src/main.c

See last commit only
Built on top of: #664

5 - libraries:iio: Move server_ops inside iio

---

iio/iio_demo/iio_demo.c
iio/iio_demo/iio_demo.h
libraries/iio/iio.c
projects/iio_demo/src/main.c

Only last commit is relevant
Built on top of: #666

6 - iio:libraries: Replace iio_interfaces with list

---

iio/iio_demo/iio_demo.c
libraries/iio/iio.c
libraries/iio/iio.h
libraries/iio/iio_types.h

Built on top of: https://github.com/analogdevicesinc/no-OS/pull/670
Last 2 commits relevant

7 -  libraries:iio: Generate xml from iio_interface 

---

network/wifi/at_params.h
network/wifi/at_parser.c
network/wifi/wifi.c
network/wifi/wifi.h

These are some changes that are needed by #698 but can be merged separately
- Add wifi_get_ip function
- Fix AT_SET_SERVER command
- At wifi init set esp8266 to work as an client (hotspot is the default on some at_firmwares)

wifi: small changes

---

iio/iio_demo/iio_demo.c
libraries/iio/iio.c
libraries/iio/iio.h
libraries/iio/iio_types.h

I couldn't reopen #702 
Here are the commit from #702 and some iio fixes

8 - iio small changes

---

iio/iio_demo/iio_demo.c
iio/iio_demo/iio_demo.h
libraries/iio/iio.c
projects/iio_demo/src/main.c

Small libraries:iio fixes

---

network/network_interface.h
network/tcp_socket.c
network/tcp_socket.h
network/wifi/at_parser.c
network/wifi/wifi.c

This functions will be used to implement network backend for iio.
**Last 1 commits** are related to this PR. The first ones will are from #694  and #696

iio_wifi_backend 3: Add function for use tcp_socket as server

---

libraries/iio/iio.c
libraries/iio/iio.h
projects/iio_demo/src/app_config.h
projects/iio_demo/src/main.c
projects/iio_demo/src/parameters.h

- Add iio network support using tcp_socket
- Add network support on iio_demo
**Last 2 commits** are relevant
Will be rebased when network commits are merged

iio_wifi_backend 4: Iio network support in iio and iio_demo

---

projects/iio_demo/src/main.c

Fix minor typo in the main iio demo app.

projects: iio_demo: fix typo

---

drivers/adc/ad9656/ad9656.c
drivers/adc/ad9656/ad9656.h

Added driver for the ad9656 chip.

ad9656:Add driver for ad9656 chip

---

drivers/dac/ad9144/ad9144.c

Ad9144 fixes

---

drivers/adc/ad7124/ad7124.c
drivers/adc/ad7124/ad7124.h
projects/ad7124-4sdz/Makefile
projects/ad7124-4sdz/src.mk
projects/ad7124-4sdz/src/ad7124-4sdz.c

Ad7124 4sdz

---

drivers/axi_core/spi_engine/spi_engine.c
drivers/axi_core/spi_engine/spi_engine.h

Spi engine fix

---

include/pwm.h

pwm.h: Add header interface for PWM generator.

---

projects/adv7511/src.mk

projects: adv7511: fix makefile

---

projects/iio_demo/Makefile
projects/iio_demo/src.mk
tools/scripts/aducm.mk
tools/scripts/generic.mk
tools/scripts/generic_variables.mk
tools/scripts/linux.mk
tools/scripts/src_model.mk

This approach will remove the need of add a new src.mk file.
Sources can be configuret directly from the Makefile

tools:script: suggestion for more generic makefile

---

drivers/platform/linux/linux_gpio.c

... until gpio_remove() is called.

drivers: platform: linux: gpio: Keep direction/value files opened

---

projects/iio_demo/src.mk
tools/scripts/linux.mk

The result can be seen here:
iio.h and iio_types.h can be opened from here

More iio fixes

---

projects/ad9361/src.mk

projects: ad9361: Remove unused source/header files

---

tools/scripts/linux.mk

Some compiler flags and libraries where not added to the project.
No it can build.

iio_demo: Fix xilinx sdk project build

---

tools/scripts/linux.mk

This will fix the build problem for the moment but an other more generic aproach is needed.
Signed-off-by: Mihail Chindris <Mihail.Chindris@analog.com>

tools:scripts:linux.mk: Temporary fix for last makefile commit

---

drivers/dac/ad9144/ad9144.c
drivers/dac/ad9144/ad9144.h

Add nco frequency control for ad9144

Ad9144 nco

---

drivers/adc/ad7768-1/ad77681.c
drivers/frequency/ad9517/ad9517.c

Drivers fixes

---

drivers/adc/ad9081/ad9081.c
drivers/adc/ad9081/api/adi_ad9081.h
drivers/adc/ad9081/api/adi_ad9081_adc.c
drivers/adc/ad9081/api/adi_ad9081_config.h
drivers/adc/ad9081/api/adi_ad9081_dac.c
drivers/adc/ad9081/api/adi_ad9081_device.c
drivers/adc/ad9081/api/adi_ad9081_hal.c
drivers/adc/ad9081/api/adi_ad9081_hal.h
drivers/adc/ad9081/api/adi_ad9081_jesd.c
drivers/platform/xilinx/xilinx_spi.c
include/spi.h

Add SPI LSB_FIRST support for AD9081 and update its API to version 1.0.5.

AD9081 updates

---

ad9361/sw/ad9361.c

Bring AD9361 driver in sync with the Linux version.

AD9361 fixes

---

drivers/platform/linux/linux_i2c.c

drivers: platform: linux: i2c: Add generic interface support

---

drivers/rf-transceiver/ad9361/ad9361.c
drivers/rf-transceiver/ad9361/ad9361_api.c
projects/ad7768-evb/src/ad7768_evb.c

Fixes related to the TravisCI Doxygen build.

Doxygen fixes

---

iio/iio_ad9361/iio_ad9361.c
iio/iio_axi_adc/iio_axi_adc.c
iio/iio_axi_dac/iio_axi_dac.c
projects/ad9361/src/main.c

IIo load buffer, switch to DDS fix

Iio ch indexing

---

.cppcheckignore
.travis.yml
ci/travis/cppcheck.sh
drivers/platform/aducm3029/timer.c
drivers/platform/xilinx/xilinx_spi.c

Travis update and related fixes

---

iio/iio_demo/demo_dev.c
iio/iio_demo/demo_dev.h
iio/iio_demo/iio_demo_dev.h
libraries/iio/iio.c
libraries/iio/iio.h
libraries/iio/iio_types.h
projects/ad713x_fmcz/src/ad713x_fmc.c
projects/ad9081/src/app_iio.c
projects/ad9172/src/app_iio.c
projects/ad9361/src/main.c
projects/ad9371/src/app/headless.c
projects/ad9467/src/app/app_iio.c
projects/adrv9001/src/app/app_iio.c
projects/adrv9009/src/app/headless.c
projects/fmcadc2/src/app/app_iio.c
projects/fmcadc5/src/app/app_iio.c
projects/fmcdaq2/src/app/app_iio.c
projects/fmcdaq3/src/app/app_iio.c
projects/fmcjesdadc1/src/app/app_iio.c
projects/iio_demo/src/main.c

For the moment iio_demo was updated.
Updates to axi and project will come

iio: add easy support for buffers

---

drivers/axi_core/axi_adc_core/axi_adc_core.c
drivers/axi_core/axi_adc_core/axi_adc_core.h
iio/iio_axi_adc/iio_axi_adc.c
iio/iio_axi_adc/iio_axi_adc.h
projects/ad9081/src/app.c
projects/ad9081/src/app_iio.c
projects/ad9361/src/main.c
projects/ad9371/src/app/headless.c
projects/ad9467/src/app/ad9467_fmc.c
projects/ad9467/src/app/app_iio.c
projects/adrv9001/src/app/app_iio.c
projects/adrv9001/src/app/headless.c
projects/adrv9009/src/app/headless.c
projects/fmcadc2/src/app/app_iio.c
projects/fmcadc2/src/app/fmcadc2.c
projects/fmcadc5/src/app/app_iio.c
projects/fmcadc5/src/app/fmcadc5.c
projects/fmcdaq2/src/app/app_iio.c
projects/fmcdaq2/src/app/fmcdaq2.c
projects/fmcdaq3/src/app/app_iio.c
projects/fmcdaq3/src/app/fmcdaq3.c
projects/fmcjesdadc1/src/app/app_iio.c
projects/fmcjesdadc1/src/app/fmcjesdadc1.c

Update axi adc to new buffer functions

---

projects/ad9361/src/main.c

Ad9361 fix

---

projects/ad400x-fmcz/src.mk
projects/ad469x_fmcz/src.mk
projects/ad5766-sdz/src.mk
projects/ad7124-4sdz/src.mk
projects/ad713x_fmcz/src.mk
projects/ad738x_fmcz/src.mk
projects/ad7768-1fmcz/src.mk
projects/ad9081/src.mk
projects/ad9172/src.mk
projects/ad9208/src.mk
projects/ad9361/src.mk
projects/ad9371/src.mk
projects/ad9467/src.mk
projects/ad9656_fmc/src.mk
projects/adaq7980_sdz/src.mk
projects/adrv9009/src.mk
projects/adv7511/src.mk
projects/fmcadc2/src.mk
projects/fmcadc5/src.mk
projects/fmcdaq2/src.mk
projects/fmcdaq3/src.mk
projects/fmcjesdadc1/src.mk
tools/scripts/aducm.mk
tools/scripts/generic.mk
tools/scripts/generic_variables.mk
tools/scripts/libraries.mk
tools/scripts/platform/xilinx/build_project.tcl
tools/scripts/src_model.mk
tools/scripts/xilinx.mk

This is the same as https://github.com/analogdevicesinc/no-OS/pull/798 (Closed by mistake and can't reopen)
V2:
- Split changes in multiple commits
- Fix https://github.com/analogdevicesinc/no-OS/pull/798#issuecomment-725267643

Xilinx makefile improvements [UPDATED]

---

iio/iio_axi_dac/iio_axi_dac.c
iio/iio_axi_dac/iio_axi_dac.h
projects/ad9081/src/app.c
projects/ad9081/src/app_iio.c
projects/ad9172/src/app_iio.c
projects/ad9172/src/main.c
projects/ad9361/src/main.c
projects/ad9371/src/app/headless.c
projects/adrv9001/src/app/app_iio.c
projects/adrv9001/src/app/headless.c
projects/adrv9009/src/app/headless.c
projects/fmcdaq2/src/app/app_iio.c
projects/fmcdaq2/src/app/fmcdaq2.c
projects/fmcdaq3/src/app/app_iio.c
projects/fmcdaq3/src/app/fmcdaq3.c

Similar to https://github.com/analogdevicesinc/no-OS/pull/838 but for DAC
Tested with ad9361 project

Update axi dac to new buffer functions

---

projects/ad9739a-fmc-ebz/src.mk
projects/ad9739a-fmc-ebz/src/ad9739a_fmc_ebz.c
projects/ad9739a-fmc-ebz/src/app_config.h
projects/ad9739a-fmc-ebz/src/app_iio.c
projects/ad9739a-fmc-ebz/src/app_iio.h

Allow the user to read/write via UART using IIO Osc.

projects: ad9739a: add IIO Support

---

tools/scripts/aducm.mk
tools/scripts/generic.mk
tools/scripts/xilinx.mk

The output will be more similar to the old one:

Makefile verbose fix

---

projects/fmcdaq2/src/app/fmcdaq2.c

- change DMA flags
- perform Cache Flush

projects: daq2: DMA related fixes

---

projects/ad7768-evb/src.mk
projects/ad7768-evb/src/ad7768_evb.c
projects/ad7768-evb/src/app_iio.c
projects/ad7768-evb/src/app_iio.h
projects/ad7768-evb/src/parameters.h

- Create `parameters.h` header file
- Add IIO support
- Fix code style issues

projects: ad7768-evb: add IIO support & other minor updates

---

drivers/platform/linux/axi_io.c

"busybox devmem" is a tool that can be used to read/write from physical address.
The patch extends the linux/axi_io.c implementation to use this tool as needed
instead of a UIO device.
This feature can be enabled by defining a DEVMEM symbol (e.g., "-DDEVMEM").
Note: "busybox" package is mandatory to be present(e.g., "apt-get install busybox").

drivers: linux: axi_io: Add busybox devmem support

---

.travis.yml
azure-pipelines.yml
ci/travis/astyle.sh
ci/travis/doxygen.sh
ci/travis/gen_dox.sh
ci/travis/lib.sh
ci/travis/run_build.sh
drivers/platform/linux/axi_io.c

The Github docs requires a bit more testing, since it's a special job that requires to be run on the master branch.
All others seem to work fine.
Fixed a cppcheck null de-ref warning.

ci: migrate build to Azure Pipelines

---

azure-pipelines.yml
ci/travis/doxygen.sh
ci/travis/run_build.sh
doc/Doxyfile.in
drivers/platform/stm32/stm32_delay.c
drivers/platform/stm32/stm32_gpio.c
drivers/platform/stm32/stm32_gpio.h
projects/ad6676-ebz/src/app_config.h

Fix doxygen build within Azure-Pipelines.

azure-pipelines: fix doxygen

---

ci/travis/doxygen.sh

Required for pushing new commits on gh-pages branch.

ci: doxygen: add git credential

---

README.md

README: Add Azure-Pipelines Badge

---

drivers/ecg/adas1000/adas1000.c
drivers/ecg/adas1000/adas1000.h

Reference: https://wiki.analog.com/resources/tools-software/uc-drivers/renesas/adas1000

drivers: adas1000: initial commit

---

projects/ad7124/Makefile
projects/ad7124/pinmux_config.c
projects/ad7124/src.mk
projects/ad7124/src/ad7124_regs.c
projects/ad7124/src/ad7124_regs.h
projects/ad7124/src/app_config.h
projects/ad7124/src/main.c
projects/ad7124/src/parameters.h

Add example project with iio_ad7124.

projects:iio_ad7124: example project

---

projects/ad7124/src/main.c

Minor doxygen fix for build issue propagated on master branch.

projects: ad7124: fix doxygen build

---

drivers/adc/ad7124/iio_ad7124.c
drivers/adc/ad7768-1/ad77681.c
drivers/adc/ad9081/ad9081.c
drivers/platform/aducm3029/iio_aducm3029.c

Small fixes to help with azure checks.

Azure fix [DRAFT]

---

libraries/iio/iio.c
projects/adxrs290-pmdz/src.mk
projects/iio_demo/src.mk
tools/scripts/aducm.mk
tools/scripts/altera.mk
tools/scripts/generic.mk
tools/scripts/stm32.mk
tools/scripts/xilinx.mk

I spitted the changes as much as I could.
I tested them only together and that's way there are all in one PR. 
This is how the build directory will look like:
It will be easy to find sources for both standalone and linked files.

Make standalone

---

drivers/impedance-analyzer/ad5933/ad5933.c
drivers/impedance-analyzer/ad5933/ad5933.h

V2: 
- Added ad5933_get_data function
- Fixed style inconsistencies
- Added null pointer checks
- Rolled back radToDeg180ovPi and M_PI definitions

Ad5933 feature update

---

tools/scripts/aducm.mk
tools/scripts/generic.mk

A couple of fixes for Windows building.

Aducm makefile flags fix

---

build_projects.yml

This pipeline will use a localpool to build noos projects

Set up CI for build projects

---

drivers/dac/ad5791/ad5791.c
drivers/dac/ad5791/ad5791.h
drivers/dac/ad5791/iio_ad5791.c
drivers/dac/ad5791/iio_ad5791.h
projects/cn0531/Makefile
projects/cn0531/pinmux_config.c
projects/cn0531/src.mk
projects/cn0531/src/app_config.h
projects/cn0531/src/main.c
projects/cn0531/src/parameters.h

Add first draft of IIO driver for ad5791 and example IIO project for cn0531, the PMOD using ad5791.

CN0531 IIO development

---

drivers/adc/ad7799/iio_ad7799.c
drivers/adc/ad7799/iio_ad7799.h
drivers/adc/ad9680/iio_ad9680.c
drivers/dac/ad5791/iio_ad5791.c
drivers/dac/ad5791/iio_ad5791.h
drivers/dac/ad9144/iio_ad9144.c
drivers/dac/ad9152/iio_ad9152.c
drivers/platform/aducm3029/iio_aducm3029.c
drivers/platform/aducm3029/iio_aducm3029.h

Move global variable definition from header files to sources in IIO drivers.

IIO drivers header update

---

drivers/adc/adc_demo/adc_demo.c
drivers/adc/adc_demo/adc_demo.h
drivers/adc/adc_demo/iio_adc_demo.c
drivers/dac/dac_demo/iio_dac_demo.c
projects/iio_demo/src/app/main.c

Define global variables used in IIO modules of adc_demo and dac_demo in the source files.
Improve the ability to have variable number of channels.

IIO demo variable definition update

---

tools/scripts/build_projects.py

Print error messages with red.
Preppend each log line with a arrow (->).
Red if is related to an error message, green otherwise.

tools:scripts:build_projects.py:Improve log

---

drivers/adc/ad7124/iio_ad7124.c
projects/ad7124-8pmdz/src/ad7124_regs.c

Fix 3 bugs with the IIO implementation and the ad7124-8pmdz project.

AD7124 channel read bug fix

---

drivers/adc/ad7768-1/ad77681.c
drivers/adc/ad7768-1/ad77681.h

Update AD7768-1 Library. Added continuous read function. Change 16 bit frame to 8 bit frame. Fixed typo.

drivers:adc:ad7768-1: Update AD7768-1 driver

---

projects/fmcdaq3/src/app/fmcdaq3.c

- reorganize startup sequence
- add reconfiguration sequence

2019_R2: daq3 updates

---

drivers/dac/ad5791/iio_ad5791.c
drivers/dac/ad5791/iio_ad5791.h
projects/cn0531/src/main.c

- Update driver to be identical in functionality to the Linux one;
- Update the main source in the cn0531 to use the new driver.

AD5791 IIO driver update

---

projects/ad7124-8pmdz/builds.json

Add build configuration for automatic build.

projects:ad7124-8pmdz: add JSON build file

---

projects/cn0531/builds.json

Add file to automatically build the hex file for the program.

projects:cn0531: add json build file

---

README.md

wiki.analog.com no-OS drivers page link changed

README: update drivers link

---

iio/iio_app/iio_app.c
include/error.h
network/linux_socket/linux_socket.c
network/linux_socket/linux_socket.h
projects/iio_demo/Makefile.linux
projects/iio_demo/src.mk
projects/iio_demo/src/app/main.c

Add support for linux sockets. iio-demo can now be run and tested without a physical board.

New linux sockets

---

drivers/adc/ad7689/ad7689.c
tools/scripts/stm32.mk

- fix issue visible when sequencer was enabled
- update openocd and gdb scripts (unrelated to driver but used them to test the chip with fast CPU and APB clocks)

Ad7689 update

---

drivers/platform/stm32/stm32_spi.c

stm32 SPI implementation used the HAL functions for performing
the SPI transfer and CS toggling (separate, with GPIO, due to
stm32 SPI issue).
This was painfully slow and had to be done by direct register
access.
The new implementation is much faster, probably about 3x from
my measurements.

stm32: spi implementation with direct reg access

---

projects/ad400x-fmcz/builds.json
tools/scripts/generic.mk
tools/scripts/platform/xilinx/util.tcl
tools/scripts/xilinx.mk

Tested on iio_demo for both vitis and sdk in linux

[1] Fix vitis build

---

.gitignore
build_projects.yml
tools/scripts/build_projects.py

Will be rebase after #985 is merged (ignore first 3 commits)

[2] Small improvements in CI

---

build_projects.yml
tools/scripts/aducm.mk
tools/scripts/altera.mk
tools/scripts/build_projects.py
tools/scripts/generic.mk
tools/scripts/generic_variables.mk
tools/scripts/libraries.mk
tools/scripts/stm32.mk
tools/scripts/xilinx.mk

Build bsp only when needed.
This way when building all noos project the can be build a short period of time.
Will rebase onto #988  (relevant from commit wiht cleanup varibles)
To see output logs click on 1 artifact (In Projects menu):
And download the needed logs;

[3] Fix CI and Improve speed

---

drivers/instr-amplif/ada4250/ada4250.c
drivers/instr-amplif/ada4250/ada4250.h
projects/ada4250_ardz/src/ada4250_ardz.c

Updates based on the latest received datasheet.

ada4250: update driver

---

iio/iio_app/iio_app.c

iio:iio_app: fix macro syntax

---

drivers/platform/aducm3029/i2c.c

It's unfortunate that ADuCM environment defines FAILURE as 1
whereas in no-OS (and in general) it is assumed that a failure
is indicated by a negative error code.
A translation between the ADuCM internal error codes and no-OS is
therefore needed.

aducm i2c driver - translate error codes

---

drivers/amplifiers/ada4250/ada4250.c
drivers/amplifiers/ada4250/ada4250.h

- remove offset range current values
- remove range define
- rework range/bias defines

ADA4250 updates

---

drivers/amplifiers/ada4250/ada4250.c
drivers/amplifiers/ada4250/iio_ada4250.c
drivers/amplifiers/ada4250/iio_ada4250.h
projects/ada4250_ardz/src.mk
projects/ada4250_ardz/src/parameters.h

- add IIO support
- minor driver updates

ada4250: IIO support and minor updates

---

drivers/platform/xilinx/spi_extra.h
drivers/platform/xilinx/xilinx_i2c.c
drivers/platform/xilinx/xilinx_spi_pl.c
drivers/spi/spi.c
include/spi.h

New xilinx pl spi drivers using resgisters will be needed in order to do multiple transfers with CS low.
Also 2 commit with spi modifications where added in order to get feedback.

[4] Add spi_transfer and new spi PL driver

---

tools/scripts/generic.mk
tools/scripts/iio_srcs.mk
tools/scripts/linux.mk
tools/scripts/stm32.mk

Beside building and debugging: 
Problems are configured to be shown in the problems tab in order to go to them in one click

Linux userspace makefile and configuration for debugging with VSCode

---

projects/adrv9009/builds.json
projects/adrv9009/src/app/app_clocking.c
projects/adrv9009/src/app/app_config.h
projects/adrv9009/src/app/app_jesd.c
projects/adrv9009/src/app/app_talise.c
projects/adrv9009/src/app/app_transceiver.c
projects/adrv9009/src/app/headless.c

Add support for ADRV9008-1 and ADRV9008-2.

projects: adrv9008-1/adrv9008-2 support

---

projects/ad9361/src.mk
projects/ad9361/src/main.c
projects/ad9361/src/parameters.h

Modified the ad9361 main to use iio_app_run.
Added UART_BAUDRATE in parameters.h

projects: ad9361: work with iio_app

---

drivers/platform/aducm3029/i2c.c

Setting bRepeatedStart=true for a transaction does not only ommit the stop
bit of the current transaction, but actually sends the repeated start as
well as a prologue data sequence.
This means that calling a read without a
stop bit and thn a write for aducm3029 actually sends the reapeated start,
then the I2C address and then a Stop bit directly, meaning the write
operation is not atomic anymore.
At best this is a benign bug and might still work, with hardware errors and
reading wrong registers at worst.
Capture of the write operation with bRepeatedStart=true
Image credit: @buha 
Capture of a full register read after the fix.
Bug discovered by @buha.

drivers:platform:aducm3029: i2c read fix

---

drivers/adc/ad7746/ad7746.c
drivers/adc/ad7746/ad7746.h

AD7746 driver updates
Requires #1006 to be merged to work.

[cn0552 p1] ad7746 driver updates

---

projects/iio_demo/src.mk

projects: iio_demo: fix src.mk

---

include/util.h
libraries/iio/iio.c
libraries/iio/iio.h
libraries/iio/iio_types.h
util/util.c

Extend IIO core with features that are used by the ad7746 iio part of the driver

[cn0552 p2] iio extensions for cn0552 iio project

---

drivers/platform/xilinx/xilinx_spi_pl.c
drivers/spi/spi.c
network/linux_socket/linux_socket.c

- Fix warnings
- Fix _increment_iter function in xilinx_spi_pl
- Fix cs_change behavior
- Fix warnings in linux_sockets

Small fixes

---

drivers/frequency/adf4377/adf4377.c
drivers/frequency/adf4377/adf4377.h
drivers/frequency/adf4377/iio_adf4377.c
drivers/frequency/adf4377/iio_adf4377.h
projects/adf4377_sdz/Makefile
projects/adf4377_sdz/src.mk
projects/adf4377_sdz/src/app/adf4377_sdz.c
projects/adf4377_sdz/src/app/app_config.h
projects/adf4377_sdz/src/app/parameters.h

- add no-OS driver.
- add IIO support.
- add application example

ADF4377/ADF4378 driver & application

---

drivers/cdc/ad7746/iio_ad7746.c

Fix incorrect casting (endianess dependant).

driver/ad7746: iio debug write cast fix

---

drivers/adc/ad9081/ad9081.c

Fix build issue propagated into master branch.
Fixes: 6b7f049

drivers/adc/ad9081: minor build fix

---

tools/scripts/build_projects.py

Current link is broken. Switch to the new valid link.

tools:scripts:build projects: fix hw release link

---

tools/scripts/build_projects.py

Revert aba4aa86c85e70101b2a784ffd0c5bd0f6dea5cb
The link of the file was ok, the issue with downloading the new
files was releated to an eviromental variable

tools:scripts:build_projects.py: Revert fix

---

projects/fmcjesdadc1/src/app/app_iio.c
projects/fmcjesdadc1/src/app/app_iio.h
projects/fmcjesdadc1/src/app/fmcjesdadc1.c

Update IIO support source files for the fmcjesdadc1 project after the
latest HDL changes.
Related to: #1061 

projects:fmcjesdadc1: update IIO app

---

drivers/photo-electronic/adpd188/adpd188.c
drivers/photo-electronic/adpd188/adpd188.h
drivers/photo-electronic/adpd188/iio_adpd188.c
drivers/photo-electronic/adpd188/iio_adpd188.h
projects/iio_adpd1080/Makefile
projects/iio_adpd1080/pinmux_config.c
projects/iio_adpd1080/src.mk
projects/iio_adpd1080/src/app_config.h
projects/iio_adpd1080/src/main.c
projects/iio_adpd1080/src/parameters.h

Add IIO driver for ADPD1080 and a minimal example to compile the driver.

ADPD1080 IIO driver

---

build_projects.yml

Similar to `azure_pipelines.yml` update build projects file to support
Pull Requests that target `main` branch and create custom  branches with
`staging/*` prefix that trigger the project build.

build_projects.yml: minor build updates

---

projects/iio_adpd1080/builds.json

Add build json file to generate artifacts.

projects:iio_adpd1080: add build json file

---

include/list.h
include/util.h
projects/iio_demo/readme.txt
util/list.c

- Fix xilinx timer drivers
- Improve util/list.c
- add bswap_constant_16 to util
- Add windows commands in iio_demo readme

Fix some issues found during development

---

drivers/platform/xilinx/timer.c

These commit where initially in #1083

drivers:platform:xilinx:Timer: Fixes and improvements

---

projects/iio_adpd1080/src/main.c

Change @file path in main.c file.

projects: iio_adpd1080: fix typo

---

projects/iio_adpd1080/src/main.c

The ADPD1080 features two internal clocks that need to be calibrated: a
32kHz one and a 32MHz one. The 32kHz clock needs to be calibrated using an
external reference clock.
In this case a function is added to calibrate the
32kHz clock against an internal timer of the host controller.
Then a function to calibrate the 32MHz clock against the 32kHz clock is added.

projects:iio_adpd1080:src: add clock calibarion routines

---

drivers/amplifiers/ada4250/ada4250.c

1) Added changes in functions so that the device structure
remains in sync with the actual configuration of the device.
2) Modified the wake delay duration according to the power state of the device.

drivers:ada4250: device structure and wake delay changes.

---

iio/iio_app/iio_app.c

Mainly split the main code into separate functions. The main reason for this was that the wifi for aducm3029 was not working and there were a lot of ifdef to handle. I hope this looks better.
Tested:
- Aducm UART
- Aducm WIFI
- Linux userspace
Will be useful if anyone can do a test on xilinx and maybe stm32

iio_app refactor

---

drivers/afe/ad4110/ad4110.c
drivers/afe/ad4110/ad4110.h

- pass reg data after error check
- format code

drivers: ad4110: misc updates

---

projects/ad4110/Makefile
projects/ad4110/src.mk
projects/ad4110/src/app/main.c
projects/ad4110/src/app/parameters.h

projects:ad4110 Add AD4110-1 project

---

iio/iio_app/iio_app.c

iio:iio_app: Fix xilinx platform

---

drivers/platform/aducm3029/aducm3029_i2c.c
drivers/platform/aducm3029/i2c.c
drivers/platform/aducm3029/i2c_extra.h
projects/ad7746-ebz/src.mk
projects/ad7746-ebz/src/app/headless.c
projects/cn0552/src.mk
projects/cn0552/src/app/headless.c
projects/iio_adpd1080/src.mk
projects/iio_adpd1080/src/main.c

-added i2c platform ops for Aducm platform.
-fixed projects build errors

Aducm i2c_ops added

---

projects/iio_demo/src.mk

-corrected mistakes done in PR #1128

projects:iio_demo: Makefile corrected

---

drivers/platform/altera/altera_i2c.c
drivers/platform/altera/i2c_extra.h

Refactored altera_i2c_platform_ops to altera_i2c_ops.

Refactoring altera_i2c_platform_ops

---

projects/fmcdaq2/src/app/fmcdaq2.c

- fix adc ref rate
- fix DAC initialization

projects: daq2 profiles fixes

---

drivers/platform/stm32/stm32_delay.c
drivers/platform/stm32/stm32_i2c.c
drivers/platform/stm32/stm32_i2c.h
drivers/platform/stm32/stm32_spi.c
drivers/platform/stm32/stm32_spi.h
drivers/platform/stm32/stm32_uart.c
drivers/platform/stm32/stm32_uart.h
drivers/platform/stm32/stm32_uart_stdio.c
include/i2c.h

some stm32 related updates
none of these changes break anything already on master

stm32 updates

---

projects/iio_demo/src/app/parameters.h

A github warning is shown about a hidden unicode character.
Remvoe it

iio_demo:src:app:parameters.h: Remove unicode ch

---

tools/scripts/build_projects.py

Use new release link for hdl outputs.

tools:scripts:update download link for hdl outputs

---

drivers/platform/aducm3029/uart.c
iio/iio.c
iio/iio_app/iio_app.c
include/no-os/circular_buffer.h
util/circular_buffer.c

I didn't added this fixes in latest PR because it was already approved.
Tested with ad9361(xilinx) and adxrs290(aducm3029) on uart

Fix new iiod for aducm3029

---

drivers/platform/mbed/mbed_spi.cpp
drivers/platform/mbed/mbed_spi.h

Initial implementation of the Mbed SPI platform drivers.

drivers:platform:mbed: SPI platform drivers implementation

---

drivers/platform/mbed/mbed_i2c.cpp
drivers/platform/mbed/mbed_i2c.h

Initial implementation of the Mbed I2C platform drivers.

drivers:platform:mbed: I2C platform driver implementation

---

tools/scripts/aducm.mk
tools/scripts/build_projects.py
tools/scripts/generic.mk
tools/scripts/linux.mk
tools/scripts/platform/xilinx/build_project.tcl
tools/scripts/platform/xilinx/util.tcl
tools/scripts/stm32.mk
tools/scripts/xilinx.mk

Implementation of first makefile features regarding the use of a specific SDK.

Makefile update

---

drivers/platform/mbed/mbed_delay.cpp

Implemented the usec and msec delay functions for mbed platform

drivers:platform:mbed: Delay platform driver implementation

---

drivers/platform/mbed/mbed_gpio.cpp
drivers/platform/mbed/mbed_gpio.h

Implemented the GPIO read/write functionality for Mbed platform.

drivers:platform:mbed: GPIO platform driver implementation

---

projects/adf4377_sdz/builds.json

Add json file to integrate the adf4377_sdz project into the CI build.

projects: adf4377: add builds.json

---

drivers/afe/ad4110/ad4110.c
drivers/afe/ad4110/ad4110.h

Added new functions to configure the device
Updated the init structure and device descriptor
Corrected the bit shift value for AD4110_REG_ADC_CONFIG_AIN_BUFF
Signed-off-by: Janani Sunil <Janani.Sunil@analog.com>

afe:ad4110:Function additions, struct update

---

drivers/platform/stm32/stm32_spi.c
drivers/platform/stm32/stm32_uart.c
projects/eval-adxl355-pmdz/src/main.c

- Fixes several stm platform specific changes which were done previously.

Fixes for STM32 platform

---

iio/iio_types.h

Fix for commit cc5d097b3a1a598919cf8092757c8cd2afe40b67

Fix iio_app no_os naming

---

drivers/platform/mbed/mbed_platform_support.cpp
drivers/platform/mbed/mbed_platform_support.h

The Mbed platform specific additional functionality is implemented in this file.

drivers:platform:mbed: Adding platform support files

---

drivers/platform/maxim/gpio_extra.h
drivers/platform/maxim/i2c_extra.h
drivers/platform/maxim/irq_extra.h
drivers/platform/maxim/maxim_gpio.c
drivers/platform/maxim/maxim_hal.h
drivers/platform/maxim/maxim_i2c.c
drivers/platform/maxim/maxim_rtc.c
drivers/platform/maxim/maxim_spi.c
drivers/platform/maxim/maxim_uart.c
drivers/platform/maxim/maxim_uart.h
drivers/platform/maxim/spi_extra.h

Updated the Maxim drivers to run on MAX32655 and MAX32650.

Maxim drivers for MAX32650 and MAX32655

---

drivers/axi_core/jesd204/axi_jesd204_tx.h

Add documentation for the parameters of the initialization and device
structures.

axi_core: jesd204: axi_jesd204_tx: add param doc

---

drivers/axi_core/jesd204/axi_adxcvr.h
drivers/axi_core/jesd204/axi_jesd204_rx.h
drivers/axi_core/jesd204/axi_jesd204_tx.h

Add header comments for the device and initialization structures.
Add documentation for the parameters of the initialization and device
structures.

axi_core: jesd204: add jesd204_rx/tx, axi_adxcvr parameters documentation

---

drivers/axi_core/axi_adc_core/axi_adc_core.c
drivers/axi_core/axi_adc_core/axi_adc_core.h

Add documentation for the axi_adc structures and functions.

axi_core: axi_adc_core: add code doc

---

drivers/accel/adxl367/adxl367.c
drivers/accel/adxl367/adxl367.h
projects/eval-adxl367z/Makefile
projects/eval-adxl367z/builds.json
projects/eval-adxl367z/src.mk
projects/eval-adxl367z/src/common/common_data.c
projects/eval-adxl367z/src/common/common_data.h
projects/eval-adxl367z/src/examples/dummy/dummy_example.c
projects/eval-adxl367z/src/examples/dummy/dummy_example.h
projects/eval-adxl367z/src/examples/examples_src.mk
projects/eval-adxl367z/src/platform/platform_includes.h
projects/eval-adxl367z/src/platform/xilinx/main.c
projects/eval-adxl367z/src/platform/xilinx/parameters.c
projects/eval-adxl367z/src/platform/xilinx/parameters.h
projects/eval-adxl367z/src/platform/xilinx/platform_src.mk

-adxl367 driver created
-adxl367 project created

ADXL367 driver and project addition

---

drivers/axi_core/axi_adc_core/axi_adc_core.c
drivers/axi_core/axi_dac_core/axi_dac_core.c
drivers/axi_core/axi_dac_core/axi_dac_core.h

Add documentation for the device and initialization structures.
Add functions documentation.
+ axi_core: axi_adc: minor doc typo fix

axi_core: axi_dac: add code documentation 

---

drivers/platform/maxim/maxim_spi.c
tools/scripts/maxim.mk

- Changed the SPI voltage level to 3.3v.
- Maxim CFLAGS fix.

SPI level and CFLAGS fixes

---

drivers/adc/ad717x/ad7173_8_regs.h

Removed extra member for AD717X_GAIN8_REG  as here is only gain0 to gain7

drivers:adc:ad717x

---

drivers/adc/ad7616/ad7616.c
drivers/axi_core/axi_dmac/axi_dmac.c
drivers/axi_core/axi_dmac/axi_dmac.h
drivers/axi_core/iio_axi_adc/iio_axi_adc.c
drivers/axi_core/iio_axi_dac/iio_axi_dac.c
drivers/axi_core/spi_engine/spi_engine.c
drivers/axi_core/spi_engine/spi_engine.h
projects/ad6676-ebz/src/ad6676_ebz.c
projects/ad7768-evb/src/ad7768_evb.c
projects/ad9081/src/app.c
projects/ad9083/src/app.c
projects/ad9172/src/main.c
projects/ad9208/src/main.c
projects/ad9265-fmc-125ebz/src/ad9265_fmc_125ebz.c
projects/ad9361/src/main.c
projects/ad9371/src/app/headless.c
projects/ad9434-fmc-500ebz/src/ad9434_fmc_500ebz.c
projects/ad9467/src/app/ad9467_fmc.c
projects/ad9656_fmc/src/app/ad9656_fmc.c
projects/ad9739a-fmc-ebz/src/ad9739a_fmc_ebz.c
projects/adaq8092_fmc/src/adaq8092_fmc.c
projects/adrv9001/src/app/headless.c
projects/adrv9009/src/app/headless.c
projects/fmcadc2/src/fmcadc2.c
projects/fmcadc5/src/fmcadc5.c
projects/fmcdaq2/src/app/fmcdaq2.c
projects/fmcdaq3/src/app/fmcdaq3.c
projects/fmcjesdadc1/src/app/fmcjesdadc1.c

A new version of the DMA driver. 
The new driver was tested on the ad9361 project.

Dma example

---

drivers/platform/maxim/maxim_uart.c
drivers/platform/maxim/maxim_uart.h
iio/iio_app/iio_app.c
projects/eval-adxl355-pmdz/src/platform/maxim/main.c
projects/eval-adxl355-pmdz/src/platform/maxim/parameters.c
projects/eval-adxl355-pmdz/src/platform/maxim/parameters.h
projects/eval-adxl355-pmdz/src/platform/maxim/platform_src.mk

- Implemented the FIFO UART read mechanism.
- Added iio_app support for Maxim platform.
Draft until #1320 is merged.

UART read nonblocking FIFO mechanism and iio_app for Maxim

---

projects/ad719x/Makefile
projects/ad719x/builds.json
projects/ad719x/src.mk
projects/ad719x/src/common/common_data.c
projects/ad719x/src/common/common_data.h
projects/ad719x/src/examples/dummy/dummy_example.c
projects/ad719x/src/examples/dummy/dummy_example.h
projects/ad719x/src/examples/examples_src.mk
projects/ad719x/src/platform/platform_includes.h
projects/ad719x/src/platform/xilinx/main.c
projects/ad719x/src/platform/xilinx/parameters.c
projects/ad719x/src/platform/xilinx/parameters.h
projects/ad719x/src/platform/xilinx/platform_src.mk

AD719X project

---

drivers/platform/stm32/stm32_irq.c

Fix access to _events array. Instead of accessing with hal_event value, access with cb->event, which is the correct index to be
used in _events array.

drivers:platform:stm32: Fix access to _events array

---

drivers/accel/adxl367/adxl367.c
drivers/accel/adxl367/iio_adxl367.c
drivers/adc/ad719x/ad719x.c
drivers/afe/ad4110/ad4110.c
drivers/cdc/ad7746/iio_ad7746.c
drivers/dac/ad5758/ad5758.c
drivers/display/display.c
drivers/display/ssd_1306/ssd_1306.c
drivers/photo-electronic/adpd188/iio_adpd188.c
drivers/temperature/adt7420/adt7420.c
drivers/temperature/max31875/max31875.c

Minor driver fixes with respect to the compiling warnings.

drivers: misc warning fixes

---

drivers/adc/ad469x/ad469x.c
drivers/adc/ad469x/ad469x.h

* Added macro so that the drivers can be used with normal MCU without spi engine.
* Extended the existing drivers functionality.

AD4696x Spi Engine and Functional updates

---

drivers/platform/maxim/maxim_irq.c
drivers/platform/maxim/maxim_timer.c
drivers/platform/maxim/timer_extra.h

Maxim timer driver

---

drivers/platform/aducm3029/aducm3029_irq.c
drivers/platform/aducm3029/no_os_uart.c
drivers/platform/aducm3029/uart_extra.h
iio/iio_app/iio_app.c
projects/iio_aducm3029/src.mk

While testing a project that has interrupt driven uart rx, some issues were revealed on the aducm3029 platform that this PR fixes. See commit description for more info.

aducm3029 uart/irq related fixes

---

drivers/api/no_os_irq.c
drivers/platform/maxim/maxim_gpio_irq.c
drivers/platform/maxim/maxim_irq.c
drivers/platform/stm32/stm32_irq.c
include/no_os_irq.h
projects/eval-adxl355-pmdz/src/platform/maxim/main.c

Implemented interrupt priority API for Maxim and STM32 platforms.

Interrupt priority API

---

drivers/platform/xilinx/i2c_extra.h
projects/adv7511/src.mk
projects/adv7511/src/cf_hdmi.c
projects/adv7511/src/main.c
projects/adv7511/src/transmitter.c
projects/adv7511/src/transmitter.h

Update of the adv7511 sample project.

Work adv7511

---

drivers/temperature/adt7420/adt7420.c
drivers/temperature/adt7420/adt7420.h
drivers/temperature/adt7420/iio_adt7420.c
drivers/temperature/adt7420/iio_adt7420.h
projects/adt7420-pmdz/Makefile
projects/adt7420-pmdz/builds.json
projects/adt7420-pmdz/src.mk
projects/adt7420-pmdz/src/common/common_data.c
projects/adt7420-pmdz/src/common/common_data.h
projects/adt7420-pmdz/src/examples/dummy/dummy_example.c
projects/adt7420-pmdz/src/examples/dummy/dummy_example.h
projects/adt7420-pmdz/src/examples/examples_src.mk
projects/adt7420-pmdz/src/examples/iio_example/iio_example.c
projects/adt7420-pmdz/src/examples/iio_example/iio_example.h
projects/adt7420-pmdz/src/platform/maxim/main.c
projects/adt7420-pmdz/src/platform/maxim/parameters.c
projects/adt7420-pmdz/src/platform/maxim/parameters.h
projects/adt7420-pmdz/src/platform/maxim/platform_src.mk
projects/adt7420-pmdz/src/platform/platform_includes.h

Added iio support for adt7420 and example projects

Project adt7420

---

drivers/frequency/ad9517/ad9517.c
drivers/frequency/ad9517/ad9517.h

minor fixes and improvements in the ad9517 driver, used by the fmcjesdadc1 project

fmcjesdadc1 fixes

---

drivers/adc/max11205/iio_max11205.c
drivers/adc/max11205/iio_max11205.h
drivers/adc/max11205/max11205.c
drivers/adc/max11205/max11205.h
projects/max11205pmb1/Makefile
projects/max11205pmb1/builds.json
projects/max11205pmb1/src.mk
projects/max11205pmb1/src/common/common_data.c
projects/max11205pmb1/src/common/common_data.h
projects/max11205pmb1/src/examples/basic_example/basic_example.c
projects/max11205pmb1/src/examples/basic_example/basic_example.h
projects/max11205pmb1/src/examples/examples_src.mk
projects/max11205pmb1/src/examples/iio_example/iio_example.c
projects/max11205pmb1/src/examples/iio_example/iio_example.h
projects/max11205pmb1/src/platform/maxim/main.c
projects/max11205pmb1/src/platform/maxim/parameters.c
projects/max11205pmb1/src/platform/maxim/parameters.h
projects/max11205pmb1/src/platform/maxim/platform_src.mk
projects/max11205pmb1/src/platform/platform_includes.h

- max11205 driver
- max11205 basic example on maxim platform
- iio driver for max11205
- iio example for max11205 on maixm platform

max11205 driver + iio support

---

drivers/api/no_os_spi.c
drivers/io-expander/ltc4332/ltc4332.c
drivers/io-expander/ltc4332/ltc4332.h
include/no_os_spi.h

This is the same as #1490 but with the astyle fix.

Ltc4332 spi extender

---

projects/ad7616-sdz/src/ad7616_sdz.c

- use pr_info 
- update buf to array 
-  print samples

projects: ad7616 updates

---

drivers/platform/generic/no_os_timer.c
drivers/platform/generic/no_os_trng.c

- platform: generic: timer: add returns
- platform: generic: trng: remove return

platform: generic: update returns

---

drivers/platform/pico/pico_spi.c

Added spi_transfer API for pico platform which allows to send multiple spi messages with chip select either asserted or de-asserted.

drivers:platform:pico:pico_spi: Add spi_transfer API

---

drivers/platform/xilinx/timer_extra.h
drivers/platform/xilinx/xilinx_timer.c
projects/ad7768-evb/src.mk
projects/adv7511/src.mk
projects/adv7511/src/main.c
projects/iio_demo/src/platform/xilinx/platform_src.mk

- use platform ops
- add timer get elapsed func

platform: xilinx: update timer

---

drivers/api/no_os_eeprom.c
include/no_os_eeprom.h

Added EEPOM init, remove, read (byte by byte) and write (byte by byte) APIs.

drivers:api: Added basic APIs for EEPROM interface

---

drivers/platform/maxim/max32665/maxim_spi.h
drivers/platform/maxim/max78000/maxim_spi.h

- drivers: spi: max78000: fix header defines
- drivers: maxim: spi: max32665: fix spi header

maxim: spi: header file fixes

---

drivers/platform/altera/altera_i2c.c
drivers/platform/altera/altera_i2c.h
drivers/platform/xilinx/xilinx_gpio_irq.c
drivers/platform/xilinx/xilinx_gpio_irq.h
drivers/platform/xilinx/xilinx_i2c.c
drivers/platform/xilinx/xilinx_i2c.h
drivers/platform/xilinx/xilinx_timer.c
drivers/platform/xilinx/xilinx_timer.h
projects/ad4110/src.mk
projects/ad4110/src/app/main.c
projects/ad413x/src.mk
projects/ad413x/src/app/main.c
projects/ad719x/src/platform/xilinx/platform_src.mk
projects/adv7511/src.mk
projects/adv7511/src/main.c
projects/cn0565/src.mk
projects/eval-adxl367z/src/platform/xilinx/platform_src.mk
projects/iio_demo/src/platform/xilinx/platform_src.mk

platform: update header files

---

README.md

There is a new landing page for no-OS on wiki.

change link to no-OS wiki

---

drivers/platform/maxim/max32650/maxim_spi.c
drivers/platform/maxim/max32655/maxim_spi.c
drivers/platform/maxim/max32660/maxim_spi.c
drivers/platform/maxim/max32665/maxim_spi.c
drivers/platform/maxim/max32670/maxim_spi.c
drivers/platform/maxim/max78000/maxim_spi.c

- Set the CS line before a SPI transfer.

Set explicit CS on Maxim platform

---

tools/scripts/maxim.mk

- The rwildcard function didn't seem to work correctly on Windows without specifying the compiler's extension.
- For the rwildcard function to match a directory's name (first argument), it must not end with a `/` (e.g `dir` vs `dir/`).
- The `PATH` update workaround is no longer needed.

Maxim Windows build fix

---

projects/ad9081/src/app_jesd.c

Remove the cpll_enable member from adxcvr_init.

ad9081 ADXCVR fix

---

projects/ad9361/src/main.c

ADC and DAC DMA transfers example, with IRQ_ENABLED.
Fixes: 5c16868 (drivers:axi_core:axi_dmac:axi_dmac.* DMAC driver)

ad9361:src:main.c FMCOMMS5 DMA example fix

---

.cppcheckignore
drivers/adc/ad7124/iio_ad7124.c
drivers/axi_core/axi_adc_core/axi_adc_core.h
drivers/axi_core/axi_dac_core/axi_dac_core.c
drivers/axi_core/jesd204/axi_adxcvr.c
drivers/frequency/adf5902/adf5902.h

Multiple fixes related to the updated version of cppcheck.

cppcheck misc fixes 2

---

drivers/adc/ad7768-1/ad77681.c
drivers/adc/ad9081/ad9081.c
drivers/adc/adc_demo/iio_adc_demo.c
drivers/platform/maxim/max32650/maxim_irq.c
drivers/platform/maxim/max32655/maxim_irq.c
drivers/platform/maxim/max32660/maxim_irq.c
drivers/platform/maxim/max32665/maxim_irq.c
drivers/platform/maxim/max32670/maxim_irq.c
drivers/platform/maxim/max78000/maxim_irq.c
drivers/platform/mbed/mbed_gpio_irq.cpp

Multiple fixes related to the updated version of cppcheck.

cppcheck misc fixes 1

---

drivers/platform/maxim/max32650/maxim_uart.c

Properly handle the conditional jumps in case of errors during the uart initialization.

platform: max32650: fix uart init error handling

---

drivers/adc/ltc2358/ltc2358.c
drivers/adc/ltc2358/ltc2358.h

Signed-off-by: Kim Seer Paller <kimseer.paller@analog.com>

drivers:adc: add ltc2358 support

---

tools/scripts/generic.mk

tools: scripts: generic: minor typo fix

---

drivers/api/no_os_eeprom.c
drivers/api/no_os_gpio.c
drivers/api/no_os_i2c.c
drivers/api/no_os_irq.c
drivers/api/no_os_spi.c
drivers/api/no_os_timer.c

- Return the actual error code instead of -1.
- Add pointer checks where they were missing.

Fix the API pointer checks

---

projects/ad9361/builds.json
projects/ad9361/src/app_config.h
projects/ad9361/src/main.c

Remove duplicate code and rename DMA IRQ define.

Staging/ad9361 Modify ad9361 project defines

---

drivers/platform/stm32/stm32_delay.c
drivers/platform/xilinx/xilinx_delay.c
include/no_os_delay.h
include/no_os_print_log.h

Add possibility to print timestamp before pr_* message.

Add possibility to print timestamp before pr_* message

---

drivers/platform/maxim/max32650/maxim_delay.c
drivers/platform/maxim/max32650/maxim_init.c
drivers/platform/maxim/max32655/maxim_delay.c
drivers/platform/maxim/max32655/maxim_init.c
drivers/platform/maxim/max32660/maxim_delay.c
drivers/platform/maxim/max32660/maxim_init.c
drivers/platform/maxim/max32665/maxim_delay.c
drivers/platform/maxim/max32665/maxim_init.c
drivers/platform/maxim/max32670/maxim_delay.c
drivers/platform/maxim/max32670/maxim_init.c
drivers/platform/maxim/max78000/maxim_delay.c
drivers/platform/maxim/max78000/maxim_init.c
include/no_os_init.h
projects/eval-adxl355-pmdz/src.mk
projects/eval-adxl355-pmdz/src/platform/maxim/platform_src.mk

Add Maxim implementation for function getting current time value.

platform:maxim:maxim_delay.c Add time function

---

drivers/temperature/max31865pmb1/max31865.c
drivers/temperature/max31865pmb1/max31865.h

Added driver implementation for max31865pmb1
More information: https://www.analog.com/media/en/technical-documentation/data-sheets/max31865.pdf
Signed-off-by: Jose Ramon San Buenaventura <jose.sanbuenaventura@analog.com>

driver:temperature: Added support for max31865pmb1

---

drivers/adc/ad9680/ad9680.c
drivers/adc/ad9680/ad9680.h
drivers/axi_core/jesd204/axi_adxcvr.c
drivers/axi_core/jesd204/axi_adxcvr.h
drivers/axi_core/jesd204/axi_jesd204_rx.c
drivers/axi_core/jesd204/axi_jesd204_rx.h
drivers/axi_core/jesd204/axi_jesd204_tx.c
drivers/axi_core/jesd204/axi_jesd204_tx.h
drivers/axi_core/jesd204/xilinx_transceiver.h
drivers/dac/ad9144/ad9144.c
drivers/dac/ad9144/ad9144.h
projects/ad6676-ebz/src.mk
projects/ad9081/src.mk
projects/ad9083/src.mk
projects/ad9172/src.mk
projects/ad9208/src.mk
projects/ad9371/src.mk
projects/ad9656_fmc/src.mk
projects/adrv9009/src.mk
projects/fmcadc2/src.mk
projects/fmcadc5/src.mk
projects/fmcdaq2/src.mk
projects/fmcdaq2/src/app/app_config.h
projects/fmcdaq2/src/app/fmcdaq2.c
projects/fmcdaq3/src.mk
projects/fmcjesdadc1/src.mk

Add the possibility of using the JESD204 (FSM) Interface Framework.

Staging/jesd fsm JESD204 (FSM) Interface Framework

---

drivers/platform/linux/linux_timer.c
drivers/platform/linux/linux_timer.h

The implementation is using CLOCK_REALTIME.

drivers: platform: linux: Add timer support

---

iio/iio.c
iio/iio_types.h

Add rotation type with pitch, yaw and roll modifiers.

iio: Add rotation type with axis modifiers

---

drivers/axi_core/axi_adc_core/axi_adc_core.c
drivers/axi_core/axi_adc_core/axi_adc_core.h
drivers/axi_core/iio_axi_adc/iio_axi_adc.c
drivers/axi_core/iio_axi_dac/iio_axi_dac.c
drivers/rf-transceiver/ad9361/ad9361.c
drivers/rf-transceiver/ad9361/ad9361.h
drivers/rf-transceiver/ad9361/iio_ad9361.c
projects/ad9361/src/main.c

Add IIO support for FMCOMMS5.

---

projects/iio_demo/src/platform/aducm3029/main.c
tools/scripts/aducm.mk

- iio_demo: aducm3029: fix initialization condition
- tools:scripts: increase HEAP size on aducm3029

aducm3029: misc fixes

---

drivers/api/no_os_trng.c
drivers/platform/aducm3029/aducm3029_trng.c
drivers/platform/aducm3029/aducm3029_trng.h
drivers/platform/maxim/max32650/maxim_trng.c
drivers/platform/maxim/max32650/maxim_trng.h
drivers/platform/maxim/max32655/maxim_trng.c
drivers/platform/maxim/max32655/maxim_trng.h
drivers/platform/maxim/max32665/maxim_trng.c
drivers/platform/maxim/max32665/maxim_trng.h
drivers/platform/maxim/max32670/maxim_trng.c
drivers/platform/maxim/max32670/maxim_trng.h
drivers/platform/maxim/max78000/maxim_trng.c
drivers/platform/maxim/max78000/maxim_trng.h
include/no_os_trng.h

- trng: add platform ops support
- add TRNG support for the maxim platforms

trng: add platform ops and maxim support

---

iio/iio_app/iio_app.c
network/tcp_socket.c
network/wifi/at_parser.c
network/wifi/at_parser.h
network/wifi/wifi.c
network/wifi/wifi.h

- [network:wifi: update the wifi module](https://github.com/analogdevicesinc/no-OS/commit/11ed6dd232d39961fda810cbf7d6a7545537da1d)
- [network: move the wifi reset command into the at_parser.c module](https://github.com/analogdevicesinc/no-OS/commit/0fa83bbbd1fb97e405de86181c2a5783ad75ddf2)
- [network:wifi: fix timeout condition](https://github.com/analogdevicesinc/no-OS/commit/e4fcfb9cdcd627f807da8a2f04a8162639db7b64)
- [network:tcp_socket: buffer size decrease](https://github.com/analogdevicesinc/no-OS/commit/c08bbd807311e1adbc6a2a0647c9e6119634a522)
- [network: wifi: make software reset optional](https://github.com/analogdevicesinc/no-OS/commit/5e40001c5b321e92b8c1a56928fb65e8d0582068)

network: misc updates

---

iio/iio.c

With the current implementation -EINVAL error is returned when searching for triggers. However, libiio exptects -ENOENT error if no triggers are present.
This commit returns the correct error if no triggers are found.

iio: iio.c: Handle return error if no triggers are present

---

drivers/rf-transceiver/ad9361/ad9361_api.c
drivers/rf-transceiver/ad9361/ad9361_util.c
drivers/rf-transceiver/ad9361/ad9361_util.h
include/no_os_alloc.h
util/no_os_alloc.c

Add no_os memory allocation and free functions.

Add no-OS wrappers for dynamic memory management

---

ci/config.cppcheck
ci/cppcheck.sh

Add custom config file for checking the no-os memory allocation/deallocation functions.

ci: cppcheck: add config file

---

iio/iio.c
iio/iio_app/iio_app.c

- iio_app: iio_app.c: Do not exit app run for buff overrun 
- iio.c: Free desc->trigs in iio_remove

IIO small fixes

---

drivers/axi_core/axi_adc_core/axi_adc_core.h
projects/adrv9001/src/app/headless.c

Some fixes for Navassa, more details in commit descriptions.

navassa updates

---

drivers/filter/admv8818/admv8818.c

[drivers:filter:admv8818: use units header](https://github.com/analogdevicesinc/no-OS/commit/0cd9f63a1c124a9581930e1a88fb92d4c41c5817)
[drivers:filter:admv8818: close potential oob read](https://github.com/analogdevicesinc/no-OS/commit/bed80184b81e3c572564db8a44b48db3b8180f7b)

drivers: admv8818: misc updates

---

include/no_os_spi.h

Fix SPI modes documentation, according to:
https://www.analog.com/en/analog-dialogue/articles/introduction-to-spi-interface.html

include: spi: minor fix on mode description

---

drivers/temperature/max31855/iio_max31855.c
projects/max31855/Makefile
projects/max31855/builds.json
projects/max31855/src.mk
projects/max31855/src/common/common_data.c
projects/max31855/src/common/common_data.h
projects/max31855/src/examples/basic/basic_example.c
projects/max31855/src/examples/basic/basic_example.h
projects/max31855/src/examples/examples_src.mk
projects/max31855/src/examples/iio_example/iio_example.c
projects/max31855/src/examples/iio_example/iio_example.h
projects/max31855/src/platform/maxim/main.c
projects/max31855/src/platform/maxim/parameters.c
projects/max31855/src/platform/maxim/parameters.h
projects/max31855/src/platform/maxim/platform_src.mk
projects/max31855/src/platform/platform_includes.h

Example projects for the MAX31855 thermocouple.

MAX31855 project

---

tools/scripts/build_projects.py

for stm32 build use only half of processors and do not return an error in case of a timeout.

scripts: build_projects: stm32 build changes

---

drivers/adc/max9611pmb/max9611.c
drivers/adc/max9611pmb/max9611.h

Added driver implementation for max9611pmb.
More information: https://www.analog.com/media/en/technical-documentation/data-sheets/MAX9611-MAX9612.pdf

drivers:adc: added max9611pmb support.

---

drivers/adc/ad4080/ad4080.c
drivers/adc/ad4080/ad4080.h

Apply additional init param settings as part of the device initialization routine

Mach1: update device init

---

drivers/eeprom/24xx32a/24xx32a.c

Reverting the change made with this commit id: e095d7b8de867681e846cc7e5344ffa2d8334d30 since sequential read and write transaction also works.

drivers:eeprom:24xx32a Reverting repeated stop bit.

---

drivers/platform/chibios/chibios_alloc.c
drivers/platform/chibios/chibios_gpio.c
drivers/platform/chibios/chibios_spi.c

The calloc replacements needed extra var plus missing .h in memory alloc

drivers/platform/chibios: bugfix

---

include/no_os_mutex.h
util/no_os_mutex.c

PR:
- mutex header added
- mutex (empty) implementation for no_os

Add mutex support

---

drivers/platform/chibios/chibios_uart.c
drivers/platform/chibios/chibios_uart.h

Uart implementation for no os api in chibios

drivers/platform/chibios: add uart

---

drivers/platform/maxim/max32690/maxim_delay.c
drivers/platform/maxim/max32690/maxim_gpio.c
drivers/platform/maxim/max32690/maxim_gpio.h
drivers/platform/maxim/max32690/maxim_gpio_irq.c
drivers/platform/maxim/max32690/maxim_gpio_irq.h
drivers/platform/maxim/max32690/maxim_i2c.c
drivers/platform/maxim/max32690/maxim_i2c.h
drivers/platform/maxim/max32690/maxim_init.c
drivers/platform/maxim/max32690/maxim_irq.c
drivers/platform/maxim/max32690/maxim_irq.h
drivers/platform/maxim/max32690/maxim_rtc.c
drivers/platform/maxim/max32690/maxim_rtc.h
drivers/platform/maxim/max32690/maxim_spi.c
drivers/platform/maxim/max32690/maxim_spi.h
drivers/platform/maxim/max32690/maxim_timer.c
drivers/platform/maxim/max32690/maxim_timer.h
drivers/platform/maxim/max32690/maxim_uart.c
drivers/platform/maxim/max32690/maxim_uart.h
drivers/platform/maxim/max32690/maxim_uart_stdio.c
drivers/platform/maxim/max32690/maxim_uart_stdio.h
projects/adt7420-pmdz/builds.json
projects/adt7420-pmdz/src/platform/maxim/parameters.h
projects/eval-adxl355-pmdz/builds.json
projects/eval-adxl355-pmdz/src/platform/maxim/parameters.h
tools/scripts/maxim.mk

These are pretty similar to the other Maxim drivers. Kept the original author when no major change was needed. This has to be merged first: https://github.com/analogdevicesinc/no-OS/pull/1702

Max32690 platform drivers.

---

include/no_os_semaphore.h
util/no_os_semaphore.c

Added semaphore header and implementation

semaphore support in no_os

---

.gitignore
tools/scripts/build_projects.py

[tools: scripts: build_projects: use full path](https://github.com/analogdevicesinc/no-OS/commit/8a243beff4bcb047d14214745077a6865016286e)
[scripts: build_projects: add default build dir](https://github.com/analogdevicesinc/no-OS/commit/030f860c9b7d3ddb285e6e835ae88b0ae69038ca)
[.gitignore: update for build_project.py outputs](https://github.com/analogdevicesinc/no-OS/commit/70235602e19e1501a27722ceb549b3f96c7b8ecb)

tools: scripts: build_projects.py: update output paths

---

drivers/io-expander/ltc4306/ltc4306.c
drivers/io-expander/ltc4306/ltc4306.h

Added driver implementation for ltc4306
More information: https://www.analog.com/media/en/technical-documentation/data-sheets/4306.pdf

drivers:io-expander: added ltc4306 support

---

drivers/platform/stm32/stm32_irq.c
drivers/platform/stm32/stm32_tdm.c
drivers/platform/stm32/stm32_tdm.h
drivers/tdm/no_os_tdm.c
include/no_os_irq.h
include/no_os_tdm.h

1) Added no_OS driver API for TDM DMA read
2) Added no_OS driver API for Stop TDM DMA read
3) Added TDM DMA Read in STM32 platform driver
4) Added function for Stop TDM DMA read in STM32 platform driver.

drivers:platform:stm32:Add API for TDM DMA read.

---

drivers/adc/ad4858/ad4858.c
drivers/adc/ad4858/ad4858.h
include/no_os_util.h
util/no_os_util.c

Initial implementation of the ad4858 no-os drivers

drivers:adc:ad4858 Added ad4858 driver support

---

drivers/adc-dac/ad74416h/ad74416h.c
drivers/adc-dac/ad74416h/ad74416h.h

drivers:adc-dac:ad74416h: initial commit

---

projects/ad74416h/builds.json
projects/ad74416h/src/common/common_data.c
projects/ad74416h/src/common/common_data.h
projects/ad74416h/src/examples/basic/basic_example.c
projects/ad74416h/src/examples/basic/basic_example.h
projects/ad74416h/src/platform/mbed/main.c
projects/ad74416h/src/platform/mbed/parameters.c
projects/ad74416h/src/platform/mbed/parameters.h
projects/ad74416h/src/platform/mbed/platform_src.mk
projects/ad74416h/src/platform/platform_includes.h
projects/ad74416h/src/platform/stm32/main.c
projects/ad74416h/src/platform/stm32/parameters.c
projects/ad74416h/src/platform/stm32/parameters.h

Add mbed platform support for the ad74416h project.

projects: ad74416h: add mbed platform support

---

drivers/platform/maxim/max32650/maxim_irq.c
drivers/platform/maxim/max32655/maxim_irq.c
drivers/platform/maxim/max32660/maxim_irq.c
drivers/platform/maxim/max32665/maxim_irq.c
drivers/platform/maxim/max32670/maxim_irq.c
drivers/platform/maxim/max32690/maxim_irq.c
drivers/platform/maxim/max78000/maxim_irq.c

Add the possibility of using multiple interrupt callbacks for different timers.
Tested on MAX32655.

maxim_irq.c Multiple TMR interrupts and callbacks

---

drivers/adc-dac/ad74416h/ad74416h.c
drivers/adc-dac/ad74416h/ad74416h.h

[drivers: ad74416h: add vout range support](https://github.com/analogdevicesinc/no-OS/commit/ad89f6222cf44b1cf7cc21b230738ccad60916eb)
[drivers: ad74416h: update voltage to dac code func](https://github.com/analogdevicesinc/no-OS/commit/e7252655de1ebe7f3794aa2993a25d7c39d6ee54)
[drivers: ad74416h: set ADC conversion range](https://github.com/analogdevicesinc/no-OS/commit/20ac2a31b61b8968358feb447ac8ac605f41b24e)
[drivers: ad74416h: add support for ADC Input Mux](https://github.com/analogdevicesinc/no-OS/commit/2a39f01ffa4b1c04e44813bbf4e872c2c4177777)
[drivers: ad74416h: add dac current to code conv](https://github.com/analogdevicesinc/no-OS/commit/8e4c95b3fe96c3648af48e39898a44407d726c62)
[drivers: ad74416h: add current limit support](https://github.com/analogdevicesinc/no-OS/commit/f8168 …

drivers: ad74416h: misc updates

---

drivers/frequency/ltc6953/ltc6953.c
drivers/frequency/ltc6953/ltc6953.h

Added additional status functions to cover remaining register fields of LTC6953

drivers: frequency: ltc6953: Add status functions

---

drivers/io-link/max22516/max22516.c
drivers/io-link/max22516/max22516.h

Initial commit for max22516 driver.

drivers: io-link: max22516 support

---

drivers/adc/ad4858/ad4858.c
drivers/adc/ad4858/ad4858.h

Added API to change to ADC data interface mode

drivers:adc:ad4858 Data interface mode switch API

---

tools/scripts/platform/xilinx/util.tcl
tools/scripts/xilinx.mk

No building is necessary if we already have .xsa file and .elf file in project directory and booting via jtag for zynqmp projects id working now.

Fix make run for Xilinx projects

---

drivers/api/no_os_i2c.c
drivers/api/no_os_spi.c

Without mutex files implementation the mutex initialization should not be check, hence in general case it won't have value assigned to it.

Spi i2c bug fix

---

drivers/platform/stm32/stm32_tdm.c

Update the macro for TDM DMA interrupt to incorporate changes made with commit- 640b8f91408772b76e2a5b2eacee2c5c95c88a3e

drivers:platform:stm32:Update macro for TDM DMA

---

projects/demo_esp/src/common/common_data.c
projects/demo_esp/src/common/common_data.h
projects/demo_esp/src/examples/basic/basic_example.c
projects/demo_esp/src/platform/aducm3029/parameters.h
projects/demo_esp/src/platform/maxim/parameters.c
projects/demo_esp/src/platform/maxim/parameters.h

[projects: demo_esp: set VDDIOH for maxim uart](https://github.com/analogdevicesinc/no-OS/commit/0444620a64af6f2ed7efbf955656d6889c8b0694)
[projects: demo_esp: add wifi software reset macro](https://github.com/analogdevicesinc/no-OS/commit/7729f71043d3aec060507a9a6586881eda9a7e63)
[projects: demo_esp: add wifi hardware reset](https://github.com/analogdevicesinc/no-OS/commit/e5d79749836188337d01f34272323644dd7c67aa)

projects: demo_esp: add wifi hardware reset support

---

drivers/adc-dac/ad74413r/ad74413r.c

[drivers: adc-dac: ad74413r: add delay after reset](https://github.com/analogdevicesinc/no-OS/commit/404f8de8e5a3595caa87d80caecfbb826794ca4f)
[drivers: adc-dac: ad74413r: update readback](https://github.com/analogdevicesinc/no-OS/commit/2e613d7e5076b9623dd90f36cc043e6d33cf9fd9)

ad74413r: misc updates

---

drivers/api/no_os_pwm.c
drivers/api/no_os_timer.c
drivers/api/no_os_uart.c
drivers/platform/freeRTOS/freertos_mutex.c
drivers/platform/freeRTOS/freertos_semaphore.c
projects/iio_demo_freeRTOS/Makefile
projects/iio_demo_freeRTOS/src.mk
projects/iio_demo_freeRTOS/src/common/common_data.c
projects/iio_demo_freeRTOS/src/common/common_data.h
projects/iio_demo_freeRTOS/src/examples/examples_src.mk
projects/iio_demo_freeRTOS/src/examples/iio_example/iio_example.c
projects/iio_demo_freeRTOS/src/examples/iio_example/iio_example.h
projects/iio_demo_freeRTOS/src/platform/maxim/FreeRTOSConfig.h
projects/iio_demo_freeRTOS/src/platform/maxim/main.c
projects/iio_demo_freeRTOS/src/platform/maxim/parameters.c
projects/iio_demo_freeRTOS/src/platform/maxim/parameters.h
projects/iio_demo_freeRTOS/src/platform/maxim/platform_src.mk
projects/iio_demo_freeRTOS/src/platform/platform_includes.h

Currently only maxim platform beeing supported,
Demo contains two tasks started in the same time,
one is a blinking task and another one is the iio_demo task.
This project is intended as example project for further development and act as a base line solution
Example to build and run the project:
(After downloading: https://github.com/FreeRTOS/FreeRTOS-Kernel)
```
export FREERTOS=y
export MAXIM_LIBRARIES=/home/robi/Desktop/MaximSDK/MaximSDK/Libraries
export FREERTOS_KERNEL=/home/robi/Workspace_no-os/FreeRTOS-Kernel
make PLATFORM=maxim TARGET=max78000 run
```

projects/iio_demo_freeRTOS: initial commit

---

projects/ad719x/Makefile
projects/ad74413r/Makefile
projects/ad74416h/Makefile
projects/adin1110/Makefile
projects/adt7420-pmdz/Makefile
projects/adt75/Makefile
projects/adxrs290-pmdz/Makefile
projects/dc2903a/Makefile
projects/demo_esp/Makefile
projects/eval-adis1650x/Makefile
projects/eval-adis1657x/Makefile
projects/eval-adxl313z/Makefile
projects/eval-adxl355-pmdz/Makefile
projects/eval-adxl367z/Makefile
projects/eval-ltc4306/Makefile
projects/iio_demo/Makefile
projects/iio_demo_freeRTOS/Makefile
projects/ltc3337/Makefile
projects/max11205pmb1/Makefile
projects/max31855/Makefile

Fix typo propagate in the projects makefiles.

projects: Makefile: fix typo

---

drivers/dac/ad3552r/ad3552r.c

Remove redundant else statement.

drivers: dac: ad3552r: update ldac trigger func

---

drivers/adc/ad7124/ad7124.c
drivers/adc/ad7124/ad7124.h

Added Device Configurations.
Made editorial changes like function return types
and removal of brackets for single line if-else comments

drivers:ad7124: drivers enhancement

---

drivers/accel/adxl355/README.rst

In the reStructuredText format.

drivers: adxl355: Add documentation

---

projects/demo_esp/builds.json

Include the maxim build in the .json file.

projects: demo_esp: add maxim build

---

tools/scripts/release_projects.sh

[tools: scripts: release_projects: more comments](https://github.com/analogdevicesinc/no-OS/commit/5c21332124b19199b728d3155fc95876f34b1c17)
[tools: scripts: release_projects: use input param](https://github.com/analogdevicesinc/no-OS/commit/d8bea0696f1ed578813dbaf7af53a2a4364bd818)

tools: scripts: release projects updates

---

drivers/net/adin1110/adin1110.c

ADIN1110 fixes

---

tools/scripts/upload_to_artifactory.py

This script is used for a release job which takes the artifacts from azure build and then upload the files to artifactory sever.

Script for uploading to artifactory

---

tools/scripts/upload_to_artifactory.sh

Used in conjunction with upload_to_artifactory.py script to upload artifacts on artifactory via Azure Release pipeline.
Depends on: #1872

tools: scripts: add bash script for artifactory

---

tools/scripts/release_projects.sh
tools/scripts/upload_to_artifactory.sh

[tools: scripts: release_projects: update doc](https://github.com/analogdevicesinc/no-OS/commit/129228fb20356ef06562567d17702044119692f4)
[scripts: upload_to_artifactory.sh: update doc](https://github.com/analogdevicesinc/no-OS/commit/9727bfedad74e1b5bb3511252bf3760f779f3a6f)

release scripts: update code documentation

---

tools/scripts/release_projects.sh

Sources alias and Binary alias are two different things inside Azure Release pipeline. Use the correct naming to avoid future confusions.
Fixes: 5cd494d ("tools: scripts: release projects script")

scripts: release_projects: rename alias

---

tools/scripts/upload_to_artifactory.sh

[scripts: upload_to_artifactory: fix branch usage](https://github.com/analogdevicesinc/no-OS/commit/9a14f55ff3bad867d19b1f34f6d56286fe16746a)
[scripts: upload_to_artifactory: delimit variables](https://github.com/analogdevicesinc/no-OS/commit/9d3d13ea949c562b6a792e14743ddbdbf8cb37c5)

scripts: upload_to_artifactory: misc updates

---

README.md

[README.md: remove Codacy badge](https://github.com/analogdevicesinc/no-OS/commit/218530074c0e27bc9aff4375b6e3d70541f6b98a)
[README.md: update Azure Pipelines badge](https://github.com/analogdevicesinc/no-OS/commit/ee780321a157da920251b013939a7e8b6739aa5f)

README.md: badges updates

---

azure-pipelines.yml
ci/astyle.sh

[azure-pipelines: fix target branch](https://github.com/analogdevicesinc/no-OS/commit/3292360687a811b343ccb825db27032406bf2281)
[ci: astyle: fetch remote target branch](https://github.com/analogdevicesinc/no-OS/commit/761fe23bdc835dc960bce19dee1480d028da4676)

ci: azure-pipelines and astyle updates.

---

drivers/adc-dac/ad74416h/ad74416h.c
drivers/adc-dac/ad74416h/ad74416h.h

[drivers: adc-dac: ad74416h: update ch func set](https://github.com/analogdevicesinc/no-OS/commit/05238fe9ad35a7413045bb0651554f81e6053080)
[drivers: adc-dac: ad74416h: add hw reset support](https://github.com/analogdevicesinc/no-OS/commit/a6f2bab46ee1a7106b9d520c6872fe970b8fe0fa)

drivers: adc-dac: ad74416h: update ch function set and add hw reset

---

ci/astyle.sh
ci/cppcheck.sh
ci/doxygen.sh
ci/gen_dox.sh
ci/lib.sh
ci/run_build.sh

Refactor code in the ci scripts, adding suggestive functions
Misc code style fixes
Add copyright where needed.

ci: misc script updates

---

projects/swiot1l/Makefile
projects/swiot1l/src.mk
projects/swiot1l/src/common/common_data.c
projects/swiot1l/src/common/common_data.h
projects/swiot1l/src/common/swiot.c
projects/swiot1l/src/common/swiot.h
projects/swiot1l/src/platform/maxim/main.c
projects/swiot1l/src/platform/maxim/parameters.c
projects/swiot1l/src/platform/maxim/parameters.h
projects/swiot1l/src/platform/maxim/platform_src.mk
projects/swiot1l/src/platform/platform_includes.h
projects/swiot1l/src/swiot_fw.c
projects/swiot1l/src/swiot_fw.h

This is required for the release of the SWIOT1L analog.com page. Has been tested with all the other changes implemented in separate pull requests related to the ADIN1110 and AD74413R.

projects: Add SWIOT1L project

---

drivers/net/adin1110/adin1110.c
iio/iio_app/iio_app.c
network/lwip_raw_socket/lwip_socket.c
network/lwip_raw_socket/lwip_socket.h

ADIN1110 and networking updates

---

azure-pipelines.yml
ci/documentation.sh
ci/run_build.sh

Now that the sphinx build was added to the documentation build, the scripts/function naming should reflect that. For example the doxygen.sh script does now contain more that doxygen builds. Use a more generic name.

ci: documentation: update to suggestive namings

---

drivers/platform/stm32/stm32_pwm.c

Added an argument irq_id to the no_os_irq_disable() function call

drivers:platform:stm32:Add IRQ ID to no_os_irq_disable

---

README.md

After the sphinx documentation build integration into the Github pages, the doxygen path has changed. Update the README accordingly.

README: update doxygen gh pages link

---

drivers/platform/mbed/mbed_uart.cpp

1. Updated mbed_virtual_com_read function to read more than 64 Bytes data.

drivers:platform:mbed: update virtual_com_read function

---

tools/scripts/build_projects.py
tools/scripts/download_files.py

If a timestamp is specified in the hdl_branch argument given as input in a specific format the hardware files will be downloaded from that specific timestamp only.

tools: scripts: download hardware from specific timestamp

---

tools/scripts/mcufla.sh

This script is an adaptation of the maxfla.sh script which now offers support for other two non Xilinx platforms, STM32 and Pico.

tools: scripts: generic script for flashing non Xilinx platforms

---

.github/CODEOWNERS

Add myself as codeowner for the tools/scripts directory.

CODEOWNERS: Add myself as scripts owner

---

projects/eval-adis1650x/src/examples/dummy/dummy_example.c
projects/eval-adis1657x/src/examples/dummy/dummy_example.c

adis1650x and adis1657x projects: Add scale reading to dummy example

---

drivers/photo-electronic/adpd188/adpd188.c
drivers/photo-electronic/adpd188/adpd188.h
drivers/photo-electronic/adpd188/iio_adpd188.h
projects/iio_adpd1080/src/main.c

Fix several occurences of APDP1080 by replacing with ADPD1080.

fix adpd1080 related typo

---

doc/sphinx/source/drivers/adm1177.rst
doc/sphinx/source/drivers/adxl355.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/index.rst

This patch adds driver specific documentation support into the no-OS sphinx generated documentation.
This patch shows how README rst driver specific files, which are held at the driver implemetation location, are mapped into the main Table of contents from Sphinx documentation.

doc: sphinx: add sphinx driver doc example

---

drivers/axi_core/jesd204/axi_adxcvr.c
drivers/axi_core/jesd204/axi_adxcvr.h
drivers/axi_core/jesd204/axi_jesd204_rx.c
drivers/axi_core/jesd204/axi_jesd204_rx.h
drivers/axi_core/jesd204/axi_jesd204_tx.c
drivers/axi_core/jesd204/axi_jesd204_tx.h
drivers/axi_core/jesd204/xilinx_transceiver.h
drivers/frequency/hmc7044/hmc7044.c
projects/ad9081/src.mk
projects/ad9081/src/app_jesd.c
projects/fmcdaq2/src/app/fmcdaq2.c
util/no_os_clk.c

JESD204 FSM improvements

---

doc/sphinx/source/drivers/adis.rst
doc/sphinx/source/drivers_doc.rst
drivers/imu/README.rst

Add documentation for adis drivers.

drivers: imu: Add README.rst for adis drivers

---

azure-pipelines.yml

Update azure_pipeline.yml to trigger builds on next_stable branch whenever there are pushes or PRs to 'next_stable' branch.

azure_pipeline: add triggers for next_stable branch

---

tools/scripts/xilinx.mk

Change the exported system_top.bit file to system_top.xsa which is an archive that also contains system_top.bit file.

tools: scripts: export system_top.xsa file

---

doc/sphinx/source/drivers/max149x6.rst
doc/sphinx/source/drivers_doc.rst

Link the max149x6 README.rst to the sphinx no-so drivers table of content.

doc: sphinx: add max149x6 into drivers toc

---

projects/AD-ACEVSECRDSET-SL/Makefile
projects/AD-ACEVSECRDSET-SL/builds.json
projects/AD-ACEVSECRDSET-SL/src.mk
projects/AD-ACEVSECRDSET-SL/src/common/common_data.c
projects/AD-ACEVSECRDSET-SL/src/common/common_data.h
projects/AD-ACEVSECRDSET-SL/src/interface/interface.c
projects/AD-ACEVSECRDSET-SL/src/interface/interface.h
projects/AD-ACEVSECRDSET-SL/src/main.c
projects/AD-ACEVSECRDSET-SL/src/pilot/pilot.c
projects/AD-ACEVSECRDSET-SL/src/pilot/pilot.h
projects/AD-ACEVSECRDSET-SL/src/platform/parameters.c
projects/AD-ACEVSECRDSET-SL/src/platform/parameters.h
projects/AD-ACEVSECRDSET-SL/src/rcd/rcd.c
projects/AD-ACEVSECRDSET-SL/src/rcd/rcd.h
projects/AD-ACEVSECRDSET-SL/src/relay/relay.c
projects/AD-ACEVSECRDSET-SL/src/relay/relay.h
projects/AD-ACEVSECRDSET-SL/src/self_test/self_test.c
projects/AD-ACEVSECRDSET-SL/src/self_test/self_test.h
projects/AD-ACEVSECRDSET-SL/src/state_machine/state_machine.c
projects/AD-ACEVSECRDSET-SL/src/state_machine/state_machine.h
projects/AD-ACEVSECRDSET-SL/src/supply/supply.c
projects/AD-ACEVSECRDSET-SL/src/supply/supply.h

Add the AD-ACEVSECRDSET-SL project.
The [AD-ACEVSECRDSET-SL](https://www.analog.com/AD-ACEVSECRDSET-SL) is a complete Type 2 EVSE 3.6 kW charging cable solution, providing a reference design intended for evaluation and prototyping of EV charging systems.

projects: AD-ACEVSECRDSET-SL: Add project

---

drivers/adc-dac/ad74413r/iio_ad74413r.c

Update the digital input channel definition in order to use the proper attributes.
Update the digital input channel definition in order to use the proper attributes.

drivers:adc-dac:ad74413r: Fix digital input attrs

---

doc/sphinx/source/index.rst
doc/sphinx/source/projects/adrv902x.rst
doc/sphinx/source/projects_doc.rst

[doc: sphinx: add projects ToC](https://github.com/analogdevicesinc/no-OS/commit/d9b74950efe26cb84b84310ef0a503e4e7071db4)
[doc: sphinx: add adrv902x project doc](https://github.com/analogdevicesinc/no-OS/commit/e0da8cba1ad40875bf2ccce627a960be0e0ef6c9)

doc: sphinx: add projects ToC

---

doc/sphinx/source/drivers/adrv9025.rst
doc/sphinx/source/drivers_doc.rst
drivers/rf-transceiver/madura/README.rst

Add ADRV9025 driver sphinx documentation.

Add ADRV9025 driver documentation

---

tools/scripts/build_projects.py

For the build of STM32, in some cases a random failure appears, to handle this case a new run of the failed project is made.
If the new rerun exists also with error status this will be interpreted as a persistent error not a random one.
In case a project is build twice it is mentioned in the log message.

Handle STM32 random failure

---

doc/sphinx/source/drivers_guide.rst

Specify that the remove() does not set the provided pointer to NULL

document remove() function behavior

---

drivers/dac/ad5754r/ad5754r.c
drivers/dac/ad5754r/ad5754r.h

1. Add method for asynchronous clear
2. Add setter method for the tsd_en bitfield
3. Use tsd_en from init params and cache value in dev structure

drivers:dac:ad5754r: Add clear and tsd functions

---

projects/max14916/Makefile
projects/max14916/builds.json
projects/max14916/src.mk
projects/max14916/src/common/common_data.c
projects/max14916/src/common/common_data.h
projects/max14916/src/examples/basic/basic_example.c
projects/max14916/src/examples/basic/basic_example.h
projects/max14916/src/examples/examples_src.mk
projects/max14916/src/examples/iio_example/iio_example.c
projects/max14916/src/examples/iio_example/iio_example.h
projects/max14916/src/platform/maxim/main.c
projects/max14916/src/platform/maxim/parameters.c
projects/max14916/src/platform/maxim/parameters.h
projects/max14916/src/platform/maxim/platform_src.mk
projects/max14916/src/platform/platform_includes.h

Add initial header and source files for MAX14916.
This project was tested on the MAX32690 and MAX32666 microcontrollers and used the max149x6-base driver,
max14916 driver and max14916 iio driver as well.

projects: max14916 : Add project files for MAX14916

---

projects/max14906/Makefile
projects/max14906/builds.json
projects/max14906/src.mk
projects/max14906/src/common/common_data.c
projects/max14906/src/common/common_data.h
projects/max14906/src/examples/basic/basic_example.c
projects/max14906/src/examples/basic/basic_example.h
projects/max14906/src/examples/examples_src.mk
projects/max14906/src/examples/iio_example/iio_example.c
projects/max14906/src/examples/iio_example/iio_example.h
projects/max14906/src/platform/maxim/main.c
projects/max14906/src/platform/maxim/parameters.c
projects/max14906/src/platform/maxim/parameters.h
projects/max14906/src/platform/maxim/platform_src.mk
projects/max14906/src/platform/platform_includes.h

https://github.com/analogdevicesinc/no-OS/pull/1921 needs to be merged before this PR.
This PR contains an application example for MAX14906(both basic and IIO example in one file).
It has been tested on the MAX32666FTHR with the MAX14906PMB.

projects: max14906: Add application example for MAX14906

---

drivers/imu/README.rst

Add missing project examples links for adis1646x and adis1647x in the documentation.

drivers: imu: Update documentation

---

drivers/adc/ad469x/ad469x.h

Added the offset correction register to the register macro

drivers:adc:ad469x:Updated the register map

---

drivers/api/no_os_spi.c
drivers/platform/maxim/max32650/maxim_spi.c
drivers/platform/maxim/max32655/maxim_spi.c
drivers/platform/maxim/max32660/maxim_spi.c
drivers/platform/maxim/max32665/maxim_spi.c
drivers/platform/maxim/max32690/maxim_spi.c
drivers/platform/maxim/max78000/maxim_spi.c
include/no_os_spi.h
projects/swiot1l/src/common/common_data.c

Platform SPI delays

---

drivers/platform/stm32/stm32_spi.c

Rework stm32 spi driver such that it works with all platforms:
- use prescaler register value and remove SPI_CR1_BR_Pos usage which is not present for all stm32 families
- use generic HAL API for SPI transactions if SPI_SR_TXE is not defined.

platform: stm32: stm32_spi: Rework SPI driver

---

projects/max22190/Makefile
projects/max22190/builds.json
projects/max22190/src.mk
projects/max22190/src/common/common_data.c
projects/max22190/src/common/common_data.h
projects/max22190/src/examples/basic/basic_example.c
projects/max22190/src/examples/basic/basic_example.h
projects/max22190/src/examples/examples_src.mk
projects/max22190/src/examples/iio_example/iio_example.c
projects/max22190/src/examples/iio_example/iio_example.h
projects/max22190/src/platform/maxim/main.c
projects/max22190/src/platform/maxim/parameters.c
projects/max22190/src/platform/maxim/parameters.h
projects/max22190/src/platform/maxim/platform_src.mk
projects/max22190/src/platform/platform_includes.h

#1934 needs to be merged before this PR.
Only last commit is up for review in this PR.
This application example was tested with the max32690 microcontroller and max22190pmb.
The project contains 2 examples: dummy and iio_example.

projects: max22190 : Add project files for MAX22190

---

.github/CODEOWNERS

Add more members from the no-OS github team to the `ci` folder.

CODEOWNERS: add more owners for ci scripts

---

iio/iiod.c

Fix typo "Nonblockin"->"Nonblocking".

iio: iiod.c: fix typo in file description

---

doc/sphinx/source/drivers/max22196.rst
doc/sphinx/source/drivers_doc.rst

Add max22196.rst file to include MAX22196 README.rst Update drivers_doc.rst file to have max22196 appear in the list for digital-io.

doc: sphinx: source : Update documentation to include MAX22196

---

projects/eval-ade9430/README.md

Add the PLATFORM parameter in the make commands, otherwise the build will fail.

projects: eval-ade9430: README: add platform

---

projects/eval-ade9430/src/app/main.c
projects/eval-ade9430/src/app/parameters.h

[eval-ade9430: drop new line character for lcd](https://github.com/analogdevicesinc/no-OS/commit/190bfec06b5517ca943884d30f948b983a769a4d)
[eval-ade9430: use decimal values for rtc default](https://github.com/analogdevicesinc/no-OS/commit/a1b5c1c4bf5b74501c6955fa87a572fb44a25ea0)
[eval-ade9430: increase wifi reset delay](https://github.com/analogdevicesinc/no-OS/commit/38875d216c418c9ed5fd39e213f3295942a09f55)
[eval-ade9430: print timestamp in decimal format](https://github.com/analogdevicesinc/no-OS/commit/d238881e1ceba8acc8b9b2c9790942e6caff52ba)
[eval-ade9430: add green/red LED support](https://github.com/analogdevicesinc/no-OS/pull/2022/commits/4075eb07cd124873929108c8da75be8ba7d7623e)

eval-ade9430: project updates

---

tools/scripts/generic_variables.mk

Add maxim in the list of optional PLATFORM values.

tools: scripts: add maxim as available PLATFORM

---

build_projects.yml

Add trigger for release branches and also change the condition for saving artifacts to include the artifacts generated from release branches build.

Add trigger for release branches

---

projects/ad-acevsecrdset-sl/Makefile
projects/ad-acevsecrdset-sl/src/common/common_data.h
projects/ad-acevsecrdset-sl/src/platform/parameters.h
projects/ad-acevsecrdset-sl/src/self_test/self_test.c
projects/ad-acevsecrdset-sl/src/state_machine/state_machine.c
projects/ad-acevsecrdset-sl/src/state_machine/state_machine.h

Add the code for enabling operation in 120V power mains.
Make DEBUG messages display default.

Charger modifications

---

ci/lib.sh
ci/run_build.sh

[ci: lib.sh: drop ensure_command_exists wget](https://github.com/analogdevicesinc/no-OS/commit/50788a46092e8dc07881a8b18ca68ba9487407b1)
[ci: avoid duplicate function definition](https://github.com/analogdevicesinc/no-OS/commit/48bc9ad76a61230b56b0f756a8a6d1d0de5ef479)

ci: misc updates

---

drivers/adc/ad7616/ad7616.c
drivers/adc/ad7616/ad7616.h

This is preliminary work to get AD7616 working on SDP-K1 using STM32 hal. You can find the whole branch with a new project here, the hope is to get it merged too at some point (still some cleanup to do).
This PR is in draft state until I manage to test if `ad7616-sdz` project is still working.

driver: ad7616: Add support for generic no-os SPI

---

projects/demo_esp/src/common/common_data.h
projects/demo_esp/src/examples/basic/basic_example.c

[demo_esp: common_data: use generic param](https://github.com/analogdevicesinc/no-OS/commit/a9067a9d0bf21850a8ee573c7760b5667801bc0f)
[demo_esp: basic_example: update function name](https://github.com/analogdevicesinc/no-OS/commit/5fbe2538a0a4d944c28fe2d533695092c5961653)
[demo_esp: basic_example: increase wifi reset delay](https://github.com/analogdevicesinc/no-OS/commit/42dc98259f76a9cdc025eb0539740017e2b8ee65)

demo_esp: misc updates

---

drivers/adc-dac/ad74416h/ad74416h.c
drivers/adc-dac/ad74416h/ad74416h.h

Add function to set the digital output value via software.

adc-dac: ad74416h: add DO value setter func

---

doc/sphinx/source/drivers/axi_sysid.rst
doc/sphinx/source/drivers_doc.rst
drivers/axi_core/axi_sysid/README.rst
drivers/axi_core/axi_sysid/axi_sysid.c
drivers/axi_core/axi_sysid/axi_sysid.h

Add the driver for the System ID core.
Required for detecting carrier board for Xilinx projects. This will simplify parameters.h.

drivers: axi_core: axi_sysid: Add driver

---

drivers/dac/ltc2672/ltc2672.c
drivers/dac/ltc2672/ltc2672.h

Add dac code set, code conversion functions and
update current set functions

dac: ltc2672: add dac code set, conversion functions

---

iio/iio.c

iio network backend fixes

---

azure-pipelines.yml
build_projects.yml

Eliminate the trigger for master branch and also change the conditional variable for publish artifacts step.

Change variable for main branch

---

ci/gen_dox.sh

Create a list and pattern of uncommon driver paths than need special handling when generating the doxygen drivers ToC page.
Remove multiple if statements and replace them with a list that cand be easily extended when needed.

ci: gen_dox: update uncommon driver path handling

---

drivers/adc/ad4080/ad4080.c
drivers/adc/ad4080/ad4080.h

Update the register map to the latest available datasheet.
Update function implementation accordingly.

adc: ad4080: update regmap

---

drivers/adc/ad4080/ad4080.c
drivers/adc/ad4080/ad4080.h

Add device operation mode support within the driver.

adc: ad4080: add op mode support

---

drivers/api/no_os_irq.c
drivers/platform/maxim/max32650/maxim_irq.c
drivers/platform/maxim/max32655/maxim_irq.c
drivers/platform/maxim/max32660/maxim_irq.c
drivers/platform/maxim/max32665/maxim_irq.c
drivers/platform/maxim/max32670/maxim_irq.c
drivers/platform/maxim/max32690/maxim_irq.c
drivers/platform/maxim/max78000/maxim_irq.c
include/no_os_irq.h

- set event lists to NULL in order to mark them as free.
- implement reference counting for IRQ descriptors

Maxim IRQ fixes

---

drivers/dac/ad5791/ad5791.c
drivers/dac/ad5791/ad5791.h

Add ldac toggle and clear async apis and fix
set_lin_comp api

dac: ad5791: Add APIs for clear, LDAC

---

tools/scripts/build_projects.py

Change variable from master to main in order to download proper artifacts

Change from master to main

---

drivers/adc/ad7616/ad7616.c
drivers/adc/ad7616/ad7616.h
drivers/adc/ad7616/iio_ad7616.c
projects/ad7616-sdz/builds.json
projects/ad7616-sdz/src.mk
projects/ad7616-sdz/src/ad7616_sdz.c
projects/ad7616-sdz/src/parameters.h

The `ad7616-sdz` project was found broken recently. This PR aims to make it work again using the latest version of the HDL.

Update ad7616-sdz project

---

build_projects.yml
tools/scripts/build_projects.py
tools/scripts/download_files.py

Some projects from hdl are failing, in order to ignore this failing projects on hdl side a 'blacklist' was created.
This list is now processed in no-os to skip the build for those projects as well.
The build branch needs to be exported because of the changes regarding blacklist integration.

Integrate blacklist in no-os build

---

doc/sphinx/source/projects/ad7616-st.rst
doc/sphinx/source/projects_doc.rst
projects/ad7616-st/README.rst

This projects does not have a README. Add one that link to the already present [ADI wiki user guide](https://wiki.analog.com/resources/eval/user-guides/ad7616-sdz#sdp-k1_setup).
This was asked [here](https://github.com/analogdevicesinc/no-OS/pull/2000#pullrequestreview-1815155571). Since I already did the wiki guide I linked it here.

projects: ad7616-st: Add README

---

tools/scripts/aducm.mk
tools/scripts/altera.mk
tools/scripts/generic.mk
tools/scripts/linux.mk
tools/scripts/maxim.mk
tools/scripts/mbed.mk
tools/scripts/pico.mk
tools/scripts/stm32.mk
tools/scripts/xilinx.mk

build cleanup

---

drivers/adc/ad7616/iio_ad7616.c
projects/ad7616-st/builds.json
projects/ad7616-st/src/platform/stm32/main.c
projects/ad7616-st/src/platform/stm32/parameters.c
projects/ad7616-st/src/platform/stm32/parameters.h

This aims to improve the sample rate of the ad7616 projects.

Performance improvement for the ad7616 drivers and its SDP-K1 project 

---

doc/sphinx/source/drivers/adp1050.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/adp1050.rst
doc/sphinx/source/projects_doc.rst
drivers/power/adp1050/README.rst
drivers/power/adp1050/adp1050.c
drivers/power/adp1050/adp1050.h
drivers/power/adp1050/iio_adp1050.c
drivers/power/adp1050/iio_adp1050.h
projects/adp1050/Makefile
projects/adp1050/README.rst
projects/adp1050/builds.json
projects/adp1050/src.mk
projects/adp1050/src/common/common_data.c
projects/adp1050/src/common/common_data.h
projects/adp1050/src/examples/basic/basic_example.c
projects/adp1050/src/examples/basic/basic_example.h
projects/adp1050/src/examples/examples_src.mk
projects/adp1050/src/examples/iio_example/iio_example.c
projects/adp1050/src/examples/iio_example/iio_example.h
projects/adp1050/src/platform/maxim/main.c
projects/adp1050/src/platform/maxim/parameters.c
projects/adp1050/src/platform/maxim/parameters.h
projects/adp1050/src/platform/maxim/platform_src.mk
projects/adp1050/src/platform/platform_includes.h

The ADP1050 is an advanced digital controller with a PMBus™
interface targeting high density, high efficiency dc-to-dc power 
conversion. This controller implements voltage mode control 
with high speed, input voltage feedforward operation for 
enhanced transient and noise performance. The ADP1050 has
four programmable pulse-width modulation (PWM) outputs 
capable of controlling most high efficiency power supply 
topologies, with the added control of synchronous rectification (SR). 
The ADP1050 implements several features to enable a robust 
system of parallel and redundant operation for customers who
require high availability. The device provides synchronization, 
prebias startup, and conditional overvoltage techniques to 
identify and safely shut down an erroneous power supply in …

drivers: power: adp1050 : Add driver support for ADP1050

---

README.md
ci/documentation.sh
ci/lib.sh

- [ci: documentation: update source branch](https://github.com/analogdevicesinc/no-OS/commit/1f52f4ca8ce5802a78b34f82026863f2fa7659e3)
- [ci: lib: download scripts from main](https://github.com/analogdevicesinc/no-OS/commit/8b1ac766f708b8b8a1808aad4308083af363c8bb)

ci: documentation: branch updates

---

ci/release/upload_to_artifactory.py
doc/sphinx/source/drivers_guide.rst

[doc: sphinx: update drivers guide branch](https://github.com/analogdevicesinc/no-OS/commit/9ca323a6e670f42ebc4d9cca01445aa1c772c127)
[ci: release: update hdl branch to main](https://github.com/analogdevicesinc/no-OS/pull/2103/commits/83427f458095c08493397538c22d3df5bf2c7dd5)

ci: release: update hdl branch to main

---

drivers/imu/README.rst
projects/adp1050/README.rst
projects/adrv902x/README.rst
projects/eval-adis1646x/README.rst
projects/eval-adis1647x/README.rst
projects/eval-adis1650x/README.rst
projects/eval-adis1657x/README.rst
projects/max14914/README.rst
projects/max14919/README.rst

Update links to point to the main branch instead of master branch.

driver: imu: update branch in doc

---

drivers/platform/maxim/max32650/maxim_uart.c
drivers/platform/maxim/max32655/maxim_uart.c
drivers/platform/maxim/max32660/maxim_uart.c
drivers/platform/maxim/max32665/maxim_uart.c
drivers/platform/maxim/max32690/maxim_uart.c
drivers/platform/maxim/max78000/maxim_uart.c

drivers/maxim: solves unused variable warning

---

projects/ad9361/src/parameters.h

Set the ZCU102 pins for the FMCOMMS5 project to match the latest HDL.

ad9361: src: parameters.h: ZCU102 pins for FMCOMMS5

---

build_projects.yml

A new group of variables was created in azure just for next_stable branch and now we point to that one.

build_projects.yml: change group variable for next_stable

---

drivers/adc/ad4858/ad4858.c

Fixed reading raw value from 24 bit packet.
initialized product id variables to 0 in init function. Fixed the way the adc move to data interface mode.

drivers:adc:ad4858: bug fix

---

drivers/adc-dac/ad74416h/ad74416h.h

Fix minor typo for type declaration comments.
Fixes: f402d21 ("drivers:adc-dac:ad74416h: initial commit")

adc-dac: ad74416h: fix minor typo

---

drivers/adc/ad4858/ad4858.c
drivers/adc/ad4858/ad4858.h

Added sleep and SHDR support in driver

drivers:adc:ad4858: Added new feature

---

projects/adrv902x/README.rst

ADRV902X - Update documentation regarding changes between use cases
No functional changes

ADRV902X - Update documentation regarding changes between use cases

---

drivers/adc/ad7124/ad7124.c
drivers/adc/ad7124/ad7124.h

Added an API power mode and called it during the setup. Added a uint16_t status variable in enable input buffers and channel select API as the previous bool variable cannot hold the same. Added a comment for updated IDs of the newer boards.

drivers:ad7124: Minor fixes and updates to ad7124 drivers

---

projects/adrv902x/README.rst
projects/adrv902x/json2cstring.sh

Madura script for converting profile json to header file.
Update documentation.

Madura script for converting profile jeson to header file

---

projects/adrv902x/csv2cstring.sh

Add script that generates the header files correspoding to ADRV9025_RxGainTable.csv and ADRV9025_TxAttenTable.csv.

Add the csv2cstring.sh script

---

projects/adrv902x/src/examples/iio_example/iio_example.c

Set DDS initial parameters for the IIO example.
Fixes: ab393ac ("projects: adrv9025: Madura project")

adrv902x: iio_example.c: Set DDS initial parameters

---

projects/adrv902x/src/examples/basic_example/basic_example.c

Start DDS before activating JESD for the basic_example.
Fixes: ab393ac ("projects: adrv9025: Madura project")

Start DDS before enabling JESD

---

drivers/axi_core/jesd204/axi_adxcvr.c

drivers: axi_core: jesd204: axi_adxcvr: Add JESD204C

---

drivers/adc/ad7124/ad7124.c

Fixing condition check for ID register value.

drivers:adc:ad7124:Fixing Bad Comparison

---

drivers/platform/stm32/stm32_dma.c
drivers/platform/stm32/stm32_dma.h
drivers/platform/stm32/stm32_irq.c
drivers/platform/stm32/stm32_spi.c
drivers/platform/stm32/stm32_spi.h
projects/ad738x-st/src.mk
projects/ad738x-st/src/platform/stm32/platform_src.mk
projects/ad74413r/src/platform/stm32/platform_src.mk
projects/ad74416h/src.mk
projects/ad74416h/src/platform/stm32/platform_src.mk
projects/ad7616-st/src.mk
projects/ad7616-st/src/platform/stm32/platform_src.mk
projects/adxrs290-pmdz/src.mk
projects/adxrs290-pmdz/src/platform/stm32/platform_src.mk
projects/cn0565/src.mk
projects/eval-adis1646x/src/platform/stm32/platform_src.mk
projects/eval-adis1647x/src/platform/stm32/platform_src.mk
projects/eval-adis1650x/src/platform/stm32/platform_src.mk
projects/eval-adis1657x/src/platform/stm32/platform_src.mk
projects/eval-adxl313z/src/platform/stm32/platform_src.mk
projects/eval-adxl355-pmdz/src/platform/stm32/platform_src.mk
projects/max14906/src/platform/stm32/platform_src.mk

Added STM32 DMA platform driver

drivers:platform:stm32:Added DMA Driver

---

drivers/dac/ad5460/ad5460.c
drivers/dac/ad5460/ad5460.h
projects/ad5460/Makefile
projects/ad5460/builds.json
projects/ad5460/src.mk
projects/ad5460/src/common/common_data.c
projects/ad5460/src/common/common_data.h
projects/ad5460/src/examples/basic/basic_example.c
projects/ad5460/src/examples/basic/basic_example.h
projects/ad5460/src/examples/examples_src.mk
projects/ad5460/src/platform/mbed/main.c
projects/ad5460/src/platform/mbed/parameters.c
projects/ad5460/src/platform/mbed/parameters.h
projects/ad5460/src/platform/mbed/platform_src.mk
projects/ad5460/src/platform/platform_includes.h

Similar to ad74416h the driver is not yet public.
The documentation will be added when the part will become available.
This PR adds driver support and a basic application aimed for testing purposes.

ad5460: initial driver & application

---

drivers/adc/ad7091r8/ad7091r8.c
drivers/adc/ad7091r8/ad7091r8.h

Add updates to the driver & Fix set_port api
Add sleep mode part of the init_param, device structures.
Update init function to configure sleep mode.
Update set_sleep_mode API.
Add spi_write_mask function declaration to the header file.
Fix ad7091r8_set_port api

Ad7091r updates

---

util/no_os_util.c

The greatest common divisor in the previous version was executing slow. In most cases this will not be noticeable, but some drivers will need a faster execution of the GCD in order to reduce the response time of those drivers. This has been noticed with the ADF4382 and has been tested with the design to check that the new implementation is working.

util: no_os_util: Update GCD for faster execution

---

tools/scripts/generic.mk
tools/scripts/maxim.mk

A couple fixes for the build system.

tools: scripts: Properly handle assembly files

---

drivers/platform/stm32/stm32_spi.c

Added an STM32H5 check to remove compiler errors with STM32H5 platform

drivers:platform:stm32: Updated STM32 SPI Drivers

---

projects/ad5460/Makefile
projects/ad5460/builds.json
projects/ad5460/src/examples/channel_output_example/channel_output_example.c
projects/ad5460/src/examples/channel_output_example/channel_output_example.h
projects/ad5460/src/examples/current_output_example/current_output_example.c
projects/ad5460/src/examples/current_output_example/current_output_example.h
projects/ad5460/src/examples/examples_src.mk
projects/ad5460/src/examples/voltage_output_example/voltage_output_example.c
projects/ad5460/src/examples/voltage_output_example/voltage_output_example.h

[projects: ad5460: add channel output example](https://github.com/analogdevicesinc/no-OS/commit/309a9109160f998fb6ef9885f0dafcfd240ef9f6)
[projects: ad5460: add voltage output example](https://github.com/analogdevicesinc/no-OS/commit/3f2aa8258666ba868de0eaac8cd7ef36c5f59423)
[projects: ad5460: add current output example](https://github.com/analogdevicesinc/no-OS/commit/91f8e0b29b2701bcde5b1934f6bad05b6e6df057)

projects: ad5460: add project examples

---

tools/scripts/aducm.mk
tools/scripts/altera.mk
tools/scripts/generic.mk
tools/scripts/linux.mk
tools/scripts/maxim.mk
tools/scripts/mbed.mk
tools/scripts/pico.mk
tools/scripts/stm32.mk
tools/scripts/xilinx.mk

Fix 86d407b ("tools: scripts: Delete .vscode on reset").

Add platform specific reset target

---

drivers/adc/ad4170/ad4170.c
drivers/adc/ad4170/ad4170.h

Initial driver version with a device driver API that covers direct register access and higher level chip specific functionality.

add ad4170 device driver

---

doc/sphinx/source/projects_doc.rst
projects/ad400x-fmcz/README.rst

Fixing a couple of comments from Michael Bradly about the current documentation.

Small Documentation updates

---

tools/scripts/download_files.py

Add log_warn function to clearly emphasize in the build log if some artifacts are missing/outdated.

tools: scripts: download_files.py: add log_warn

---

projects/adrv9009/src/app/headless.c

Add IIO example for ADRV9008-2.

Adrv9008-2 IIO update

---

tools/scripts/linux.mk

Fixing:
*** No rule to make target 'linux_post_build', needed by 'post_build'

tools: scripts: linux: Add mandatory post_build target

---

projects/adrv9009/src/app/app_talise.c

Update adrv9008-2 JESD bring up

Adrv9008-2 JESD bring up

---

projects/ad-acevsecrdset-sl/Makefile
projects/ad-acevsecrdset-sl/src.mk
projects/ad-acevsecrdset-sl/src/common/common_data.c
projects/ad-acevsecrdset-sl/src/common/common_data.h
projects/ad-acevsecrdset-sl/src/inter/inter.c
projects/ad-acevsecrdset-sl/src/inter/inter.h
projects/ad-acevsecrdset-sl/src/interface/interface.c
projects/ad-acevsecrdset-sl/src/platform/parameters.h
projects/ad-acevsecrdset-sl/src/self_test/self_test.c
projects/ad-acevsecrdset-sl/src/self_test/self_test.h
projects/ad-acevsecrdset-sl/src/state_machine/state_machine.c
projects/ad-acevsecrdset-sl/src/state_machine/state_machine.h

rev_D functionality

---

drivers/api/no_os_dma.c
drivers/platform/stm32/stm32_irq.c
include/no_os_dma.h

Some fixes that jumped to my attention while looking

fixes for no_os_dma and stm32_dma

---

tools/scripts/generic_variables.mk
tools/scripts/maxim.mk
tools/scripts/stm32.mk
tools/scripts/xilinx.mk

While linking external libraries it is helpful to have a generic option for floating-point flag

tools: scripts: add generic floating-point option

---

drivers/meter/ade9113/ade9113.c
drivers/meter/ade9113/ade9113.h
projects/ad-acevsecrdset-sl/src/platform/parameters.h
projects/ad-acevsecrdset-sl/src/self_test/self_test.c
projects/ad-acevsecrdset-sl/src/self_test/self_test.h
projects/ad-acevsecrdset-sl/src/state_machine/state_machine.c
projects/ad-acevsecrdset-sl/src/state_machine/state_machine.h
projects/ad-acevsecrdset-sl/src/supply/supply.c
projects/ad-acevsecrdset-sl/src/supply/supply.h

Add rms function for measurements.

Stout dev2

---

build_projects.yml
projects/iio_demo/builds.json
tools/scripts/download_files.py

Cherry-pick from main for next_stable.

Cherry picks for next_stable

---

drivers/adc/ad7606/ad7606.c

drivers: ad7606: add name field to chip info table (for debugging)

---

projects/adv7511/src/main.c

Set I2C device ID for I2C MUX.

projects: adv7511: src: main.c: Set I2C device ID

---

projects/adrv902x/src/common/app_config.h

Set baud rate to 921600 for IIOD.

adrv902x: src: common: app_config.h: Set higher baud for IIOD

---

drivers/axi_core/axi_dmac/axi_dmac.c
drivers/axi_core/spi_engine/spi_engine.c

##Offload transfer fixes
fixes needed for offload to not return early and invalid data to be sent to the user.

Offload transfer fixes

---

drivers/adc/ad7606/ad7606.c
drivers/adc/ad7606/ad7606.h

Just a bunch of cleanups before coming in with some more changes

ad7606: minor cleanups

---

drivers/meter/ade9113/ade9113.c
drivers/meter/ade9113/ade9113.h
projects/ad-acevsecrdset-sl/src/supply/supply.c

Add ADE9113 daisy-chain operation.

Ade9113 daisy

---

projects/eval-pqmon/Makefile
projects/eval-pqmon/README.md
projects/eval-pqmon/src.mk
projects/eval-pqmon/src/common/afe_config.c
projects/eval-pqmon/src/common/afe_config.h
projects/eval-pqmon/src/common/common_data.c
projects/eval-pqmon/src/common/common_data.h
projects/eval-pqmon/src/common/common_src.mk
projects/eval-pqmon/src/common/iio_pqm.c
projects/eval-pqmon/src/common/iio_pqm.h
projects/eval-pqmon/src/common/intrpt_handler.c
projects/eval-pqmon/src/common/intrpt_handler.h
projects/eval-pqmon/src/common/pqlib_afe.c
projects/eval-pqmon/src/common/pqlib_afe.h
projects/eval-pqmon/src/common/pqlib_convert.c
projects/eval-pqmon/src/common/pqlib_convert.h
projects/eval-pqmon/src/common/pqlib_example.c
projects/eval-pqmon/src/common/pqlib_example.h
projects/eval-pqmon/src/common/status.h
projects/eval-pqmon/src/examples/basic/basic_example.c
projects/eval-pqmon/src/examples/basic/basic_example.h
projects/eval-pqmon/src/examples/examples_src.mk
projects/eval-pqmon/src/platform/maxim/main.c
projects/eval-pqmon/src/platform/maxim/parameters.c
projects/eval-pqmon/src/platform/maxim/parameters.h
projects/eval-pqmon/src/platform/maxim/platform_src.mk
projects/eval-pqmon/src/platform/platform_includes.h

projects: add eval-pqmon

---

drivers/rtc/max31343/max31343.c
drivers/rtc/max31343/max31343.h

Add support for https://www.analog.com/en/products/max31343.html

drivers: rtc: add support for max31343 real-time-clock

---

iio/iio.c
iio/iio_types.h

Add support for weight as a channel type in IIO

iio: Add support for Weight

---

doc/sphinx/source/drivers/lt7182s.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/lt7182s.rst
doc/sphinx/source/projects_doc.rst
drivers/power/lt7182s/README.rst
drivers/power/lt7182s/iio_lt7182s.c
drivers/power/lt7182s/iio_lt7182s.h
drivers/power/lt7182s/lt7182s.c
drivers/power/lt7182s/lt7182s.h
projects/lt7182s/Makefile
projects/lt7182s/README.rst
projects/lt7182s/builds.json
projects/lt7182s/src.mk
projects/lt7182s/src/common/common_data.c
projects/lt7182s/src/common/common_data.h
projects/lt7182s/src/examples/basic/basic_example.c
projects/lt7182s/src/examples/basic/basic_example.h
projects/lt7182s/src/examples/examples_src.mk
projects/lt7182s/src/examples/iio_example/iio_example.c
projects/lt7182s/src/examples/iio_example/iio_example.h
projects/lt7182s/src/platform/maxim/main.c
projects/lt7182s/src/platform/maxim/parameters.c
projects/lt7182s/src/platform/maxim/parameters.h
projects/lt7182s/src/platform/maxim/platform_src.mk
projects/lt7182s/src/platform/platform_includes.h

The LT7182S is a dual-output monolithic PolyPhase DC/DC synchronous step-down
regulator that delivers up to 6A of continuous current from both channels
simultaneously and supports loads up to 8A from either channel. The LT7182S
features the second generation Silent Switcher architecture with integrated VIN
bypass capacitors for fast, clean, low-overshoot switching edges delivering high
efficiency at high switching frequencies while minimizing EMI emissions.

drivers: power: lt7182s: Add driver support for LT7182S

---

doc/sphinx/source/drivers/lt8722.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/lt8722.rst
doc/sphinx/source/projects_doc.rst
drivers/power/lt8722/README.rst
drivers/power/lt8722/iio_lt8722.c
drivers/power/lt8722/iio_lt8722.h
drivers/power/lt8722/lt8722.c
drivers/power/lt8722/lt8722.h
projects/lt8722/Makefile
projects/lt8722/README.rst
projects/lt8722/builds.json
projects/lt8722/src.mk
projects/lt8722/src/common/common_data.c
projects/lt8722/src/common/common_data.h
projects/lt8722/src/examples/basic/basic_example.c
projects/lt8722/src/examples/basic/basic_example.h
projects/lt8722/src/examples/examples_src.mk
projects/lt8722/src/examples/iio_example/iio_example.c
projects/lt8722/src/examples/iio_example/iio_example.h
projects/lt8722/src/platform/maxim/main.c
projects/lt8722/src/platform/maxim/parameters.c
projects/lt8722/src/platform/maxim/parameters.h
projects/lt8722/src/platform/maxim/platform_src.mk
projects/lt8722/src/platform/platform_includes.h

The LT8722 is a high performance, high efficiency, monolithic full bridge DC/DC
converter. One side of the full bridge is driven by a pulse width modulation
(PWM) buck power stage, while the other side of the full bridge is driven by
a linear power stage. The LT8722 can deliver up to ±54W of power to its load
while only requiring a single inductor. An integrated 25-bit digital-to-analog
converter (DAC) is used to control the LT8722 output voltage. Two additional
9-bit DACs control the positive and negative output current limits. An analog
output telemetry pin can be used to monitor SPI selectable parameters such as
VIN, VOUT, IOUT or the LT8722 junction temperature. The serial peripheral
interface (SPI) can be used to configure and control the LT8722 allowing for
flexibility to set the …

drivers: power: lt8722: Add driver support for LT8722

---

drivers/rf-transceiver/madura/adrv9025.c
drivers/rf-transceiver/madura/adrv9025.h
projects/adrv902x/src/examples/basic_example/basic_example.c
projects/adrv902x/src/examples/dma_example/dma_example.c
projects/adrv902x/src/examples/iio_example/iio_example.c

Add AGC config and possibility to change the Rx gain control mode

Add AGC config and possibility to change the Rx gain control mode

---

drivers/adc/ad738x/iio_ad738x.c

drivers: iio_ad738x: remove unreachable return

---

iio/iio_app/iio_app.c

iio-app: minor fixes and tweaks found in iio_app_init()

---

drivers/rf-transceiver/madura/adrv9025.c
drivers/rf-transceiver/madura/adrv9025.h
drivers/rf-transceiver/madura/common/adi_common_user.h
projects/adrv902x/src/common/app_config.h
projects/adrv902x/src/examples/basic_example/basic_example.c
projects/adrv902x/src/examples/dma_example/dma_example.c
projects/adrv902x/src/examples/iio_example/iio_example.c
projects/adrv902x/src/platform/xilinx/parameters.h

Add MicroBlaze support for Madura and minor improvements

Add MicroBlaze support for Madura and minor improvements

---

drivers/adc/ad4858/ad4858.c
drivers/adc/ad4858/ad4858.h

Enable support for the rest of the ad485x product IDs.

drivers: adc: ad485x extend support for ad485x family

---

drivers/platform/stm32/stm32_spi.c

Dummy read in spi dma callback function clears appropriate data register

Dummy read to clear any pending read on SPI

---

drivers/adc/ad7606/ad7606.c
drivers/adc/ad7606/ad7606.h
projects/ad7606x-fmc/src/common_data.c

Misc changes added before adding the IIO example project.

drivers: ad7606: misc changes to provide support for IIO-example project

---

drivers/adc/ad405x/README.rst

Replace a max2201x occurence with ad405x

minor fix in ad405x documentation

---

projects/eval-pqmon/src/common/iio_pqm.c
projects/eval-pqmon/src/common/pqlib_afe.c

project:eval-pqmon: small fixes on waveform buffer

---

network/tcp_socket.c

There are some code formatting issues is the network directory. Run astyle to fix them.

network: Apply new astyle config

---

doc/sphinx/source/drivers/ltc4162l.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/ltc4162l.rst
doc/sphinx/source/projects_doc.rst
drivers/power/ltc4162l/README.rst
drivers/power/ltc4162l/iio_ltc4162l.c
drivers/power/ltc4162l/iio_ltc4162l.h
drivers/power/ltc4162l/ltc4162l.c
drivers/power/ltc4162l/ltc4162l.h
projects/ltc4162l/Makefile
projects/ltc4162l/README.rst
projects/ltc4162l/builds.json
projects/ltc4162l/src.mk
projects/ltc4162l/src/common/common_data.c
projects/ltc4162l/src/common/common_data.h
projects/ltc4162l/src/examples/basic/basic_example.c
projects/ltc4162l/src/examples/basic/basic_example.h
projects/ltc4162l/src/examples/examples_src.mk
projects/ltc4162l/src/examples/iio_example/iio_example.c
projects/ltc4162l/src/examples/iio_example/iio_example.h
projects/ltc4162l/src/platform/maxim/main.c
projects/ltc4162l/src/platform/maxim/parameters.c
projects/ltc4162l/src/platform/maxim/parameters.h
projects/ltc4162l/src/platform/maxim/platform_src.mk
projects/ltc4162l/src/platform/platform_includes.h

Add support for LTC4162L

---

drivers/rf-transceiver/madura/devices/adrv9025/private/include/adrv9025_bf_hal.h
projects/adrv902x/builds.json

Remove commented includes.
Fixes: 98ae8c4 ("Remove the wrong SPDX details")

madura: adrv9025_bf_hal.h: Remove comment

---

drivers/accel/adxl38x/adxl38x.c

Adxl38x ID fix

---

projects/adrv9009/arm_src.mk
projects/adrv9009/mb_src.mk
projects/adrv9009/src/app/headless_arm.c
projects/adrv9009/src/app/headless_mb.c

Rename headless.c and headless1.c files to headless_arm.c and headless_mb.c to better show the target for each one.
No functional change.

projects: adrv9009: src: Rename headless files

---

drivers/adc/ad9656/ad9656.c
drivers/frequency/ad9508/ad9508.c
drivers/frequency/ad9553/ad9553.c
projects/ad9656_fmc/src/app/ad9656_fmc.c

Update of the ad9656_fmc project.

Driver updates ad95xx

---

doc/sphinx/source/contributing.rst

[doc: sphinx: contributing: update astyle command](https://github.com/analogdevicesinc/no-OS/commit/c9f9c476077f542385adb491fff8d837b568746b)
[doc: sphinx: contributing: add 50/72 rule](https://github.com/analogdevicesinc/no-OS/commit/fed496354f6a3cb8289ee2ac4e2f67d1e861798b)
[doc: sphinx: contributing: add commit prefix doc](https://github.com/analogdevicesinc/no-OS/commit/6d4b9735dd72773aede649d41e85d859b9dc9132)

doc: sphinx: contributing: update submission checklist

---

.github/PULL_REQUEST_TEMPLATE.md

Add the submission checklist into the PR checklist.
This aims to ease the review process, since most of the topics are anyways required and repeated all over again through personal review.

github: pr_template: add submission checklist

---

projects/ad74416h/builds.json
projects/ad74416h/src/examples/digital_input_logic/digital_input_logic.c
projects/ad74416h/src/examples/digital_input_loop/digital_input_loop.c
projects/ad74416h/src/examples/digital_output/digital_output.c
projects/ad74416h/src/examples/temperature_2wire_rtd/temperature_2wire_rtd.c
projects/ad74416h/src/examples/temperature_3wire_rtd/temperature_3wire_rtd.c

[projects: ad74416h: add digital input logic](https://github.com/analogdevicesinc/no-OS/commit/246b7bd6cde060454a502917ac09f177bab10599)
[projects: ad74416h: add digital input loop](https://github.com/analogdevicesinc/no-OS/commit/4fe04d8501669dce0592685b4f6f82c4663a0e7f)
[projects: ad74416h: add digital output example](https://github.com/analogdevicesinc/no-OS/commit/257e19e950f895516b0d7e63486a04241578cb0f)
[projects: ad74416h: add temp 2wire rtd](https://github.com/analogdevicesinc/no-OS/commit/73dc1a0b32a9f6db3c6b6e1f07544d33abe8225a)
[projects: ad74416h: add temp 3wire rtd](https://github.com/analogdevicesinc/no-OS/commit/37d07993571e72ce9856e9c704927308a9f8e8b8)

projects: ad74416h: add examples p2

---

projects/adrv9001/src/app/headless.c

Set correct sample number for the DMA example.

projects: adrv9001: headless.c: Set sample number

---

projects/eval-pqmon/src/common/iio_pqm.c

- for py-adi usage, buffer type modified to signed
- for better representation, event specific channels are no longer defined as scan elements

Pqm channel type

---

doc/sphinx/source/build_guide.rst
doc/sphinx/source/build_guides/build_maxim.rst
doc/sphinx/source/index.rst

doc: sphinx: Add building instructions for Maxim

---

projects/adrv9001/builds.json
projects/adrv9001/src/app/headless.c

Set correct DMA_EXAMPLE macro for the ADRV9001 DMA example.

ADRV9001 DMA example

---

doc/sphinx/source/drivers/ad7768-1.rst
doc/sphinx/source/drivers_doc.rst
drivers/adc/ad7768-1/README.rst

Signed-off-by: {jvelasc2} <joyce.velasco@analog.com>
This adds the rst readme document for the AD7768-1 driver.
Also modified the sphinx driver doc to add the corresponding source for this new readme.

drivers: adc: ad7768-1 : Add README documentation for AD7768-1

---

ci/cppcheck.sh
ci/run_build.sh

Fix checks

---

drivers/dac/ad3552r/ad3552r.c
drivers/dac/ad3552r/ad3552r.h

Add compile time checks for AXI function calls and header includes

drivers:dac:ad3552r: Fix build failures for platforms other than xilinx

---

projects/max14916/src/examples/iio_example/iio_example.mk
projects/max31827-evkit/src/examples/iio_example/iio_example.mk

Add remaining iio_example.mk files for max14916 and max31827-evkit projects.

projects: max14916 : Add iio_example.mk file

---

tools/scripts/build_projects.py

The bitbucket project was migrated to github and the download command needs to be updated to use github API.

Update command for blacklist download

---

drivers/display/ssd_1306/ssd_1306.c
drivers/display/ssd_1306/ssd_1306.h

SSD1306 supports I2C as well, besides SPI

drivers: display: make ssd1306 driver i2c compatible

---

projects/ad3552r_fmcz/builds.json

Change the name of the project to be the as the hdl one.

projects: ad3552r_fmcz: builds.json: update project name

---

doc/sphinx/source/drivers/ad9083.rst
doc/sphinx/source/drivers_doc.rst
drivers/adc/ad9083/README.rst

Signed-off-by: {jvelasc2} <joyce.velasco@analog.com>
This adds the rst readme document for the AD9083 driver.
Also modified the sphinx driver doc to add the corresponding source for this new readme

drivers: adc: ad9083 : Add README documentation for AD9083

---

drivers/display/display.c
drivers/display/display.h
drivers/display/ssd_1306/ssd_1306.c
drivers/display/ssd_1306/ssd_1306.h

Extend display api
Extend API with buffer print, that allows printing pixel wise images.

Extend display api

---

projects/ad9371/src/app/headless.c
projects/ad9371/src/devices/adi_hal/parameters.h

Init Rx and ORx DMAs for IIO app.

ad9371 IIO app

---

drivers/frequency/adf4382/adf4382.h

Add header guard to avoid multiple inclusion issues.

drivers: adf4382: add header guard

---

projects/ad9172/src/main.c

Add text indicating data that is sent in the DMA example.

projects: ad9172: src: main.c: Add DMA text

---

projects/ad6676-ebz/src/ad6676_ebz.c

Minor corrections for the AD6676 sample project:
- solve PN23 error issue
- display text messages for the DMA transfers

Ad6676 work

---

projects/ad9081/Makefile

Set flag in Makefile so that the basic project does not use IIOD.

projects: ad9081: Makefile: No IIOD by default

---

doc/sphinx/source/drivers/ade7913.rst
doc/sphinx/source/drivers_doc.rst
drivers/meter/ade7913/README.rst

Added the rst readme document for the ADE7913 driver.
Also modified the sphinx driver doc to add the corresponding source for this new readme.

drivers: meter: ade7913 : Add README documentation for ADE7913

---

doc/sphinx/source/drivers/ad74416h.rst
doc/sphinx/source/drivers_doc.rst
drivers/adc-dac/ad74416h/README.rst

Added the rst readme document for the AD74416H driver.
Also modified the sphinx driver doc to add the corresponding source for this new readme.

drivers: adc-dac: ad74416h: Add README documentation for AD74416H

---

projects/ad7768-1fmcz/src/ad77681evb.c

ad7768-1 work

---

drivers/potentiometer/ad514x/ad5141.c
drivers/potentiometer/ad514x/ad5141.h
drivers/potentiometer/ad514x/ad5142.c
drivers/potentiometer/ad514x/ad5142.h
drivers/potentiometer/ad514x/ad5143.c
drivers/potentiometer/ad514x/ad5143.h
drivers/potentiometer/ad514x/ad5144.c
drivers/potentiometer/ad514x/ad5144.h
drivers/potentiometer/ad514x/ad51xx_cmd.h
drivers/potentiometer/common/dpot.c
drivers/potentiometer/common/dpot.h

Digipot driver for AD514x family 

---

projects/ad469x_evb/src/examples/iio_example/iio_example.c

Display example message regarding device reading sequence.

ad469x_evb: iio_example.c: Display example message

---

doc/sphinx/source/drivers/adxrs290.rst
doc/sphinx/source/drivers_doc.rst
drivers/gyro/adxrs290/README.rst

Added the rst readme document for the ADXRS290 driver.
Also modified the sphinx driver doc to add the corresponding source for this new readme.

drivers: gyro: adxrs290: Add README documentation for ADXRS290

---

doc/sphinx/source/drivers/ad9208.rst
doc/sphinx/source/drivers_doc.rst
drivers/adc/ad9208/README.rst

Signed-off-by: Ramos <cayetonallan.ramos@analog.com>
This adds the .rst file and readme document for AD9208 driver. Also modified the sphinx driver doc to add the source for this readme document.
This adds the .rst file and readme document for AD9208 driver. Also modified the sphinx driver doc to add the source for this readme document.

drivers: adc: ad9208: Added README documentation for AD9208

---

doc/sphinx/source/drivers/adf4030.rst
doc/sphinx/source/drivers_doc.rst
doc/sphinx/source/projects/adf4030.rst
doc/sphinx/source/projects_doc.rst
drivers/frequency/adf4030/README.rst
drivers/frequency/adf4030/adf4030.c
drivers/frequency/adf4030/adf4030.h
drivers/frequency/adf4030/iio_adf4030.c
drivers/frequency/adf4030/iio_adf4030.h
projects/adf4030/Makefile
projects/adf4030/README.rst
projects/adf4030/builds.json
projects/adf4030/src.mk
projects/adf4030/src/common/common_data.c
projects/adf4030/src/common/common_data.h
projects/adf4030/src/examples/basic/basic_example.c
projects/adf4030/src/examples/basic/basic_example.h
projects/adf4030/src/examples/examples_src.mk
projects/adf4030/src/examples/iio_example/iio_example.c
projects/adf4030/src/examples/iio_example/iio_example.h
projects/adf4030/src/platform/mbed/main.c
projects/adf4030/src/platform/mbed/parameters.c
projects/adf4030/src/platform/mbed/parameters.h
projects/adf4030/src/platform/mbed/platform_src.mk
projects/adf4030/src/platform/platform_includes.h

Add support for ADF4030

---

drivers/potentiometer/ad5171/ad5171.c
drivers/potentiometer/ad5171/ad5171.h

This is the driver for the AD5161 digipot.
- [X ] New feature (change that adds new functionality)

Driver for AD5171 and AD5273

---

doc/sphinx/source/drivers/talise.rst
doc/sphinx/source/drivers_doc.rst
drivers/rf-transceiver/talise/README.rst

This adds the rst readme for the ADRV9009.
Also modified the drivers_doc.rst file to add the corresponding sphinx source pointer.

drivers: rf-transceiver: adrv9009:  Add readme documentation for ADRV9009

---

drivers/frequency/admfm2000/README.rst

Add https:// suffix for the analog.com product page.
Related issues: https://github.com/analogdevicesinc/no-OS/issues/2609

drivers: frequency: admfm2000: fix product link

---

doc/sphinx/source/projects/ad74416h.rst
doc/sphinx/source/projects_doc.rst
projects/ad74416h/README.rst

Added the readme document for the AD74416H project.
Also modified the sphinx projects_doc.rst file to add the corresponding source for this new readme.

projects: ad74416h: Added readme documentation

---

drivers/potentiometer/ad5242/ad5242.c
drivers/potentiometer/ad5242/ad5242.h

- [x ] New feature (change that adds new functionality)
- [ x] I have performed a self-review of the changes
- [ x] I have commented my code, at least hard-to-understand parts
- [ x] I have tested in hardware affected projects, at the relevant boards
- [ x] I have signed off all commits from this PR
- [ x] I have updated the documentation (wiki pages, ReadMe etc), if applies

Driver for ad5242

---

doc/sphinx/source/build_guide.rst
doc/sphinx/source/build_guides/build_win.rst
drivers/api/no_os_uart.c
drivers/platform/ftd2xx/mpsse/ftd2xx_platform.h
drivers/platform/win/win_delay.c
drivers/platform/win/win_uart.c
drivers/platform/win/win_uart.h
include/no_os_util.h
projects/max31827-evkit/src/platform/win/main.c
projects/max31827-evkit/src/platform/win/parameters.c
projects/max31827-evkit/src/platform/win/parameters.h
projects/max31827-evkit/src/platform/win/platform_src.mk
tools/scripts/ftd2xx.mk
tools/scripts/generic.mk
tools/scripts/libraries.mk
tools/scripts/platform/win/.vscode/c_cpp_properties.json
tools/scripts/platform/win/.vscode/launch.json
tools/scripts/platform/win/.vscode/tasks.json
tools/scripts/platform/win/config_build.py
tools/scripts/win.mk
util/no_os_alloc.c
util/no_os_mutex.c
util/no_os_semaphore.c

Add WIN (windows) platform for no-OS. This PR includes:
- drivers for the platform
- scripts to include the platform in the build system
- support for ftd2xx library
- platform documentation & build guide
- example of usage of the platform on one of the project examples.

drivers: platform: win : Add WIN platform

---

doc/sphinx/source/drivers/max31855.rst
doc/sphinx/source/drivers_doc.rst
drivers/temperature/max31855/README.rst

Added the readme file for max31855 driver.
Modified the sphinx drivers_doc.rst file to add the corresponding source.

drivers: temperature:max31855: Added README for MAX31855

---

doc/sphinx/source/projects/ad3552r_fmcz.rst
doc/sphinx/source/projects_doc.rst
projects/ad3552r_fmcz/README.rst

Added the readme document for the AD3552R_FMCZ project.
Also modified the sphinx projects_doc.rst file to add the corresponding source for this new readme.

projects: ad3552r_fmcz: Added README documentation

---

doc/sphinx/source/build_guide.rst

Legacy folder was removed so the paragraph needs to be removed as well.

doc: remove paragraph about legacy build

---

doc/sphinx/source/drivers/adt75.rst
doc/sphinx/source/drivers_doc.rst
drivers/temperature/adt75/README.rst

Added the readme document for the ADT75 driver.
Also modified the driver doc toctree to add the corresponding source for this new readme.

drivers: temperature: adt75: Added readme doc

---

doc/sphinx/source/drivers/ad9625.rst
doc/sphinx/source/drivers_doc.rst
drivers/adc/ad9625/README.rst

Added the readme file for the AD9625 driver.
Modified the sphinx drivers_doc.rst file to add the corresponding source.

drivers: adc: ad9625: Added README for AD9625

---

drivers/frequency/adf4377/README.rst
drivers/frequency/adf4377/adf4377.c
drivers/frequency/adf4377/adf4377.h
drivers/frequency/adf4377/iio_adf4377.c
drivers/frequency/adf4377/iio_adf4377.h

Added R Delay and N delay features with the documentation.

drivers: frequency: adf4377: Added Rdel and Ndel features

---

doc/sphinx/source/projects/ad9739a-fmc-ebz.rst
doc/sphinx/source/projects_doc.rst
projects/ad9739a-fmc-ebz/README.rst

Added the readme document for the AD9739A-FMC-EBZ project.
Also modified the sphinx projects_doc.rst file to add the corresponding source for this new readme.

projects: AD9739A-FMC-EBZ: Added README document

---

doc/sphinx/source/projects/ad9208.rst
doc/sphinx/source/projects_doc.rst
projects/ad9208/README.rst

Added the readme document for the AD9208 project.
Also modified the projects_doc.rst file to add the corresponding source for this new readme.

projects: AD9208: Added readme documentation

---

libraries/esh/no_os_esh.c
libraries/esh/no_os_esh.h

When initializing the esh library, initial_setup() needs access, from sources.

libraries: esh: add missing include and function prototype

---

doc/sphinx/source/drivers/ad9523.rst
doc/sphinx/source/drivers_doc.rst
drivers/frequency/ad9523/README.rst

Added the readme file for the AD9523 driver.
Modified the sphinx drivers_doc.rst file to add the corresponding source.

[drivers: frequency: ad9523: Add README documentation for AD9523]

---

doc/sphinx/source/drivers/ad9152.rst
doc/sphinx/source/drivers_doc.rst
drivers/dac/ad9152/README.rst

Added the readme file for the AD9152 driver.
Modified the sphinx drivers_doc.rst file to add the corresponding source.

[drivers: adc: ad9152: Add README documentation for AD9152]

---

doc/sphinx/source/drivers/max22516.rst
doc/sphinx/source/drivers_doc.rst
drivers/io-link/max22516/README.rst

Add README documentation for the MAX22516 IO-Link data link controller with integrated transceiver. Documentation includes device overview, operation modes, configuration functions, and initialization example. Also integrates the documentation into the Sphinx build system under the IO-Link section.

io-link: max22516: Add README doc for MAX22516

---

doc/sphinx/source/drivers/adg1712.rst
doc/sphinx/source/drivers_doc.rst
drivers/switch/adg1712/README.rst
drivers/switch/adg1712/adg1712.c
drivers/switch/adg1712/adg1712.h

[switch: adg1712: add initial driver support](https://github.com/analogdevicesinc/no-OS/commit/8617920d3dca7f79bd8a0c0958ed8ff5ba3e01c5)
[switch: adg1712: add README documentation](https://github.com/analogdevicesinc/no-OS/commit/1bf95086ba5de4d2fb475772f2ba320cbdd472e0)

switch: adg1712: add initial driver support 

---

doc/sphinx/source/drivers/adgm3121.rst
doc/sphinx/source/drivers/switch/adgm3121.rst
doc/sphinx/source/drivers/switch/adgs6414d.rst
doc/sphinx/source/drivers_doc.rst
drivers/switch/adgs6414d/README.rst
drivers/switch/adgs6414d/adgs6414d.c
drivers/switch/adgs6414d/adgs6414d.h

[switch: adgs6414d: add initial driver support](https://github.com/analogdevicesinc/no-OS/commit/58f154e9223847d281d5267c724e48102a6293a0)
[switch: adgs6414d: add README documentation](https://github.com/analogdevicesinc/no-OS/commit/b504165d0afaefc396f7e2b3b43ce33e4279ba3a)

switch: adgs6414d: add initial driver support

---

drivers/adc/ad463x/ad463x.c
drivers/adc/ad463x/ad463x.h
drivers/adc/ad463x/iio_ad463x.c
projects/ad463x_fmcz/Makefile
projects/ad463x_fmcz/src.mk
projects/ad463x_fmcz/src/common/common_data.c

Add ADAQ4216 device ID to distinguish ADAQ4216 from ADAQ4224.

drivers: adc: ad463x: adaq4216 support

---

ci/documentation.sh

The documentation check script incorrectly assumed both drivers and projects follow the same directory structure. Projects are organized directly under projects/ but their documentation is categorized under subdirectories in doc/sphinx/source/projects/, while drivers follow the expected structure of drivers/category/driver_name/.
This fix handles projects separately by:
- Finding the .rst file anywhere under doc/sphinx/source/projects/
- Extracting the category from the actual file location
- Checking the appropriate wildcard pattern in projects_doc.rst
Fixes: 77d5a55c6 ("doc: reorganize sphinx docs with subdir categories")

ci: documentation: Fix project directory structure handling

---

projects/adrv902x/Makefile
projects/adrv902x/src/examples/basic_example/basic_example.c

ADRV902X project preparation for adding ORx.
Addition of ORx components for the basic example.

ADRV902X ORx preparation

---

iio/iio_app/iio_app.c

Makeing possible to configure IIOD app uart async rx from project level.
Tested with MAX32662
- [x I have signed off all commits from this PR

iio_app.c: make iiod uart asynchronous_rx configurable from project

---

drivers/platform/freeRTOS/freertos_semaphore.c
tools/scripts/freertos.mk

freertos: adapt memory handling to new freertos_alloc.c
